# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/4/2013
Last Updated: 1/16/2013
Purpose: Recipe list for Armorcrafting used by Crafting.py
'''
armor = {
	"0":{
		"Bolt of Jute":{"Jute Scrap":2},
		"Bronze Chain Boot Lining":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Bronze Chain Boot Panel":{"Bronze Ingot":2},
		"Bronze Chain Chest Padding":{"Bolt of Jute":3,"Spool of Jute Thread":2},
		"Bronze Chain Chest Panel":{"Bronze Ingot":4},
		"Bronze Chain Glove Lining":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Bronze Chain Glove Panel":{"Bronze Ingot":2},
		"Bronze Chain Legging Lining":{"Bolt of Jute":3,"Spool of Jute Thread":2},
		"Bronze Chain Leggings Panel":{"Bronze Ingot":3},
		"Bronze Ingot":{"Copper Ore":2,"Lump of Tin":1},
		"Malign Chain Boots-Fine":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Malign Jute Insignia":1},
		"Malign Chain Coat-Fine":{"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1,"Malign Jute Insignia":1},
		"Malign Chain Gauntlets-Fine":{"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1,"Malign Jute Insignia":1},
		"Malign Chain Legs-Fine":{"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1,"Malign Jute Insignia":1},
		"Mighty Chain Boots-Fine":{"Mighty Jute Insignia":1,"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1},
		"Mighty Chain Coat-Fine":{"Mighty Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Mighty Chain Gauntlets-Fine":{"Mighty Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Mighty Chain Legs-Fine":{"Mighty Jute Insignia":1,"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1},
		"Minor Rune of the Guardian":{"Charged Sliver":2,"Bronze Ingot":1},
		"Minor Rune of the Warrior":{"Onyx Sliver":2,"Tiny Scale":1,"Bronze Ingot":1},
		"Vital Chain Boots-Fine":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Vital Jute Insignia":1},
		"Vital Chain Coat-Fine":{"Bronze Chain Chest Panel":1,"Vital Jute Insignia":1,"Bronze Chain Chest Padding":1},
		"Vital Chain Gauntlets-Fine":{"Bronze Chain Glove Lining":1,"Vital Jute Insignia":1,"Bronze Chain Glove Panel":1},
		"Vital Chain Legs-Fine":{"Bronze Chain Leggings Panel":1,"Vital Jute Insignia":1,"Bronze Chain Legging Lining":1}
	},
	"10":{
		"Rune of Life":{"Bolt of Jute":1,"Bronze Ingot":2}
	},
	"25":{
		"Bronze Helmet Casing":{"Bronze Ingot":2},
		"Bronze Helmet Lining":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Giver's Chain Boots-Fine":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Chain Coat-Fine":{"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Chain Gauntlets-Fine":{"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Chain Helm-Fine":{"Bronze Helmet Casing":1,"Bronze Helmet Lining":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Chain Legs-Fine":{"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1,"Giver's Embroidered Jute Insignia":1},
		"Healing Chain Boots-Fine":{"Bronze Chain Boot Panel":1,"Healing Jute Insignia":1,"Bronze Chain Boot Lining":1},
		"Healing Chain Coat-Fine":{"Healing Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Healing Chain Gauntlets-Fine":{"Healing Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Healing Chain Helm-Fine":{"Bronze Helmet Casing":1,"Healing Jute Insignia":1,"Bronze Helmet Lining":1},
		"Healing Chain Legs-Fine":{"Bronze Chain Leggings Panel":1,"Healing Jute Insignia":1,"Bronze Chain Legging Lining":1},
		"Minor Rune of the Fighter":{"Crystal Sliver":2,"Bronze Ingot":1},
		"Minor Rune of the Soldier":{"Molten Sliver":2,"Vial of Weak Blood":1,"Bronze Ingot":1},
		"Precise Chain Boots-Fine":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Precise Jute Insignia":1},
		"Precise Chain Coat-Fine":{"Bronze Chain Chest Panel":1,"Precise Jute Insignia":1,"Bronze Chain Chest Padding":1},
		"Precise Chain Gauntlets-Fine":{"Bronze Chain Glove Lining":1,"Precise Jute Insignia":1,"Bronze Chain Glove Panel":1},
		"Precise Chain Helm-Fine":{"Bronze Helmet Casing":1,"Precise Jute Insignia":1,"Bronze Helmet Lining":1},
		"Precise Chain Legs-Fine":{"Bronze Chain Leggings Panel":1,"Precise Jute Insignia":1,"Bronze Chain Legging Lining":1},
		"Resilient Chain Boots-Fine":{"Resilient Jute Insignia":1,"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1},
		"Resilient Chain Coat-Fine":{"Resilient Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Resilient Chain Gauntlets-Fine":{"Resilient Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Resilient Chain Helm-Fine":{"Resilient Jute Insignia":1,"Bronze Helmet Casing":1,"Bronze Helmet Lining":1},
		"Resilient Chain Legs-Fine":{"Resilient Jute Insignia":1,"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1}
	},
	"50":{
		"Bronze Pauldron Casing":{"Bronze Ingot":2},
		"Bronze Pauldron Lining":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Healing Chain Boots-Master":{"Bronze Chain Boot Panel":1,"Healing Embroidered Jute Insignia":1,"Bronze Chain Boot Lining":1},
		"Healing Chain Coat-Master":{"Healing Embroidered Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Healing Chain Gauntlets-Master":{"Healing Embroidered Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Healing Chain Helm-Master":{"Bronze Helmet Casing":1,"Healing Embroidered Jute Insignia":1,"Bronze Helmet Lining":1},
		"Healing Chain Legs-Master":{"Bronze Chain Leggings Panel":1,"Healing Embroidered Jute Insignia":1,"Bronze Chain Legging Lining":1},
		"Healing Chain Pauldrons-Master":{"Bronze Pauldron Lining":1,"Healing Embroidered Jute Insignia":1,"Bronze Pauldron Casing":1},
		"Malign Chain Boots-Master":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Malign Embroidered Jute Insignia":1},
		"Malign Chain Coat-Master":{"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1,"Malign Embroidered Jute Insignia":1},
		"Malign Chain Gauntlets-Master":{"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1,"Malign Embroidered Jute Insignia":1},
		"Malign Chain Helm-Master":{"Bronze Helmet Casing":1,"Bronze Helmet Lining":1,"Malign Embroidered Jute Insignia":1},
		"Malign Chain Legs-Master":{"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1,"Malign Embroidered Jute Insignia":1},
		"Malign Chain Pauldrons-Master":{"Bronze Pauldron Lining":1,"Bronze Pauldron Casing":1,"Malign Embroidered Jute Insignia":1},
		"Mighty Chain Boots-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1},
		"Mighty Chain Coat-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Mighty Chain Gauntlets-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Mighty Chain Helm-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Helmet Casing":1,"Bronze Helmet Lining":1},
		"Mighty Chain Legs-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1},
		"Mighty Chain Pauldrons-Master":{"Mighty Embroidered Jute Insignia":1,"Bronze Pauldron Lining":1,"Bronze Pauldron Casing":1},
		"Minor Rune of Svanir":{"Corrupted Sliver":2,"Bronze Ingot":1},
		"Minor Rune of the Krait":{"Pile of Soiled Essence":2,"Bronze Ingot":1},
		"Precise Chain Boots-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1},
		"Precise Chain Coat-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Chain Chest Panel":1,"Bronze Chain Chest Padding":1},
		"Precise Chain Gauntlets-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Chain Glove Lining":1,"Bronze Chain Glove Panel":1},
		"Precise Chain Helm-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Helmet Casing":1,"Bronze Helmet Lining":1},
		"Precise Chain Legs-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Chain Leggings Panel":1,"Bronze Chain Legging Lining":1},
		"Precise Chain Pauldrons-Master":{"Precise Embroidered Jute Insignia":1,"Bronze Pauldron Lining":1,"Bronze Pauldron Casing":1},
		"Resilient Chain Boots-Master":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Chain Coat-Master":{"Bronze Chain Chest Panel":1,"Resilient Embroidered Jute Insignia":1,"Bronze Chain Chest Padding":1},
		"Resilient Chain Gauntlets-Master":{"Bronze Chain Glove Lining":1,"Resilient Embroidered Jute Insignia":1,"Bronze Chain Glove Panel":1},
		"Resilient Chain Helm-Master":{"Bronze Helmet Casing":1,"Resilient Embroidered Jute Insignia":1,"Bronze Helmet Lining":1},
		"Resilient Chain Legs-Master":{"Bronze Chain Leggings Panel":1,"Resilient Embroidered Jute Insignia":1,"Bronze Chain Legging Lining":1},
		"Resilient Chain Pauldrons-Master":{"Bronze Pauldron Lining":1,"Resilient Embroidered Jute Insignia":1,"Bronze Pauldron Casing":1},
		"Vital Chain Boots-Master":{"Bronze Chain Boot Panel":1,"Bronze Chain Boot Lining":1,"Vital Embroidered Jute Insignia":1},
		"Vital Chain Coat-Master":{"Bronze Chain Chest Panel":1,"Vital Embroidered Jute Insignia":1,"Bronze Chain Chest Padding":1},
		"Vital Chain Gauntlets-Master":{"Bronze Chain Glove Lining":1,"Vital Embroidered Jute Insignia":1,"Bronze Chain Glove Panel":1},
		"Vital Chain Helm-Master":{"Bronze Helmet Casing":1,"Vital Embroidered Jute Insignia":1,"Bronze Helmet Lining":1},
		"Vital Chain Legs-Master":{"Bronze Chain Leggings Panel":1,"Vital Embroidered Jute Insignia":1,"Bronze Chain Legging Lining":1},
		"Vital Chain Pauldrons-Master":{"Bronze Pauldron Lining":1,"Vital Embroidered Jute Insignia":1,"Bronze Pauldron Casing":1}
	},
	"75":{
		"Minor Rune of the Mad King":{"Iron Ingot":1,"Onyx Fragment":2,"Piece of Candy Corn":75,"Plastic Fang":1},
		"Bolt of Wool":{"Wool Scrap":2},
		"Giver's Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Scale Coat-Fine":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Giver's Embroidered Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Giver's Scale Helm-Fine":{"Iron Casque Lining":1,"Iron Casque Casing":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Scale Pauldrons-Fine":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Giver's Embroidered Wool Insignia":1},
		"Iron Casque Casing":{"Iron Ingot":2},
		"Iron Casque Lining":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Iron Ingot":{"Iron Ore":3},
		"Iron Pauldron Casing":{"Iron Ingot":2},
		"Iron Pauldron Lining":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Iron Scale Armguard Lining":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Iron Scale Armguard Panel":{"Iron Ingot":2},
		"Iron Scale Boot Lining":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Iron Scale Boot Panel":{"Iron Ingot":2},
		"Iron Scale Chest Padding":{"Spool of Wool Thread":2,"Bolt of Wool":3},
		"Iron Scale Chest Panel":{"Iron Ingot":4},
		"Iron Scale Legging Lining":{"Spool of Wool Thread":2,"Bolt of Wool":3},
		"Iron Scale Legging Panel":{"Iron Ingot":4},
		"Minor Rune of the Earth":{"Onyx Sliver":2,"Iron Ingot":1},
		"Minor Rune of the Fire":{"Molten Sliver":2,"Iron Ingot":1},
		"Pillaging Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Pillaging Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Pillaging Scale Coat-Fine":{"Pillaging Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Pillaging Scale Gauntlets-Fine":{"Pillaging Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Pillaging Scale Helm-Fine":{"Pillaging Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Pillaging Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Pillaging Wool Insignia":1,"Iron Scale Legging Panel":1},
		"Pillaging Scale Pauldrons-Fine":{"Pillaging Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Ravaging Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Ravaging Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Ravaging Scale Coat-Fine":{"Ravaging Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Ravaging Scale Gauntlets-Fine":{"Ravaging Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Ravaging Scale Helm-Fine":{"Ravaging Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Ravaging Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Ravaging Wool Insignia":1,"Iron Scale Legging Panel":1},
		"Ravaging Scale Pauldrons-Fine":{"Ravaging Wool Insignia":1,"Iron Pauldron Lining":1,"Iron Pauldron Casing":1},
		"Vigorous Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Vigorous Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Vigorous Scale Coat-Fine":{"Vigorous Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Vigorous Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Vigorous Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Vigorous Scale Helm-Fine":{"Iron Casque Casing":1,"Vigorous Wool Insignia":1,"Iron Casque Lining":1},
		"Vigorous Scale Legs-Fine":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Vigorous Wool Insignia":1},
		"Vigorous Scale Pauldrons-Fine":{"Iron Pauldron Casing":1,"Vigorous Wool Insignia":1,"Iron Pauldron Lining":1}
	},
	"100":{
		"Minor Rune of Altruism":{"Iron Ingot":1,"Glacial Fragment":1,"Delicate Snowflake":1},
		"Hearty Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Hearty Wool Insignia":1},
		"Hearty Scale Coat-Fine":{"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1,"Hearty Wool Insignia":1},
		"Hearty Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Hearty Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Hearty Scale Helm-Fine":{"Iron Casque Casing":1,"Hearty Wool Insignia":1,"Iron Casque Lining":1},
		"Hearty Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Hearty Wool Insignia":1},
		"Hearty Scale Pauldrons-Fine":{"Iron Pauldron Lining":1,"Iron Pauldron Casing":1,"Hearty Wool Insignia":1},
		"Honed Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Honed Wool Insignia":1},
		"Honed Scale Coat-Fine":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Honed Wool Insignia":1},
		"Honed Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1,"Honed Wool Insignia":1},
		"Honed Scale Helm-Fine":{"Iron Casque Casing":1,"Iron Casque Lining":1,"Honed Wool Insignia":1},
		"Honed Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Honed Wool Insignia":1},
		"Honed Scale Pauldrons-Fine":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Honed Wool Insignia":1},
		"Minor Rune of the Guardian-2":{"Charged Fragment":1,"Iron Ingot":1},
		"Minor Rune of the Warrior-2":{"Small Scale":1,"Onyx Fragment":1,"Iron Ingot":1},
		"Rejuvenating Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Rejuvenating Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Rejuvenating Scale Coat-Fine":{"Rejuvenating Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Rejuvenating Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Rejuvenating Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Rejuvenating Scale Helm-Fine":{"Iron Casque Casing":1,"Rejuvenating Wool Insignia":1,"Iron Casque Lining":1},
		"Rejuvenating Scale Legs-Fine":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Scale Pauldrons-Fine":{"Iron Pauldron Casing":1,"Rejuvenating Wool Insignia":1,"Iron Pauldron Lining":1},
		"Strong Scale Boots-Fine":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Strong Wool Insignia":1},
		"Strong Scale Coat-Fine":{"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1,"Strong Wool Insignia":1},
		"Strong Scale Gauntlets-Fine":{"Iron Scale Armguard Panel":1,"Strong Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Strong Scale Helm-Fine":{"Iron Casque Casing":1,"Strong Wool Insignia":1,"Iron Casque Lining":1},
		"Strong Scale Legs-Fine":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Strong Wool Insignia":1},
		"Strong Scale Pauldrons-Fine":{"Iron Pauldron Lining":1,"Iron Pauldron Casing":1,"Strong Wool Insignia":1}
	},
	"125":{
		"Hearty Gladiator Boots-t2":{"Iron Scale Boot Lining":1,"Hearty Intricate Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Hearty Gladiator Chestplate-t2":{"Hearty Intricate Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Hearty Gladiator Gauntlets-t2":{"Iron Scale Armguard Panel":1,"Hearty Intricate Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Hearty Gladiator Helm-t2":{"Iron Casque Casing":1,"Hearty Intricate Wool Insignia":1,"Iron Casque Lining":1},
		"Hearty Gladiator Legplates-t2":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Gladiator Pauldrons-t2":{"Iron Pauldron Casing":1,"Hearty Intricate Wool Insignia":1,"Iron Pauldron Lining":1},
		"Hearty Scale Boots-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1},
		"Hearty Scale Coat-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Hearty Scale Gauntlets-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Hearty Scale Helm-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Hearty Scale Legs-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1},
		"Hearty Scale Pauldrons-Master":{"Hearty Embroidered Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Honed Gladiator Boots-t2":{"Iron Scale Boot Lining":1,"Honed Intricate Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Honed Gladiator Chestplate-t2":{"Honed Intricate Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Honed Gladiator Gauntlets-t2":{"Honed Intricate Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Honed Gladiator Helm-t2":{"Honed Intricate Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Honed Gladiator Legplates-t2":{"Iron Scale Legging Lining":1,"Honed Intricate Wool Insignia":1,"Iron Scale Legging Panel":1},
		"Honed Gladiator Pauldrons-t2":{"Honed Intricate Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Honed Scale Boots-Master":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Honed Embroidered Wool Insignia":1},
		"Honed Scale Coat-Master":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Honed Embroidered Wool Insignia":1},
		"Honed Scale Gauntlets-Master":{"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1,"Honed Embroidered Wool Insignia":1},
		"Honed Scale Helm-Master":{"Iron Casque Casing":1,"Iron Casque Lining":1,"Honed Embroidered Wool Insignia":1},
		"Honed Scale Legs-Master":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Honed Embroidered Wool Insignia":1},
		"Honed Scale Pauldrons-Master":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Honed Embroidered Wool Insignia":1},
		"Minor Rune of the Fighter-2":{"Crystal Fragment":1,"Iron Ingot":1},
		"Minor Rune of the Soldier-2":{"Vial of Thin Blood":1,"Molten Fragment":1,"Iron Ingot":1},
		"Pillaging Gladiator Boots-t2":{"Iron Scale Boot Lining":1,"Pillaging Intricate Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Pillaging Gladiator Chestplate-t2":{"Pillaging Intricate Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Pillaging Gladiator Gauntlets-t2":{"Pillaging Intricate Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Pillaging Gladiator Helm-t2":{"Pillaging Intricate Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Pillaging Gladiator Legplates-t2":{"Iron Scale Legging Lining":1,"Pillaging Intricate Wool Insignia":1,"Iron Scale Legging Panel":1},
		"Pillaging Gladiator Pauldrons-t2":{"Pillaging Intricate Wool Insignia":1,"Iron Pauldron Lining":1,"Iron Pauldron Casing":1},
		"Pillaging Scale Boots-Master":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Scale Coat-Master":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Scale Gauntlets-Master":{"Iron Scale Armguard Panel":1,"Pillaging Embroidered Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Pillaging Scale Helm-Master":{"Iron Casque Lining":1,"Iron Casque Casing":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Scale Legs-Master":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Scale Pauldrons-Master":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Pillaging Embroidered Wool Insignia":1},
		"Ravaging Gladiator Boots-t2":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Gladiator Chestplate-t2":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Gladiator Gauntlets-t2":{"Iron Scale Armguard Panel":1,"Ravaging Intricate Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Ravaging Gladiator Helm-t2":{"Iron Casque Lining":1,"Iron Casque Casing":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Gladiator Legplates-t2":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Gladiator Pauldrons-t2":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Scale Boots-Master":{"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Scale Coat-Master":{"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Scale Gauntlets-Master":{"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Scale Helm-Master":{"Iron Casque Casing":1,"Iron Casque Lining":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Scale Legs-Master":{"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Scale Pauldrons-Master":{"Iron Pauldron Casing":1,"Iron Pauldron Lining":1,"Ravaging Embroidered Wool Insignia":1},
		"Rejuvenating Gladiator Boots-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1},
		"Rejuvenating Gladiator Chestplate-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Rejuvenating Gladiator Gauntlets-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Rejuvenating Gladiator Helm-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Rejuvenating Gladiator Legplates-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1},
		"Rejuvenating Gladiator Pauldrons-t2":{"Rejuvenating Intricate Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Rejuvenating Scale Boots-Master":{"Iron Scale Boot Lining":1,"Rejuvenating Embroidered Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Rejuvenating Scale Coat-Master":{"Rejuvenating Embroidered Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Rejuvenating Scale Gauntlets-Master":{"Iron Scale Armguard Panel":1,"Rejuvenating Embroidered Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Rejuvenating Scale Helm-Master":{"Iron Casque Casing":1,"Rejuvenating Embroidered Wool Insignia":1,"Iron Casque Lining":1},
		"Rejuvenating Scale Legs-Master":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Scale Pauldrons-Master":{"Iron Pauldron Casing":1,"Rejuvenating Embroidered Wool Insignia":1,"Iron Pauldron Lining":1},
		"Strong Gladiator Boots-t2":{"Iron Scale Boot Lining":1,"Strong Intricate Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Strong Gladiator Chestplate-t2":{"Strong Intricate Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Strong Gladiator Gauntlets-t2":{"Iron Scale Armguard Panel":1,"Strong Intricate Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Strong Gladiator Helm-t2":{"Iron Casque Casing":1,"Strong Intricate Wool Insignia":1,"Iron Casque Lining":1},
		"Strong Gladiator Legplates-t2":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Strong Intricate Wool Insignia":1},
		"Strong Gladiator Pauldrons-t2":{"Iron Pauldron Casing":1,"Strong Intricate Wool Insignia":1,"Iron Pauldron Lining":1},
		"Strong Scale Boots-Master":{"Strong Embroidered Wool Insignia":1,"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1},
		"Strong Scale Coat-Master":{"Strong Embroidered Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Strong Scale Gauntlets-Master":{"Strong Embroidered Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Strong Scale Helm-Master":{"Strong Embroidered Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Strong Scale Legs-Master":{"Strong Embroidered Wool Insignia":1,"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1},
		"Strong Scale Pauldrons-Master":{"Strong Embroidered Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Vigorous Gladiator Boots-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Scale Boot Lining":1,"Iron Scale Boot Panel":1},
		"Vigorous Gladiator Chestplate-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Scale Chest Panel":1,"Iron Scale Chest Padding":1},
		"Vigorous Gladiator Gauntlets-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Scale Armguard Panel":1,"Iron Scale Armguard Lining":1},
		"Vigorous Gladiator Helm-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Casque Casing":1,"Iron Casque Lining":1},
		"Vigorous Gladiator Legplates-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Scale Legging Lining":1,"Iron Scale Legging Panel":1},
		"Vigorous Gladiator Pauldrons-t2":{"Vigorous Intricate Wool Insignia":1,"Iron Pauldron Casing":1,"Iron Pauldron Lining":1},
		"Vigorous Scale Boots-Master":{"Iron Scale Boot Lining":1,"Vigorous Embroidered Wool Insignia":1,"Iron Scale Boot Panel":1},
		"Vigorous Scale Coat-Master":{"Vigorous Embroidered Wool Insignia":1,"Iron Scale Chest Padding":1,"Iron Scale Chest Panel":1},
		"Vigorous Scale Gauntlets-Master":{"Iron Scale Armguard Panel":1,"Vigorous Embroidered Wool Insignia":1,"Iron Scale Armguard Lining":1},
		"Vigorous Scale Helm-Master":{"Iron Casque Casing":1,"Vigorous Embroidered Wool Insignia":1,"Iron Casque Lining":1},
		"Vigorous Scale Legs-Master":{"Iron Scale Legging Panel":1,"Iron Scale Legging Lining":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Scale Pauldrons-Master":{"Iron Pauldron Casing":1,"Vigorous Embroidered Wool Insignia":1,"Iron Pauldron Lining":1}
	},
	"150":{
		"Bolt of Cotton":{"Cotton Scrap":2},
		"Minor Rune of Svanir-2":{"Steel Ingot":1,"Corrupted Fragment":1},
		"Minor Rune of the Krait-2":{"Pile of Foul Essence":1,"Steel Ingot":1},
		"Pillaging Splint Coat-Fine":{"Steel Splint Chestplate Panel":1,"Pillaging Cotton Insignia":1,"Steel Splint Chestplate Padding":1},
		"Pillaging Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Pillaging Cotton Insignia":1},
		"Pillaging Splint Greaves-Fine":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Pillaging Cotton Insignia":1},
		"Pillaging Splint Helm-Fine":{"Steel Splint Helmet Lining":1,"Steel Splint Helmet Casing":1,"Pillaging Cotton Insignia":1},
		"Pillaging Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Pillaging Cotton Insignia":1},
		"Pillaging Splint Pauldrons-Fine":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Pillaging Cotton Insignia":1},
		"Ravaging Splint Coat-Fine":{"Steel Splint Chestplate Padding":1,"Steel Splint Chestplate Panel":1,"Ravaging Cotton Insignia":1},
		"Ravaging Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Ravaging Cotton Insignia":1},
		"Ravaging Splint Greaves-Fine":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Ravaging Cotton Insignia":1},
		"Ravaging Splint Helm-Fine":{"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1,"Ravaging Cotton Insignia":1},
		"Ravaging Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Ravaging Cotton Insignia":1},
		"Ravaging Splint Pauldrons-Fine":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Ravaging Cotton Insignia":1},
		"Steel Ingot":{"Iron Ore":3,"Lump of Coal":1},
		"Steel Splint Boot Casing":{"Steel Ingot":3},
		"Steel Splint Boot Lining":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Steel Splint Chestplate Padding":{"Spool of Cotton Thread":3,"Bolt of Cotton":1},
		"Steel Splint Chestplate Panel":{"Steel Ingot":4},
		"Steel Splint Gauntlet Lining":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Steel Splint Gauntlet Plates":{"Steel Ingot":2},
		"Steel Splint Helmet Casing":{"Steel Ingot":2},
		"Steel Splint Helmet Lining":{"Spool of Cotton Thread":1,"Bolt of Cotton":2},
		"Steel Splint Legging Lining":{"Spool of Cotton Thread":3,"Bolt of Cotton":1},
		"Steel Splint Legging Panel":{"Steel Ingot":3},
		"Steel Splint Pauldron Casing":{"Steel Ingot":2},
		"Steel Splint Pauldron Lining":{"Spool of Cotton Thread":1,"Bolt of Cotton":2},
		"Vigorous Splint Coat-Fine":{"Vigorous Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Vigorous Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Vigorous Cotton Insignia":1},
		"Vigorous Splint Greaves-Fine":{"Steel Splint Boot Lining":1,"Vigorous Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Vigorous Splint Helm-Fine":{"Steel Splint Helmet Lining":1,"Vigorous Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Vigorous Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Vigorous Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Vigorous Splint Pauldrons-Fine":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Vigorous Cotton Insignia":1}
	},
	"175":{
		"Hearty Splint Coat-Fine":{"Hearty Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Hearty Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Hearty Cotton Insignia":1},
		"Hearty Splint Greaves-Fine":{"Steel Splint Boot Casing":1,"Steel Splint Boot Lining":1,"Hearty Cotton Insignia":1},
		"Hearty Splint Helm-Fine":{"Steel Splint Helmet Casing":1,"Hearty Cotton Insignia":1,"Steel Splint Helmet Lining":1},
		"Hearty Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Hearty Cotton Insignia":1},
		"Hearty Splint Pauldrons-Fine":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Hearty Cotton Insignia":1},
		"Honed Splint Coat-Fine":{"Steel Splint Chestplate Padding":1,"Steel Splint Chestplate Panel":1,"Honed Cotton Insignia":1},
		"Honed Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Honed Cotton Insignia":1},
		"Honed Splint Greaves-Fine":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Honed Cotton Insignia":1},
		"Honed Splint Helm-Fine":{"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1,"Honed Cotton Insignia":1},
		"Honed Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Honed Cotton Insignia":1},
		"Honed Splint Pauldrons-Fine":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Honed Cotton Insignia":1},
		"Minor Rune of the Earth-2":{"Steel Ingot":1,"Onyx Fragment":1},
		"Minor Rune of the Fire-2":{"Steel Ingot":1,"Molten Fragment":1},
		"Rejuvenating Splint Coat-Fine":{"Rejuvenating Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Rejuvenating Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Rejuvenating Cotton Insignia":1},
		"Rejuvenating Splint Greaves-Fine":{"Steel Splint Boot Lining":1,"Rejuvenating Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Rejuvenating Splint Helm-Fine":{"Steel Splint Helmet Lining":1,"Rejuvenating Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Rejuvenating Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Rejuvenating Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Rejuvenating Splint Pauldrons-Fine":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Rejuvenating Cotton Insignia":1},
		"Strong Splint Coat-Fine":{"Strong Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Strong Splint Gauntlets-Fine":{"Steel Splint Gauntlet Plates":1,"Steel Splint Gauntlet Lining":1,"Strong Cotton Insignia":1},
		"Strong Splint Greaves-Fine":{"Steel Splint Boot Casing":1,"Steel Splint Boot Lining":1,"Strong Cotton Insignia":1},
		"Strong Splint Helm-Fine":{"Steel Splint Helmet Casing":1,"Strong Cotton Insignia":1,"Steel Splint Helmet Lining":1},
		"Strong Splint Legs-Fine":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Strong Cotton Insignia":1},
		"Strong Splint Pauldrons-Fine":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Strong Cotton Insignia":1}
	},
	"200":{
		"Giver's Splint Coat-Master":{"Steel Splint Chestplate Panel":1,"Giver's Embroidered Cotton Insignia":1,"Steel Splint Chestplate Padding":1},
		"Giver's Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Splint Greaves-Master":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Splint Helm-Master":{"Steel Splint Helmet Lining":1,"Steel Splint Helmet Casing":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Splint Legs-Master":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Splint Pauldrons-Master":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Giver's Embroidered Cotton Insignia":1},
		"Hearty Gladiator Boots-t3":{"Steel Splint Boot Lining":1,"Hearty Intricate Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Hearty Gladiator Chestplate-t3":{"Hearty Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Hearty Gladiator Gauntlets-t3":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Hearty Intricate Cotton Insignia":1},
		"Hearty Gladiator Helm-t3":{"Steel Splint Helmet Lining":1,"Hearty Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Hearty Gladiator Legplates-t3":{"Steel Splint Legging Panel":1,"Hearty Intricate Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Hearty Gladiator Pauldrons-t3":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Hearty Intricate Cotton Insignia":1},
		"Hearty Splint Coat-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Hearty Splint Gauntlets-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1},
		"Hearty Splint Greaves-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Hearty Splint Helm-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Hearty Splint Legs-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1},
		"Hearty Splint Pauldrons-Master":{"Hearty Embroidered Cotton Insignia":1,"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1},
		"Honed Gladiator Boots-t3":{"Honed Intricate Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Honed Gladiator Chestplate-t3":{"Honed Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Honed Gladiator Gauntlets-t3":{"Steel Splint Gauntlet Lining":1,"Honed Intricate Cotton Insignia":1,"Steel Splint Gauntlet Plates":1},
		"Honed Gladiator Helm-t3":{"Honed Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Honed Gladiator Legplates-t3":{"Steel Splint Legging Panel":1,"Honed Intricate Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Honed Gladiator Pauldrons-t3":{"Steel Splint Pauldron Lining":1,"Honed Intricate Cotton Insignia":1,"Steel Splint Pauldron Casing":1},
		"Honed Splint Coat-Master":{"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Splint Greaves-Master":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Splint Helm-Master":{"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Splint Legs-Master":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Splint Pauldrons-Master":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Honed Embroidered Cotton Insignia":1},
		"Pillaging Gladiator Boots-t3":{"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Gladiator Chestplate-t3":{"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Gladiator Gauntlets-t3":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Gladiator Helm-t3":{"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Gladiator Legplates-t3":{"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Gladiator Pauldrons-t3":{"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Splint Coat-Master":{"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Pillaging Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Gauntlet Plates":1},
		"Pillaging Splint Greaves-Master":{"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Pillaging Splint Helm-Master":{"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Pillaging Splint Legs-Master":{"Steel Splint Legging Panel":1,"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Pillaging Splint Pauldrons-Master":{"Steel Splint Pauldron Lining":1,"Pillaging Embroidered Cotton Insignia":1,"Steel Splint Pauldron Casing":1},
		"Ravaging Gladiator Boots-t3":{"Ravaging Intricate Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Ravaging Gladiator Chestplate-t3":{"Ravaging Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Ravaging Gladiator Gauntlets-t3":{"Steel Splint Gauntlet Lining":1,"Ravaging Intricate Cotton Insignia":1,"Steel Splint Gauntlet Plates":1},
		"Ravaging Gladiator Helm-t3":{"Ravaging Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Ravaging Gladiator Legplates-t3":{"Steel Splint Legging Panel":1,"Ravaging Intricate Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Ravaging Gladiator Pauldrons-t3":{"Steel Splint Pauldron Lining":1,"Ravaging Intricate Cotton Insignia":1,"Steel Splint Pauldron Casing":1},
		"Ravaging Splint Coat-Master":{"Ravaging Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Ravaging Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Ravaging Embroidered Cotton Insignia":1},
		"Ravaging Splint Greaves-Master":{"Ravaging Embroidered Cotton Insignia":1,"Steel Splint Boot Casing":1,"Steel Splint Boot Lining":1},
		"Ravaging Splint Helm-Master":{"Ravaging Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Ravaging Splint Legs-Master":{"Steel Splint Legging Panel":1,"Ravaging Embroidered Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Ravaging Splint Pauldrons-Master":{"Steel Splint Pauldron Casing":1,"Ravaging Embroidered Cotton Insignia":1,"Steel Splint Pauldron Lining":1},
		"Rejuvenating Gladiator Boots-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Rejuvenating Gladiator Chestplate-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Rejuvenating Gladiator Gauntlets-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1},
		"Rejuvenating Gladiator Helm-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Rejuvenating Gladiator Legplates-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1},
		"Rejuvenating Gladiator Pauldrons-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1},
		"Rejuvenating Splint Coat-Master":{"Rejuvenating Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Rejuvenating Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Rejuvenating Embroidered Cotton Insignia":1},
		"Rejuvenating Splint Greaves-Master":{"Steel Splint Boot Lining":1,"Rejuvenating Embroidered Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Rejuvenating Splint Helm-Master":{"Steel Splint Helmet Lining":1,"Rejuvenating Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Rejuvenating Splint Legs-Master":{"Steel Splint Legging Panel":1,"Rejuvenating Embroidered Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Rejuvenating Splint Pauldrons-Master":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Rejuvenating Embroidered Cotton Insignia":1},
		"Strong Gladiator Boots-t3":{"Steel Splint Boot Lining":1,"Strong Intricate Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Strong Gladiator Chestplate-t3":{"Strong Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Strong Gladiator Gauntlets-t3":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Strong Intricate Cotton Insignia":1},
		"Strong Gladiator Helm-t3":{"Steel Splint Helmet Lining":1,"Strong Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Strong Gladiator Legplates-t3":{"Steel Splint Legging Panel":1,"Strong Intricate Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Strong Gladiator Pauldrons-t3":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Strong Intricate Cotton Insignia":1},
		"Strong Splint Coat-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Strong Splint Gauntlets-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1},
		"Strong Splint Greaves-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Strong Splint Helm-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Strong Splint Legs-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1},
		"Strong Splint Pauldrons-Master":{"Strong Embroidered Cotton Insignia":1,"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1},
		"Vigorous Gladiator Boots-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Boot Lining":1,"Steel Splint Boot Casing":1},
		"Vigorous Gladiator Chestplate-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Vigorous Gladiator Gauntlets-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1},
		"Vigorous Gladiator Helm-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Helmet Casing":1,"Steel Splint Helmet Lining":1},
		"Vigorous Gladiator Legplates-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Legging Panel":1,"Steel Splint Legging Lining":1},
		"Vigorous Gladiator Pauldrons-t3":{"Vigorous Intricate Cotton Insignia":1,"Steel Splint Pauldron Casing":1,"Steel Splint Pauldron Lining":1},
		"Vigorous Splint Coat-Master":{"Vigorous Embroidered Cotton Insignia":1,"Steel Splint Chestplate Panel":1,"Steel Splint Chestplate Padding":1},
		"Vigorous Splint Gauntlets-Master":{"Steel Splint Gauntlet Lining":1,"Steel Splint Gauntlet Plates":1,"Vigorous Embroidered Cotton Insignia":1},
		"Vigorous Splint Greaves-Master":{"Steel Splint Boot Lining":1,"Vigorous Embroidered Cotton Insignia":1,"Steel Splint Boot Casing":1},
		"Vigorous Splint Helm-Master":{"Steel Splint Helmet Lining":1,"Vigorous Embroidered Cotton Insignia":1,"Steel Splint Helmet Casing":1},
		"Vigorous Splint Legs-Master":{"Steel Splint Legging Panel":1,"Vigorous Embroidered Cotton Insignia":1,"Steel Splint Legging Lining":1},
		"Vigorous Splint Pauldrons-Master":{"Steel Splint Pauldron Lining":1,"Steel Splint Pauldron Casing":1,"Vigorous Embroidered Cotton Insignia":1},
	},
	"225":{
		"Bolt of Linen":{"Linen Scrap":2},
		"Carrion Reinforced Scale Boots-Fine":{"Carrion Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Carrion Reinforced Scale Chest-Fine":{"Carrion Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Carrion Reinforced Scale Gauntlets-Fine":{"Carrion Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Carrion Reinforced Scale Helm-Fine":{"Carrion Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Carrion Reinforced Scale Legs-Fine":{"Carrion Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Carrion Reinforced Scale Pauldrons-Fine":{"Carrion Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Darksteel Boot Casing":{"Darksteel Ingot":2},
		"Darksteel Boot Lining":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Darksteel Chestplate Padding":{"Spool of Linen Thread":3,"Bolt of Linen":1},
		"Darksteel Chestplate Panel":{"Darksteel Ingot":5},
		"Darksteel Gaunlet Plates":{"Darksteel Ingot":2},
		"Darksteel Gauntlet Lining":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Darksteel Helmet Casing":{"Darksteel Ingot":1},
		"Darksteel Helmet Lining":{"Spool of Linen Thread":1,"Bolt of Linen":2},
		"Darksteel Ingot":{"Lump of Primordium":1,"Platinum Ore":2},
		"Darksteel Legging Lining":{"Spool of Linen Thread":3,"Bolt of Linen":1},
		"Darksteel Legging Panel":{"Darksteel Ingot":4},
		"Darksteel Pauldron Casing":{"Darksteel Ingot":2},
		"Darksteel Pauldron Lining":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Knight's Reinforced Scale Boots-Fine":{"Darksteel Boot Lining":1,"Knight's Linen Insignia":1,"Darksteel Boot Casing":1},
		"Knight's Reinforced Scale Chest-Fine":{"Darksteel Chestplate Padding":1,"Knight's Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Knight's Reinforced Scale Gauntlets-Fine":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Knight's Linen Insignia":1},
		"Knight's Reinforced Scale Helm-Fine":{"Darksteel Helmet Lining":1,"Knight's Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Knight's Reinforced Scale Legs-Fine":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Knight's Linen Insignia":1},
		"Knight's Reinforced Scale Pauldrons-Fine":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Knight's Linen Insignia":1},
		"Major Rune of the Fighter":{"Crystal Shard":2,"Steel Ingot":1},
		"Major Rune of the Soldier":{"Molten Shard":2,"Darksteel Ingot":1,"Vial of Thick Blood":1},
		"Valkyrie Reinforced Scale Boots-Fine":{"Darksteel Boot Lining":1,"Darksteel Boot Casing":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Reinforced Scale Chest-Fine":{"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Reinforced Scale Gauntlets-Fine":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Reinforced Scale Helm-Fine":{"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Reinforced Scale Legs-Fine":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Reinforced Scale Pauldrons-Fine":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Valkyrie Linen Insignia":1}
	},
	"250":{
		"Berserker's Reinforced Scale Boots-Fine":{"Darksteel Boot Lining":1,"Berserker's Linen Insignia":1,"Darksteel Boot Casing":1},
		"Berserker's Reinforced Scale Chest-Fine":{"Darksteel Chestplate Padding":1,"Berserker's Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Berserker's Reinforced Scale Gauntlets-Fine":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Berserker's Linen Insignia":1},
		"Berserker's Reinforced Scale Helm-Fine":{"Darksteel Helmet Lining":1,"Berserker's Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Berserker's Reinforced Scale Legs-Fine":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Berserker's Linen Insignia":1},
		"Berserker's Reinforced Scale Pauldrons-Fine":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Berserker's Linen Insignia":1},
		"Cleric's Reinforced Scale Boots-Fine":{"Darksteel Boot Lining":1,"Cleric's Linen Insignia":1,"Darksteel Boot Casing":1},
		"Cleric's Reinforced Scale Chest-Fine":{"Darksteel Chestplate Padding":1,"Cleric's Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Cleric's Reinforced Scale Gauntlets-Fine":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Cleric's Linen Insignia":1},
		"Cleric's Reinforced Scale Helm-Fine":{"Darksteel Helmet Lining":1,"Cleric's Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Cleric's Reinforced Scale Legs-Fine":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Cleric's Linen Insignia":1},
		"Cleric's Reinforced Scale Pauldrons-Fine":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Cleric's Linen Insignia":1},
		"Explorer's Reinforced Scale Boots-Fine":{"Darksteel Boot Lining":1,"Explorer's Linen Insignia":1,"Darksteel Boot Casing":1},
		"Explorer's Reinforced Scale Chest-Fine":{"Darksteel Chestplate Padding":1,"Explorer's Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Explorer's Reinforced Scale Gauntlets-Fine":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Explorer's Linen Insignia":1},
		"Explorer's Reinforced Scale Helm-Fine":{"Darksteel Helmet Lining":1,"Explorer's Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Explorer's Reinforced Scale Legs-Fine":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Explorer's Linen Insignia":1},
		"Explorer's Reinforced Scale Pauldrons-Fine":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Explorer's Linen Insignia":1},
		"Major Rune of Svanir":{"Darksteel Ingot":1,"Corrupted Shard":2},
		"Major Rune of the Krait":{"Darksteel Ingot":1,"Pile of Filthy Essence":2},
		"Rampager's Reinforced Scale Boots-Fine":{"Rampager's Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Rampager's Reinforced Scale Chest-Fine":{"Rampager's Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Rampager's Reinforced Scale Gauntlets-Fine":{"Rampager's Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Rampager's Reinforced Scale Helm-Fine":{"Rampager's Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Rampager's Reinforced Scale Legs-Fine":{"Rampager's Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Rampager's Reinforced Scale Pauldrons-Fine":{"Rampager's Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1}
	},
	"275":{
		"Major Rune of the Earth":{"Onyx Shard":2,"Darksteel Ingot":1},
		"Major Rune of the Fire":{"Molten Shard":2,"Darksteel Ingot":1},
		"Berserker's Gladiator Boots-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Berserker's Gladiator Chestplate-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Berserker's Gladiator Gauntlets-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Berserker's Gladiator Helm-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Berserker's Gladiator Legplates-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Berserker's Gladiator Pauldrons-t4":{"Berserker's Intricate Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Berserker's Reinforced Scale Boots-Master":{"Berserker's Embroidered Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Berserker's Reinforced Scale Chest-Master":{"Darksteel Chestplate Padding":1,"Berserker's Embroidered Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Berserker's Reinforced Scale Gauntlets-Master":{"Darksteel Gaunlet Plates":1,"Berserker's Embroidered Linen Insignia":1,"Darksteel Gauntlet Lining":1},
		"Berserker's Reinforced Scale Helm-Master":{"Berserker's Embroidered Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Berserker's Reinforced Scale Legs-Master":{"Berserker's Embroidered Linen Insignia":1,"Darksteel Legging Lining":1,"Darksteel Legging Panel":1},
		"Berserker's Reinforced Scale Pauldrons-Master":{"Darksteel Pauldron Casing":1,"Berserker's Embroidered Linen Insignia":1,"Darksteel Pauldron Lining":1},
		"Carrion Gladiator Boots-t4":{"Darksteel Boot Lining":1,"Carrion Intricate Linen Insignia":1,"Darksteel Boot Casing":1},
		"Carrion Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Carrion Intricate Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Carrion Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Gladiator Helm-t4":{"Darksteel Helmet Lining":1,"Carrion Intricate Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Carrion Gladiator Legplates-t4":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Reinforced Scale Boots-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Carrion Reinforced Scale Chest-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Carrion Reinforced Scale Gauntlets-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Carrion Reinforced Scale Helm-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Carrion Reinforced Scale Legs-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Carrion Reinforced Scale Pauldrons-Master":{"Carrion Embroidered Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Cleric's Gladiator Boots-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Cleric's Gladiator Chestplate-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Cleric's Gladiator Gauntlets-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Cleric's Gladiator Helm-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Cleric's Gladiator Legplates-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Cleric's Gladiator Pauldrons-t4":{"Cleric's Intricate Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Cleric's Reinforced Scale Boots-Master":{"Darksteel Boot Lining":1,"Cleric's Embroidered Linen Insignia":1,"Darksteel Boot Casing":1},
		"Cleric's Reinforced Scale Chest-Master":{"Darksteel Chestplate Padding":1,"Cleric's Embroidered Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Cleric's Reinforced Scale Gauntlets-Master":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Reinforced Scale Helm-Master":{"Darksteel Helmet Lining":1,"Cleric's Embroidered Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Cleric's Reinforced Scale Legs-Master":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Reinforced Scale Pauldrons-Master":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Cleric's Embroidered Linen Insignia":1},
		"Explorer's Gladiator Boots-t4":{"Darksteel Boot Lining":1,"Explorer's Intricate Linen Insignia":1,"Darksteel Boot Casing":1},
		"Explorer's Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Explorer's Intricate Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Explorer's Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Gladiator Helm-t4":{"Darksteel Helmet Lining":1,"Explorer's Intricate Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Explorer's Gladiator Legplates-t4":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Reinforced Scale Boots-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Explorer's Reinforced Scale Chest-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Explorer's Reinforced Scale Gauntlets-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Explorer's Reinforced Scale Helm-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Explorer's Reinforced Scale Legs-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Explorer's Reinforced Scale Pauldrons-Master":{"Explorer's Embroidered Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Giver's Gladiator Boots-t4":{"Darksteel Boot Lining":1,"Giver's Embroidered Linen Insignia":1,"Darksteel Boot Casing":1},
		"Giver's Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Giver's Embroidered Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Giver's Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Gladiator Helm-t4":{"Darksteel Helmet Lining":1,"Giver's Embroidered Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Giver's Gladiator Legplates-t4":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Giver's Embroidered Linen Insignia":1},
		"Knight's Gladiator Boots-t4":{"Knight's Intricate Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Knight's Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Knight's Intricate Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Knight's Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Knight's Intricate Linen Insignia":1,"Darksteel Gauntlet Lining":1},
		"Knight's Gladiator Helm-t4":{"Knight's Intricate Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Knight's Gladiator Legplates-t4":{"Knight's Intricate Linen Insignia":1,"Darksteel Legging Lining":1,"Darksteel Legging Panel":1},
		"Knight's Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Knight's Intricate Linen Insignia":1,"Darksteel Pauldron Lining":1},
		"Knight's Reinforced Scale Boots-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Knight's Reinforced Scale Chest-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Chestplate Padding":1,"Darksteel Chestplate Panel":1},
		"Knight's Reinforced Scale Gauntlets-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1},
		"Knight's Reinforced Scale Helm-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Knight's Reinforced Scale Legs-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Legging Panel":1,"Darksteel Legging Lining":1},
		"Knight's Reinforced Scale Pauldrons-Master":{"Knight's Embroidered Linen Insignia":1,"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1},
		"Rampager's Gladiator Boots-t4":{"Rampager's Intricate Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Rampager's Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Rampager's Intricate Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Rampager's Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Rampager's Intricate Linen Insignia":1,"Darksteel Gauntlet Lining":1},
		"Rampager's Gladiator Helm-t4":{"Rampager's Intricate Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Rampager's Gladiator Legplates-t4":{"Rampager's Intricate Linen Insignia":1,"Darksteel Legging Lining":1,"Darksteel Legging Panel":1},
		"Rampager's Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Rampager's Intricate Linen Insignia":1,"Darksteel Pauldron Lining":1},
		"Rampager's Reinforced Scale Boots-Master":{"Darksteel Boot Lining":1,"Rampager's Embroidered Linen Insignia":1,"Darksteel Boot Casing":1},
		"Rampager's Reinforced Scale Chest-Master":{"Darksteel Chestplate Padding":1,"Rampager's Embroidered Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Rampager's Reinforced Scale Gauntlets-Master":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Rampager's Embroidered Linen Insignia":1},
		"Rampager's Reinforced Scale Helm-Master":{"Darksteel Helmet Lining":1,"Rampager's Embroidered Linen Insignia":1,"Darksteel Helmet Casing":1},
		"Rampager's Reinforced Scale Legs-Master":{"Darksteel Legging Panel":1,"Darksteel Legging Lining":1,"Rampager's Embroidered Linen Insignia":1},
		"Rampager's Reinforced Scale Pauldrons-Master":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Rampager's Embroidered Linen Insignia":1},
		"Valkyrie Gladiator Boots-t4":{"Valkyrie Intricate Linen Insignia":1,"Darksteel Boot Casing":1,"Darksteel Boot Lining":1},
		"Valkyrie Gladiator Chestplate-t4":{"Darksteel Chestplate Padding":1,"Valkyrie Intricate Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Valkyrie Gladiator Gauntlets-t4":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Valkyrie Intricate Linen Insignia":1},
		"Valkyrie Gladiator Helm-t4":{"Valkyrie Intricate Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Valkyrie Gladiator Legplates-t4":{"Darksteel Legging Panel":1,"Valkyrie Intricate Linen Insignia":1,"Darksteel Legging Lining":1},
		"Valkyrie Gladiator Pauldrons-t4":{"Darksteel Pauldron Casing":1,"Darksteel Pauldron Lining":1,"Valkyrie Intricate Linen Insignia":1},
		"Valkyrie Reinforced Scale Boots-Master":{"Valkyrie Embroidered Linen Insignia":1,"Darksteel Boot Lining":1,"Darksteel Boot Casing":1},
		"Valkyrie Reinforced Scale Chest-Master":{"Darksteel Chestplate Padding":1,"Valkyrie Embroidered Linen Insignia":1,"Darksteel Chestplate Panel":1},
		"Valkyrie Reinforced Scale Gauntlets-Master":{"Darksteel Gaunlet Plates":1,"Darksteel Gauntlet Lining":1,"Valkyrie Embroidered Linen Insignia":1},
		"Valkyrie Reinforced Scale Helm-Master":{"Valkyrie Embroidered Linen Insignia":1,"Darksteel Helmet Lining":1,"Darksteel Helmet Casing":1},
		"Valkyrie Reinforced Scale Legs-Master":{"Darksteel Legging Panel":1,"Valkyrie Embroidered Linen Insignia":1,"Darksteel Legging Lining":1},
		"Valkyrie Reinforced Scale Pauldrons-Master":{"Darksteel Pauldron Casing":1,"Valkyrie Embroidered Linen Insignia":1,"Darksteel Pauldron Lining":1},
	},
	"300":{
		"Major Rune of Altruism":{"Mithril Ingot":1,"Glacial Core":1,"Pristine Snowflake":1},
		"Bolt of Silk":{"Silk Scrap":2},
		"Carrion Barbaric Boots-Fine":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Carrion Silk Insignia":1},
		"Carrion Barbaric Coat-Fine":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Carrion Silk Insignia":1},
		"Carrion Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Carrion Silk Insignia":1},
		"Carrion Barbaric Helm-Fine":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Carrion Silk Insignia":1},
		"Carrion Barbaric Legplates-Fine":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Carrion Silk Insignia":1},
		"Carrion Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Carrion Silk Insignia":1},
		"Knight's Barbaric Boots-Fine":{"Knight's Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Knight's Barbaric Coat-Fine":{"Mithril Chestplate Padding":1,"Knight's Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Knight's Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Knight's Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Knight's Barbaric Helm-Fine":{"Knight's Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Knight's Barbaric Legplates-Fine":{"Mithril Legging Panel":1,"Knight's Silk Insignia":1,"Mithril Legging Lining":1},
		"Knight's Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Knight's Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Major Rune of the Guardian-2":{"Charged Core":1,"Mithril Ingot":1},
		"Major Rune of the Warrior-2":{"Large Scale":1,"Mithril Ingot":1,"Onyx Core":1},
		"Mithril Boot Casing":{"Mithril Ingot":2},
		"Mithril Boot Lining":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Mithril Chestplate Padding":{"Spool of Silk Thread":3,"Bolt of Silk":1},
		"Mithril Chestplate Panel":{"Mithril Ingot":5},
		"Mithril Gaunlet Plates":{"Mithril Ingot":2},
		"Mithril Gauntlet Lining":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Mithril Helmet Casing":{"Mithril Ingot":1},
		"Mithril Helmet Lining":{"Spool of Silk Thread":1,"Bolt of Silk":2},
		"Mithril Ingot":{"Mithril Ore":2},
		"Mithril Legging Lining":{"Spool of Silk Thread":3,"Bolt of Silk":1},
		"Mithril Legging Panel":{"Mithril Ingot":4},
		"Mithril Pauldron Casing":{"Mithril Ingot":2},
		"Mithril Pauldron Lining":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Valkyrie Barbaric Boots-Fine":{"Valkyrie Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Valkyrie Barbaric Coat-Fine":{"Valkyrie Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Valkyrie Barbaric Gloves-Fine":{"Valkyrie Silk Insignia":1,"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1},
		"Valkyrie Barbaric Helm-Fine":{"Valkyrie Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Valkyrie Barbaric Legplates-Fine":{"Valkyrie Silk Insignia":1,"Mithril Legging Panel":1,"Mithril Legging Lining":1},
		"Valkyrie Barbaric Pauldrons-Fine":{"Valkyrie Silk Insignia":1,"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1}
	},
	"325":{
		"Berserker's Barbaric Boots-Fine":{"Berserker's Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Berserker's Barbaric Coat-Fine":{"Berserker's Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Berserker's Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Berserker's Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Berserker's Barbaric Helm-Fine":{"Berserker's Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Berserker's Barbaric Legplates-Fine":{"Berserker's Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Berserker's Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Berserker's Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Cleric's Barbaric Boots-Fine":{"Cleric's Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Cleric's Barbaric Coat-Fine":{"Cleric's Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Cleric's Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Cleric's Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Cleric's Barbaric Helm-Fine":{"Cleric's Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Cleric's Barbaric Legplates-Fine":{"Cleric's Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Cleric's Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Cleric's Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Explorer's Barbaric Boots-Fine":{"Explorer's Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Explorer's Barbaric Coat-Fine":{"Mithril Chestplate Padding":1,"Explorer's Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Explorer's Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Explorer's Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Explorer's Barbaric Helm-Fine":{"Explorer's Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Explorer's Barbaric Legplates-Fine":{"Mithril Legging Panel":1,"Explorer's Silk Insignia":1,"Mithril Legging Lining":1},
		"Explorer's Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Explorer's Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Major Rune of the Fighter-2":{"Crystal Core":1,"Mithril Ingot":1},
		"Major Rune of the Soldier-2":{"Mithril Ingot":1,"Vial of Potent Blood":1,"Molten Core":1},
		"Rampager's Barbaric Boots-Fine":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Rampager's Silk Insignia":1},
		"Rampager's Barbaric Coat-Fine":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Rampager's Silk Insignia":1},
		"Rampager's Barbaric Gloves-Fine":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Rampager's Silk Insignia":1},
		"Rampager's Barbaric Helm-Fine":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Rampager's Silk Insignia":1},
		"Rampager's Barbaric Legplates-Fine":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Rampager's Silk Insignia":1},
		"Rampager's Barbaric Pauldrons-Fine":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Rampager's Silk Insignia":1}
	},
	"350":{
		"Berserker's Barbaric Boots-Master":{"Mithril Boot Casing":1,"Mithril Boot Lining":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Berserker's Embroidered Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Berserker's Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Barbaric Helm-Master":{"Mithril Helmet Lining":1,"Berserker's Embroidered Silk Insignia":1,"Mithril Helmet Casing":1},
		"Berserker's Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Berserker's Embroidered Silk Insignia":1},
		"Carrion Barbaric Boots-Master":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Barbaric Helm-Master":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Carrion Embroidered Silk Insignia":1},
		"Cleric's Barbaric Boots-Master":{"Cleric's Embroidered Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Cleric's Barbaric Coat-Master":{"Cleric's Embroidered Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Cleric's Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Cleric's Embroidered Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Cleric's Barbaric Helm-Master":{"Cleric's Embroidered Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Cleric's Barbaric Legplates-Master":{"Cleric's Embroidered Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Cleric's Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Cleric's Embroidered Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Explorer's Barbaric Boots-Master":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Barbaric Helm-Master":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Explorer's Embroidered Silk Insignia":1},
		"Knight's Barbaric Boots-Master":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Barbaric Helm-Master":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Knight's Embroidered Silk Insignia":1},
		"Major Rune of Svanir-2":{"Corrupted Core":1,"Mithril Ingot":1},
		"Major Rune of the Krait-2":{"Mithril Ingot":1,"Pile of Vile Essence":1},
		"Rampager's Barbaric Boots-Master":{"Rampager's Embroidered Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Rampager's Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Rampager's Embroidered Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Rampager's Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Rampager's Embroidered Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Rampager's Barbaric Helm-Master":{"Rampager's Embroidered Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Rampager's Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Rampager's Embroidered Silk Insignia":1,"Mithril Legging Lining":1},
		"Rampager's Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Rampager's Embroidered Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Valkyrie Barbaric Boots-Master":{"Mithril Boot Lining":1,"Valkyrie Embroidered Silk Insignia":1,"Mithril Boot Casing":1},
		"Valkyrie Barbaric Coat-Master":{"Mithril Chestplate Padding":1,"Valkyrie Embroidered Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Valkyrie Barbaric Gloves-Master":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Barbaric Helm-Master":{"Mithril Helmet Lining":1,"Valkyrie Embroidered Silk Insignia":1,"Mithril Helmet Casing":1},
		"Valkyrie Barbaric Legplates-Master":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Barbaric Pauldrons-Master":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Valkyrie Embroidered Silk Insignia":1}
	},
	"375":{
		"Major Rune of the Earth-2":{"Mithril Ingot":1,"Onyx Core":1},
		"Major Rune of the Fire-2":{"Mithril Ingot":1,"Molten Core":1},
		"Apothecary's Gladiator Boots-t5":{"Apothecary's Intricate Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Apothecary's Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Apothecary's Intricate Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Apothecary's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Apothecary's Intricate Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Apothecary's Gladiator Helm-t5":{"Apothecary's Intricate Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Apothecary's Gladiator Legplates-t5":{"Mithril Legging Panel":1,"Apothecary's Intricate Silk Insignia":1,"Mithril Legging Lining":1},
		"Apothecary's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Apothecary's Intricate Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Berserker's Gladiator Boots-t5":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Gladiator Helm-t5":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Gladiator Legplates-t5":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Berserker's Intricate Silk Insignia":1},
		"Carrion Gladiator Boots-t5":{"Mithril Boot Casing":1,"Mithril Boot Lining":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Carrion Intricate Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Carrion Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Gladiator Helm-t5":{"Mithril Helmet Lining":1,"Carrion Intricate Silk Insignia":1,"Mithril Helmet Casing":1},
		"Carrion Gladiator Legplates-t5":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Carrion Intricate Silk Insignia":1},
		"Cleric's Gladiator Boots-t5":{"Mithril Boot Lining":1,"Mithril Boot Casing":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Gladiator Helm-t5":{"Mithril Helmet Lining":1,"Mithril Helmet Casing":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Gladiator Legplates-t5":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Cleric's Intricate Silk Insignia":1},
		"Explorer's Gladiator Boots-t5":{"Explorer's Intricate Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Explorer's Gladiator Chestplate-t5":{"Explorer's Intricate Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Explorer's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Explorer's Intricate Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Explorer's Gladiator Helm-t5":{"Explorer's Intricate Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Explorer's Gladiator Legplates-t5":{"Explorer's Intricate Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Explorer's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Explorer's Intricate Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Giver's Gladiator Boots-t5":{"Giver's Embroidered Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Giver's Gladiator Chestplate-t5":{"Giver's Embroidered Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Giver's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Giver's Embroidered Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Giver's Gladiator Helm-t5":{"Giver's Embroidered Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Giver's Gladiator Legplates-t5":{"Giver's Embroidered Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Giver's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Giver's Embroidered Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Knight's Gladiator Boots-t5":{"Knight's Intricate Silk Insignia":1,"Mithril Boot Lining":1,"Mithril Boot Casing":1},
		"Knight's Gladiator Chestplate-t5":{"Knight's Intricate Silk Insignia":1,"Mithril Chestplate Padding":1,"Mithril Chestplate Panel":1},
		"Knight's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Knight's Intricate Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Knight's Gladiator Helm-t5":{"Knight's Intricate Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Knight's Gladiator Legplates-t5":{"Knight's Intricate Silk Insignia":1,"Mithril Legging Lining":1,"Mithril Legging Panel":1},
		"Knight's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Knight's Intricate Silk Insignia":1,"Mithril Pauldron Lining":1},
		"Rampager's Gladiator Boots-t5":{"Mithril Boot Casing":1,"Mithril Boot Lining":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Rampager's Intricate Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Rampager's Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Mithril Gaunlet Plates":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Gladiator Helm-t5":{"Mithril Helmet Lining":1,"Rampager's Intricate Silk Insignia":1,"Mithril Helmet Casing":1},
		"Rampager's Gladiator Legplates-t5":{"Mithril Legging Panel":1,"Mithril Legging Lining":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Rampager's Intricate Silk Insignia":1},
		"Valkyrie Gladiator Boots-t5":{"Valkyrie Intricate Silk Insignia":1,"Mithril Boot Casing":1,"Mithril Boot Lining":1},
		"Valkyrie Gladiator Chestplate-t5":{"Mithril Chestplate Padding":1,"Valkyrie Intricate Silk Insignia":1,"Mithril Chestplate Panel":1},
		"Valkyrie Gladiator Gauntlets-t5":{"Mithril Gauntlet Lining":1,"Valkyrie Intricate Silk Insignia":1,"Mithril Gaunlet Plates":1},
		"Valkyrie Gladiator Helm-t5":{"Valkyrie Intricate Silk Insignia":1,"Mithril Helmet Lining":1,"Mithril Helmet Casing":1},
		"Valkyrie Gladiator Legplates-t5":{"Mithril Legging Lining":1,"Mithril Legging Panel":1,"Valkyrie Intricate Silk Insignia":1},
		"Valkyrie Gladiator Pauldrons-t5":{"Mithril Pauldron Casing":1,"Mithril Pauldron Lining":1,"Valkyrie Intricate Silk Insignia":1},
	},
}
