# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/1/2013
Last Updated: 1/1/2013
Purpose: Recipe list for Artificing used by Crafting.py
'''
artificer = {
	"0":{
		"Bronze Ingot":{"Copper Ore":2,"Lump of Tin":1},
		"Green Wood Dowel":{"Green Wood Plank":1},
		"Green Wood Plank":{"Green Wood Log":3},
		"Apprentice Tuning Crystal":{"Pile of Glittering Dust":6},
		"Bronze Trident Head":{"Bronze Ingot":2},
		"Green Focus Casing":{"Green Wood Plank":3},
		"Green Focus Core":{"Green Wood Plank":2},
		"Green Scepter Core":{"Green Wood Plank":2},
		"Green Scepter Rod":{"Green Wood Plank":3},
		"Green Staff Head":{"Green Wood Plank":2},
		"Green Staff Shaft":{"Green Wood Plank":6},
		"Green Trident Shaft":{"Green Wood Plank":2},
		"Minor Sigil of Frailty":{"Crystal Sliver":2,"Bronze Ingot":1},
		"Malign Crude Focus-Fine":{"Green Focus Core":1,"Malign Green Inscription":1,"Green Focus Casing":1},
		"Malign Crude Scepter-Fine":{"Malign Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Malign Crude Staff-Fine":{"Malign Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Malign Crude Trident-Fine":{"Bronze Trident Head":1,"Malign Green Inscription":1,"Green Trident Shaft":1},
		"Mighty Crude Focus-Fine":{"Mighty Green Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Mighty Crude Scepter-Fine":{"Mighty Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Mighty Crude Staff-Fine":{"Mighty Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Mighty Crude Trident-Fine":{"Mighty Green Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Vital Crude Focus-Fine":{"Vital Green Inscription":1,"Green Focus Casing":1,"Green Focus Core":1},
		"Vital Crude Scepter-Fine":{"Vital Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Vital Crude Staff-Fine":{"Vital Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Vital Crude Trident-Fine":{"Bronze Trident Head":1,"Vital Green Inscription":1,"Green Trident Shaft":1}
	},
	"25":{
		"Minor Sigil of Impact":{"Onyx Sliver":2,"Bronze Ingot":1},
		"Healing Crude Focus-Fine":{"Healing Green Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Healing Crude Scepter-Fine":{"Healing Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Healing Crude Staff-Fine":{"Healing Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Healing Crude Trident-Fine":{"Healing Green Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Precise Crude Focus-Fine":{"Green Focus Core":1,"Green Focus Casing":1,"Precise Green Inscription":1},
		"Precise Crude Scepter-Fine":{"Green Scepter Rod":1,"Precise Green Inscription":1,"Green Scepter Core":1},
		"Precise Crude Staff-Fine":{"Green Staff Head":1,"Precise Green Inscription":1,"Green Staff Shaft":1},
		"Precise Crude Trident-Fine":{"Bronze Trident Head":1,"Precise Green Inscription":1,"Green Trident Shaft":1},
		"Resilient Crude Focus-Fine":{"Resilient Green Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Resilient Crude Scepter-Fine":{"Resilient Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Resilient Crude Staff-Fine":{"Resilient Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Resilient Crude Trident-Fine":{"Resilient Green Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Weak Potion of Centaur Slaying":{"Pile of Glittering Dust":1,"Carrot":1,"Rawhide Leather Section":1,"Jug of Water":1},
		"Weak Potion of Flame Legion Slaying":{"Pile of Glittering Dust":1,"Tiny Claw":1,"Vial of Weak Blood":1,"Iron Ingot":1},
		"Weak Potion of Inquest Slaying":{"Garnet Pebble":1,"Green Focus Core":1,"Pile of Glittering Dust":1,"Jug of Water":1},
		"Weak Potion of Nightmare Court Slaying":{"Head of Lettuce":1,"Spinach Leaf":1,"Tiny Venom Sac":1,"Jug of Water":1},
		"Weak Potion of Outlaw Slaying":{"Pile of Glittering Dust":1,"Vial of Weak Blood":1,"Jug of Water":1,"Slab of Red Meat":1},
		"Weak Potion of Sons of Svanir Slaying":{"Pile of Glittering Dust":1,"Tiny Claw":1,"Tiny Totem":1,"Jug of Water":1},
		"Giver's Crude Focus-Fine":{"Green Focus Core":1,"Giver's Green Inscription":1,"Green Focus Casing":1},
		"Giver's Crude Scepter-Fine":{"Giver's Green Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Giver's Crude Staff-Fine":{"Giver's Green Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Giver's Crude Trident-Fine":{"Bronze Trident Head":1,"Giver's Green Inscription":1,"Green Trident Shaft":1}
	},
	"50":{
		"Bronze Plated Dowel":{"Green Wood Plank":2,"Bronze Ingot":3},
		"Minor Sigil of Elemental Slaying":{"Glacial Sliver":2,"Bronze Ingot":1},
		"Healing Crude Focus-Master":{"Healing Bronze Plated Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Healing Crude Scepter-Master":{"Healing Bronze Plated Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Healing Crude Staff-Master":{"Healing Bronze Plated Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Healing Crude Trident-Master":{"Healing Bronze Plated Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Malign Crude Focus-Master":{"Green Focus Core":1,"Green Focus Casing":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Scepter-Master":{"Green Scepter Rod":1,"Green Scepter Core":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Staff-Master":{"Green Staff Head":1,"Green Staff Shaft":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Trident-Master":{"Bronze Trident Head":1,"Green Trident Shaft":1,"Malign Bronze Plated Inscription":1},
		"Mighty Crude Focus-Master":{"Mighty Bronze Plated Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Mighty Crude Scepter-Master":{"Mighty Bronze Plated Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Mighty Crude Staff-Master":{"Mighty Bronze Plated Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Mighty Crude Trident-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Precise Crude Focus-Master":{"Precise Bronze Plated Inscription":1,"Green Focus Core":1,"Green Focus Casing":1},
		"Precise Crude Scepter-Master":{"Precise Bronze Plated Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Precise Crude Staff-Master":{"Precise Bronze Plated Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Precise Crude Trident-Master":{"Precise Bronze Plated Inscription":1,"Bronze Trident Head":1,"Green Trident Shaft":1},
		"Resilient Crude Focus-Master":{"Green Focus Casing":1,"Green Focus Core":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Crude Scepter-Master":{"Resilient Bronze Plated Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Resilient Crude Staff-Master":{"Green Staff Head":1,"Resilient Bronze Plated Inscription":1,"Green Staff Shaft":1},
		"Resilient Crude Trident-Master":{"Bronze Trident Head":1,"Resilient Bronze Plated Inscription":1,"Green Trident Shaft":1},
		"Vital Crude Focus-Master":{"Green Focus Core":1,"Vital Bronze Plated Inscription":1,"Green Focus Casing":1},
		"Vital Crude Scepter-Master":{"Vital Bronze Plated Inscription":1,"Green Scepter Rod":1,"Green Scepter Core":1},
		"Vital Crude Staff-Master":{"Vital Bronze Plated Inscription":1,"Green Staff Head":1,"Green Staff Shaft":1},
		"Vital Crude Trident-Master":{"Bronze Trident Head":1,"Vital Bronze Plated Inscription":1,"Green Trident Shaft":1},
		"Weak Potion of Demon Slaying":{"Pile of Glittering Dust":1,"Tiny Totem":1,"Vial of Weak Blood":1,"Jug of Water":1},
		"Weak Potion of Destroyer Slaying":{"Destroyer Sliver":1,"Pile of Glittering Dust":1,"Jug of Water":1,"Lump of Coal":1},
		"Weak Potion of Dredge Slaying":{"Pile of Glittering Dust":1,"Copper Ore":1,"Lump of Tin":1,"Jug of Water":1},
		"Weak Potion of Elemental Slaying":{"Garnet Pebble":1,"Turquoise Pebble":1,"Pile of Glittering Dust":1,"Jug of Water":1},
		"Weak Potion of Grawl Slaying":{"Pile of Glittering Dust":1,"Tiny Totem":1,"Jug of Water":1,"Mushroom":1},
		"Weak Potion of Halloween Slaying":{"Nougat Center":5,"Pile of Glittering Dust":1,"Jug of Water":1,"Chattering Skull":5},
		"Weak Potion of Ice Brood Slaying":{"Tiny Scale":1,"Pile of Glittering Dust":1,"Jug of Water":1,"Corrupted Sliver":1},
		"Weak Potion of Krait Slaying":{"Adorned Pearl":1,"Pile of Glittering Dust":1,"Jug of Water":1,"Tiny Fang":1},
		"Weak Potion of Ogre Slaying":{"Pile of Glittering Dust":1,"Sage Leaf":1,"Rawhide Leather Section":1,"Jug of Water":1},
		"Weak Potion of Undead Slaying":{"Pile of Glittering Dust":1,"Bone Chip":1,"Pile of Soiled Essence":1,"Jug of Water":1}
	},
	"75":{
		"Iron Ingot":{"Iron Ore":3},
		"Soft Wood Dowel":{"Soft Wood Plank":1},
		"Soft Wood Plank":{"Soft Wood Log":4},
		"Iron Trident Head":{"Iron Ingot":2},
		"Journeyman Tuning Crystal":{"Pile of Shimmering Dust":6},
		"Minor Sigil of Luck":{"Copper Doubloon":2,"Iron Ingot":1},
		"Soft Focus Casing":{"Soft Wood Plank":3},
		"Soft Focus Core":{"Soft Wood Plank":2},
		"Soft Scepter Core":{"Soft Wood Plank":2},
		"Soft Scepter Rod":{"Soft Wood Plank":3},
		"Soft Staff Head":{"Soft Wood Plank":2},
		"Soft Staff Shaft":{"Soft Wood Plank":6},
		"Soft Trident Shaft":{"Soft Wood Plank":2},
		"Pillaging Simple Focus-Fine":{"Pillaging Soft Inscription":1,"Soft Focus Core":1,"Soft Focus Casing":1},
		"Pillaging Simple Scepter-Fine":{"Pillaging Soft Inscription":1,"Soft Scepter Rod":1,"Soft Scepter Core":1},
		"Pillaging Simple Staff-Fine":{"Pillaging Soft Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Pillaging Simple Trident-Fine":{"Iron Trident Head":1,"Pillaging Soft Inscription":1,"Soft Trident Shaft":1},
		"Ravaging Simple Focus-Fine":{"Soft Focus Casing":1,"Soft Focus Core":1,"Ravaging Soft Inscription":1},
		"Ravaging Simple Scepter-Fine":{"Soft Scepter Rod":1,"Ravaging Soft Inscription":1,"Soft Scepter Core":1},
		"Ravaging Simple Staff-Fine":{"Soft Staff Head":1,"Ravaging Soft Inscription":1,"Soft Staff Shaft":1},
		"Ravaging Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Ravaging Soft Inscription":1},
		"Vigorous Simple Focus-Fine":{"Soft Focus Core":1,"Vigorous Soft Inscription":1,"Soft Focus Casing":1},
		"Vigorous Simple Scepter-Fine":{"Soft Scepter Rod":1,"Vigorous Soft Inscription":1,"Soft Scepter Core":1},
		"Vigorous Simple Staff-Fine":{"Vigorous Soft Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Vigorous Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Vigorous Soft Inscription":1}
	},
	"100":{
		"Minor Potion of Centaur Slaying":{"Carrot":1,"Thin Leather Section":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Flame Legion Slaying":{"Vial of Thin Blood":1,"Small Claw":1,"Iron Ingot":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Inquest Slaying":{"Peridot Nugget":1,"Soft Focus Core":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Nightmare Court Slaying":{"Head of Lettuce":1,"Spinach Leaf":1,"Jug of Water":1,"Small Venom Sac":1},
		"Minor Potion of Outlaw Slaying":{"Vial of Thin Blood":1,"Slab of Red Meat":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Sons of Svanir Slaying":{"Small Totem":1,"Small Claw":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Sigil of Frailty-2":{"Crystal Fragment":1,"Iron Ingot":1},
		"Hearty Simple Focus-Fine":{"Soft Focus Core":1,"Soft Focus Casing":1,"Hearty Soft Inscription":1},
		"Hearty Simple Scepter-Fine":{"Soft Scepter Rod":1,"Soft Scepter Core":1,"Hearty Soft Inscription":1},
		"Hearty Simple Staff-Fine":{"Soft Staff Head":1,"Soft Staff Shaft":1,"Hearty Soft Inscription":1},
		"Hearty Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Hearty Soft Inscription":1},
		"Honed Simple Focus-Fine":{"Soft Focus Casing":1,"Soft Focus Core":1,"Honed Soft Inscription":1},
		"Honed Simple Scepter-Fine":{"Soft Scepter Rod":1,"Honed Soft Inscription":1,"Soft Scepter Core":1},
		"Honed Simple Staff-Fine":{"Soft Staff Head":1,"Honed Soft Inscription":1,"Soft Staff Shaft":1},
		"Honed Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Honed Soft Inscription":1},
		"Rejuvenating Simple Focus-Fine":{"Soft Focus Core":1,"Rejuvenating Soft Inscription":1,"Soft Focus Casing":1},
		"Rejuvenating Simple Scepter-Fine":{"Soft Scepter Rod":1,"Rejuvenating Soft Inscription":1,"Soft Scepter Core":1},
		"Rejuvenating Simple Staff-Fine":{"Rejuvenating Soft Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Rejuvenating Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Rejuvenating Soft Inscription":1},
		"Strong Simple Focus-Fine":{"Soft Focus Core":1,"Soft Focus Casing":1,"Strong Soft Inscription":1},
		"Strong Simple Scepter-Fine":{"Soft Scepter Rod":1,"Soft Scepter Core":1,"Strong Soft Inscription":1},
		"Strong Simple Staff-Fine":{"Soft Staff Head":1,"Soft Staff Shaft":1,"Strong Soft Inscription":1},
		"Strong Simple Trident-Fine":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Strong Soft Inscription":1}
	},
	"125":{
		"Iron Plated Dowel":{"Soft Wood Plank":2,"Iron Ingot":3},
		"Minor Potion of Demon Slaying":{"Small Totem":1,"Vial of Thin Blood":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Destroyer Slaying":{"Destroyer Sliver":1,"Jug of Water":1,"Pile of Shimmering Dust":1,"Lump of Coal":1},
		"Minor Potion of Dredge Slaying":{"Iron Ore":1,"Jug of Water":1,"Silver Ore":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Elemental Slaying":{"Carnelian Nugget":1,"Lapis Nugget":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Grawl Slaying":{"Small Totem":1,"Jug of Water":1,"Pile of Shimmering Dust":1,"Mushroom":1},
		"Minor Potion of Halloween Slaying":{"Nougat Center":10,"Jug of Water":1,"Pile of Shimmering Dust":1,"Plastic Fang":10},
		"Minor Potion of Krait Slaying":{"Adorned Pearl":1,"Small Fang":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Ogre Slaying":{"Sage Leaf":1,"Thin Leather Section":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Potion of Undead Slaying":{"Bone Shard":1,"Pile of Soiled Essence":1,"Jug of Water":1,"Pile of Shimmering Dust":1},
		"Minor Sigil of Impact-2":{"Onyx Fragment":1,"Iron Ingot":1},
		"Hearty Bandit Baton":{"Hearty Iron Imbued Inscription":1,"Soft Scepter Rod":1,"Soft Scepter Core":1},
		"Hearty Bandit Focus":{"Hearty Iron Imbued Inscription":1,"Soft Focus Core":1,"Soft Focus Casing":1},
		"Hearty Bandit Spire":{"Hearty Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Hearty Bandit Trident":{"Iron Trident Head":1,"Hearty Iron Imbued Inscription":1,"Soft Trident Shaft":1},
		"Hearty Simple Focus-Master":{"Soft Focus Core":1,"Hearty Iron Plated Inscription":1,"Soft Focus Casing":1},
		"Hearty Simple Scepter-Master":{"Soft Scepter Rod":1,"Hearty Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Hearty Simple Staff-Master":{"Hearty Iron Plated Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Hearty Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Hearty Iron Plated Inscription":1},
		"Honed Bandit Baton":{"Soft Scepter Rod":1,"Honed Iron Imbued Inscription":1,"Soft Scepter Core":1},
		"Honed Bandit Focus":{"Soft Focus Core":1,"Honed Iron Imbued Inscription":1,"Soft Focus Casing":1},
		"Honed Bandit Spire":{"Honed Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Honed Bandit Trident":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Honed Iron Imbued Inscription":1},
		"Honed Simple Focus-Master":{"Soft Focus Core":1,"Soft Focus Casing":1,"Honed Iron Plated Inscription":1},
		"Honed Simple Scepter-Master":{"Soft Scepter Rod":1,"Honed Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Honed Simple Staff-Master":{"Soft Staff Head":1,"Honed Iron Plated Inscription":1,"Soft Staff Shaft":1},
		"Honed Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Honed Iron Plated Inscription":1},
		"Pillaging Bandit Baton":{"Pillaging Iron Imbued Inscription":1,"Soft Scepter Rod":1,"Soft Scepter Core":1},
		"Pillaging Bandit Focus":{"Pillaging Iron Imbued Inscription":1,"Soft Focus Core":1,"Soft Focus Casing":1},
		"Pillaging Bandit Spire":{"Pillaging Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Pillaging Bandit Trident":{"Pillaging Iron Imbued Inscription":1,"Iron Trident Head":1,"Soft Trident Shaft":1},
		"Pillaging Simple Focus-Master":{"Pillaging Iron Plated Inscription":1,"Soft Focus Casing":1,"Soft Focus Core":1},
		"Pillaging Simple Scepter-Master":{"Soft Scepter Rod":1,"Pillaging Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Pillaging Simple Staff-Master":{"Pillaging Iron Plated Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Pillaging Simple Trident-Master":{"Iron Trident Head":1,"Pillaging Iron Plated Inscription":1,"Soft Trident Shaft":1},
		"Ravaging Bandit Baton":{"Soft Scepter Rod":1,"Ravaging Iron Imbued Inscription":1,"Soft Scepter Core":1},
		"Ravaging Bandit Focus":{"Soft Focus Core":1,"Ravaging Iron Imbued Inscription":1,"Soft Focus Casing":1},
		"Ravaging Bandit Spire":{"Ravaging Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Ravaging Bandit Trident":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Ravaging Iron Imbued Inscription":1},
		"Ravaging Simple Focus-Master":{"Ravaging Iron Plated Inscription":1,"Soft Focus Core":1,"Soft Focus Casing":1},
		"Ravaging Simple Scepter-Master":{"Ravaging Iron Plated Inscription":1,"Soft Scepter Rod":1,"Soft Scepter Core":1},
		"Ravaging Simple Staff-Master":{"Ravaging Iron Plated Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Ravaging Simple Trident-Master":{"Iron Trident Head":1,"Ravaging Iron Plated Inscription":1,"Soft Trident Shaft":1},
		"Rejuvenating Bandit Baton":{"Soft Scepter Rod":1,"Rejuvenating Iron Imbued Inscription":1,"Soft Scepter Core":1},
		"Rejuvenating Bandit Focus":{"Rejuvenating Iron Imbued Inscription":1,"Soft Focus Casing":1,"Soft Focus Core":1},
		"Rejuvenating Bandit Spire":{"Rejuvenating Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Rejuvenating Bandit Trident":{"Iron Trident Head":1,"Rejuvenating Iron Imbued Inscription":1,"Soft Trident Shaft":1},
		"Rejuvenating Simple Focus-Master":{"Soft Focus Casing":1,"Soft Focus Core":1,"Rejuvenating Iron Plated Inscription":1},
		"Rejuvenating Simple Scepter-Master":{"Soft Scepter Rod":1,"Rejuvenating Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Rejuvenating Simple Staff-Master":{"Soft Staff Head":1,"Rejuvenating Iron Plated Inscription":1,"Soft Staff Shaft":1},
		"Rejuvenating Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Rejuvenating Iron Plated Inscription":1},
		"Strong Bandit Baton":{"Strong Iron Imbued Inscription":1,"Soft Scepter Rod":1,"Soft Scepter Core":1},
		"Strong Bandit Focus":{"Strong Iron Imbued Inscription":1,"Soft Focus Core":1,"Soft Focus Casing":1},
		"Strong Bandit Spire":{"Strong Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Strong Bandit Trident":{"Iron Trident Head":1,"Strong Iron Imbued Inscription":1,"Soft Trident Shaft":1},
		"Strong Simple Focus-Master":{"Soft Focus Core":1,"Strong Iron Plated Inscription":1,"Soft Focus Casing":1},
		"Strong Simple Scepter-Master":{"Soft Scepter Rod":1,"Strong Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Strong Simple Staff-Master":{"Strong Iron Plated Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Strong Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Strong Iron Plated Inscription":1},
		"Vigorous Bandit Baton":{"Soft Scepter Rod":1,"Vigorous Iron Imbued Inscription":1,"Soft Scepter Core":1},
		"Vigorous Bandit Focus":{"Vigorous Iron Imbued Inscription":1,"Soft Focus Casing":1,"Soft Focus Core":1},
		"Vigorous Bandit Spire":{"Vigorous Iron Imbued Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Vigorous Bandit Trident":{"Iron Trident Head":1,"Vigorous Iron Imbued Inscription":1,"Soft Trident Shaft":1},
		"Vigorous Simple Focus-Master":{"Soft Focus Casing":1,"Soft Focus Core":1,"Vigorous Iron Plated Inscription":1},
		"Vigorous Simple Scepter-Master":{"Soft Scepter Rod":1,"Vigorous Iron Plated Inscription":1,"Soft Scepter Core":1},
		"Vigorous Simple Staff-Master":{"Soft Staff Head":1,"Vigorous Iron Plated Inscription":1,"Soft Staff Shaft":1},
		"Vigorous Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Vigorous Iron Plated Inscription":1},
		"Giver's Simple Focus-Master":{"Soft Focus Core":1,"Giver's Iron-Plated Inscription":1,"Soft Focus Casing":1},
		"Giver's Simple Scepter-Master":{"Soft Scepter Rod":1,"Giver's Iron-Plated Inscription":1,"Soft Scepter Core":1},
		"Giver's Simple Staff-Master":{"Giver's Iron-Plated Inscription":1,"Soft Staff Head":1,"Soft Staff Shaft":1},
		"Giver's Simple Trident-Master":{"Iron Trident Head":1,"Soft Trident Shaft":1,"Giver's Iron-Plated Inscription":1}
	},
	"150":{
		"Seasoned Wood Dowel":{"Seasoned Wood Plank":1},
		"Seasoned Wood Plank":{"Seasoned Wood Log":3},
		"Steel Ingot":{"Iron Ore":3,"Lump of Coal":1},
		"Minor Sigil of Elemental Slaying-2":{"Glacial Fragment":1,"Steel Ingot":1},
		"Seasoned Focus Casing":{"Seasoned Wood Plank":3},
		"Seasoned Focus Core":{"Seasoned Wood Plank":2},
		"Seasoned Scepter Core":{"Seasoned Wood Plank":2},
		"Seasoned Scepter Rod":{"Seasoned Wood Plank":3},
		"Seasoned Staff Head":{"Seasoned Wood Plank":2},
		"Seasoned Staff Shaft":{"Seasoned Wood Plank":6},
		"Seasoned Trident Shaft":{"Seasoned Wood Plank":2},
		"Standard Tuning Crystal":{"Pile of Radiant Dust":6},
		"Steel Trident Head":{"Steel Ingot":2},
		"Pillaging Focus-Fine":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Scepter-Fine":{"Seasoned Scepter Rod":1,"Pillaging Seasoned Inscription":1,"Seasoned Scepter Core":1},
		"Pillaging Staff-Fine":{"Seasoned Staff Head":1,"Pillaging Seasoned Inscription":1,"Seasoned Staff Shaft":1},
		"Pillaging Trident-Fine":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Pillaging Seasoned Inscription":1},
		"Ravaging Focus-Fine":{"Seasoned Focus Casing":1,"Seasoned Focus Core":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Scepter-Fine":{"Seasoned Scepter Rod":1,"Ravaging Seasoned Inscription":1,"Seasoned Scepter Core":1},
		"Ravaging Staff-Fine":{"Seasoned Staff Head":1,"Ravaging Seasoned Inscription":1,"Seasoned Staff Shaft":1},
		"Ravaging Trident-Fine":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Ravaging Seasoned Inscription":1},
		"Vigorous Focus-Fine":{"Seasoned Focus Core":1,"Vigorous Seasoned Inscription":1,"Seasoned Focus Casing":1},
		"Vigorous Scepter-Fine":{"Seasoned Scepter Rod":1,"Vigorous Seasoned Inscription":1,"Seasoned Scepter Core":1},
		"Vigorous Staff-Fine":{"Seasoned Staff Head":1,"Vigorous Seasoned Inscription":1,"Seasoned Staff Shaft":1},
		"Vigorous Trident-Fine":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Vigorous Seasoned Inscription":1}
	},
	"175":{
		"Minor Sigil of Luck-2":{"Steel Ingot":1,"Silver Doubloon":1},
		"Potion of Centaur Slaying":{"Carrot":1,"Coarse Leather Section":1,"Jug of Water":1,"Pile of Radiant Dust":1},
		"Potion of Flame Legion Slaying":{"Claw":1,"Pile of Radiant Dust":1,"Iron Ingot":1,"Vial of Blood":1},
		"Potion of Inquest Slaying":{"Seasoned Focus Core":1,"Peridot Lump":1,"Jug of Water":1,"Pile of Radiant Dust":1},
		"Potion of Nightmare Court Slaying":{"Head of Lettuce":1,"Spinach Leaf":1,"Jug of Water":1,"Venom Sac":1},
		"Potion of Outlaw Slaying":{"Pile of Radiant Dust":1,"Slab of Red Meat":1,"Jug of Water":1,"Vial of Blood":1},
		"Potion of Sons of Svanir Slaying":{"Claw":1,"Pile of Radiant Dust":1,"Jug of Water":1,"Totem":1},
		"Hearty Focus-Fine":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Hearty Seasoned Inscription":1},
		"Hearty Scepter-Fine":{"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1,"Hearty Seasoned Inscription":1},
		"Hearty Staff-Fine":{"Seasoned Staff Head":1,"Seasoned Staff Shaft":1,"Hearty Seasoned Inscription":1},
		"Hearty Trident-Fine":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Hearty Seasoned Inscription":1},
		"Honed Focus-Fine":{"Seasoned Focus Casing":1,"Seasoned Focus Core":1,"Honed Seasoned Inscription":1},
		"Honed Scepter-Fine":{"Seasoned Scepter Rod":1,"Honed Seasoned Inscription":1,"Seasoned Scepter Core":1},
		"Honed Staff-Fine":{"Seasoned Staff Head":1,"Honed Seasoned Inscription":1,"Seasoned Staff Shaft":1},
		"Honed Trident-Fine":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Honed Seasoned Inscription":1},
		"Rejuvenating Focus-Fine":{"Seasoned Focus Core":1,"Rejuvenating Seasoned Inscription":1,"Seasoned Focus Casing":1},
		"Rejuvenating Scepter-Fine":{"Seasoned Scepter Rod":1,"Rejuvenating Seasoned Inscription":1,"Seasoned Scepter Core":1},
		"Rejuvenating Staff-Fine":{"Seasoned Staff Head":1,"Rejuvenating Seasoned Inscription":1,"Seasoned Staff Shaft":1},
		"Rejuvenating Trident-Fine":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Rejuvenating Seasoned Inscription":1},
		"Strong Focus-Fine":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Strong Seasoned Inscription":1},
		"Strong Scepter-Fine":{"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1,"Strong Seasoned Inscription":1},
		"Strong Staff-Fine":{"Seasoned Staff Head":1,"Seasoned Staff Shaft":1,"Strong Seasoned Inscription":1},
		"Strong Trident-Fine":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Strong Seasoned Inscription":1}
	},
	"200":{
		"Steel Plated Dowel":{"Steel Ingot":3,"Seasoned Wood Plank":2},
		"Major Sigil of Frailty":{"Crystal Shard":2,"Steel Ingot":1},
		"Potion of Demon Slaying":{"Pile of Radiant Dust":1,"Jug of Water":1,"Totem":1,"Vial of Blood":1},
		"Potion of Destroyer Slaying":{"Pile of Radiant Dust":1,"Destroyer Fragment":1,"Jug of Water":1,"Lump of Coal":1},
		"Potion of Dredge Slaying":{"Iron Ore":1,"Jug of Water":1,"Gold Ore":1,"Pile of Radiant Dust":1},
		"Potion of Elemental Slaying":{"Amethyst Lump":1,"Lapis Lump":1,"Pile of Radiant Dust":1,"Jug of Water":1},
		"Potion of Grawl Slaying":{"Pile of Radiant Dust":1,"Jug of Water":1,"Totem":1,"Mushroom":1},
		"Potion of Halloween Slaying":{"Pile of Radiant Dust":1,"Jug of Water":1,"Chattering Skull":15,"Plastic Fang":15},
		"Potion of Ice Brood Slaying":{"Pile of Radiant Dust":1,"Scale":1,"Jug of Water":1,"Corrupted Fragment":1},
		"Potion of Krait Slaying":{"Adorned Pearl":1,"Pile of Radiant Dust":1,"Jug of Water":1,"Fang":1},
		"Potion of Ogre Slaying":{"Sage Leaf":1,"Pile of Radiant Dust":1,"Coarse Leather Section":1,"Jug of Water":1},
		"Potion of Undead Slaying":{"Pile of Foul Essence":1,"Pile of Radiant Dust":1,"Jug of Water":1,"Bone":1},
		"Ruminant Tonic":{"Rugged Leather Section":1,"Slab of Red Meat":1,"Jug of Water":1,"Pile of Radiant Dust":1},
		"Hearty Dredge Baton":{"Seasoned Scepter Rod":1,"Hearty Steel Imbued Inscription":1,"Seasoned Scepter Core":1},
		"Hearty Dredge Canary":{"Seasoned Focus Core":1,"Hearty Steel Imbued Inscription":1,"Seasoned Focus Casing":1},
		"Hearty Dredge Pillar":{"Seasoned Staff Head":1,"Hearty Steel Imbued Inscription":1,"Seasoned Staff Shaft":1},
		"Hearty Dredge Trident":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Hearty Steel Imbued Inscription":1},
		"Hearty Focus-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Focus Core":1,"Seasoned Focus Casing":1},
		"Hearty Scepter-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1},
		"Hearty Staff-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Staff Head":1,"Seasoned Staff Shaft":1},
		"Hearty Trident-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Trident Shaft":1,"Steel Trident Head":1},
		"Honed Dredge Baton":{"Seasoned Scepter Rod":1,"Honed Steel Imbued Inscription":1,"Seasoned Scepter Core":1},
		"Honed Dredge Canary":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Pillar":{"Seasoned Staff Head":1,"Honed Steel Imbued Inscription":1,"Seasoned Staff Shaft":1},
		"Honed Dredge Trident":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Honed Steel Imbued Inscription":1},
		"Honed Focus-Master":{"Seasoned Focus Core":1,"Honed Steel Plated Inscription":1,"Seasoned Focus Casing":1},
		"Honed Scepter-Master":{"Seasoned Scepter Rod":1,"Honed Steel Plated Inscription":1,"Seasoned Scepter Core":1},
		"Honed Staff-Master":{"Seasoned Staff Head":1,"Honed Steel Plated Inscription":1,"Seasoned Staff Shaft":1},
		"Honed Trident-Master":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Honed Steel Plated Inscription":1},
		"Pillaging Dredge Baton":{"Seasoned Scepter Rod":1,"Pillaging Steel Imbued Inscription":1,"Seasoned Scepter Core":1},
		"Pillaging Dredge Canary":{"Seasoned Focus Casing":1,"Seasoned Focus Core":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Dredge Pillar":{"Seasoned Staff Head":1,"Pillaging Steel Imbued Inscription":1,"Seasoned Staff Shaft":1},
		"Pillaging Dredge Trident":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Focus-Master":{"Pillaging Steel Plated Inscription":1,"Seasoned Focus Casing":1,"Seasoned Focus Core":1},
		"Pillaging Scepter-Master":{"Seasoned Scepter Rod":1,"Pillaging Steel Plated Inscription":1,"Seasoned Scepter Core":1},
		"Pillaging Staff-Master":{"Pillaging Steel Plated Inscription":1,"Seasoned Staff Head":1,"Seasoned Staff Shaft":1},
		"Pillaging Trident-Master":{"Pillaging Steel Plated Inscription":1,"Steel Trident Head":1,"Seasoned Trident Shaft":1},
		"Ravaging Dredge Baton":{"Seasoned Scepter Rod":1,"Ravaging Steel Imbued Inscription":1,"Seasoned Scepter Core":1},
		"Ravaging Dredge Canary":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Pillar":{"Seasoned Staff Head":1,"Ravaging Steel Imbued Inscription":1,"Seasoned Staff Shaft":1},
		"Ravaging Dredge Trident":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Focus-Master":{"Seasoned Focus Core":1,"Ravaging Steel Plated Inscription":1,"Seasoned Focus Casing":1},
		"Ravaging Scepter-Master":{"Seasoned Scepter Rod":1,"Ravaging Steel Plated Inscription":1,"Seasoned Scepter Core":1},
		"Ravaging Staff-Master":{"Seasoned Staff Head":1,"Ravaging Steel Plated Inscription":1,"Seasoned Staff Shaft":1},
		"Ravaging Trident-Master":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Ravaging Steel Plated Inscription":1},
		"Rejuvenating Dredge Baton":{"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Canary":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Pillar":{"Seasoned Staff Head":1,"Seasoned Staff Shaft":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Trident":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Focus-Master":{"Seasoned Focus Casing":1,"Seasoned Focus Core":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Scepter-Master":{"Seasoned Scepter Rod":1,"Rejuvenating Steel Plated Inscription":1,"Seasoned Scepter Core":1},
		"Rejuvenating Staff-Master":{"Seasoned Staff Head":1,"Rejuvenating Steel Plated Inscription":1,"Seasoned Staff Shaft":1},
		"Rejuvenating Trident-Master":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Rejuvenating Steel Plated Inscription":1},
		"Strong Dredge Baton":{"Seasoned Scepter Rod":1,"Strong Steel Imbued Inscription":1,"Seasoned Scepter Core":1},
		"Strong Dredge Canary":{"Seasoned Focus Core":1,"Strong Steel Imbued Inscription":1,"Seasoned Focus Casing":1},
		"Strong Dredge Pillar":{"Seasoned Staff Head":1,"Strong Steel Imbued Inscription":1,"Seasoned Staff Shaft":1},
		"Strong Dredge Trident":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Strong Steel Imbued Inscription":1},
		"Strong Focus-Master":{"Strong Steel Plated Inscription":1,"Seasoned Focus Core":1,"Seasoned Focus Casing":1},
		"Strong Scepter-Master":{"Strong Steel Plated Inscription":1,"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1},
		"Strong Staff-Master":{"Strong Steel Plated Inscription":1,"Seasoned Staff Head":1,"Seasoned Staff Shaft":1},
		"Strong Trident-Master":{"Strong Steel Plated Inscription":1,"Seasoned Trident Shaft":1,"Steel Trident Head":1},
		"Vigorous Dredge Baton":{"Seasoned Scepter Rod":1,"Seasoned Scepter Core":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Canary":{"Seasoned Focus Core":1,"Seasoned Focus Casing":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Pillar":{"Seasoned Staff Head":1,"Seasoned Staff Shaft":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Trident":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Focus-Master":{"Seasoned Focus Casing":1,"Seasoned Focus Core":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Scepter-Master":{"Seasoned Scepter Rod":1,"Vigorous Steel Plated Inscription":1,"Seasoned Scepter Core":1},
		"Vigorous Staff-Master":{"Seasoned Staff Head":1,"Vigorous Steel Plated Inscription":1,"Seasoned Staff Shaft":1},
		"Vigorous Trident-Master":{"Seasoned Trident Shaft":1,"Steel Trident Head":1,"Vigorous Steel Plated Inscription":1},
		"Giver's Focus-Master":{"Seasoned Focus Core":1,"Giver's Steel-Plated Inscription":1,"Seasoned Focus Casing":1},
		"Giver's Scepter-Master":{"Seasoned Scepter Rod":1,"Giver's Steel-Plated Inscription":1,"Seasoned Scepter Core":1},
		"Giver's Staff-Master":{"Seasoned Staff Head":1,"Giver's Steel-Plated Inscription":1,"Seasoned Staff Shaft":1},
		"Giver's Trident-Master":{"Steel Trident Head":1,"Seasoned Trident Shaft":1,"Giver's Steel-Plated Inscription":1}
	},
	"225":{
		"Darksteel Ingot":{"Lump of Primordium":1,"Platinum Ore":2},
		"Hard Wood Dowel":{"Hard Wood Plank":1},
		"Hard Wood Plank":{"Hard Wood Log":3},
		"Artisan Tuning Crystal":{"Pile of Luminous Dust":6},
		"Darksteel Trident Head":{"Darksteel Ingot":2},
		"Hard Focus Casing":{"Hard Wood Plank":3},
		"Hard Focus Core":{"Hard Wood Plank":2},
		"Hard Scepter Core":{"Hard Wood Plank":2},
		"Hard Scepter Rod":{"Hard Wood Plank":3},
		"Hard Staff Head":{"Hard Wood Plank":2},
		"Hard Staff Shaft":{"Hard Wood Plank":6},
		"Hard Trident Shaft":{"Hard Wood Plank":2},
		"Major Sigil of Impact":{"Onyx Shard":2,"Darksteel Ingot":1},
		"Carrion Hard Focus-Fine":{"Hard Focus Casing":1,"Carrion Hard Inscription":1,"Hard Focus Core":1},
		"Carrion Hard Scepter-Fine":{"Hard Scepter Core":1,"Carrion Hard Inscription":1,"Hard Scepter Rod":1},
		"Carrion Hard Staff-Fine":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Carrion Hard Inscription":1},
		"Carrion Hard Trident-Fine":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Carrion Hard Inscription":1},
		"Knight's Hard Focus-Fine":{"Hard Focus Casing":1,"Knight's Hard Inscription":1,"Hard Focus Core":1},
		"Knight's Hard Scepter-Fine":{"Hard Scepter Core":1,"Knight's Hard Inscription":1,"Hard Scepter Rod":1},
		"Knight's Hard Staff-Fine":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Knight's Hard Inscription":1},
		"Knight's Hard Trident-Fine":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Knight's Hard Inscription":1},
		"Valkyrie Hard Focus-Fine":{"Valkyrie Hard Inscription":1,"Hard Focus Core":1,"Hard Focus Casing":1},
		"Valkyrie Hard Scepter-Fine":{"Valkyrie Hard Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Valkyrie Hard Staff-Fine":{"Hard Staff Shaft":1,"Valkyrie Hard Inscription":1,"Hard Staff Head":1},
		"Valkyrie Hard Trident-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Trident Head":1,"Hard Trident Shaft":1}
	},
	"250":{
		"Major Sigil of Elemental Slaying":{"Darksteel Ingot":1,"Glacial Shard":2},
		"Strong Potion of Centaur Slaying":{"Pile of Luminous Dust":1,"Rugged Leather Section":1,"Carrot":1,"Jug of Water":1},
		"Strong Potion of Flame Legion Slaying":{"Sharp Claw":1,"Vial of Thick Blood":1,"Pile of Luminous Dust":1,"Iron Ingot":1},
		"Strong Potion of Inquest Slaying":{"Pile of Luminous Dust":1,"Ruby Shard":1,"Hard Focus Core":1,"Jug of Water":1},
		"Strong Potion of Nightmare Court Slaying":{"Head of Lettuce":1,"Spinach Leaf":1,"Full Venom Sac":1,"Jug of Water":1},
		"Strong Potion of Outlaw Slaying":{"Pile of Luminous Dust":1,"Vial of Thick Blood":1,"Jug of Water":1,"Slab of Red Meat":1},
		"Strong Potion of Sons of Svanir Slaying":{"Engraved Totem":1,"Sharp Claw":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Berserker's Hard Focus-Fine":{"Hard Focus Casing":1,"Hard Focus Core":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Scepter-Fine":{"Hard Scepter Core":1,"Hard Scepter Rod":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Staff-Fine":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Trident-Fine":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Berserker's Hard Inscription":1},
		"Cleric's Hard Focus-Fine":{"Hard Focus Casing":1,"Cleric's Hard Inscription":1,"Hard Focus Core":1},
		"Cleric's Hard Scepter-Fine":{"Cleric's Hard Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Cleric's Hard Staff-Fine":{"Hard Staff Shaft":1,"Cleric's Hard Inscription":1,"Hard Staff Head":1},
		"Cleric's Hard Trident-Fine":{"Hard Trident Shaft":1,"Cleric's Hard Inscription":1,"Darksteel Trident Head":1},
		"Explorer's Hard Focus-Fine":{"Hard Focus Casing":1,"Explorer's Hard Inscription":1,"Hard Focus Core":1},
		"Explorer's Hard Scepter-Fine":{"Hard Scepter Core":1,"Explorer's Hard Inscription":1,"Hard Scepter Rod":1},
		"Explorer's Hard Staff-Fine":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Explorer's Hard Inscription":1},
		"Explorer's Hard Trident-Fine":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Explorer's Hard Inscription":1},
		"Rampager's Hard Focus-Fine":{"Hard Focus Casing":1,"Rampager's Hard Inscription":1,"Hard Focus Core":1},
		"Rampager's Hard Scepter-Fine":{"Hard Scepter Core":1,"Rampager's Hard Inscription":1,"Hard Scepter Rod":1},
		"Rampager's Hard Staff-Fine":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Rampager's Hard Inscription":1},
		"Rampager's Hard Trident-Fine":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Rampager's Hard Inscription":1}
	},
	"275":{
		"Darksteel Plated Dowel":{"Darksteel Ingot":3,"Hard Wood Plank":2},
		"Major Sigil of Luck":{"Darksteel Ingot":1,"Gold Doubloon":1},
		"Strong Potion of Demon Slaying":{"Engraved Totem":1,"Vial of Thick Blood":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Destroyer Slaying":{"Destroyer Shard":1,"Pile of Luminous Dust":1,"Jug of Water":1,"Lump of Coal":1},
		"Strong Potion of Dredge Slaying":{"Platinum Ore":1,"Gold Ore":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Elemental Slaying":{"Opal Shard":1,"Beryl Shard":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Grawl Slaying":{"Engraved Totem":1,"Pile of Luminous Dust":1,"Jug of Water":1,"Mushroom":1},
		"Strong Potion of Halloween Slaying":{"Nougat Center":20,"Pile of Luminous Dust":1,"Jug of Water":1,"Chattering Skull":20},
		"Strong Potion of Ice Brood Slaying":{"Smooth Scale":1,"Corrupted Shard":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Krait Slaying":{"Sharp Fang":1,"Intricate Sunstone Jewel":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Ogre Slaying":{"Sage Leaf":1,"Rugged Leather Section":1,"Jug of Water":1,"Pile of Luminous Dust":1},
		"Strong Potion of Undead Slaying":{"Pile of Luminous Dust":1,"Heavy Bone":1,"Jug of Water":1,"Pile of Filthy Essence":1},
		"Berserker's Hard Focus-Master":{"Hard Focus Casing":1,"Berserker's Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Berserker's Hard Scepter-Master":{"Berserker's Darksteel Plated Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Berserker's Hard Staff-Master":{"Hard Staff Shaft":1,"Berserker's Darksteel Plated Inscription":1,"Hard Staff Head":1},
		"Berserker's Hard Trident-Master":{"Hard Trident Shaft":1,"Berserker's Darksteel Plated Inscription":1,"Darksteel Trident Head":1},
		"Berserker's Ogre Effigy":{"Hard Focus Casing":1,"Hard Focus Core":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Trident":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Truncheon":{"Hard Scepter Core":1,"Berserker's Darksteel Imbued Inscription":1,"Hard Scepter Rod":1},
		"Berserker's Ogre Warstaff":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Berserker's Darksteel Imbued Inscription":1},
		"Carrion Hard Focus-Master":{"Hard Focus Casing":1,"Carrion Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Carrion Hard Scepter-Master":{"Hard Scepter Core":1,"Carrion Darksteel Plated Inscription":1,"Hard Scepter Rod":1},
		"Carrion Hard Staff-Master":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Hard Trident-Master":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Ogre Effigy":{"Hard Focus Casing":1,"Hard Focus Core":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Trident":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Truncheon":{"Hard Scepter Core":1,"Carrion Darksteel Imbued Inscription":1,"Hard Scepter Rod":1},
		"Carrion Ogre Warstaff":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Carrion Darksteel Imbued Inscription":1},
		"Cleric's Hard Focus-Master":{"Hard Focus Casing":1,"Cleric's Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Cleric's Hard Scepter-Master":{"Cleric's Darksteel Plated Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Cleric's Hard Staff-Master":{"Hard Staff Shaft":1,"Cleric's Darksteel Plated Inscription":1,"Hard Staff Head":1},
		"Cleric's Hard Trident-Master":{"Hard Trident Shaft":1,"Cleric's Darksteel Plated Inscription":1,"Darksteel Trident Head":1},
		"Cleric's Ogre Effigy":{"Cleric's Darksteel Imbued Inscription":1,"Hard Focus Casing":1,"Hard Focus Core":1},
		"Cleric's Ogre Trident":{"Cleric's Darksteel Imbued Inscription":1,"Hard Trident Shaft":1,"Darksteel Trident Head":1},
		"Cleric's Ogre Truncheon":{"Cleric's Darksteel Imbued Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Cleric's Ogre Warstaff":{"Cleric's Darksteel Imbued Inscription":1,"Hard Staff Shaft":1,"Hard Staff Head":1},
		"Explorer's Hard Focus-Master":{"Hard Focus Casing":1,"Explorer's Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Explorer's Hard Scepter-Master":{"Hard Scepter Core":1,"Explorer's Darksteel Plated Inscription":1,"Hard Scepter Rod":1},
		"Explorer's Hard Staff-Master":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Hard Trident-Master":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Ogre Effigy":{"Hard Focus Casing":1,"Hard Focus Core":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Trident":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Truncheon":{"Hard Scepter Core":1,"Explorer's Darksteel Imbued Inscription":1,"Hard Scepter Rod":1},
		"Explorer's Ogre Warstaff":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Explorer's Darksteel Imbued Inscription":1},
		"Knight's Hard Focus-Master":{"Hard Focus Casing":1,"Knight's Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Knight's Hard Scepter-Master":{"Hard Scepter Core":1,"Knight's Darksteel Plated Inscription":1,"Hard Scepter Rod":1},
		"Knight's Hard Staff-Master":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Hard Trident-Master":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Ogre Effigy":{"Hard Focus Casing":1,"Hard Focus Core":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Trident":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Truncheon":{"Hard Scepter Core":1,"Knight's Darksteel Imbued Inscription":1,"Hard Scepter Rod":1},
		"Knight's Ogre Warstaff":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Knight's Darksteel Imbued Inscription":1},
		"Rampager's Hard Focus-Master":{"Hard Focus Casing":1,"Rampager's Darksteel Plated Inscription":1,"Hard Focus Core":1},
		"Rampager's Hard Scepter-Master":{"Hard Scepter Core":1,"Rampager's Darksteel Plated Inscription":1,"Hard Scepter Rod":1},
		"Rampager's Hard Staff-Master":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Hard Trident-Master":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Ogre Effigy":{"Rampager's Darksteel Imbued Inscription":1,"Hard Focus Core":1,"Hard Focus Casing":1},
		"Rampager's Ogre Trident":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Trident Head":1,"Hard Trident Shaft":1},
		"Rampager's Ogre Truncheon":{"Rampager's Darksteel Imbued Inscription":1,"Hard Scepter Core":1,"Hard Scepter Rod":1},
		"Rampager's Ogre Warstaff":{"Hard Staff Shaft":1,"Rampager's Darksteel Imbued Inscription":1,"Hard Staff Head":1},
		"Valkyrie Hard Focus-Master":{"Hard Focus Casing":1,"Hard Focus Core":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Hard Scepter-Master":{"Hard Scepter Core":1,"Valkyrie Darksteel Plated Inscription":1,"Hard Scepter Rod":1},
		"Valkyrie Hard Staff-Master":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Hard Trident-Master":{"Hard Trident Shaft":1,"Darksteel Trident Head":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Ogre Effigy":{"Hard Focus Casing":1,"Valkyrie Darksteel Imbued Inscription":1,"Hard Focus Core":1},
		"Valkyrie Ogre Trident":{"Darksteel Trident Head":1,"Hard Trident Shaft":1,"Valkyrie Darksteel Imbued Inscription":1},
		"Valkyrie Ogre Truncheon":{"Hard Scepter Core":1,"Valkyrie Darksteel Imbued Inscription":1,"Hard Scepter Rod":1},
		"Valkyrie Ogre Warstaff":{"Hard Staff Shaft":1,"Hard Staff Head":1,"Valkyrie Darksteel Imbued Inscription":1}
	},
	"300":{
		"Elder Wood Dowel":{"Elder Wood Plank":1},
		"Elder Wood Plank":{"Elder Wood Log":3},
		"Mithril Ingot":{"Mithril Ore":2},
		"Elder Focus Casing":{"Elder Wood Plank":3},
		"Elder Focus Core":{"Elder Wood Plank":2},
		"Elder Scepter Core":{"Elder Wood Plank":2},
		"Elder Scepter Rod":{"Elder Wood Plank":3},
		"Elder Staff Head":{"Elder Wood Plank":2},
		"Elder Staff Shaft":{"Elder Wood Plank":6},
		"Elder Trident Shaft":{"Elder Wood Plank":2},
		"Major Sigil of Frailty-2":{"Crystal Core":1,"Mithril Ingot":1},
		"Mithril Trident Head":{"Mithril Ingot":2},
		"Quality Tuning Crystal":{"Pile of Incandescent Dust":6},
		"Carrion Elder Focus-Fine":{"Carrion Elder Inscription":1,"Elder Focus Casing":1,"Elder Focus Core":1},
		"Carrion Elder Scepter-Fine":{"Elder Scepter Core":1,"Carrion Elder Inscription":1,"Elder Scepter Rod":1},
		"Carrion Elder Staff-Fine":{"Elder Staff Head":1,"Carrion Elder Inscription":1,"Elder Staff Shaft":1},
		"Carrion Elder Trident-Fine":{"Mithril Trident Head":1,"Carrion Elder Inscription":1,"Elder Trident Shaft":1},
		"Knight's Elder Focus-Fine":{"Elder Focus Core":1,"Elder Focus Casing":1,"Knight's Elder Inscription":1},
		"Knight's Elder Scepter-Fine":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Knight's Elder Inscription":1},
		"Knight's Elder Staff-Fine":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Knight's Elder Inscription":1},
		"Knight's Elder Trident-Fine":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Knight's Elder Inscription":1},
		"Valkyrie Elder Focus-Fine":{"Elder Focus Core":1,"Valkyrie Elder Inscription":1,"Elder Focus Casing":1},
		"Valkyrie Elder Scepter-Fine":{"Elder Scepter Core":1,"Valkyrie Elder Inscription":1,"Elder Scepter Rod":1},
		"Valkyrie Elder Staff-Fine":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Elder Trident-Fine":{"Elder Trident Shaft":1,"Valkyrie Elder Inscription":1,"Mithril Trident Head":1}
	},
	"325":{
		"Major Sigil of Impact-2":{"Mithril Ingot":1,"Onyx Core":1},
		"Potent Potion of Centaur Slaying":{"Thick Leather Section":1,"Carrot":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Flame Legion Slaying":{"Large Claw":1,"Vial of Potent Blood":1,"Pile of Incandescent Dust":1,"Iron Ingot":1},
		"Potent Potion of Inquest Slaying":{"Elder Focus Core":1,"Ruby Crystal":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Nightmare Court Slaying":{"Head of Lettuce":1,"Potent Venom Sac":1,"Spinach Leaf":1,"Jug of Water":1},
		"Potent Potion of Outlaw Slaying":{"Pile of Incandescent Dust":1,"Slab of Red Meat":1,"Jug of Water":1,"Vial of Potent Blood":1},
		"Potent Potion of Sons of Svanir Slaying":{"Jug of Water":1,"Intricate Totem":1,"Large Claw":1,"Pile of Incandescent Dust":1},
		"Berserker's Elder Focus-Fine":{"Elder Focus Core":1,"Elder Focus Casing":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Scepter-Fine":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Staff-Fine":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Trident-Fine":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Berserker's Elder Inscription":1},
		"Cleric's Elder Focus-Fine":{"Elder Focus Core":1,"Elder Focus Casing":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Scepter-Fine":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Staff-Fine":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Trident-Fine":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Cleric's Elder Inscription":1},
		"Explorer's Elder Focus-Fine":{"Elder Focus Core":1,"Elder Focus Casing":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Scepter-Fine":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Staff-Fine":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Trident-Fine":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Explorer's Elder Inscription":1},
		"Rampager's Elder Focus-Fine":{"Rampager's Elder Inscription":1,"Elder Focus Casing":1,"Elder Focus Core":1},
		"Rampager's Elder Scepter-Fine":{"Elder Scepter Core":1,"Rampager's Elder Inscription":1,"Elder Scepter Rod":1},
		"Rampager's Elder Staff-Fine":{"Elder Staff Head":1,"Rampager's Elder Inscription":1,"Elder Staff Shaft":1},
		"Rampager's Elder Trident-Fine":{"Mithril Trident Head":1,"Rampager's Elder Inscription":1,"Elder Trident Shaft":1}
	},
	"350":{
		"Mithril Plated Dowel":{"Mithril Ingot":3,"Elder Wood Plank":2},
		"Major Sigil of Elemental Slaying-2":{"Mithril Ingot":1,"Glacial Core":1},
		"Potent Potion of Demon Slaying":{"Pile of Incandescent Dust":1,"Intricate Totem":1,"Jug of Water":1,"Vial of Potent Blood":1},
		"Potent Potion of Destroyer Slaying":{"Destroyer Core":1,"Jug of Water":1,"Pile of Incandescent Dust":1,"Lump of Coal":1},
		"Potent Potion of Dredge Slaying":{"Pile of Incandescent Dust":1,"Mithril Ore":1,"Jug of Water":1,"Platinum Ore":1},
		"Potent Potion of Elemental Slaying":{"Sapphire Crystal":1,"Ruby Crystal":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Grawl Slaying":{"Intricate Totem":1,"Jug of Water":1,"Pile of Incandescent Dust":1,"Mushroom":1},
		"Potent Potion of Halloween Slaying":{"Nougat Center":25,"Jug of Water":1,"Pile of Incandescent Dust":1,"Plastic Fang":25},
		"Potent Potion of Ice Brood Slaying":{"Large Scale":1,"Corrupted Core":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Krait Slaying":{"Intricate Sunstone Jewel":1,"Large Fang":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Ogre Slaying":{"Thick Leather Section":1,"Sage Leaf":1,"Jug of Water":1,"Pile of Incandescent Dust":1},
		"Potent Potion of Undead Slaying":{"Pile of Incandescent Dust":1,"Large Bone":1,"Jug of Water":1,"Pile of Vile Essence":1},
		"Berserker's Elder Focus-Master":{"Elder Focus Core":1,"Elder Focus Casing":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Scepter-Master":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Trident-Master":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Berserker's Mithril Plated Inscription":1},
		"Carrion Elder Focus-Master":{"Elder Focus Core":1,"Carrion Mithril Plated Inscription":1,"Elder Focus Casing":1},
		"Carrion Elder Scepter-Master":{"Elder Scepter Core":1,"Carrion Mithril Plated Inscription":1,"Elder Scepter Rod":1},
		"Carrion Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Elder Trident-Master":{"Elder Trident Shaft":1,"Carrion Mithril Plated Inscription":1,"Mithril Trident Head":1},
		"Cleric's Elder Focus-Master":{"Elder Focus Core":1,"Elder Focus Casing":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Scepter-Master":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Trident-Master":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Cleric's Mithril Plated Inscription":1},
		"Explorer's Elder Focus-Master":{"Elder Focus Core":1,"Explorer's Mithril Plated Inscription":1,"Elder Focus Casing":1},
		"Explorer's Elder Scepter-Master":{"Elder Scepter Core":1,"Explorer's Mithril Plated Inscription":1,"Elder Scepter Rod":1},
		"Explorer's Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Elder Trident-Master":{"Elder Trident Shaft":1,"Explorer's Mithril Plated Inscription":1,"Mithril Trident Head":1},
		"Knight's Elder Focus-Master":{"Elder Focus Core":1,"Knight's Mithril Plated Inscription":1,"Elder Focus Casing":1},
		"Knight's Elder Scepter-Master":{"Elder Scepter Core":1,"Knight's Mithril Plated Inscription":1,"Elder Scepter Rod":1},
		"Knight's Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Elder Trident-Master":{"Elder Trident Shaft":1,"Knight's Mithril Plated Inscription":1,"Mithril Trident Head":1},
		"Rampager's Elder Focus-Master":{"Elder Focus Core":1,"Rampager's Mithril Plated Inscription":1,"Elder Focus Casing":1},
		"Rampager's Elder Scepter-Master":{"Elder Scepter Core":1,"Rampager's Mithril Plated Inscription":1,"Elder Scepter Rod":1},
		"Rampager's Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Elder Trident-Master":{"Elder Trident Shaft":1,"Rampager's Mithril Plated Inscription":1,"Mithril Trident Head":1},
		"Valkyrie Elder Focus-Master":{"Elder Focus Core":1,"Elder Focus Casing":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Scepter-Master":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Staff-Master":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Trident-Master":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Valkyrie Mithril Plated Inscription":1}
	},
	"375":{
		"Berserker's Krait Crook":{"Berserker's Mithril Imbued Inscription":1,"Elder Staff Head":1,"Elder Staff Shaft":1},
		"Berserker's Krait Star":{"Berserker's Mithril Imbued Inscription":1,"Elder Focus Core":1,"Elder Focus Casing":1},
		"Berserker's Krait Trident":{"Berserker's Mithril Imbued Inscription":1,"Elder Trident Shaft":1,"Mithril Trident Head":1},
		"Berserker's Krait Wand":{"Berserker's Mithril Imbued Inscription":1,"Elder Scepter Core":1,"Elder Scepter Rod":1},
		"Carrion Krait Crook":{"Elder Staff Head":1,"Carrion Mithril Imbued Inscription":1,"Elder Staff Shaft":1},
		"Carrion Krait Star":{"Carrion Mithril Imbued Inscription":1,"Elder Focus Casing":1,"Elder Focus Core":1},
		"Carrion Krait Trident":{"Mithril Trident Head":1,"Carrion Mithril Imbued Inscription":1,"Elder Trident Shaft":1},
		"Carrion Krait Wand":{"Elder Scepter Core":1,"Carrion Mithril Imbued Inscription":1,"Elder Scepter Rod":1},
		"Cleric's Krait Crook":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Star":{"Elder Focus Core":1,"Elder Focus Casing":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Trident":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Wand":{"Elder Scepter Rod":1,"Elder Scepter Core":1,"Cleric's Mithril Imbued Inscription":1},
		"Explorer's Krait Crook":{"Elder Staff Head":1,"Explorer's Mithril Imbued Inscription":1,"Elder Staff Shaft":1},
		"Explorer's Krait Star":{"Explorer's Mithril Imbued Inscription":1,"Elder Focus Casing":1,"Elder Focus Core":1},
		"Explorer's Krait Trident":{"Mithril Trident Head":1,"Explorer's Mithril Imbued Inscription":1,"Elder Trident Shaft":1},
		"Explorer's Krait Wand":{"Elder Scepter Core":1,"Explorer's Mithril Imbued Inscription":1,"Elder Scepter Rod":1},
		"Knight's Krait Crook":{"Elder Staff Head":1,"Knight's Mithril Imbued Inscription":1,"Elder Staff Shaft":1},
		"Knight's Krait Star":{"Knight's Mithril Imbued Inscription":1,"Elder Focus Casing":1,"Elder Focus Core":1},
		"Knight's Krait Trident":{"Mithril Trident Head":1,"Knight's Mithril Imbued Inscription":1,"Elder Trident Shaft":1},
		"Knight's Krait Wand":{"Elder Scepter Core":1,"Knight's Mithril Imbued Inscription":1,"Elder Scepter Rod":1},
		"Rampager's Krait Crook":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Star":{"Elder Focus Core":1,"Elder Focus Casing":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Trident":{"Mithril Trident Head":1,"Elder Trident Shaft":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Wand":{"Elder Scepter Core":1,"Elder Scepter Rod":1,"Rampager's Mithril Imbued Inscription":1},
		"Valkyrie Krait Crook":{"Elder Staff Head":1,"Elder Staff Shaft":1,"Valkyrie Mithril Imbued Inscription":1},
		"Valkyrie Krait Star":{"Elder Focus Core":1,"Valkyrie Mithril Imbued Inscription":1,"Elder Focus Casing":1},
		"Valkyrie Krait Trident":{"Elder Trident Shaft":1,"Valkyrie Mithril Imbued Inscription":1,"Mithril Trident Head":1},
		"Valkyrie Krait Wand":{"Elder Scepter Core":1,"Valkyrie Mithril Imbued Inscription":1,"Elder Scepter Rod":1}
	}
}
