# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/3/2013
Last Updated: 1/3/2013
Purpose: Recipe list for Huntsman used by Crafting.py
'''
huntsman = {
	"0":{
		"Apprentice Maintenance Oil":{"Pile of Glittering Dust":4,"Jug of Water":3},
		"Bronze Horn":{"Green Wood Plank":2,"Bronze Ingot":1},
		"Bronze Ingot":{"Copper Ore":2,"Lump of Tin":1},
		"Bronze Pistol Barrel":{"Bronze Ingot":3},
		"Bronze Rifle Barrel":{"Bronze Ingot":3},
		"Bronze Torch Head":{"Bronze Ingot":2},
		"Bronze Warhorn Mouthpiece":{"Bronze Ingot":1},
		"Green Harpoon":{"Green Wood Plank":2,"Bronze Ingot":2},
		"Green Longbow Stave":{"Green Wood Plank":4},
		"Green Pistol Frame":{"Green Wood Plank":2},
		"Green Rifle Stock":{"Green Wood Plank":3},
		"Green Short-Bow Stave":{"Green Wood Plank":4},
		"Green Torch Handle":{"Green Wood Plank":2},
		"Green Wood Dowel":{"Green Wood Plank":1},
		"Green Wood Plank":{"Green Wood Log":3},
		"Malign Bronze Pistol-Fine":{"Bronze Pistol Barrel":1,"Malign Green Inscription":1,"Green Pistol Frame":1},
		"Malign Bronze Rifle-Fine":{"Green Rifle Stock":1,"Malign Green Inscription":1,"Bronze Rifle Barrel":1},
		"Malign Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Green Harpoon":1,"Malign Green Inscription":1},
		"Malign Crude Longbow-Fine":{"Green Longbow Stave":1,"Rawhide String":1,"Malign Green Inscription":1},
		"Malign Crude Short Bow-Fine":{"Rawhide String":1,"Malign Green Inscription":1,"Green Short-Bow Stave":1},
		"Malign Crude Torch-Fine":{"Green Torch Handle":1,"Malign Green Inscription":1,"Bronze Torch Head":1},
		"Malign Crude Warhorn-Fine":{"Bronze Horn":1,"Malign Green Inscription":1,"Bronze Warhorn Mouthpiece":1},
		"Mighty Bronze Pistol-Fine":{"Mighty Green Inscription":1,"Green Pistol Frame":1,"Bronze Pistol Barrel":1},
		"Mighty Bronze Rifle-Fine":{"Green Rifle Stock":1,"Mighty Green Inscription":1,"Bronze Rifle Barrel":1},
		"Mighty Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Mighty Green Inscription":1,"Green Harpoon":1},
		"Mighty Crude Longbow-Fine":{"Mighty Green Inscription":1,"Rawhide String":1,"Green Longbow Stave":1},
		"Mighty Crude Short Bow-Fine":{"Mighty Green Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Mighty Crude Torch-Fine":{"Mighty Green Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Mighty Crude Warhorn-Fine":{"Bronze Horn":1,"Mighty Green Inscription":1,"Bronze Warhorn Mouthpiece":1},
		"Minor Sigil of Speed":{"Charged Sliver":2,"Bronze Ingot":1},
		"Rawhide String":{"Stretched Rawhide Leather Square":2},
		"Stretched Rawhide Leather Square":{"Rawhide Leather Section":2},
		"Vital Bronze Pistol-Fine":{"Bronze Pistol Barrel":1,"Vital Green Inscription":1,"Green Pistol Frame":1},
		"Vital Bronze Rifle-Fine":{"Green Rifle Stock":1,"Vital Green Inscription":1,"Bronze Rifle Barrel":1},
		"Vital Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Green Harpoon":1,"Vital Green Inscription":1},
		"Vital Crude Longbow-Fine":{"Green Longbow Stave":1,"Vital Green Inscription":1,"Rawhide String":1},
		"Vital Crude Short Bow-Fine":{"Vital Green Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Vital Crude Torch-Fine":{"Green Torch Handle":1,"Vital Green Inscription":1,"Bronze Torch Head":1},
		"Vital Crude Warhorn-Fine":{"Bronze Horn":1,"Vital Green Inscription":1,"Bronze Warhorn Mouthpiece":1}
	},
	"25":{
		"Giver's Bronze Pistol-Fine":{"Bronze Pistol Barrel":1,"Giver's Green Inscription":1,"Green Pistol Frame":1},
		"Giver's Bronze Rifle-Fine":{"Green Rifle Stock":1,"Giver's Green Inscription":1,"Bronze Rifle Barrel":1},
		"Giver's Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Green Harpoon":1,"Giver's Green Inscription":1},
		"Giver's Crude Longbow-Fine":{"Green Longbow Stave":1,"Rawhide String":1,"Giver's Green Inscription":1},
		"Giver's Crude Short Bow-Fine":{"Rawhide String":1,"Giver's Green Inscription":1,"Green Short-Bow Stave":1},
		"Giver's Crude Torch-Fine":{"Green Torch Handle":1,"Giver's Green Inscription":1,"Bronze Torch Head":1},
		"Giver's Crude Warhorn-Fine":{"Bronze Horn":1,"Giver's Green Inscription":1,"Bronze Warhorn Mouthpiece":1},
		"Healing Bronze Pistol-Fine":{"Healing Green Inscription":1,"Bronze Pistol Barrel":1,"Green Pistol Frame":1},
		"Healing Bronze Rifle-Fine":{"Healing Green Inscription":1,"Green Rifle Stock":1,"Bronze Rifle Barrel":1},
		"Healing Crude Harpoon Gun-Fine":{"Healing Green Inscription":1,"Green Harpoon":1,"Green Rifle Stock":1},
		"Healing Crude Longbow-Fine":{"Healing Green Inscription":1,"Green Longbow Stave":1,"Rawhide String":1},
		"Healing Crude Short Bow-Fine":{"Healing Green Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Healing Crude Torch-Fine":{"Healing Green Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Healing Crude Warhorn-Fine":{"Healing Green Inscription":1,"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1},
		"Minor Sigil of Paralyzation":{"Onyx Sliver":2,"Bronze Ingot":1},
		"Precise Bronze Pistol-Fine":{"Bronze Pistol Barrel":1,"Green Pistol Frame":1,"Precise Green Inscription":1},
		"Precise Bronze Rifle-Fine":{"Green Rifle Stock":1,"Bronze Rifle Barrel":1,"Precise Green Inscription":1},
		"Precise Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Green Harpoon":1,"Precise Green Inscription":1},
		"Precise Crude Longbow-Fine":{"Green Longbow Stave":1,"Rawhide String":1,"Precise Green Inscription":1},
		"Precise Crude Short Bow-Fine":{"Rawhide String":1,"Green Short-Bow Stave":1,"Precise Green Inscription":1},
		"Precise Crude Torch-Fine":{"Green Torch Handle":1,"Precise Green Inscription":1,"Bronze Torch Head":1},
		"Precise Crude Warhorn-Fine":{"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1,"Precise Green Inscription":1},
		"Resilient Bronze Pistol-Fine":{"Resilient Green Inscription":1,"Green Pistol Frame":1,"Bronze Pistol Barrel":1},
		"Resilient Bronze Rifle-Fine":{"Green Rifle Stock":1,"Resilient Green Inscription":1,"Bronze Rifle Barrel":1},
		"Resilient Crude Harpoon Gun-Fine":{"Green Rifle Stock":1,"Resilient Green Inscription":1,"Green Harpoon":1},
		"Resilient Crude Longbow-Fine":{"Resilient Green Inscription":1,"Rawhide String":1,"Green Longbow Stave":1},
		"Resilient Crude Short Bow-Fine":{"Resilient Green Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Resilient Crude Torch-Fine":{"Resilient Green Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Resilient Crude Warhorn-Fine":{"Bronze Horn":1,"Resilient Green Inscription":1,"Bronze Warhorn Mouthpiece":1}
	},
	"50":{
		"Bronze Plated Dowel":{"Green Wood Plank":2,"Bronze Ingot":3},
		"Healing Bronze Pistol-Master":{"Healing Bronze Plated Inscription":1,"Green Pistol Frame":1,"Bronze Pistol Barrel":1},
		"Healing Bronze Rifle-Master":{"Green Rifle Stock":1,"Healing Bronze Plated Inscription":1,"Bronze Rifle Barrel":1},
		"Healing Crude Harpoon Gun-Master":{"Green Rifle Stock":1,"Healing Bronze Plated Inscription":1,"Green Harpoon":1},
		"Healing Crude Longbow-Master":{"Healing Bronze Plated Inscription":1,"Rawhide String":1,"Green Longbow Stave":1},
		"Healing Crude Short Bow-Master":{"Healing Bronze Plated Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Healing Crude Torch-Master":{"Healing Bronze Plated Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Healing Crude Warhorn-Master":{"Bronze Horn":1,"Healing Bronze Plated Inscription":1,"Bronze Warhorn Mouthpiece":1},
		"Malign Bronze Pistol-Master":{"Bronze Pistol Barrel":1,"Green Pistol Frame":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Rifle-Master":{"Green Rifle Stock":1,"Bronze Rifle Barrel":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Harpoon Gun-Master":{"Green Rifle Stock":1,"Green Harpoon":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Longbow-Master":{"Green Longbow Stave":1,"Rawhide String":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Short Bow-Master":{"Rawhide String":1,"Green Short-Bow Stave":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Torch-Master":{"Green Torch Handle":1,"Bronze Torch Head":1,"Malign Bronze Plated Inscription":1},
		"Malign Crude Warhorn-Master":{"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1,"Malign Bronze Plated Inscription":1},
		"Mighty Bronze Pistol-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Pistol Barrel":1,"Green Pistol Frame":1},
		"Mighty Bronze Rifle-Master":{"Mighty Bronze Plated Inscription":1,"Green Rifle Stock":1,"Bronze Rifle Barrel":1},
		"Mighty Crude Harpoon Gun-Master":{"Mighty Bronze Plated Inscription":1,"Green Harpoon":1,"Green Rifle Stock":1},
		"Mighty Crude Longbow-Master":{"Mighty Bronze Plated Inscription":1,"Green Longbow Stave":1,"Rawhide String":1},
		"Mighty Crude Short Bow-Master":{"Mighty Bronze Plated Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Mighty Crude Torch-Master":{"Mighty Bronze Plated Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Mighty Crude Warhorn-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1},
		"Minor Sigil of Icebrood Slaying":{"Corrupted Sliver":2,"Bronze Ingot":1},
		"Precise Bronze Pistol-Master":{"Precise Bronze Plated Inscription":1,"Bronze Pistol Barrel":1,"Green Pistol Frame":1},
		"Precise Bronze Rifle-Master":{"Precise Bronze Plated Inscription":1,"Green Rifle Stock":1,"Bronze Rifle Barrel":1},
		"Precise Crude Harpoon Gun-Master":{"Precise Bronze Plated Inscription":1,"Green Harpoon":1,"Green Rifle Stock":1},
		"Precise Crude Longbow-Master":{"Precise Bronze Plated Inscription":1,"Green Longbow Stave":1,"Rawhide String":1},
		"Precise Crude Short Bow-Master":{"Precise Bronze Plated Inscription":1,"Rawhide String":1,"Green Short-Bow Stave":1},
		"Precise Crude Torch-Master":{"Precise Bronze Plated Inscription":1,"Green Torch Handle":1,"Bronze Torch Head":1},
		"Precise Crude Warhorn-Master":{"Precise Bronze Plated Inscription":1,"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1},
		"Resilient Bronze Pistol-Master":{"Bronze Pistol Barrel":1,"Green Pistol Frame":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Bronze Rifle-Master":{"Green Rifle Stock":1,"Resilient Bronze Plated Inscription":1,"Bronze Rifle Barrel":1},
		"Resilient Crude Harpoon Gun-Master":{"Green Rifle Stock":1,"Green Harpoon":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Crude Longbow-Master":{"Green Longbow Stave":1,"Rawhide String":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Crude Short Bow-Master":{"Green Short-Bow Stave":1,"Rawhide String":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Crude Torch-Master":{"Green Torch Handle":1,"Resilient Bronze Plated Inscription":1,"Bronze Torch Head":1},
		"Resilient Crude Warhorn-Master":{"Bronze Horn":1,"Bronze Warhorn Mouthpiece":1,"Resilient Bronze Plated Inscription":1},
		"Vital Bronze Pistol-Master":{"Bronze Pistol Barrel":1,"Vital Bronze Plated Inscription":1,"Green Pistol Frame":1},
		"Vital Bronze Rifle-Master":{"Green Rifle Stock":1,"Vital Bronze Plated Inscription":1,"Bronze Rifle Barrel":1},
		"Vital Crude Harpoon Gun-Master":{"Green Rifle Stock":1,"Green Harpoon":1,"Vital Bronze Plated Inscription":1},
		"Vital Crude Longbow-Master":{"Green Longbow Stave":1,"Rawhide String":1,"Vital Bronze Plated Inscription":1},
		"Vital Crude Short Bow-Master":{"Rawhide String":1,"Vital Bronze Plated Inscription":1,"Green Short-Bow Stave":1},
		"Vital Crude Torch-Master":{"Green Torch Handle":1,"Vital Bronze Plated Inscription":1,"Bronze Torch Head":1},
		"Vital Crude Warhorn-Master":{"Bronze Horn":1,"Vital Bronze Plated Inscription":1,"Bronze Warhorn Mouthpiece":1}
	},
	"75":{
		"Cured Thin Leather Square":{"Thin Leather Section":2},
		"Iron Horn":{"Soft Wood Plank":2,"Iron Ingot":1},
		"Iron Ingot":{"Iron Ore":3},
		"Iron Pistol Barrel":{"Iron Ingot":3},
		"Iron Rifle Barrel":{"Iron Ingot":3},
		"Iron Torch Head":{"Iron Ingot":2},
		"Iron Warhorn Mouthpiece":{"Iron Ingot":1},
		"Journeyman Maintenance Oil":{"Jug of Water":6,"Pile of Shimmering Dust":4},
		"Minor Sigil of Conjuration":{"Pile of Soiled Essence":2,"Iron Ingot":1},
		"Pillaging Iron Pistol-Fine":{"Pillaging Soft Inscription":1,"Iron Pistol Barrel":1,"Soft Pistol Frame":1},
		"Pillaging Iron Rifle-Fine":{"Pillaging Soft Inscription":1,"Iron Rifle Barrel":1,"Soft Rifle Stock":1},
		"Pillaging Journeymen Longbow-Fine":{"Pillaging Soft Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Pillaging Simple Harpoon Gun-Fine":{"Pillaging Soft Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Pillaging Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Pillaging Soft Inscription":1,"Thin String":1},
		"Pillaging Simple Torch-Fine":{"Pillaging Soft Inscription":1,"Iron Torch Head":1,"Soft Torch Handle":1},
		"Pillaging Simple Warhorn-Fine":{"Pillaging Soft Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Ravaging Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Ravaging Soft Inscription":1},
		"Ravaging Iron Rifle-Fine":{"Soft Rifle Stock":1,"Iron Rifle Barrel":1,"Ravaging Soft Inscription":1},
		"Ravaging Journeyman Longbow-Fine":{"Thin String":1,"Ravaging Soft Inscription":1,"Soft Longbow Stave":1},
		"Ravaging Simple Harpoon Gun-Fine":{"Soft Rifle Stock":1,"Ravaging Soft Inscription":1,"Soft Harpoon":1},
		"Ravaging Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Ravaging Soft Inscription":1},
		"Ravaging Simple Torch-Fine":{"Soft Torch Handle":1,"Ravaging Soft Inscription":1,"Iron Torch Head":1},
		"Ravaging Simple Warhorn-Fine":{"Iron Horn":1,"Iron Warhorn Mouthpiece":1,"Ravaging Soft Inscription":1},
		"Soft Harpoon":{"Soft Wood Plank":2,"Iron Ingot":2},
		"Soft Longbow Stave":{"Soft Wood Plank":4},
		"Soft Pistol Frame":{"Soft Wood Plank":2},
		"Soft Rifle Stock":{"Soft Wood Plank":3},
		"Soft Short-Bow Stave":{"Soft Wood Plank":4},
		"Soft Torch Handle":{"Soft Wood Plank":2},
		"Soft Wood Dowel":{"Soft Wood Plank":1},
		"Soft Wood Plank":{"Soft Wood Log":4},
		"Thin String":{"Cured Thin Leather Square":3},
		"Vigorous Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Vigorous Soft Inscription":1,"Soft Pistol Frame":1},
		"Vigorous Iron Rifle-Fine":{"Iron Rifle Barrel":1,"Vigorous Soft Inscription":1,"Soft Rifle Stock":1},
		"Vigorous Journeymen Longbow-Fine":{"Thin String":1,"Vigorous Soft Inscription":1,"Soft Longbow Stave":1},
		"Vigorous Simple Harpoon Gun-Fine":{"Vigorous Soft Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Vigorous Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Vigorous Soft Inscription":1},
		"Vigorous Simple Torch-Fine":{"Soft Torch Handle":1,"Vigorous Soft Inscription":1,"Iron Torch Head":1},
		"Vigorous Simple Warhorn-Fine":{"Vigorous Soft Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1}
	},
	"100":{
		"Hearty Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Hearty Soft Inscription":1},
		"Hearty Iron Rifle-Fine":{"Iron Rifle Barrel":1,"Soft Rifle Stock":1,"Hearty Soft Inscription":1},
		"Hearty Journeymen Longbow-Fine":{"Thin String":1,"Soft Longbow Stave":1,"Hearty Soft Inscription":1},
		"Hearty Simple Harpoon Gun-Fine":{"Soft Rifle Stock":1,"Soft Harpoon":1,"Hearty Soft Inscription":1},
		"Hearty Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Hearty Soft Inscription":1},
		"Hearty Simple Torch-Fine":{"Soft Torch Handle":1,"Iron Torch Head":1,"Hearty Soft Inscription":1},
		"Hearty Simple Warhorn-Fine":{"Iron Warhorn Mouthpiece":1,"Iron Horn":1,"Hearty Soft Inscription":1},
		"Honed Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Honed Soft Inscription":1},
		"Honed Iron Rifle-Fine":{"Soft Rifle Stock":1,"Iron Rifle Barrel":1,"Honed Soft Inscription":1},
		"Honed Journeymen Longbow-Fine":{"Thin String":1,"Honed Soft Inscription":1,"Soft Longbow Stave":1},
		"Honed Simple Harpoon Gun-Fine":{"Soft Rifle Stock":1,"Honed Soft Inscription":1,"Soft Harpoon":1},
		"Honed Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Honed Soft Inscription":1},
		"Honed Simple Torch-Fine":{"Soft Torch Handle":1,"Honed Soft Inscription":1,"Iron Torch Head":1},
		"Honed Simple Warhorn-Fine":{"Iron Horn":1,"Iron Warhorn Mouthpiece":1,"Honed Soft Inscription":1},
		"Rejuvenating Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Rejuvenating Soft Inscription":1,"Soft Pistol Frame":1},
		"Rejuvenating Iron Rifle-Fine":{"Iron Rifle Barrel":1,"Rejuvenating Soft Inscription":1,"Soft Rifle Stock":1},
		"Rejuvenating Journeymen Longbow-Fine":{"Thin String":1,"Rejuvenating Soft Inscription":1,"Soft Longbow Stave":1},
		"Rejuvenating Simple Harpoon Gun-Fine":{"Rejuvenating Soft Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Rejuvenating Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Rejuvenating Soft Inscription":1},
		"Rejuvenating Simple Torch-Fine":{"Soft Torch Handle":1,"Rejuvenating Soft Inscription":1,"Iron Torch Head":1},
		"Rejuvenating Simple Warhorn-Fine":{"Rejuvenating Soft Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Strong Iron Pistol-Fine":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Strong Soft Inscription":1},
		"Strong Iron Rifle-Fine":{"Iron Rifle Barrel":1,"Soft Rifle Stock":1,"Strong Soft Inscription":1},
		"Strong Journeymen Longbow-Fine":{"Thin String":1,"Soft Longbow Stave":1,"Strong Soft Inscription":1},
		"Strong Simple Harpoon Gun-Fine":{"Soft Rifle Stock":1,"Soft Harpoon":1,"Strong Soft Inscription":1},
		"Strong Simple Short Bow-Fine":{"Soft Short-Bow Stave":1,"Thin String":1,"Strong Soft Inscription":1},
		"Strong Simple Torch-Fine":{"Soft Torch Handle":1,"Iron Torch Head":1,"Strong Soft Inscription":1},
		"Strong Simple Warhorn-Fine":{"Iron Warhorn Mouthpiece":1,"Iron Horn":1,"Strong Soft Inscription":1}
	},
	"125":{
		"Giver's Iron Pistol-Master":{"Iron Pistol Barrel":1,"Giver's Iron-Plated Inscription":1,"Soft Pistol Frame":1},
		"Giver's Iron Rifle-Master":{"Iron Rifle Barrel":1,"Giver's Iron-Plated Inscription":1,"Soft Rifle Stock":1},
		"Giver's Journeyman Longbow-Master":{"Thin String":1,"Giver's Iron-Plated Inscription":1,"Soft Longbow Stave":1},
		"Giver's Simple Harpoon Gun-Master":{"Giver's Iron-Plated Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Giver's Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Giver's Iron-Plated Inscription":1},
		"Giver's Simple Torch-Master":{"Soft Torch Handle":1,"Giver's Iron-Plated Inscription":1,"Iron Torch Head":1},
		"Giver's Simple Warhorn-Master":{"Giver's Iron-Plated Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Hearty Bandit Bugle":{"Hearty Iron Imbued Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Hearty Bandit Harpoon Gun":{"Hearty Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Hearty Bandit Longbow":{"Hearty Iron Imbued Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Hearty Bandit Musket":{"Hearty Iron Imbued Inscription":1,"Iron Rifle Barrel":1,"Soft Rifle Stock":1},
		"Hearty Bandit Revolver":{"Hearty Iron Imbued Inscription":1,"Iron Pistol Barrel":1,"Soft Pistol Frame":1},
		"Hearty Bandit Short Bow":{"Soft Short-Bow Stave":1,"Hearty Iron Imbued Inscription":1,"Thin String":1},
		"Hearty Bandit Torch":{"Hearty Iron Imbued Inscription":1,"Iron Torch Head":1,"Soft Torch Handle":1},
		"Hearty Iron Pistol-Master":{"Iron Pistol Barrel":1,"Hearty Iron Plated Inscription":1,"Soft Pistol Frame":1},
		"Hearty Iron Rifle-Master":{"Iron Rifle Barrel":1,"Hearty Iron Plated Inscription":1,"Soft Rifle Stock":1},
		"Hearty Journeymen Longbow-Master":{"Thin String":1,"Hearty Iron Plated Inscription":1,"Soft Longbow Stave":1},
		"Hearty Simple Harpoon Gun-Master":{"Hearty Iron Plated Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Hearty Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Hearty Iron Plated Inscription":1},
		"Hearty Simple Torch-Master":{"Soft Torch Handle":1,"Hearty Iron Plated Inscription":1,"Iron Torch Head":1},
		"Hearty Simple Warhorn-Master":{"Hearty Iron Plated Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Honed Bandit Bugle":{"Honed Iron Imbued Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Honed Bandit Harpoon Gun":{"Honed Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Honed Bandit Longbow":{"Thin String":1,"Honed Iron Imbued Inscription":1,"Soft Longbow Stave":1},
		"Honed Bandit Musket":{"Iron Rifle Barrel":1,"Honed Iron Imbued Inscription":1,"Soft Rifle Stock":1},
		"Honed Bandit Revolver":{"Iron Pistol Barrel":1,"Honed Iron Imbued Inscription":1,"Soft Pistol Frame":1},
		"Honed Bandit Short Bow":{"Soft Short-Bow Stave":1,"Thin String":1,"Honed Iron Imbued Inscription":1},
		"Honed Bandit Torch":{"Soft Torch Handle":1,"Honed Iron Imbued Inscription":1,"Iron Torch Head":1},
		"Honed Iron Pistol-Master":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Honed Iron Plated Inscription":1},
		"Honed Iron Rifle-Master":{"Iron Rifle Barrel":1,"Soft Rifle Stock":1,"Honed Iron Plated Inscription":1},
		"Honed Journeymen Longbow-Master":{"Soft Longbow Stave":1,"Thin String":1,"Honed Iron Plated Inscription":1},
		"Honed Simple Harpoon Gun-Master":{"Soft Rifle Stock":1,"Honed Iron Plated Inscription":1,"Soft Harpoon":1},
		"Honed Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Honed Iron Plated Inscription":1},
		"Honed Simple Torch-Master":{"Soft Torch Handle":1,"Iron Torch Head":1,"Honed Iron Plated Inscription":1},
		"Honed Simple Warhorn-Master":{"Iron Warhorn Mouthpiece":1,"Iron Horn":1,"Honed Iron Plated Inscription":1},
		"Iron Plated Dowel":{"Soft Wood Plank":2,"Iron Ingot":3},
		"Minor Sigil of Paralyzation-2":{"Onyx Fragment":1,"Iron Ingot":1},
		"Pillaging Bandit Bugle":{"Pillaging Iron Imbued Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Pillaging Bandit Harpoon Gun":{"Pillaging Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Pillaging Bandit Longbow":{"Pillaging Iron Imbued Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Pillaging Bandit Musket":{"Pillaging Iron Imbued Inscription":1,"Iron Rifle Barrel":1,"Soft Rifle Stock":1},
		"Pillaging Bandit Revolver":{"Pillaging Iron Imbued Inscription":1,"Iron Pistol Barrel":1,"Soft Pistol Frame":1},
		"Pillaging Bandit Short Bow":{"Pillaging Iron Imbued Inscription":1,"Soft Short-Bow Stave":1,"Thin String":1},
		"Pillaging Bandit Torch":{"Pillaging Iron Imbued Inscription":1,"Soft Torch Handle":1,"Iron Torch Head":1},
		"Pillaging Iron Pistol-Master":{"Iron Pistol Barrel":1,"Pillaging Iron Plated Inscription":1,"Soft Pistol Frame":1},
		"Pillaging Iron Rifle-Master":{"Iron Rifle Barrel":1,"Pillaging Iron Plated Inscription":1,"Soft Rifle Stock":1},
		"Pillaging Journeymen Longbow-Master":{"Pillaging Iron Plated Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Pillaging Simple Harpoon Gun-Master":{"Pillaging Iron Plated Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Pillaging Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Pillaging Iron Plated Inscription":1,"Thin String":1},
		"Pillaging Simple Torch-Master":{"Soft Torch Handle":1,"Pillaging Iron Plated Inscription":1,"Iron Torch Head":1},
		"Pillaging Simple Warhorn-Master":{"Pillaging Iron Plated Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Ravaging Bandit Bugle":{"Ravaging Iron Imbued Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Ravaging Bandit Harpoon Gun":{"Ravaging Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Ravaging Bandit Longbow":{"Thin String":1,"Ravaging Iron Imbued Inscription":1,"Soft Longbow Stave":1},
		"Ravaging Bandit Musket":{"Iron Rifle Barrel":1,"Ravaging Iron Imbued Inscription":1,"Soft Rifle Stock":1},
		"Ravaging Bandit Revolver":{"Iron Pistol Barrel":1,"Ravaging Iron Imbued Inscription":1,"Soft Pistol Frame":1},
		"Ravaging Bandit Short Bow":{"Soft Short-Bow Stave":1,"Thin String":1,"Ravaging Iron Imbued Inscription":1},
		"Ravaging Bandit Torch":{"Soft Torch Handle":1,"Ravaging Iron Imbued Inscription":1,"Iron Torch Head":1},
		"Ravaging Iron Pistol-Master":{"Ravaging Iron Plated Inscription":1,"Iron Pistol Barrel":1,"Soft Pistol Frame":1},
		"Ravaging Iron Rifle-Master":{"Ravaging Iron Plated Inscription":1,"Iron Rifle Barrel":1,"Soft Rifle Stock":1},
		"Ravaging Simple Harpoon Gun-Master":{"Ravaging Iron Plated Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Ravaging Simple Longbow-Master":{"Ravaging Iron Plated Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Ravaging Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Ravaging Iron Plated Inscription":1,"Thin String":1},
		"Ravaging Simple Torch-Master":{"Ravaging Iron Plated Inscription":1,"Iron Torch Head":1,"Soft Torch Handle":1},
		"Ravaging Simple Warhorn-Master":{"Ravaging Iron Plated Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Rejuvenating Bandit Bugle":{"Rejuvenating Iron Imbued Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Rejuvenating Bandit Harpoon Gun":{"Rejuvenating Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Rejuvenating Bandit Longbow":{"Rejuvenating Iron Imbued Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Rejuvenating Bandit Musket":{"Iron Rifle Barrel":1,"Rejuvenating Iron Imbued Inscription":1,"Soft Rifle Stock":1},
		"Rejuvenating Bandit Revolver":{"Iron Pistol Barrel":1,"Rejuvenating Iron Imbued Inscription":1,"Soft Pistol Frame":1},
		"Rejuvenating Bandit Short Bow":{"Soft Short-Bow Stave":1,"Rejuvenating Iron Imbued Inscription":1,"Thin String":1},
		"Rejuvenating Bandit Torch":{"Soft Torch Handle":1,"Rejuvenating Iron Imbued Inscription":1,"Iron Torch Head":1},
		"Rejuvenating Iron Pistol-Master":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Rejuvenating Iron Plated Inscription":1},
		"Rejuvenating Iron Rifle-Master":{"Soft Rifle Stock":1,"Iron Rifle Barrel":1,"Rejuvenating Iron Plated Inscription":1},
		"Rejuvenating Journeymen Longbow-Master":{"Thin String":1,"Rejuvenating Iron Plated Inscription":1,"Soft Longbow Stave":1},
		"Rejuvenating Simple Harpoon Gun-Master":{"Soft Rifle Stock":1,"Rejuvenating Iron Plated Inscription":1,"Soft Harpoon":1},
		"Rejuvenating Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Rejuvenating Iron Plated Inscription":1},
		"Rejuvenating Simple Torch-Master":{"Soft Torch Handle":1,"Rejuvenating Iron Plated Inscription":1,"Iron Torch Head":1},
		"Rejuvenating Simple Warhorn-Master":{"Iron Horn":1,"Iron Warhorn Mouthpiece":1,"Rejuvenating Iron Plated Inscription":1},
		"Strong Bandit Bugle":{"Strong Iron Imbued Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Strong Bandit Harpoon Gun":{"Strong Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Strong Bandit Longbow":{"Strong Iron Imbued Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Strong Bandit Musket":{"Strong Iron Imbued Inscription":1,"Iron Rifle Barrel":1,"Soft Rifle Stock":1},
		"Strong Bandit Revolver":{"Strong Iron Imbued Inscription":1,"Iron Pistol Barrel":1,"Soft Pistol Frame":1},
		"Strong Bandit Short Bow":{"Soft Short-Bow Stave":1,"Strong Iron Imbued Inscription":1,"Thin String":1},
		"Strong Bandit Torch":{"Strong Iron Imbued Inscription":1,"Iron Torch Head":1,"Soft Torch Handle":1},
		"Strong Iron Pistol-Master":{"Iron Pistol Barrel":1,"Strong Iron Plated Inscription":1,"Soft Pistol Frame":1},
		"Strong Iron Rifle-Master":{"Iron Rifle Barrel":1,"Strong Iron Plated Inscription":1,"Soft Rifle Stock":1},
		"Strong Journeymen Longbow-Master":{"Thin String":1,"Strong Iron Plated Inscription":1,"Soft Longbow Stave":1},
		"Strong Simple Harpoon Gun-Master":{"Strong Iron Plated Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Strong Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Strong Iron Plated Inscription":1},
		"Strong Simple Torch-Master":{"Soft Torch Handle":1,"Strong Iron Plated Inscription":1,"Iron Torch Head":1},
		"Strong Simple Warhorn-Master":{"Strong Iron Plated Inscription":1,"Iron Horn":1,"Iron Warhorn Mouthpiece":1},
		"Vigorous Bandit Bugle":{"Vigorous Iron Imbued Inscription":1,"Iron Warhorn Mouthpiece":1,"Iron Horn":1},
		"Vigorous Bandit Harpoon Gun":{"Vigorous Iron Imbued Inscription":1,"Soft Rifle Stock":1,"Soft Harpoon":1},
		"Vigorous Bandit Longbow":{"Vigorous Iron Imbued Inscription":1,"Thin String":1,"Soft Longbow Stave":1},
		"Vigorous Bandit Musket":{"Iron Rifle Barrel":1,"Vigorous Iron Imbued Inscription":1,"Soft Rifle Stock":1},
		"Vigorous Bandit Revolver":{"Iron Pistol Barrel":1,"Vigorous Iron Imbued Inscription":1,"Soft Pistol Frame":1},
		"Vigorous Bandit Short Bow":{"Soft Short-Bow Stave":1,"Vigorous Iron Imbued Inscription":1,"Thin String":1},
		"Vigorous Bandit Torch":{"Soft Torch Handle":1,"Vigorous Iron Imbued Inscription":1,"Iron Torch Head":1},
		"Vigorous Iron Pistol-Master":{"Iron Pistol Barrel":1,"Soft Pistol Frame":1,"Vigorous Iron Plated Inscription":1},
		"Vigorous Iron Rifle-Master":{"Soft Rifle Stock":1,"Iron Rifle Barrel":1,"Vigorous Iron Plated Inscription":1},
		"Vigorous Journeymen Longbow-Master":{"Thin String":1,"Vigorous Iron Plated Inscription":1,"Soft Longbow Stave":1},
		"Vigorous Simple Harpoon Gun-Master":{"Soft Rifle Stock":1,"Vigorous Iron Plated Inscription":1,"Soft Harpoon":1},
		"Vigorous Simple Short Bow-Master":{"Soft Short-Bow Stave":1,"Thin String":1,"Vigorous Iron Plated Inscription":1},
		"Vigorous Simple Torch-Master":{"Soft Torch Handle":1,"Vigorous Iron Plated Inscription":1,"Iron Torch Head":1},
		"Vigorous Simple Warhorn-Master":{"Iron Horn":1,"Iron Warhorn Mouthpiece":1,"Vigorous Iron Plated Inscription":1}
	},
	"150":{
		"Coarse String":{"Cured Coarse Leather Square":3},
		"Cured Coarse Leather Square":{"Coarse Leather Section":2},
		"Pillaging Harpoon Gun-Fine":{"Seasoned Rifle Stock":1,"Pillaging Seasoned Inscription":1,"Seasoned Harpoon":1},
		"Pillaging Longbow-Fine":{"Coarse String":1,"Seasoned Longbow Stave":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Pistol-Fine":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Rifle-Fine":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Torch-Fine":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Pillaging Seasoned Inscription":1},
		"Ravaging Harpoon Gun-Fine":{"Seasoned Rifle Stock":1,"Ravaging Seasoned Inscription":1,"Seasoned Harpoon":1},
		"Ravaging Longbow-Fine":{"Coarse String":1,"Ravaging Seasoned Inscription":1,"Seasoned Longbow Stave":1},
		"Ravaging Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Steel Pistol-Fine":{"Seasoned Pistol Frame":1,"Ravaging Seasoned Inscription":1,"Steel Pistol Barrel":1},
		"Ravaging Steel Rifle-Fine":{"Seasoned Rifle Stock":1,"Steel Rifle Barrel":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Torch-Fine":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Ravaging Seasoned Inscription":1},
		"Seasoned Harpoon":{"Steel Ingot":2,"Seasoned Wood Plank":2},
		"Seasoned Longbow Stave":{"Seasoned Wood Plank":4},
		"Seasoned Pistol Frame":{"Seasoned Wood Plank":2},
		"Seasoned Rifle Stock":{"Seasoned Wood Plank":3},
		"Seasoned Short-Bow Stave":{"Seasoned Wood Plank":4},
		"Seasoned Torch Handle":{"Seasoned Wood Plank":2},
		"Seasoned Wood Dowel":{"Seasoned Wood Plank":1},
		"Seasoned Wood Plank":{"Seasoned Wood Log":3},
		"Standard Maintenance Oil":{"Pile of Radiant Dust":4,"Jug of Water":9},
		"Steel Horn":{"Steel Ingot":1,"Seasoned Wood Plank":2},
		"Steel Ingot":{"Iron Ore":3,"Lump of Coal":1},
		"Steel Pistol Barrel":{"Steel Ingot":3},
		"Steel Rifle Barrel":{"Steel Ingot":3},
		"Steel Torch Head":{"Steel Ingot":2},
		"Steel Warhorn Mouthpiece":{"Steel Ingot":1},
		"Vigorous Harpoon Gun-Fine":{"Vigorous Seasoned Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Vigorous Longbow-Fine":{"Coarse String":1,"Vigorous Seasoned Inscription":1,"Seasoned Longbow Stave":1},
		"Vigorous Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Vigorous Seasoned Inscription":1},
		"Vigorous Steel Pistol-Fine":{"Vigorous Seasoned Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Vigorous Steel Rifle-Fine":{"Steel Rifle Barrel":1,"Vigorous Seasoned Inscription":1,"Seasoned Rifle Stock":1},
		"Vigorous Torch-Fine":{"Seasoned Torch Handle":1,"Vigorous Seasoned Inscription":1,"Steel Torch Head":1},
		"Vigorous Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Vigorous Seasoned Inscription":1}
	},
	"175":{
		"Hearty Harpoon Gun-Fine":{"Seasoned Rifle Stock":1,"Seasoned Harpoon":1,"Hearty Seasoned Inscription":1},
		"Hearty Longbow-Fine":{"Coarse String":1,"Seasoned Longbow Stave":1,"Hearty Seasoned Inscription":1},
		"Hearty Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Pistol-Fine":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Rifle-Fine":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Hearty Seasoned Inscription":1},
		"Hearty Torch-Fine":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Hearty Seasoned Inscription":1},
		"Hearty Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Hearty Seasoned Inscription":1},
		"Honed Harpoon Gun-Fine":{"Seasoned Rifle Stock":1,"Honed Seasoned Inscription":1,"Seasoned Harpoon":1},
		"Honed Longbow-Fine":{"Coarse String":1,"Honed Seasoned Inscription":1,"Seasoned Longbow Stave":1},
		"Honed Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Honed Seasoned Inscription":1},
		"Honed Steel Pistol-Fine":{"Seasoned Pistol Frame":1,"Honed Seasoned Inscription":1,"Steel Pistol Barrel":1},
		"Honed Steel Rifle-Fine":{"Seasoned Rifle Stock":1,"Steel Rifle Barrel":1,"Honed Seasoned Inscription":1},
		"Honed Torch-Fine":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Honed Seasoned Inscription":1},
		"Honed Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Honed Seasoned Inscription":1},
		"Minor Sigil of Conjuration-2":{"Pile of Foul Essence":1,"Steel Ingot":1},
		"Rejuvenating Harpoon Gun-Fine":{"Rejuvenating Seasoned Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Rejuvenating Longbow-Fine":{"Coarse String":1,"Rejuvenating Seasoned Inscription":1,"Seasoned Longbow Stave":1},
		"Rejuvenating Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Rejuvenating Seasoned Inscription":1},
		"Rejuvenating Steel Pistol-Fine":{"Rejuvenating Seasoned Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Rejuvenating Steel Rifle-Fine":{"Steel Rifle Barrel":1,"Rejuvenating Seasoned Inscription":1,"Seasoned Rifle Stock":1},
		"Rejuvenating Torch-Fine":{"Seasoned Torch Handle":1,"Rejuvenating Seasoned Inscription":1,"Steel Torch Head":1},
		"Rejuvenating Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Rejuvenating Seasoned Inscription":1},
		"Strong Harpoon Gun-Fine":{"Seasoned Rifle Stock":1,"Seasoned Harpoon":1,"Strong Seasoned Inscription":1},
		"Strong Longbow-Fine":{"Coarse String":1,"Seasoned Longbow Stave":1,"Strong Seasoned Inscription":1},
		"Strong Short Bow-Fine":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Strong Seasoned Inscription":1},
		"Strong Steel Pistol-Fine":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Strong Seasoned Inscription":1},
		"Strong Steel Rifle-Fine":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Strong Seasoned Inscription":1},
		"Strong Torch-Fine":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Strong Seasoned Inscription":1},
		"Strong Warhorn-Fine":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Strong Seasoned Inscription":1}
	},
	"200":{
		"Giver's Harpoon Gun-Master":{"Giver's Steel-Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Giver's Longbow-Master":{"Coarse String":1,"Giver's Steel-Plated Inscription":1,"Seasoned Longbow Stave":1},
		"Giver's Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Giver's Steel-Plated Inscription":1},
		"Giver's Steel Pistol-Master":{"Giver's Steel-Plated Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Giver's Steel Rifle-Master":{"Steel Rifle Barrel":1,"Giver's Steel-Plated Inscription":1,"Seasoned Rifle Stock":1},
		"Giver's Torch-Master":{"Seasoned Torch Handle":1,"Giver's Steel-Plated Inscription":1,"Steel Torch Head":1},
		"Giver's Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Giver's Steel-Plated Inscription":1},
		"Hearty Dredge Boomstick":{"Steel Rifle Barrel":1,"Hearty Steel Imbued Inscription":1,"Seasoned Rifle Stock":1},
		"Hearty Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Hearty Steel Imbued Inscription":1},
		"Hearty Dredge Firearm":{"Hearty Steel Imbued Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Hearty Dredge Harpoon Gun":{"Hearty Steel Imbued Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Hearty Dredge Lamp":{"Seasoned Torch Handle":1,"Hearty Steel Imbued Inscription":1,"Steel Torch Head":1},
		"Hearty Dredge Reflex Bow":{"Coarse String":1,"Hearty Steel Imbued Inscription":1,"Seasoned Longbow Stave":1},
		"Hearty Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Hearty Steel Imbued Inscription":1},
		"Hearty Harpoon Gun-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Hearty Longbow-Master":{"Hearty Steel Plated Inscription":1,"Coarse String":1,"Seasoned Longbow Stave":1},
		"Hearty Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Hearty Steel Plated Inscription":1,"Coarse String":1},
		"Hearty Steel Pistol-Master":{"Hearty Steel Plated Inscription":1,"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1},
		"Hearty Steel Rifle-Master":{"Hearty Steel Plated Inscription":1,"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1},
		"Hearty Torch-Master":{"Hearty Steel Plated Inscription":1,"Steel Torch Head":1,"Seasoned Torch Handle":1},
		"Hearty Warhorn-Master":{"Hearty Steel Plated Inscription":1,"Steel Horn":1,"Steel Warhorn Mouthpiece":1},
		"Honed Dredge Boomstick":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Firearm":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Harpoon Gun":{"Seasoned Rifle Stock":1,"Honed Steel Imbued Inscription":1,"Seasoned Harpoon":1},
		"Honed Dredge Lamp":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Reflex Bow":{"Coarse String":1,"Seasoned Longbow Stave":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Honed Steel Imbued Inscription":1},
		"Honed Harpoon Gun-Master":{"Honed Steel Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Honed Longbow-Master":{"Coarse String":1,"Honed Steel Plated Inscription":1,"Seasoned Longbow Stave":1},
		"Honed Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Honed Steel Plated Inscription":1},
		"Honed Steel Pistol-Master":{"Honed Steel Plated Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Honed Steel Rifle-Master":{"Steel Rifle Barrel":1,"Honed Steel Plated Inscription":1,"Seasoned Rifle Stock":1},
		"Honed Torch-Master":{"Seasoned Torch Handle":1,"Honed Steel Plated Inscription":1,"Steel Torch Head":1},
		"Honed Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Honed Steel Plated Inscription":1},
		"Pillaging Dredge Boomstick":{"Seasoned Rifle Stock":1,"Steel Rifle Barrel":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Dredge Firearm":{"Seasoned Pistol Frame":1,"Pillaging Steel Imbued Inscription":1,"Steel Pistol Barrel":1},
		"Pillaging Dredge Harpoon Gun":{"Seasoned Rifle Stock":1,"Pillaging Steel Imbued Inscription":1,"Seasoned Harpoon":1},
		"Pillaging Dredge Lamp":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Dredge Reflex Bow":{"Coarse String":1,"Pillaging Steel Imbued Inscription":1,"Seasoned Longbow Stave":1},
		"Pillaging Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Harpoon Gun-Master":{"Pillaging Steel Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Pillaging Longbow-Master":{"Pillaging Steel Plated Inscription":1,"Coarse String":1,"Seasoned Longbow Stave":1},
		"Pillaging Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Pillaging Steel Plated Inscription":1,"Coarse String":1},
		"Pillaging Steel Pistol-Master":{"Pillaging Steel Plated Inscription":1,"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1},
		"Pillaging Steel Rifle-Master":{"Pillaging Steel Plated Inscription":1,"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1},
		"Pillaging Torch-Master":{"Seasoned Torch Handle":1,"Pillaging Steel Plated Inscription":1,"Steel Torch Head":1},
		"Pillaging Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Pillaging Steel Plated Inscription":1,"Steel Horn":1},
		"Ravaging Dredge Boomstick":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Firearm":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Harpoon Gun":{"Seasoned Rifle Stock":1,"Ravaging Steel Imbued Inscription":1,"Seasoned Harpoon":1},
		"Ravaging Dredge Lamp":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Reflex Bow":{"Coarse String":1,"Seasoned Longbow Stave":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Harpoon Gun-Master":{"Ravaging Steel Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Ravaging Longbow-Master":{"Coarse String":1,"Ravaging Steel Plated Inscription":1,"Seasoned Longbow Stave":1},
		"Ravaging Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Ravaging Steel Plated Inscription":1},
		"Ravaging Steel Pistol-Master":{"Ravaging Steel Plated Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Ravaging Steel Rifle-Master":{"Steel Rifle Barrel":1,"Ravaging Steel Plated Inscription":1,"Seasoned Rifle Stock":1},
		"Ravaging Torch-Master":{"Seasoned Torch Handle":1,"Ravaging Steel Plated Inscription":1,"Steel Torch Head":1},
		"Ravaging Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Ravaging Steel Plated Inscription":1},
		"Rejuvenating Dredge Boomstick":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Firearm":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Harpoon Gun":{"Seasoned Rifle Stock":1,"Seasoned Harpoon":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Lamp":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Reflex Bow":{"Coarse String":1,"Seasoned Longbow Stave":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Harpoon Gun-Master":{"Seasoned Rifle Stock":1,"Rejuvenating Steel Plated Inscription":1,"Seasoned Harpoon":1},
		"Rejuvenating Longbow-Master":{"Coarse String":1,"Rejuvenating Steel Plated Inscription":1,"Seasoned Longbow Stave":1},
		"Rejuvenating Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Steel Pistol-Master":{"Seasoned Pistol Frame":1,"Rejuvenating Steel Plated Inscription":1,"Steel Pistol Barrel":1},
		"Rejuvenating Steel Rifle-Master":{"Seasoned Rifle Stock":1,"Steel Rifle Barrel":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Torch-Master":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Rejuvenating Steel Plated Inscription":1},
		"Steel Plated Dowel":{"Steel Ingot":3,"Seasoned Wood Plank":2},
		"Strong Dredge Boomstick":{"Steel Rifle Barrel":1,"Strong Steel Imbued Inscription":1,"Seasoned Rifle Stock":1},
		"Strong Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Strong Steel Imbued Inscription":1},
		"Strong Dredge Firearm":{"Strong Steel Imbued Inscription":1,"Steel Pistol Barrel":1,"Seasoned Pistol Frame":1},
		"Strong Dredge Harpoon Gun":{"Strong Steel Imbued Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Strong Dredge Lamp":{"Seasoned Torch Handle":1,"Strong Steel Imbued Inscription":1,"Steel Torch Head":1},
		"Strong Dredge Reflex Bow":{"Coarse String":1,"Strong Steel Imbued Inscription":1,"Seasoned Longbow Stave":1},
		"Strong Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Strong Steel Imbued Inscription":1},
		"Strong Harpoon Gun-Master":{"Strong Steel Plated Inscription":1,"Seasoned Rifle Stock":1,"Seasoned Harpoon":1},
		"Strong Longbow-Master":{"Strong Steel Plated Inscription":1,"Coarse String":1,"Seasoned Longbow Stave":1},
		"Strong Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Strong Steel Plated Inscription":1,"Coarse String":1},
		"Strong Steel Pistol-Master":{"Strong Steel Plated Inscription":1,"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1},
		"Strong Steel Rifle-Master":{"Strong Steel Plated Inscription":1,"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1},
		"Strong Torch-Master":{"Strong Steel Plated Inscription":1,"Steel Torch Head":1,"Seasoned Torch Handle":1},
		"Strong Warhorn-Master":{"Strong Steel Plated Inscription":1,"Steel Horn":1,"Steel Warhorn Mouthpiece":1},
		"Vigorous Dredge Boomstick":{"Steel Rifle Barrel":1,"Seasoned Rifle Stock":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Double Horn":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Firearm":{"Seasoned Pistol Frame":1,"Steel Pistol Barrel":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Harpoon Gun":{"Seasoned Rifle Stock":1,"Seasoned Harpoon":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Lamp":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Reflex Bow":{"Coarse String":1,"Seasoned Longbow Stave":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Short Bow":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Harpoon Gun-Master":{"Seasoned Rifle Stock":1,"Vigorous Steel Plated Inscription":1,"Seasoned Harpoon":1},
		"Vigorous Longbow-Master":{"Coarse String":1,"Vigorous Steel Plated Inscription":1,"Seasoned Longbow Stave":1},
		"Vigorous Short Bow-Master":{"Seasoned Short-Bow Stave":1,"Coarse String":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Steel Pistol-Master":{"Seasoned Pistol Frame":1,"Vigorous Steel Plated Inscription":1,"Steel Pistol Barrel":1},
		"Vigorous Steel Rifle-Master":{"Seasoned Rifle Stock":1,"Steel Rifle Barrel":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Torch-Master":{"Seasoned Torch Handle":1,"Steel Torch Head":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Warhorn-Master":{"Steel Warhorn Mouthpiece":1,"Steel Horn":1,"Vigorous Steel Plated Inscription":1}
	},
	"225":{
		"Artisan Maintenance Oil":{"Jug of Water":12,"Pile of Luminous Dust":4},
		"Carrion Darksteel Pistol-Fine":{"Carrion Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Carrion Darksteel Rifle-Fine":{"Hard Rifle Stock":1,"Carrion Hard Inscription":1,"Darksteel Rifle Barrel":1},
		"Carrion Hard Harpoon Gun-Fine":{"Hard Rifle Stock":1,"Carrion Hard Inscription":1,"Hard Harpoon":1},
		"Carrion Hard Longbow-Fine":{"Hard Longbow Stave":1,"Carrion Hard Inscription":1,"Rugged String":1},
		"Carrion Hard Short Bow-Fine":{"Hard Short-Bow Stave":1,"Carrion Hard Inscription":1,"Rugged String":1},
		"Carrion Hard Torch-Fine":{"Darksteel Torch Head":1,"Carrion Hard Inscription":1,"Hard Torch Handle":1},
		"Carrion Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Carrion Hard Inscription":1},
		"Cured Rugged Leather Square":{"Rugged Leather Section":2},
		"Darksteel Horn":{"Darksteel Ingot":1,"Hard Wood Plank":2},
		"Darksteel Ingot":{"Lump of Primordium":1,"Platinum Ore":2},
		"Darksteel Pistol Barrel":{"Darksteel Ingot":3},
		"Darksteel Rifle Barrel":{"Darksteel Ingot":3},
		"Darksteel Torch Head":{"Darksteel Ingot":2},
		"Darksteel Warhorn Mouthpiece":{"Darksteel Ingot":1},
		"Hard Harpoon":{"Darksteel Ingot":2,"Hard Wood Plank":2},
		"Hard Longbow Stave":{"Hard Wood Plank":4},
		"Hard Pistol Frame":{"Hard Wood Plank":2},
		"Hard Rifle Stock":{"Hard Wood Plank":3},
		"Hard Short-Bow Stave":{"Hard Wood Plank":4},
		"Hard Torch Handle":{"Hard Wood Plank":2},
		"Hard Wood Dowel":{"Hard Wood Plank":1},
		"Hard Wood Plank":{"Hard Wood Log":3},
		"Knight's Darksteel Pistol-Fine":{"Knight's Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Knight's Darksteel Rifle-Fine":{"Hard Rifle Stock":1,"Knight's Hard Inscription":1,"Darksteel Rifle Barrel":1},
		"Knight's Hard Harpoon Gun-Fine":{"Hard Rifle Stock":1,"Knight's Hard Inscription":1,"Hard Harpoon":1},
		"Knight's Hard Longbow-Fine":{"Hard Longbow Stave":1,"Knight's Hard Inscription":1,"Rugged String":1},
		"Knight's Hard Short Bow-Fine":{"Hard Short-Bow Stave":1,"Knight's Hard Inscription":1,"Rugged String":1},
		"Knight's Hard Torch-Fine":{"Darksteel Torch Head":1,"Knight's Hard Inscription":1,"Hard Torch Handle":1},
		"Knight's Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Knight's Hard Inscription":1},
		"Rugged String":{"Cured Rugged Leather Square":3},
		"Valkyrie Darksteel Pistol-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Valkyrie Darksteel Rifle-Fine":{"Valkyrie Hard Inscription":1,"Hard Rifle Stock":1,"Darksteel Rifle Barrel":1},
		"Valkyrie Hard Harpoon Gun-Fine":{"Valkyrie Hard Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Valkyrie Hard Longbow-Fine":{"Valkyrie Hard Inscription":1,"Hard Longbow Stave":1,"Rugged String":1},
		"Valkyrie Hard Torch-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Valkyrie Hard Warhorn-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Horn":1,"Darksteel Warhorn Mouthpiece":1},
		"Valkyrie's Hard Short Bow-Fine":{"Valkyrie Hard Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1}
	},
	"250":{
		"Berserker's Darksteel Pistol-Fine":{"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Rifle-Fine":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Harpoon Gun-Fine":{"Hard Rifle Stock":1,"Hard Harpoon":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Longbow-Fine":{"Hard Longbow Stave":1,"Rugged String":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Short Bow-Fine":{"Hard Short-Bow Stave":1,"Rugged String":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Torch-Fine":{"Darksteel Torch Head":1,"Hard Torch Handle":1,"Berserker's Hard Inscription":1},
		"Berserker's Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Berserker's Hard Inscription":1},
		"Cleric's Darksteel Pistol-Fine":{"Cleric's Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Cleric's Darksteel Rifle-Fine":{"Darksteel Rifle Barrel":1,"Cleric's Hard Inscription":1,"Hard Rifle Stock":1},
		"Cleric's Hard Harpoon Gun-Fine":{"Cleric's Hard Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Cleric's Hard Longbow-Fine":{"Cleric's Hard Inscription":1,"Rugged String":1,"Hard Longbow Stave":1},
		"Cleric's Hard Short Bow-Fine":{"Cleric's Hard Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1},
		"Cleric's Hard Torch-Fine":{"Cleric's Hard Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Cleric's Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Cleric's Hard Inscription":1,"Darksteel Horn":1},
		"Explorer's Darksteel Pistol-Fine":{"Explorer's Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Explorer's Darksteel Rifle-Fine":{"Hard Rifle Stock":1,"Explorer's Hard Inscription":1,"Darksteel Rifle Barrel":1},
		"Explorer's Hard Harpoon Gun-Fine":{"Hard Rifle Stock":1,"Explorer's Hard Inscription":1,"Hard Harpoon":1},
		"Explorer's Hard Longbow-Fine":{"Hard Longbow Stave":1,"Explorer's Hard Inscription":1,"Rugged String":1},
		"Explorer's Hard Short Bow-Fine":{"Hard Short-Bow Stave":1,"Explorer's Hard Inscription":1,"Rugged String":1},
		"Explorer's Hard Torch-Fine":{"Darksteel Torch Head":1,"Explorer's Hard Inscription":1,"Hard Torch Handle":1},
		"Explorer's Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Explorer's Hard Inscription":1},
		"Rampager's Darksteel Pistol-Fine":{"Rampager's Hard Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Rampager's Darksteel Rifle-Fine":{"Hard Rifle Stock":1,"Rampager's Hard Inscription":1,"Darksteel Rifle Barrel":1},
		"Rampager's Hard Harpoon Gun-Fine":{"Hard Rifle Stock":1,"Rampager's Hard Inscription":1,"Hard Harpoon":1},
		"Rampager's Hard Longbow-Fine":{"Hard Longbow Stave":1,"Rampager's Hard Inscription":1,"Rugged String":1},
		"Rampager's Hard Short Bow-Fine":{"Hard Short-Bow Stave":1,"Rampager's Hard Inscription":1,"Rugged String":1},
		"Rampager's Hard Torch-Fine":{"Darksteel Torch Head":1,"Rampager's Hard Inscription":1,"Hard Torch Handle":1},
		"Rampager's Hard Warhorn-Fine":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Rampager's Hard Inscription":1}
	},
	"275":{
		"Berserker's Darksteel Pistol-Master":{"Berserker's Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Berserker's Darksteel Rifle-Master":{"Darksteel Rifle Barrel":1,"Berserker's Darksteel Plated Inscription":1,"Hard Rifle Stock":1},
		"Berserker's Hard Harpoon Gun-Master":{"Berserker's Darksteel Plated Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Berserker's Hard Longbow-Master":{"Berserker's Darksteel Plated Inscription":1,"Rugged String":1,"Hard Longbow Stave":1},
		"Berserker's Hard Short Bow-Master":{"Berserker's Darksteel Plated Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1},
		"Berserker's Hard Torch-Master":{"Berserker's Darksteel Plated Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Berserker's Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Berserker's Darksteel Plated Inscription":1,"Darksteel Horn":1},
		"Berserker's Ogre Blaster":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Blaze":{"Hard Torch Handle":1,"Darksteel Torch Head":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Flintlock":{"Berserker's Darksteel Imbued Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Berserker's Ogre Harbinger":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Harpoon Gun":{"Hard Rifle Stock":1,"Berserker's Darksteel Imbued Inscription":1,"Hard Harpoon":1},
		"Berserker's Ogre Hornbow":{"Rugged String":1,"Hard Longbow Stave":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Short Bow":{"Rugged String":1,"Hard Short-Bow Stave":1,"Berserker's Darksteel Imbued Inscription":1},
		"Carrion Darksteel Pistol-Master":{"Carrion Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Carrion Darksteel Rifle-Master":{"Hard Rifle Stock":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Rifle Barrel":1},
		"Carrion Hard Harpoon Gun-Master":{"Hard Rifle Stock":1,"Carrion Darksteel Plated Inscription":1,"Hard Harpoon":1},
		"Carrion Hard Longbow-Master":{"Hard Longbow Stave":1,"Carrion Darksteel Plated Inscription":1,"Rugged String":1},
		"Carrion Hard Short Bow-Master":{"Hard Short-Bow Stave":1,"Carrion Darksteel Plated Inscription":1,"Rugged String":1},
		"Carrion Hard Torch-Master":{"Darksteel Torch Head":1,"Carrion Darksteel Plated Inscription":1,"Hard Torch Handle":1},
		"Carrion Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Ogre Blaster":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Blaze":{"Darksteel Torch Head":1,"Hard Torch Handle":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Flintlock":{"Darksteel Pistol Barrel":1,"Carrion Darksteel Imbued Inscription":1,"Hard Pistol Frame":1},
		"Carrion Ogre Harbinger":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Harpoon Gun":{"Hard Rifle Stock":1,"Carrion Darksteel Imbued Inscription":1,"Hard Harpoon":1},
		"Carrion Ogre Hornbow":{"Hard Longbow Stave":1,"Rugged String":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Short Bow":{"Hard Short-Bow Stave":1,"Rugged String":1,"Carrion Darksteel Imbued Inscription":1},
		"Cleric's Darksteel Pistol-Master":{"Cleric's Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Cleric's Darksteel Rifle-Master":{"Darksteel Rifle Barrel":1,"Cleric's Darksteel Plated Inscription":1,"Hard Rifle Stock":1},
		"Cleric's Hard Harpoon Gun-Master":{"Cleric's Darksteel Plated Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Cleric's Hard Longbow-Master":{"Cleric's Darksteel Plated Inscription":1,"Rugged String":1,"Hard Longbow Stave":1},
		"Cleric's Hard Short Bow-Master":{"Cleric's Darksteel Plated Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1},
		"Cleric's Hard Torch-Master":{"Cleric's Darksteel Plated Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Cleric's Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Cleric's Darksteel Plated Inscription":1,"Darksteel Horn":1},
		"Cleric's Ogre Blaster":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1},
		"Cleric's Ogre Blaze":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Cleric's Ogre Flintlock":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Cleric's Ogre Harbinger":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1},
		"Cleric's Ogre Harpoon Gun":{"Cleric's Darksteel Imbued Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Cleric's Ogre Hornbow":{"Cleric's Darksteel Imbued Inscription":1,"Hard Longbow Stave":1,"Rugged String":1},
		"Cleric's Ogre Short Bow":{"Cleric's Darksteel Imbued Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1},
		"Darksteel Plated Dowel":{"Darksteel Ingot":3,"Hard Wood Plank":2},
		"Explorer's Darksteel Pistol-Master":{"Explorer's Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Explorer's Darksteel Rifle-Master":{"Hard Rifle Stock":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Rifle Barrel":1},
		"Explorer's Hard Harpoon Gun-Master":{"Hard Rifle Stock":1,"Explorer's Darksteel Plated Inscription":1,"Hard Harpoon":1},
		"Explorer's Hard Longbow-Master":{"Hard Longbow Stave":1,"Explorer's Darksteel Plated Inscription":1,"Rugged String":1},
		"Explorer's Hard Short Bow-Master":{"Hard Short-Bow Stave":1,"Explorer's Darksteel Plated Inscription":1,"Rugged String":1},
		"Explorer's Hard Torch-Master":{"Darksteel Torch Head":1,"Explorer's Darksteel Plated Inscription":1,"Hard Torch Handle":1},
		"Explorer's Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Ogre Blaster":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Blaze":{"Darksteel Torch Head":1,"Hard Torch Handle":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Flintlock":{"Darksteel Pistol Barrel":1,"Explorer's Darksteel Imbued Inscription":1,"Hard Pistol Frame":1},
		"Explorer's Ogre Harbinger":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Harpoon Gun":{"Hard Rifle Stock":1,"Explorer's Darksteel Imbued Inscription":1,"Hard Harpoon":1},
		"Explorer's Ogre Hornbow":{"Hard Longbow Stave":1,"Rugged String":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Short Bow":{"Hard Short-Bow Stave":1,"Rugged String":1,"Explorer's Darksteel Imbued Inscription":1},
		"Knight's Darksteel Pistol-Master":{"Knight's Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Knight's Darksteel Rifle-Master":{"Hard Rifle Stock":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Rifle Barrel":1},
		"Knight's Hard Harpoon Gun-Master":{"Hard Rifle Stock":1,"Knight's Darksteel Plated Inscription":1,"Hard Harpoon":1},
		"Knight's Hard Longbow-Master":{"Hard Longbow Stave":1,"Knight's Darksteel Plated Inscription":1,"Rugged String":1},
		"Knight's Hard Short Bow-Master":{"Hard Short-Bow Stave":1,"Knight's Darksteel Plated Inscription":1,"Rugged String":1},
		"Knight's Hard Torch-Master":{"Darksteel Torch Head":1,"Knight's Darksteel Plated Inscription":1,"Hard Torch Handle":1},
		"Knight's Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Ogre Blaster":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Blaze":{"Darksteel Torch Head":1,"Hard Torch Handle":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Flintlock":{"Darksteel Pistol Barrel":1,"Knight's Darksteel Imbued Inscription":1,"Hard Pistol Frame":1},
		"Knight's Ogre Harbinger":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Harpoon Gun":{"Hard Rifle Stock":1,"Knight's Darksteel Imbued Inscription":1,"Hard Harpoon":1},
		"Knight's Ogre Hornbow":{"Hard Longbow Stave":1,"Rugged String":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Short Bow":{"Hard Short-Bow Stave":1,"Rugged String":1,"Knight's Darksteel Imbued Inscription":1},
		"Major Sigil of Conjuration":{"Darksteel Ingot":1,"Pile of Filthy Essence":2},
		"Rampager's Darksteel Pistol-Master":{"Rampager's Darksteel Plated Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Rampager's Darksteel Rifle-Master":{"Hard Rifle Stock":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Rifle Barrel":1},
		"Rampager's Hard Harpoon Gun-Master":{"Hard Rifle Stock":1,"Rampager's Darksteel Plated Inscription":1,"Hard Harpoon":1},
		"Rampager's Hard Longbow-Master":{"Hard Longbow Stave":1,"Rampager's Darksteel Plated Inscription":1,"Rugged String":1},
		"Rampager's Hard Short Bow-Master":{"Hard Short-Bow Stave":1,"Rampager's Darksteel Plated Inscription":1,"Rugged String":1},
		"Rampager's Hard Torch-Master":{"Darksteel Torch Head":1,"Rampager's Darksteel Plated Inscription":1,"Hard Torch Handle":1},
		"Rampager's Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Ogre Blaster":{"Rampager's Darksteel Imbued Inscription":1,"Hard Rifle Stock":1,"Darksteel Rifle Barrel":1},
		"Rampager's Ogre Blaze":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Torch Head":1,"Hard Torch Handle":1},
		"Rampager's Ogre Flintlock":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Rampager's Ogre Harbinger":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Horn":1,"Darksteel Warhorn Mouthpiece":1},
		"Rampager's Ogre Harpoon Gun":{"Rampager's Darksteel Imbued Inscription":1,"Hard Rifle Stock":1,"Hard Harpoon":1},
		"Rampager's Ogre Hornbow":{"Rampager's Darksteel Imbued Inscription":1,"Hard Longbow Stave":1,"Rugged String":1},
		"Rampager's Ogre Short Bow":{"Rampager's Darksteel Imbued Inscription":1,"Hard Short-Bow Stave":1,"Rugged String":1},
		"Valkyrie Darksteel Pistol-Master":{"Darksteel Pistol Barrel":1,"Valkyrie Darksteel Plated Inscription":1,"Hard Pistol Frame":1},
		"Valkyrie Darksteel Rifle-Master":{"Darksteel Rifle Barrel":1,"Hard Rifle Stock":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Hard Harpoon Gun-Master":{"Hard Rifle Stock":1,"Valkyrie Darksteel Plated Inscription":1,"Hard Harpoon":1},
		"Valkyrie Hard Longbow-Master":{"Hard Longbow Stave":1,"Rugged String":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Hard Torch-Master":{"Darksteel Torch Head":1,"Hard Torch Handle":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Hard Warhorn-Master":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Ogre Blaster":{"Hard Rifle Stock":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Rifle Barrel":1},
		"Valkyrie Ogre Blaze":{"Darksteel Torch Head":1,"Valkyrie Darksteel Imbued Inscription":1,"Hard Torch Handle":1},
		"Valkyrie Ogre Flintlock":{"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Pistol Barrel":1,"Hard Pistol Frame":1},
		"Valkyrie Ogre Harbinger":{"Darksteel Warhorn Mouthpiece":1,"Darksteel Horn":1,"Valkyrie Darksteel Imbued Inscription":1},
		"Valkyrie Ogre Harpoon Gun":{"Hard Rifle Stock":1,"Valkyrie Darksteel Imbued Inscription":1,"Hard Harpoon":1},
		"Valkyrie Ogre Hornbow":{"Hard Longbow Stave":1,"Valkyrie Darksteel Imbued Inscription":1,"Rugged String":1},
		"Valkyrie Ogre Short Bow":{"Hard Short-Bow Stave":1,"Valkyrie Darksteel Imbued Inscription":1,"Rugged String":1},
		"Valkyrie's Hard Short Bow-Master":{"Hard Short-Bow Stave":1,"Rugged String":1,"Valkyrie Darksteel Plated Inscription":1}
	},
	"300":{
		"Carrion Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Carrion Elder Inscription":1,"Elder Rifle Stock":1},
		"Carrion Elder Longbow-Fine":{"Elder Longbow Stave":1,"Carrion Elder Inscription":1,"Thick String":1},
		"Carrion Elder Short Bow-Fine":{"Carrion Elder Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Carrion Elder Torch-Fine":{"Carrion Elder Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Carrion Elder Warhorn-Fine":{"Carrion Elder Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Carrion Mithril Pistol-Fine":{"Carrion Elder Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Carrion Mithril Rifle-Fine":{"Carrion Elder Inscription":1,"Mithril Rifle Barrel":1,"Elder Rifle Stock":1},
		"Cured Thick Leather Square":{"Thick Leather Section":2},
		"Elder Harpoon":{"Mithril Ingot":2,"Elder Wood Plank":2},
		"Elder Longbow Stave":{"Elder Wood Plank":4},
		"Elder Pistol Frame":{"Elder Wood Plank":2},
		"Elder Rifle Stock":{"Elder Wood Plank":3},
		"Elder Short-Bow Stave":{"Elder Wood Plank":4},
		"Elder Torch Handle":{"Elder Wood Plank":2},
		"Elder Wood Dowel":{"Elder Wood Plank":1},
		"Elder Wood Plank":{"Elder Wood Log":3},
		"Knight's Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Knight's Elder Inscription":1},
		"Knight's Elder Longbow-Fine":{"Elder Longbow Stave":1,"Thick String":1,"Knight's Elder Inscription":1},
		"Knight's Elder Short Bow-Fine":{"Thick String":1,"Elder Short-Bow Stave":1,"Knight's Elder Inscription":1},
		"Knight's Elder Torch-Fine":{"Mithril Torch Head":1,"Knight's Elder Inscription":1,"Elder Torch Handle":1},
		"Knight's Elder Warhorn-Fine":{"Mithril Warhorn Mouthpiece":1,"Mithril Horn":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Pistol-Fine":{"Mithril Pistol Barrel":1,"Elder Pistol Frame":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Rifle-Fine":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Knight's Elder Inscription":1},
		"Mithril Horn":{"Mithril Ingot":1,"Elder Wood Plank":2},
		"Mithril Ingot":{"Mithril Ore":2},
		"Mithril Pistol Barrel":{"Mithril Ingot":3},
		"Mithril Rifle Barrel":{"Mithril Ingot":3},
		"Mithril Torch Head":{"Mithril Ingot":2},
		"Mithril Warhorn Mouthpiece":{"Mithril Ingot":1},
		"Quality Maintenance Oil":{"Jug of Water":15,"Pile of Incandescent Dust":4},
		"Thick String":{"Cured Thick Leather Square":3},
		"Valkyrie Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Elder Longbow-Fine":{"Elder Longbow Stave":1,"Thick String":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Elder Torch-Fine":{"Mithril Torch Head":1,"Valkyrie Elder Inscription":1,"Elder Torch Handle":1},
		"Valkyrie Elder Warhorn-Fine":{"Mithril Horn":1,"Valkyrie Elder Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Valkyrie Mithril Pistol-Fine":{"Valkyrie Elder Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Valkyrie Mithril Rifle-Fine":{"Elder Rifle Stock":1,"Valkyrie Elder Inscription":1,"Mithril Rifle Barrel":1},
		"Valkyrie's Elder Short Bow-Fine":{"Thick String":1,"Valkyrie Elder Inscription":1,"Elder Short-Bow Stave":1}
	},
	"325":{
		"Berserker's Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Longbow-Fine":{"Elder Longbow Stave":1,"Thick String":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Short Bow-Fine":{"Thick String":1,"Elder Short-Bow Stave":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Torch-Fine":{"Mithril Torch Head":1,"Elder Torch Handle":1,"Berserker's Elder Inscription":1},
		"Berserker's Elder Warhorn-Fine":{"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Pistol-Fine":{"Elder Pistol Frame":1,"Mithril Pistol Barrel":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Rifle-Fine":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Berserker's Elder Inscription":1},
		"Cleric's Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Longbow-Fine":{"Elder Longbow Stave":1,"Thick String":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Short Bow-Fine":{"Thick String":1,"Elder Short-Bow Stave":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Torch-Fine":{"Mithril Torch Head":1,"Elder Torch Handle":1,"Cleric's Elder Inscription":1},
		"Cleric's Elder Warhorn-Fine":{"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Pistol-Fine":{"Elder Pistol Frame":1,"Mithril Pistol Barrel":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Rifle-Fine":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Cleric's Elder Inscription":1},
		"Explorer's Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Longbow-Fine":{"Elder Longbow Stave":1,"Thick String":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Short Bow-Fine":{"Thick String":1,"Elder Short-Bow Stave":1,"Explorer's Elder Inscription":1},
		"Explorer's Elder Torch-Fine":{"Mithril Torch Head":1,"Explorer's Elder Inscription":1,"Elder Torch Handle":1},
		"Explorer's Elder Warhorn-Fine":{"Mithril Warhorn Mouthpiece":1,"Mithril Horn":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Pistol-Fine":{"Mithril Pistol Barrel":1,"Elder Pistol Frame":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Rifle-Fine":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Explorer's Elder Inscription":1},
		"Major Sigil of Paralyzation":{"Mithril Ingot":1,"Onyx Core":1},
		"Rampager's Elder Harpoon Gun-Fine":{"Elder Harpoon":1,"Rampager's Elder Inscription":1,"Elder Rifle Stock":1},
		"Rampager's Elder Longbow-Fine":{"Elder Longbow Stave":1,"Rampager's Elder Inscription":1,"Thick String":1},
		"Rampager's Elder Short Bow-Fine":{"Rampager's Elder Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Rampager's Elder Torch-Fine":{"Rampager's Elder Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Rampager's Elder Warhorn-Fine":{"Rampager's Elder Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Rampager's Mithril Pistol-Fine":{"Rampager's Elder Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Rampager's Mithril Rifle-Fine":{"Rampager's Elder Inscription":1,"Mithril Rifle Barrel":1,"Elder Rifle Stock":1}
	},
	"350":{
		"Berserker's Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Short Bow-Master":{"Thick String":1,"Elder Short-Bow Stave":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Torch-Master":{"Mithril Torch Head":1,"Elder Torch Handle":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Elder Warhorn-Master":{"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Pistol-Master":{"Elder Pistol Frame":1,"Mithril Pistol Barrel":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Rifle-Master":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Berserker's Mithril Plated Inscription":1},
		"Carrion Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Elder Short Bow-Master":{"Thick String":1,"Carrion Mithril Plated Inscription":1,"Elder Short-Bow Stave":1},
		"Carrion Elder Torch-Master":{"Mithril Torch Head":1,"Carrion Mithril Plated Inscription":1,"Elder Torch Handle":1},
		"Carrion Elder Warhorn-Master":{"Mithril Horn":1,"Carrion Mithril Plated Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Carrion Mithril Pistol-Master":{"Carrion Mithril Plated Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Carrion Mithril Rifle-Master":{"Elder Rifle Stock":1,"Carrion Mithril Plated Inscription":1,"Mithril Rifle Barrel":1},
		"Cleric's Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Short Bow-Master":{"Thick String":1,"Elder Short-Bow Stave":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Torch-Master":{"Mithril Torch Head":1,"Elder Torch Handle":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Elder Warhorn-Master":{"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Pistol-Master":{"Elder Pistol Frame":1,"Mithril Pistol Barrel":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Rifle-Master":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Cleric's Mithril Plated Inscription":1},
		"Explorer's Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Elder Short Bow-Master":{"Thick String":1,"Explorer's Mithril Plated Inscription":1,"Elder Short-Bow Stave":1},
		"Explorer's Elder Torch-Master":{"Mithril Torch Head":1,"Explorer's Mithril Plated Inscription":1,"Elder Torch Handle":1},
		"Explorer's Elder Warhorn-Master":{"Mithril Horn":1,"Explorer's Mithril Plated Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Explorer's Mithril Pistol-Master":{"Explorer's Mithril Plated Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Explorer's Mithril Rifle-Master":{"Elder Rifle Stock":1,"Explorer's Mithril Plated Inscription":1,"Mithril Rifle Barrel":1},
		"Knight's Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Elder Short Bow-Master":{"Thick String":1,"Knight's Mithril Plated Inscription":1,"Elder Short-Bow Stave":1},
		"Knight's Elder Torch-Master":{"Mithril Torch Head":1,"Knight's Mithril Plated Inscription":1,"Elder Torch Handle":1},
		"Knight's Elder Warhorn-Master":{"Mithril Horn":1,"Knight's Mithril Plated Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Knight's Mithril Pistol-Master":{"Knight's Mithril Plated Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Knight's Mithril Rifle-Master":{"Elder Rifle Stock":1,"Knight's Mithril Plated Inscription":1,"Mithril Rifle Barrel":1},
		"Major Sigil of Icebrood Slaying":{"Corrupted Core":1,"Mithril Ingot":1},
		"Major Sigil of Speed":{"Charged Core":1,"Mithril Ingot":1},
		"Mithril Plated Dowel":{"Mithril Ingot":3,"Elder Wood Plank":2},
		"Rampager's Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Elder Short Bow-Master":{"Thick String":1,"Rampager's Mithril Plated Inscription":1,"Elder Short-Bow Stave":1},
		"Rampager's Elder Torch-Master":{"Mithril Torch Head":1,"Rampager's Mithril Plated Inscription":1,"Elder Torch Handle":1},
		"Rampager's Elder Warhorn-Master":{"Mithril Horn":1,"Rampager's Mithril Plated Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Rampager's Mithril Pistol-Master":{"Rampager's Mithril Plated Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Rampager's Mithril Rifle-Master":{"Elder Rifle Stock":1,"Rampager's Mithril Plated Inscription":1,"Mithril Rifle Barrel":1},
		"Valkyrie Elder Harpoon Gun-Master":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Longbow-Master":{"Elder Longbow Stave":1,"Thick String":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Short Bow-Master":{"Thick String":1,"Elder Short-Bow Stave":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Elder Torch-Master":{"Mithril Torch Head":1,"Valkyrie Mithril Plated Inscription":1,"Elder Torch Handle":1},
		"Valkyrie Elder Warhorn-Master":{"Mithril Warhorn Mouthpiece":1,"Mithril Horn":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Pistol-Master":{"Mithril Pistol Barrel":1,"Elder Pistol Frame":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Rifle-Master":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Valkyrie Mithril Plated Inscription":1}
	},
	"375":{
		"Berserker's Krait Brazier":{"Berserker's Mithril Imbued Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Berserker's Krait Handgun":{"Berserker's Mithril Imbued Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Berserker's Krait Harpoon Gun":{"Berserker's Mithril Imbued Inscription":1,"Elder Harpoon":1,"Elder Rifle Stock":1},
		"Berserker's Krait Recurve Bow":{"Berserker's Mithril Imbued Inscription":1,"Elder Longbow Stave":1,"Thick String":1},
		"Berserker's Krait Shooter":{"Berserker's Mithril Imbued Inscription":1,"Elder Rifle Stock":1,"Mithril Rifle Barrel":1},
		"Berserker's Krait Short Bow":{"Berserker's Mithril Imbued Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Berserker's Krait Whelk":{"Berserker's Mithril Imbued Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Carrion Krait Brazier":{"Carrion Mithril Imbued Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Carrion Krait Handgun":{"Carrion Mithril Imbued Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Carrion Krait Harpoon Gun":{"Elder Harpoon":1,"Carrion Mithril Imbued Inscription":1,"Elder Rifle Stock":1},
		"Carrion Krait Recurve Bow":{"Elder Longbow Stave":1,"Carrion Mithril Imbued Inscription":1,"Thick String":1},
		"Carrion Krait Shooter":{"Carrion Mithril Imbued Inscription":1,"Mithril Rifle Barrel":1,"Elder Rifle Stock":1},
		"Carrion Krait Short Bow":{"Carrion Mithril Imbued Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Carrion Krait Whelk":{"Carrion Mithril Imbued Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Cleric's Krait Brazier":{"Mithril Torch Head":1,"Cleric's Mithril Imbued Inscription":1,"Elder Torch Handle":1},
		"Cleric's Krait Handgun":{"Elder Pistol Frame":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Pistol Barrel":1},
		"Cleric's Krait Harpoon Gun":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Recurve Bow":{"Elder Longbow Stave":1,"Thick String":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Shooter":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Short Bow":{"Thick String":1,"Cleric's Mithril Imbued Inscription":1,"Elder Short-Bow Stave":1},
		"Cleric's Krait Whelk":{"Mithril Horn":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Explorer's Krait Brazier":{"Explorer's Mithril Imbued Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Explorer's Krait Handgun":{"Explorer's Mithril Imbued Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Explorer's Krait Harpoon Gun":{"Elder Harpoon":1,"Explorer's Mithril Imbued Inscription":1,"Elder Rifle Stock":1},
		"Explorer's Krait Recurve Bow":{"Elder Longbow Stave":1,"Explorer's Mithril Imbued Inscription":1,"Thick String":1},
		"Explorer's Krait Shooter":{"Explorer's Mithril Imbued Inscription":1,"Mithril Rifle Barrel":1,"Elder Rifle Stock":1},
		"Explorer's Krait Short Bow":{"Explorer's Mithril Imbued Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Explorer's Krait Whelk":{"Explorer's Mithril Imbued Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Knight's Krait Brazier":{"Knight's Mithril Imbued Inscription":1,"Mithril Torch Head":1,"Elder Torch Handle":1},
		"Knight's Krait Handgun":{"Knight's Mithril Imbued Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Knight's Krait Harpoon Gun":{"Elder Harpoon":1,"Knight's Mithril Imbued Inscription":1,"Elder Rifle Stock":1},
		"Knight's Krait Recurve Bow":{"Elder Longbow Stave":1,"Knight's Mithril Imbued Inscription":1,"Thick String":1},
		"Knight's Krait Shooter":{"Knight's Mithril Imbued Inscription":1,"Mithril Rifle Barrel":1,"Elder Rifle Stock":1},
		"Knight's Krait Short Bow":{"Knight's Mithril Imbued Inscription":1,"Thick String":1,"Elder Short-Bow Stave":1},
		"Knight's Krait Whelk":{"Knight's Mithril Imbued Inscription":1,"Mithril Horn":1,"Mithril Warhorn Mouthpiece":1},
		"Major Sigil of Conjuration-2":{"Mithril Ingot":1,"Pile of Vile Essence":1},
		"Rampager's Krait Brazier":{"Mithril Torch Head":1,"Rampager's Mithril Imbued Inscription":1,"Elder Torch Handle":1},
		"Rampager's Krait Handgun":{"Mithril Pistol Barrel":1,"Elder Pistol Frame":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Harpoon Gun":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Recurve Bow":{"Elder Longbow Stave":1,"Thick String":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Shooter":{"Elder Rifle Stock":1,"Mithril Rifle Barrel":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Short Bow":{"Thick String":1,"Elder Short-Bow Stave":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Whelk":{"Mithril Warhorn Mouthpiece":1,"Mithril Horn":1,"Rampager's Mithril Imbued Inscription":1},
		"Valkyrie Krait Brazier":{"Mithril Torch Head":1,"Valkyrie Mithril Imbued Inscription":1,"Elder Torch Handle":1},
		"Valkyrie Krait Handgun":{"Valkyrie Mithril Imbued Inscription":1,"Elder Pistol Frame":1,"Mithril Pistol Barrel":1},
		"Valkyrie Krait Harpoon Gun":{"Elder Harpoon":1,"Elder Rifle Stock":1,"Valkyrie Mithril Imbued Inscription":1},
		"Valkyrie Krait Recurve Bow":{"Elder Longbow Stave":1,"Thick String":1,"Valkyrie Mithril Imbued Inscription":1},
		"Valkyrie Krait Shooter":{"Elder Rifle Stock":1,"Valkyrie Mithril Imbued Inscription":1,"Mithril Rifle Barrel":1},
		"Valkyrie Krait Whelk":{"Mithril Horn":1,"Valkyrie Mithril Imbued Inscription":1,"Mithril Warhorn Mouthpiece":1},
		"Valkyrie's Krait Short Bow":{"Thick String":1,"Valkyrie Mithril Imbued Inscription":1,"Elder Short-Bow Stave":1}
	},
}
