# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/5/2013
Last Updated: 1/6/2013
Purpose: Recipe list for Jewelcrafting used by Crafting.py
'''
jewelcraft = {
	"0":{
		"Amber Copper Ring-Fine":{"Copper Setting":1,"Copper Band":1,"Amber Pebble":1},
		"Amber Copper Stud-Fine":{"Copper Setting":1,"Copper Hook":1,"Amber Pebble":1},
		"Copper Band":{"Copper Ingot":3},
		"Copper Hook":{"Copper Ingot":2},
		"Copper Ingot":{"Copper Ore":2},
		"Copper Setting":{"Copper Ingot":2},
		"Garnet Copper Ring-Fine":{"Garnet Pebble":1,"Copper Setting":1,"Copper Band":1},
		"Garnet Copper Stud-Fine":{"Garnet Pebble":1,"Copper Setting":1,"Copper Hook":1},
		"Turquoise Copper Ring-Fine":{"Turquoise Pebble":1,"Copper Setting":1,"Copper Band":1},
		"Turquoise Copper Stud-Fine":{"Turquoise Pebble":1,"Copper Setting":1,"Copper Hook":1}
	},
	"25":{
		"Malachite Copper Ring-Fine":{"Copper Setting":1,"Malachite Pebble":1,"Copper Band":1},
		"Malachite Copper Stud-Fine":{"Copper Setting":1,"Malachite Pebble":1,"Copper Hook":1},
		"Pearl Copper Ring-Fine":{"Copper Setting":1,"Copper Band":1,"Pearl":1},
		"Pearl Copper Stud-Fine":{"Copper Setting":1,"Copper Hook":1,"Pearl":1},
		"Tiger's Eye Copper Ring-Fine":{"Copper Setting":1,"Tiger's Eye Pebble":1,"Copper Band":1},
		"Tiger's Eye Copper Stud-Fine":{"Copper Setting":1,"Tiger's Eye Pebble":1,"Copper Hook":1}
	},
	"50":{
		"Adorned Amber Jewel":{"Copper Filigree":1,"Amber Pebble":1},
		"Adorned Garnet Jewel":{"Garnet Pebble":1,"Copper Filigree":1},
		"Adorned Malachite Jewel":{"Copper Filigree":1,"Malachite Pebble":1},
		"Adorned Pearl":{"Copper Filigree":1,"Pearl":1},
		"Adorned Snowflake":{"Tiny Snowflake":1,"Copper Filigree":1},
		"Adorned Tiger's Eye Jewel":{"Copper Filigree":1,"Tiger's Eye Pebble":1},
		"Adorned Turquoise Jewel":{"Turquoise Pebble":1,"Copper Filigree":1},
		"Amber Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Amber Pebble":1},
		"Amber Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Amber Jewel":1},
		"Amber Copper Ring-Master":{"Copper Setting":1,"Adorned Amber Jewel":1,"Copper Band":1},
		"Amber Copper Stud-Master":{"Copper Setting":1,"Adorned Amber Jewel":1,"Copper Hook":1},
		"Amethyst Nugget":{"Garnet Pebble":1,"Turquoise Pebble":1,"Pile of Glittering Dust":1},
		"Carnelian Nugget":{"Garnet Pebble":1,"Tiger's Eye Pebble":1,"Pile of Glittering Dust":1},
		"Copper Chain":{"Copper Ingot":4},
		"Copper Filigree":{"Copper Ingot":2},
		"Garnet Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Garnet Pebble":1},
		"Garnet Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Garnet Jewel":1},
		"Garnet Copper Ring-Master":{"Copper Setting":1,"Copper Band":1,"Adorned Garnet Jewel":1},
		"Garnet Copper Stud-Master":{"Copper Setting":1,"Copper Hook":1,"Adorned Garnet Jewel":1},
		"Lapis Nugget":{"Turquoise Pebble":1,"Malachite Pebble":1,"Pile of Glittering Dust":1},
		"Malachite Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Malachite Pebble":1},
		"Malachite Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Malachite Jewel":1},
		"Malachite Copper Ring-Master":{"Adorned Malachite Jewel":1,"Copper Setting":1,"Copper Band":1},
		"Malachite Copper Stud-Master":{"Adorned Malachite Jewel":1,"Copper Setting":1,"Copper Hook":1},
		"Pearl Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Pearl":1},
		"Pearl Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Pearl":1},
		"Pearl Copper Ring-Master":{"Copper Setting":1,"Copper Band":1,"Adorned Pearl":1},
		"Pearl Copper Stud-Master":{"Copper Setting":1,"Copper Hook":1,"Adorned Pearl":1},
		"Peridot Nugget":{"Turquoise Pebble":1,"Tiger's Eye Pebble":1,"Pile of Glittering Dust":1},
		"Snowflake Copper Amulet":{"Copper Chain":1,"Copper Setting":1,"Adorned Snowflake":1},
		"Snowflake Copper Earring":{"Copper Setting":1,"Copper Hook":1,"Adorned Snowflake":1},
		"Snowflake Copper Ring":{"Copper Setting":1,"Copper Band":1,"Adorned Snowflake":1},
		"Spinel Nugget":{"Garnet Pebble":1,"Pearl":1,"Pile of Glittering Dust":1},
		"Sunstone Nugget":{"Copper Doubloon":1,"Tiger's Eye Pebble":1,"Pile of Glittering Dust":1},
		"Tiger's Eye Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Tiger's Eye Pebble":1},
		"Tiger's Eye Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Tiger's Eye Jewel":1},
		"Tiger's Eye Copper Ring-Master":{"Copper Setting":1,"Copper Band":1,"Adorned Tiger's Eye Jewel":1},
		"Tiger's Eye Copper Stud-Master":{"Copper Setting":1,"Copper Hook":1,"Adorned Tiger's Eye Jewel":1},
		"Topaz Nugget":{"Pile of Glittering Dust":1,"Tiger's Eye Pebble":1,"Amber Pebble":1},
		"Turquoise Copper Amulet-Fine":{"Copper Chain":1,"Copper Setting":1,"Turquoise Pebble":1},
		"Turquoise Copper Amulet-Master":{"Copper Chain":1,"Copper Setting":1,"Adorned Turquoise Jewel":1},
		"Turquoise Copper Ring-Master":{"Adorned Turquoise Jewel":1,"Copper Setting":1,"Copper Band":1},
		"Turquoise Copper Stud-Master":{"Adorned Turquoise Jewel":1,"Copper Setting":1,"Copper Hook":1}
	},
	"75":{
		"Amethyst Silver Band-Fine":{"Silver Band":1,"Silver Setting":1,"Amethyst Nugget":1},
		"Amethyst Silver Earring-Fine":{"Silver Hook":1,"Silver Setting":1,"Amethyst Nugget":1},
		"Amethyst Silver Pendant-Fine":{"Silver Chain":1,"Silver Setting":1,"Amethyst Nugget":1},
		"Silver Band":{"Silver Ingot":3},
		"Silver Chain":{"Silver Ingot":4},
		"Silver Hook":{"Silver Ingot":2},
		"Silver Ingot":{"Silver Ore":2},
		"Silver Setting":{"Silver Ingot":2},
		"Sunstone Silver Band-Fine":{"Sunstone Nugget":1,"Silver Band":1,"Silver Setting":1},
		"Sunstone Silver Earring-Fine":{"Sunstone Nugget":1,"Silver Hook":1,"Silver Setting":1},
		"Sunstone Silver Pendant-Fine":{"Sunstone Nugget":1,"Silver Chain":1,"Silver Setting":1},
		"Topaz Silver Band-Fine":{"Silver Band":1,"Silver Setting":1,"Topaz Nugget":1},
		"Topaz Silver Earring-Fine":{"Silver Hook":1,"Silver Setting":1,"Topaz Nugget":1},
		"Topaz Silver Pendant-Fine":{"Silver Chain":1,"Silver Setting":1,"Topaz Nugget":1}
	},
	"100":{
		"Carnelian Silver Amulet-Fine":{"Carnelian Nugget":1,"Silver Chain":1,"Silver Setting":1},
		"Carnelian Silver Ring-Fine":{"Carnelian Nugget":1,"Silver Band":1,"Silver Setting":1},
		"Carnelian Silver Stud-Fine":{"Carnelian Nugget":1,"Silver Hook":1,"Silver Setting":1},
		"Intricate Amethyst Jewel":{"Silver Filigree":1,"Amethyst Nugget":1},
		"Intricate Carnelian Jewel":{"Carnelian Nugget":1,"Silver Filigree":1},
		"Intricate Lapis Jewel":{"Lapis Nugget":1,"Silver Filigree":1},
		"Intricate Peridot Jewel":{"Peridot Nugget":1,"Silver Filigree":1},
		"Intricate Snowflake":{"Delicate Snowflake":1,"Silver Filigree":1},
		"Intricate Spinel Jewel":{"Spinel Nugget":1,"Silver Filigree":1},
		"Intricate Sunstone Jewel":{"Sunstone Nugget":1,"Silver Filigree":1},
		"Intricate Topaz Jewel":{"Silver Filigree":1,"Topaz Nugget":1},
		"Lapis Silver Amulet-Fine":{"Lapis Nugget":1,"Silver Chain":1,"Silver Setting":1},
		"Lapis Silver Earring-Fine":{"Silver Hook":1,"Lapis Nugget":1,"Silver Setting":1},
		"Lapis Silver Ring-Fine":{"Silver Band":1,"Lapis Nugget":1,"Silver Setting":1},
		"Peridot Silver Amulet-Fine":{"Peridot Nugget":1,"Silver Chain":1,"Silver Setting":1},
		"Peridot Silver Earring-Fine":{"Peridot Nugget":1,"Silver Hook":1,"Silver Setting":1},
		"Peridot Silver Ring-Fine":{"Peridot Nugget":1,"Silver Band":1,"Silver Setting":1},
		"Silver Filigree":{"Silver Ingot":2},
		"Snowflake Silver Amulet":{"Intricate Snowflake":1,"Silver Chain":1,"Silver Setting":1},
		"Snowflake Silver Earring":{"Intricate Snowflake":1,"Silver Hook":1,"Silver Setting":1},
		"Snowflake Silver Ring":{"Intricate Snowflake":1,"Silver Band":1,"Silver Setting":1},
		"Spinel Silver Amulet-Fine":{"Spinel Nugget":1,"Silver Chain":1,"Silver Setting":1},
		"Spinel Silver Earring-Fine":{"Spinel Nugget":1,"Silver Hook":1,"Silver Setting":1},
		"Spinel Silver Ring-Fine":{"Spinel Nugget":1,"Silver Band":1,"Silver Setting":1}
	},
	"125":{
		"Amethyst Lump":{"Pile of Shimmering Dust":1,"Amethyst Nugget":2},
		"Amethyst Silver Band-Master":{"Intricate Amethyst Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Amethyst Silver Band-Rare":{"Embellished Intricate Amethyst Jewel":3,"Silver Band":1,"Silver Setting":1},
		"Amethyst Silver Earring-Master":{"Intricate Amethyst Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Amethyst Silver Earring-Rare":{"Embellished Intricate Amethyst Jewel":3,"Silver Hook":1,"Silver Setting":1},
		"Amethyst Silver Pendant-Master":{"Intricate Amethyst Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Amethyst Silver Pendant-Rare":{"Embellished Intricate Amethyst Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Candy Corn Silver Pendant":{"Embellished Intricate Sunstone Jewel":3,"Silver Chain":1,"Silver Setting":1,"Piece of Candy Corn":50},
		"Carnelian Lump":{"Carnelian Nugget":2,"Pile of Shimmering Dust":1},
		"Carnelian Silver Amulet-Master":{"Intricate Carnelian Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Carnelian Silver Amulet-Rare":{"Embellished Intricate Carnelian Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Carnelian Silver Ring-Master":{"Intricate Carnelian Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Carnelian Silver Ring-Rare":{"Embellished Intricate Carnelian Jewel":3,"Silver Band":1,"Silver Setting":1},
		"Carnelian Silver Stud-Master":{"Intricate Carnelian Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Carnelian Silver Stud-Rare":{"Embellished Intricate Carnelian Jewel":3,"Silver Hook":1,"Silver Setting":1},
		"Embellished Intricate Amethyst Jewel":{"Silver Filigree":1,"Amethyst Nugget":5},
		"Embellished Intricate Carnelian Jewel":{"Carnelian Nugget":5,"Silver Filigree":1},
		"Embellished Intricate Lapis Jewel":{"Lapis Nugget":5,"Silver Filigree":1},
		"Embellished Intricate Peridot Jewel":{"Peridot Nugget":5,"Silver Filigree":1},
		"Embellished Intricate Spinel Jewel":{"Spinel Nugget":5,"Silver Filigree":1},
		"Embellished Intricate Sunstone Jewel":{"Sunstone Nugget":5,"Silver Filigree":1},
		"Embellished Intricate Topaz Jewel":{"Silver Filigree":1,"Topaz Nugget":5},
		"Lapis Lump":{"Lapis Nugget":2,"Pile of Shimmering Dust":1},
		"Lapis Silver Amulet-Master":{"Intricate Lapis Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Lapis Silver Amulet-Rare":{"Embellished Intricate Lapis Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Lapis Silver Earring-Master":{"Intricate Lapis Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Lapis Silver Earring-Rare":{"Embellished Intricate Lapis Jewel":3,"Silver Hook":1,"Silver Setting":1},
		"Lapis Silver Ring-Master":{"Intricate Lapis Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Lapis Silver Ring-Rare":{"Embellished Intricate Lapis Jewel":3,"Silver Band":1,"Silver Setting":1},
		"Peridot Lump":{"Peridot Nugget":2,"Pile of Shimmering Dust":1},
		"Peridot Silver Earring-Master":{"Silver Hook":1,"Intricate Peridot Jewel":1,"Silver Setting":1},
		"Peridot Silver Earring-Rare":{"Silver Hook":1,"Embellished Intricate Peridot Jewel":3,"Silver Setting":1},
		"Peridot Silver Pendant-Master":{"Intricate Peridot Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Peridot Silver Pendant-Rare":{"Embellished Intricate Peridot Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Peridot Silver Ring-Master":{"Silver Band":1,"Intricate Peridot Jewel":1,"Silver Setting":1},
		"Peridot Silver Ring-Rare":{"Silver Band":1,"Embellished Intricate Peridot Jewel":3,"Silver Setting":1},
		"Spinel Lump":{"Spinel Nugget":2,"Pile of Shimmering Dust":1},
		"Spinel Silver Amulet-Master":{"Intricate Spinel Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Spinel Silver Amulet-Rare":{"Embellished Intricate Spinel Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Spinel Silver Earring-Master":{"Intricate Spinel Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Spinel Silver Earring-Rare":{"Silver Hook":1,"Embellished Intricate Spinel Jewel":3,"Silver Setting":1},
		"Spinel Silver Ring-Master":{"Intricate Spinel Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Spinel Silver Ring-Rare":{"Silver Band":1,"Embellished Intricate Spinel Jewel":3,"Silver Setting":1},
		"Sunstone Lump":{"Sunstone Nugget":2,"Pile of Shimmering Dust":1},
		"Sunstone Silver Band-Master":{"Intricate Sunstone Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Sunstone Silver Band-Rare":{"Embellished Intricate Sunstone Jewel":3,"Silver Band":1,"Silver Setting":1},
		"Sunstone Silver Earring-Master":{"Intricate Sunstone Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Sunstone Silver Earring-Rare":{"Embellished Intricate Sunstone Jewel":3,"Silver Hook":1,"Silver Setting":1},
		"Sunstone Silver Pendant-Master":{"Intricate Sunstone Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Sunstone Silver Pendant-Rare":{"Embellished Intricate Sunstone Jewel":3,"Silver Chain":1,"Silver Setting":1},
		"Topaz Lump":{"Pile of Shimmering Dust":1,"Topaz Nugget":2},
		"Topaz Silver Band-Master":{"Intricate Topaz Jewel":1,"Silver Band":1,"Silver Setting":1},
		"Topaz Silver Band-Rare":{"Embellished Intricate Topaz Jewel":3,"Silver Band":1,"Silver Setting":1},
		"Topaz Silver Earring-Master":{"Intricate Topaz Jewel":1,"Silver Hook":1,"Silver Setting":1},
		"Topaz Silver Earring-Rare":{"Embellished Intricate Topaz Jewel":3,"Silver Hook":1,"Silver Setting":1},
		"Topaz Silver Pendant-Master":{"Intricate Topaz Jewel":1,"Silver Chain":1,"Silver Setting":1},
		"Topaz Silver Pendant-Rare":{"Embellished Intricate Topaz Jewel":3,"Silver Chain":1,"Silver Setting":1}
	},
	"150":{
		"Amethyst Gold Amulet-Fine":{"Amethyst Lump":1,"Gold Chain":1,"Gold Setting":1},
		"Amethyst Gold Earring-Fine":{"Amethyst Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Amethyst Gold Ring-Fine":{"Amethyst Lump":1,"Gold Band":1,"Gold Setting":1},
		"Gold Band":{"Gold Ingot":3},
		"Gold Chain":{"Gold Ingot":4},
		"Gold Hook":{"Gold Ingot":2},
		"Gold Ingot":{"Gold Ore":2},
		"Gold Setting":{"Gold Ingot":2},
		"Sunstone Gold Amulet-Fine":{"Gold Chain":1,"Sunstone Lump":1,"Gold Setting":1},
		"Sunstone Gold Earring-Fine":{"Sunstone Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Sunstone Gold Ring-Fine":{"Gold Band":1,"Sunstone Lump":1,"Gold Setting":1},
		"Topaz Gold Amulet-Fine":{"Gold Chain":1,"Topaz Lump":1,"Gold Setting":1},
		"Topaz Gold Earring-Fine":{"Topaz Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Topaz Gold Ring-Fine":{"Gold Band":1,"Topaz Lump":1,"Gold Setting":1}
	},
	"175":{
		"Gilded Amethyst Jewel":{"Gold Filigree":1,"Amethyst Lump":1},
		"Gilded Lapis Jewel":{"Gold Filigree":1,"Lapis Lump":1},
		"Gilded Sunstone Jewel":{"Gold Filigree":1,"Sunstone Lump":1},
		"Gilded Topaz Jewel":{"Gold Filigree":1,"Topaz Lump":1},
		"Carnelian Band-Fine":{"Gold Band":1,"Carnelian Lump":1,"Gold Setting":1},
		"Carnelian Earring-Fine":{"Carnelian Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Carnelian Pendant-Fine":{"Carnelian Lump":1,"Gold Chain":1,"Gold Setting":1},
		"Gilded Carnelian Jewel":{"Gold Filigree":1,"Carnelian Lump":1},
		"Gilded Peridot Jewel":{"Gold Filigree":1,"Peridot Lump":1},
		"Gilded Snowflake":{"Gold Filigree":1,"Glittering Snowflake":1},
		"Gilded Spinel Jewel":{"Gold Filigree":1,"Spinel Lump":1},
		"Gold Filigree":{"Gold Ingot":2},
		"Lapis Gold Earring-Fine":{"Lapis Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Lapis Gold Ring-Fine":{"Lapis Lump":1,"Gold Band":1,"Gold Setting":1},
		"Lapis Gold Amulet-Fine":{"Lapis Lump":1,"Gold Chain":1,"Gold Setting":1},
		"Peridot Gold Amulet-Fine":{"Peridot Lump":1,"Gold Chain":1,"Gold Setting":1},
		"Peridot Gold Earring-Fine":{"Peridot Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Peridot Gold Ring-Fine":{"Gold Band":1,"Peridot Lump":1,"Gold Setting":1},
		"Snowflake Gold Amulet":{"Gilded Snowflake":1,"Gold Setting":1,"Gold Chain":1},
		"Snowflake Gold Earring":{"Gilded Snowflake":1,"Gold Setting":1,"Gold Hook":1},
		"Snowflake Gold Ring":{"Gold Band":1,"Gilded Snowflake":1,"Gold Setting":1},
		"Spinel Gold Amulet-Fine":{"Gold Chain":1,"Spinel Lump":1,"Gold Setting":1},
		"Spinel Gold Earring-Fine":{"Spinel Lump":1,"Gold Setting":1,"Gold Hook":1},
		"Spinel Gold Ring-Fine":{"Gold Band":1,"Spinel Lump":1,"Gold Setting":1}
	},
	"200":{
		"Amethyst Gold Amulet-Master":{"Gold Chain":1,"Gilded Amethyst Jewel":1,"Gold Setting":1},
		"Amethyst Gold Amulet-Rare":{"Gold Chain":1,"Embellished Gilded Amethyst Jewel":3,"Gold Setting":1},
		"Amethyst Gold Earring-Master":{"Gilded Amethyst Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Amethyst Gold Earring-Rare":{"Embellished Gilded Amethyst Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Amethyst Gold Ring-Master":{"Gold Band":1,"Gilded Amethyst Jewel":1,"Gold Setting":1},
		"Amethyst Gold Ring-Rare":{"Gold Band":1,"Embellished Gilded Amethyst Jewel":3,"Gold Setting":1},
		"Beryl Shard":{"Lapis Lump":1,"Pile of Radiant Dust":1,"Peridot Lump":1},
		"Candy Corn Gold Amulet":{"Embellished Gilded Sunstone Jewel":3,"Gold Chain":1,"Piece of Candy Corn":100,"Gold Setting":1},
		"Carnelian Gold Band-Master":{"Gilded Carnelian Jewel":1,"Gold Band":1,"Gold Setting":1},
		"Carnelian Gold Band-Rare":{"Embellished Gilded Carnelian Jewel":3,"Gold Band":1,"Gold Setting":1},
		"Carnelian Gold Earring-Master":{"Gilded Carnelian Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Carnelian Gold Earring-Rare":{"Embellished Gilded Carnelian Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Carnelian Gold Pendant-Master":{"Gilded Carnelian Jewel":1,"Gold Chain":1,"Gold Setting":1},
		"Carnelian Gold Pendant-Rare":{"Embellished Gilded Carnelian Jewel":3,"Gold Chain":1,"Gold Setting":1},
		"Chrysocola Shard":{"Amethyst Lump":2,"Pile of Radiant Dust":1},
		"Coral Chunk":{"Pile of Radiant Dust":1,"Topaz Lump":2},
		"Embellished Gilded Amethyst Jewel":{"Gold Filigree":1,"Amethyst Lump":5},
		"Embellished Gilded Carnelian Jewel":{"Gold Filigree":1,"Carnelian Lump":5},
		"Embellished Gilded Lapis Jewel":{"Gold Filigree":1,"Lapis Lump":5},
		"Embellished Gilded Peridot Jewel":{"Gold Filigree":1,"Peridot Lump":5},
		"Embellished Gilded Spinel Jewel":{"Gold Filigree":1,"Spinel Lump":5},
		"Embellished Gilded Sunstone Jewel":{"Gold Filigree":1,"Sunstone Lump":5},
		"Embellished Gilded Topaz Jewel":{"Gold Filigree":1,"Topaz Lump":5},
		"Emerald Shard":{"Pile of Radiant Dust":1,"Peridot Lump":2},
		"Lapis Gold Amulet-Master":{"Gold Chain":1,"Gilded Lapis Jewel":1,"Gold Setting":1},
		"Lapis Gold Amulet-Rare":{"Gold Chain":1,"Embellished Gilded Lapis Jewel":3,"Gold Setting":1},
		"Lapis Gold Earring-Master":{"Gilded Lapis Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Lapis Gold Earring-Rare":{"Embellished Gilded Lapis Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Lapis Gold Ring-Master":{"Gold Band":1,"Gilded Lapis Jewel":1,"Gold Setting":1},
		"Lapis Gold Ring-Rare":{"Gold Band":1,"Embellished Gilded Lapis Jewel":3,"Gold Setting":1},
		"Opal Shard":{"Pile of Radiant Dust":1,"Sunstone Lump":2},
		"Peridot Gold Amulet-Master":{"Gold Chain":1,"Gilded Peridot Jewel":1,"Gold Setting":1},
		"Peridot Gold Amulet-Rare":{"Gold Chain":1,"Embellished Gilded Peridot Jewel":3,"Gold Setting":1},
		"Peridot Gold Earring-Master":{"Gilded Peridot Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Peridot Gold Earring-Rare":{"Embellished Gilded Peridot Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Peridot Gold Ring-Master":{"Gold Band":1,"Gilded Peridot Jewel":1,"Gold Setting":1},
		"Peridot Gold Ring-Rare":{"Gold Band":1,"Embellished Gilded Peridot Jewel":3,"Gold Setting":1},
		"Ruby Shard":{"Pile of Radiant Dust":1,"Carnelian Lump":2},
		"Sapphire Shard":{"Lapis Lump":2,"Pile of Radiant Dust":1},
		"Spinel Gold Amulet-Master":{"Gold Chain":1,"Gilded Spinel Jewel":1,"Gold Setting":1},
		"Spinel Gold Amulet-Rare":{"Gold Chain":1,"Embellished Gilded Spinel Jewel":3,"Gold Setting":1},
		"Spinel Gold Earring-Master":{"Gilded Spinel Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Spinel Gold Earring-Rare":{"Embellished Gilded Spinel Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Spinel Gold Ring-Master":{"Gold Band":1,"Gilded Spinel Jewel":1,"Gold Setting":1},
		"Spinel Gold Ring-Rare":{"Gold Band":1,"Embellished Gilded Spinel Jewel":3,"Gold Setting":1},
		"Sunstone Gold Amulet-Master":{"Gilded Sunstone Jewel":1,"Gold Chain":1,"Gold Setting":1},
		"Sunstone Gold Amulet-Rare":{"Embellished Gilded Sunstone Jewel":3,"Gold Chain":1,"Gold Setting":1},
		"Sunstone Gold Earring-Master":{"Gilded Sunstone Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Sunstone Gold Earring-Rare":{"Embellished Gilded Sunstone Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Sunstone Gold Ring-Master":{"Gilded Sunstone Jewel":1,"Gold Band":1,"Gold Setting":1},
		"Sunstone Gold Ring-Rare":{"Embellished Gilded Sunstone Jewel":3,"Gold Band":1,"Gold Setting":1},
		"Topaz Gold Amulet-Master":{"Gold Chain":1,"Gilded Topaz Jewel":1,"Gold Setting":1},
		"Topaz Gold Amulet-Rare":{"Gold Chain":1,"Embellished Gilded Topaz Jewel":3,"Gold Setting":1},
		"Topaz Gold Earring-Master":{"Gilded Topaz Jewel":1,"Gold Setting":1,"Gold Hook":1},
		"Topaz Gold Earring-Rare":{"Embellished Gilded Topaz Jewel":3,"Gold Setting":1,"Gold Hook":1},
		"Topaz Gold Ring-Master":{"Gold Band":1,"Gilded Topaz Jewel":1,"Gold Setting":1},
		"Topaz Gold Ring-Rare":{"Gold Band":1,"Embellished Gilded Topaz Jewel":3,"Gold Setting":1}
	},
	"225":{
		"Beryl Platinum Amulet-Fine":{"Beryl Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Beryl Platinum Earring-Fine":{"Platinum Hook":1,"Beryl Shard":1,"Platinum Setting":1},
		"Beryl Platinum Ring-Fine":{"Platinum Band":1,"Beryl Shard":1,"Platinum Setting":1},
		"Chrysocola Platinum Amulet-Fine":{"Chrysocola Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Chrysocola Platinum Earring-Fine":{"Platinum Hook":1,"Chrysocola Shard":1,"Platinum Setting":1},
		"Chrysocola Platinum Ring-Fine":{"Platinum Band":1,"Chrysocola Shard":1,"Platinum Setting":1},
		"Emerald Platinum Amulet-Fine":{"Emerald Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Emerald Platinum Earring-Fine":{"Platinum Hook":1,"Platinum Setting":1,"Emerald Shard":1},
		"Emerald Platinum Ring-Fine":{"Platinum Band":1,"Platinum Setting":1,"Emerald Shard":1},
		"Platinum Band":{"Platinum Ingot":3},
		"Platinum Chain":{"Platinum Ingot":4},
		"Platinum Hook":{"Platinum Ingot":2},
		"Platinum Ingot":{"Platinum Ore":2},
		"Platinum Setting":{"Platinum Ingot":2}
	},
	"250":{
		"Ornate Beryl Jewel":{"Platinum Filigree":1,"Beryl Shard":1},
		"Ornate Chrysocola Jewel":{"Platinum Filigree":1,"Chrysocola Shard":1},
		"Ornate Coral Jewel":{"Platinum Filigree":1,"Coral Chunk":1},
		"Ornate Emerald Jewel":{"Platinum Filigree":1,"Emerald Shard":1},
		"Ornate Opal Jewel":{"Platinum Filigree":1,"Opal Shard":1},
		"Ornate Ruby Jewel":{"Platinum Filigree":1,"Ruby Shard":1},
		"Ornate Sapphire Jewel":{"Sapphire Shard":1,"Platinum Filigree":1},
		"Coral Platinum Amulet-Fine":{"Coral Chunk":1,"Platinum Setting":1,"Platinum Chain":1},
		"Coral Platinum Earring-Fine":{"Platinum Hook":1,"Coral Chunk":1,"Platinum Setting":1},
		"Coral Platinum Ring-Fine":{"Platinum Band":1,"Coral Chunk":1,"Platinum Setting":1},
		"Opal Platinum Amulet-Fine":{"Opal Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Opal Platinum Earring-Fine":{"Platinum Hook":1,"Opal Shard":1,"Platinum Setting":1},
		"Opal Platinum Ring-Fine":{"Platinum Band":1,"Opal Shard":1,"Platinum Setting":1},
		"Platinum Filigree":{"Platinum Ingot":2},
		"Ruby Platinum Amulet-Fine":{"Ruby Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Ruby Platinum Earring-Fine":{"Platinum Hook":1,"Ruby Shard":1,"Platinum Setting":1},
		"Ruby Platinum Ring-Fine":{"Platinum Band":1,"Ruby Shard":1,"Platinum Setting":1},
		"Sapphire Platinum Amulet-Fine":{"Sapphire Shard":1,"Platinum Setting":1,"Platinum Chain":1},
		"Sapphire Platinum Earring-Fine":{"Platinum Hook":1,"Sapphire Shard":1,"Platinum Setting":1},
		"Sapphire Platinum Ring-Fine":{"Platinum Band":1,"Sapphire Shard":1,"Platinum Setting":1}
	},
	"275":{
		"Beryl Crystal":{"Beryl Shard":2,"Pile of Luminous Dust":1},
		"Beryl Platinum Amulet-Master":{"Platinum Setting":1,"Platinum Chain":1,"Ornate Beryl Jewel":1},
		"Beryl Platinum Amulet-Rare":{"Platinum Setting":1,"Platinum Chain":1,"Embellished Ornate Beryl Jewel":3},
		"Beryl Platinum Earring-Master":{"Platinum Hook":1,"Platinum Setting":1,"Ornate Beryl Jewel":1},
		"Beryl Platinum Earring-Rare":{"Platinum Hook":1,"Platinum Setting":1,"Embellished Ornate Beryl Jewel":3},
		"Beryl Platinum Ring-Master":{"Platinum Band":1,"Platinum Setting":1,"Ornate Beryl Jewel":1},
		"Beryl Platinum Ring-Rare":{"Platinum Band":1,"Platinum Setting":1,"Embellished Ornate Beryl Jewel":3},
		"Chrysocola Crystal":{"Chrysocola Shard":2,"Pile of Luminous Dust":1},
		"Chrysocola Platinum Amulet-Master":{"Platinum Setting":1,"Platinum Chain":1,"Ornate Chrysocola Jewel":1},
		"Chrysocola Platinum Amulet-Rare":{"Platinum Setting":1,"Platinum Chain":1,"Embellished Ornate Chrysocola Jewel":3},
		"Chrysocola Platinum Earring-Master":{"Platinum Hook":1,"Platinum Setting":1,"Ornate Chrysocola Jewel":1},
		"Chrysocola Platinum Earring-Rare":{"Platinum Hook":1,"Platinum Setting":1,"Embellished Ornate Chrysocola Jewel":3},
		"Chrysocola Platinum Ring-Master":{"Platinum Band":1,"Platinum Setting":1,"Ornate Chrysocola Jewel":1},
		"Chrysocola Platinum Ring-Rare":{"Platinum Band":1,"Platinum Setting":1,"Embellished Ornate Chrysocola Jewel":3},
		"Coral Platinum Amulet-Master":{"Ornate Coral Jewel":1,"Platinum Setting":1,"Platinum Chain":1},
		"Coral Platinum Amulet-Rare":{"Embellished Ornate Coral Jewel":3,"Platinum Setting":1,"Platinum Chain":1},
		"Coral Platinum Earring-Master":{"Platinum Hook":1,"Ornate Coral Jewel":1,"Platinum Setting":1},
		"Coral Platinum Earring-Rare":{"Platinum Hook":1,"Embellished Ornate Coral Jewel":3,"Platinum Setting":1},
		"Coral Platinum Ring-Master":{"Platinum Band":1,"Ornate Coral Jewel":1,"Platinum Setting":1},
		"Coral Platinum Ring-Rare":{"Platinum Band":1,"Embellished Ornate Coral Jewel":3,"Platinum Setting":1},
		"Coral Tentacle":{"Coral Chunk":2,"Pile of Luminous Dust":1},
		"Embellished Ornate Beryl Jewel":{"Platinum Filigree":1,"Beryl Shard":5},
		"Embellished Ornate Chrysocola Jewel":{"Platinum Filigree":1,"Chrysocola Shard":5},
		"Embellished Ornate Coral Jewel":{"Platinum Filigree":1,"Coral Chunk":5},
		"Embellished Ornate Emerald Jewel":{"Platinum Filigree":1,"Emerald Shard":5},
		"Embellished Ornate Opal Jewel":{"Platinum Filigree":1,"Opal Shard":5},
		"Embellished Ornate Ruby Jewel":{"Platinum Filigree":1,"Ruby Shard":5},
		"Embellished Ornate Sapphire Jewel":{"Sapphire Shard":5,"Platinum Filigree":1},
		"Emerald Crystal":{"Pile of Luminous Dust":1,"Emerald Shard":2},
		"Emerald Platinum Amulet-Master":{"Ornate Emerald Jewel":1,"Platinum Setting":1,"Platinum Chain":1},
		"Emerald Platinum Amulet-Rare":{"Embellished Ornate Emerald Jewel":3,"Platinum Setting":1,"Platinum Chain":1},
		"Emerald Platinum Earring-Master":{"Platinum Hook":1,"Ornate Emerald Jewel":1,"Platinum Setting":1},
		"Emerald Platinum Earring-Rare":{"Platinum Hook":1,"Embellished Ornate Emerald Jewel":3,"Platinum Setting":1},
		"Emerald Platinum Ring-Master":{"Platinum Band":1,"Ornate Emerald Jewel":1,"Platinum Setting":1},
		"Emerald Platinum Ring-Rare":{"Platinum Band":1,"Embellished Ornate Emerald Jewel":3,"Platinum Setting":1},
		"Opal Crystal":{"Pile of Luminous Dust":1,"Opal Shard":2},
		"Opal Platinum Amulet-Master":{"Ornate Opal Jewel":1,"Platinum Setting":1,"Platinum Chain":1},
		"Opal Platinum Amulet-Rare":{"Embellished Ornate Opal Jewel":3,"Platinum Setting":1,"Platinum Chain":1},
		"Opal Platinum Earring-Master":{"Platinum Hook":1,"Ornate Opal Jewel":1,"Platinum Setting":1},
		"Opal Platinum Earring-Rare":{"Platinum Hook":1,"Embellished Ornate Opal Jewel":3,"Platinum Setting":1},
		"Opal Platinum Ring-Master":{"Platinum Band":1,"Ornate Opal Jewel":1,"Platinum Setting":1},
		"Opal Platinum Ring-Rare":{"Platinum Band":1,"Embellished Ornate Opal Jewel":3,"Platinum Setting":1},
		"Ornate Snowflake":{"Platinum Filigree":1,"Unique Snowflake":1},
		"Ruby Crystal":{"Ruby Shard":2,"Pile of Luminous Dust":1},
		"Ruby Platinum Amulet-Master":{"Ornate Ruby Jewel":1,"Platinum Setting":1,"Platinum Chain":1},
		"Ruby Platinum Amulet-Rare":{"Embellished Ornate Ruby Jewel":3,"Platinum Setting":1,"Platinum Chain":1},
		"Ruby Platinum Earring-Master":{"Platinum Hook":1,"Ornate Ruby Jewel":1,"Platinum Setting":1},
		"Ruby Platinum Earring-Rare":{"Platinum Hook":1,"Embellished Ornate Ruby Jewel":3,"Platinum Setting":1},
		"Ruby Platinum Ring-Master":{"Platinum Band":1,"Ornate Ruby Jewel":1,"Platinum Setting":1},
		"Ruby Platinum Ring-Rare":{"Platinum Band":1,"Embellished Ornate Ruby Jewel":3,"Platinum Setting":1},
		"Sapphire Crystal":{"Sapphire Shard":2,"Pile of Luminous Dust":1},
		"Sapphire Platinum Amulet-Master":{"Ornate Sapphire Jewel":1,"Platinum Setting":1,"Platinum Chain":1},
		"Sapphire Platinum Amulet-Rare":{"Embellished Ornate Sapphire Jewel":3,"Platinum Setting":1,"Platinum Chain":1},
		"Sapphire Platinum Earring-Master":{"Platinum Hook":1,"Ornate Sapphire Jewel":1,"Platinum Setting":1},
		"Sapphire Platinum Earring-Rare":{"Platinum Hook":1,"Embellished Ornate Sapphire Jewel":3,"Platinum Setting":1},
		"Sapphire Platinum Ring-Master":{"Platinum Band":1,"Ornate Sapphire Jewel":1,"Platinum Setting":1},
		"Sapphire Platinum Ring-Rare":{"Platinum Band":1,"Embellished Ornate Sapphire Jewel":3,"Platinum Setting":1},
		"Snowflake Platinum Amulet":{"Ornate Snowflake":1,"Platinum Setting":1,"Platinum Chain":1},
		"Snowflake Platinum Earring":{"Platinum Hook":1,"Ornate Snowflake":1,"Platinum Setting":1},
		"Snowflake Platinum Ring":{"Platinum Band":1,"Ornate Snowflake":1,"Platinum Setting":1}
	},
	"300":{
		"Beryl Mithril Amulet-Fine":{"Beryl Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Beryl Mithril Earring-Fine":{"Mithril Hook":1,"Beryl Crystal":1,"Mithril Setting":1},
		"Beryl Mithril Ring-Fine":{"Mithril Band":1,"Beryl Crystal":1,"Mithril Setting":1},
		"Chrysocola Mithril Amulet-Fine":{"Chrysocola Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Chrysocola Mithril Earring-Fine":{"Mithril Hook":1,"Chrysocola Crystal":1,"Mithril Setting":1},
		"Chrysocola Mithril Ring-Fine":{"Mithril Band":1,"Chrysocola Crystal":1,"Mithril Setting":1},
		"Emerald Mithril Amulet-Fine":{"Emerald Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Emerald Mithril Earring-Fine":{"Mithril Hook":1,"Emerald Crystal":1,"Mithril Setting":1},
		"Emerald Mithril Ring-Fine":{"Mithril Band":1,"Emerald Crystal":1,"Mithril Setting":1},
		"Mithril Band":{"Mithril Ingot":3},
		"Mithril Chain":{"Mithril Ingot":4},
		"Mithril Hook":{"Mithril Ingot":2},
		"Mithril Ingot":{"Mithril Ore":2},
		"Mithril Setting":{"Mithril Ingot":2}
	},
	"325":{
		"Brilliant Azurite Jewel":{"Mithril Filigree":1,"Azurite Crystal":1},
		"Brilliant Beryl Jewel":{"Mithril Filigree":1,"Beryl Crystal":1},
		"Brilliant Chrysocola Jewel":{"Mithril Filigree":1,"Chrysocola Crystal":1},
		"Brilliant Coral Jewel":{"Coral Tentacle":1,"Mithril Filigree":1},
		"Brilliant Emerald Jewel":{"Emerald Crystal":1,"Mithril Filigree":1},
		"Brilliant Opal Jewel":{"Mithril Filigree":1,"Opal Crystal":1},
		"Brilliant Ruby Jewel":{"Mithril Filigree":1,"Ruby Crystal":1},
		"Brilliant Sapphire Jewel":{"Sapphire Crystal":1,"Mithril Filigree":1},
		"Azurite Mithril Amulet-Fine":{"Azurite Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Azurite Mithril Earring-Fine":{"Mithril Hook":1,"Azurite Crystal":1,"Mithril Setting":1},
		"Azurite Mithril Ring-Fine":{"Mithril Band":1,"Azurite Crystal":1,"Mithril Setting":1},
		"Coral Mithril Amulet-Fine":{"Coral Tentacle":1,"Mithril Setting":1,"Mithril Chain":1},
		"Coral Mithril Earring-Fine":{"Mithril Hook":1,"Coral Tentacle":1,"Mithril Setting":1},
		"Coral Mithril Ring-Fine":{"Mithril Band":1,"Coral Tentacle":1,"Mithril Setting":1},
		"Mithril Filigree":{"Mithril Ingot":2},
		"Opal Mithril Amulet-Fine":{"Opal Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Opal Mithril Earring-Fine":{"Mithril Hook":1,"Opal Crystal":1,"Mithril Setting":1},
		"Opal Mithril Ring-Fine":{"Mithril Band":1,"Opal Crystal":1,"Mithril Setting":1},
		"Ruby Mithril Amulet-Fine":{"Ruby Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Ruby Mithril Earring-Fine":{"Mithril Hook":1,"Ruby Crystal":1,"Mithril Setting":1},
		"Ruby Mithril Ring-Fine":{"Mithril Band":1,"Ruby Crystal":1,"Mithril Setting":1},
		"Sapphire Mithril Amulet-Fine":{"Sapphire Crystal":1,"Mithril Setting":1,"Mithril Chain":1},
		"Sapphire Mithril Earring-Fine":{"Mithril Hook":1,"Sapphire Crystal":1,"Mithril Setting":1},
		"Sapphire Mithril Ring-Fine":{"Mithril Band":1,"Sapphire Crystal":1,"Mithril Setting":1}
	},
	"350":{
		"Azurite Mithril Amulet-Master":{"Brilliant Azurite Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Azurite Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Azurite Jewel":1,"Mithril Setting":1},
		"Azurite Mithril Ring-Master":{"Mithril Band":1,"Brilliant Azurite Jewel":1,"Mithril Setting":1},
		"Azurite Orb":{"Azurite Crystal":2,"Pile of Incandescent Dust":5},
		"Beryl Mithril Amulet-Master":{"Brilliant Beryl Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Beryl Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Beryl Jewel":1,"Mithril Setting":1},
		"Beryl Mithril Ring-Master":{"Mithril Band":1,"Brilliant Beryl Jewel":1,"Mithril Setting":1},
		"Beryl Orb":{"Beryl Crystal":2,"Pile of Incandescent Dust":5},
		"Chrysocola Mithril Amulet-Master":{"Brilliant Chrysocola Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Chrysocola Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Chrysocola Jewel":1,"Mithril Setting":1},
		"Chrysocola Mithril Ring-Master":{"Mithril Band":1,"Brilliant Chrysocola Jewel":1,"Mithril Setting":1},
		"Chrysocola Orb":{"Chrysocola Crystal":2,"Pile of Incandescent Dust":5},
		"Coral Mithril Amulet-Master":{"Mithril Setting":1,"Mithril Chain":1,"Brilliant Coral Jewel":1},
		"Coral Mithril Earring-Master":{"Mithril Hook":1,"Mithril Setting":1,"Brilliant Coral Jewel":1},
		"Coral Mithril Ring-Master":{"Mithril Band":1,"Mithril Setting":1,"Brilliant Coral Jewel":1},
		"Coral Orb":{"Coral Tentacle":2,"Pile of Incandescent Dust":5},
		"Emerald Mithril Amulet-Master":{"Brilliant Emerald Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Emerald Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Emerald Jewel":1,"Mithril Setting":1},
		"Emerald Mithril Ring-Master":{"Mithril Band":1,"Brilliant Emerald Jewel":1,"Mithril Setting":1},
		"Emerald Orb":{"Emerald Crystal":2,"Pile of Incandescent Dust":5},
		"Opal Mithril Amulet-Master":{"Brilliant Opal Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Opal Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Opal Jewel":1,"Mithril Setting":1},
		"Opal Mithril Ring-Master":{"Mithril Band":1,"Brilliant Opal Jewel":1,"Mithril Setting":1},
		"Opal Orb":{"Opal Crystal":2,"Pile of Incandescent Dust":5},
		"Ruby Mithril Amulet-Master":{"Mithril Setting":1,"Mithril Chain":1,"Brilliant Ruby Jewel":1},
		"Ruby Mithril Earring-Master":{"Mithril Hook":1,"Mithril Setting":1,"Brilliant Ruby Jewel":1},
		"Ruby Mithril Ring-Master":{"Mithril Band":1,"Mithril Setting":1,"Brilliant Ruby Jewel":1},
		"Ruby Orb":{"Ruby Crystal":2,"Pile of Incandescent Dust":5},
		"Sapphire Mithril Amulet-Master":{"Brilliant Sapphire Jewel":1,"Mithril Setting":1,"Mithril Chain":1},
		"Sapphire Mithril Earring-Master":{"Mithril Hook":1,"Brilliant Sapphire Jewel":1,"Mithril Setting":1},
		"Sapphire Mithril Ring-Master":{"Mithril Band":1,"Brilliant Sapphire Jewel":1,"Mithril Setting":1},
		"Sapphire Orb":{"Sapphire Crystal":2,"Pile of Incandescent Dust":5}
	},
	"375":{
		"Azurite Mithril Amulet-Rare":{"Embellished Brilliant Azurite Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Azurite Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Azurite Jewel":3,"Mithril Setting":1},
		"Azurite Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Azurite Jewel":3,"Mithril Setting":1},
		"Beryl Mithril Amulet-Rare":{"Embellished Brilliant Beryl Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Beryl Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Beryl Jewel":3,"Mithril Setting":1},
		"Beryl Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Beryl Jewel":3,"Mithril Setting":1},
		"Brilliant Snowflake":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Pristine Snowflake":1},
		"Chrysocola Mithril Amulet-Rare":{"Embellished Brilliant Chrysocola Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Chrysocola Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Chrysocola Jewel":3,"Mithril Setting":1},
		"Chrysocola Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Chrysocola Jewel":3,"Mithril Setting":1},
		"Coral Mithril Amulet-Rare":{"Mithril Setting":1,"Mithril Chain":1,"Embellished Brilliant Coral Jewel":3},
		"Coral Mithril Earring-Rare":{"Mithril Hook":1,"Mithril Setting":1,"Embellished Brilliant Coral Jewel":3},
		"Coral Mithril Ring-Rare":{"Mithril Band":1,"Mithril Setting":1,"Embellished Brilliant Coral Jewel":3},
		"Embellished Brilliant Azurite Jewel":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Azurite Crystal":5},
		"Embellished Brilliant Beryl Jewel":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Beryl Crystal":5},
		"Embellished Brilliant Chrysocola Jewel":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Chrysocola Crystal":5},
		"Embellished Brilliant Coral Jewel":{"Glob of Ectoplasm":1,"Coral Tentacle":5,"Mithril Filigree":1},
		"Embellished Brilliant Emerald Jewel":{"Glob of Ectoplasm":1,"Emerald Crystal":5,"Mithril Filigree":1},
		"Embellished Brilliant Opal Jewel":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Opal Crystal":5},
		"Embellished Brilliant Ruby Jewel":{"Glob of Ectoplasm":1,"Mithril Filigree":1,"Ruby Crystal":5},
		"Embellished Brilliant Sapphire Jewel":{"Sapphire Crystal":5,"Glob of Ectoplasm":1,"Mithril Filigree":1},
		"Emerald Mithril Amulet-Rare":{"Embellished Brilliant Emerald Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Emerald Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Emerald Jewel":3,"Mithril Setting":1},
		"Emerald Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Emerald Jewel":3,"Mithril Setting":1},
		"Opal Mithril Amulet-Rare":{"Embellished Brilliant Opal Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Opal Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Opal Jewel":3,"Mithril Setting":1},
		"Opal Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Opal Jewel":3,"Mithril Setting":1},
		"Ruby Mithril Amulet-Rare":{"Mithril Setting":1,"Mithril Chain":1,"Embellished Brilliant Ruby Jewel":3},
		"Ruby Mithril Earring-Rare":{"Mithril Hook":1,"Mithril Setting":1,"Embellished Brilliant Ruby Jewel":3},
		"Ruby Mithril Ring-Rare":{"Mithril Band":1,"Mithril Setting":1,"Embellished Brilliant Ruby Jewel":3},
		"Sapphire Mithril Amulet-Rare":{"Embellished Brilliant Sapphire Jewel":3,"Mithril Setting":1,"Mithril Chain":1},
		"Sapphire Mithril Earring-Rare":{"Mithril Hook":1,"Embellished Brilliant Sapphire Jewel":3,"Mithril Setting":1},
		"Sapphire Mithril Ring-Rare":{"Mithril Band":1,"Embellished Brilliant Sapphire Jewel":3,"Mithril Setting":1},
		"Snowflake Mithril Amulet":{"Brilliant Snowflake":3,"Mithril Setting":1,"Mithril Chain":1},
		"Snowflake Mithril Earring":{"Mithril Hook":1,"Brilliant Snowflake":3,"Mithril Setting":1},
		"Snowflake Mithril Ring":{"Mithril Band":1,"Brilliant Snowflake":3,"Mithril Setting":1}
	}
}
