# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/10/2013
Last Updated: 1/21/2013
Purpose: Recipe list for Leatherworking used by Crafting.py
'''
leatherwork = {
	"0":{
		"Bolt of Jute":{"Jute Scrap":2},
		"Malign Seeker Boots-Fine":{"Rawhide Boot Upper":1,"Rawhide Boot Sole":2,"Malign Jute Insignia":1},
		"Malign Seeker Coat-Fine":{"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1,"Malign Jute Insignia":1},
		"Malign Seeker Gloves-Fine":{"Rawhide Glove Lining":1,"Rawhide Glove Strap":1,"Malign Jute Insignia":1},
		"Malign Seeker Pants-Fine":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Malign Jute Insignia":1},
		"Mighty Seeker Boots-Fine":{"Mighty Jute Insignia":1,"Rawhide Boot Upper":1,"Rawhide Boot Sole":2},
		"Mighty Seeker Coat-Fine":{"Mighty Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Mighty Seeker Gloves-Fine":{"Mighty Jute Insignia":1,"Rawhide Glove Lining":1,"Rawhide Glove Strap":1},
		"Mighty Seeker Pants-Fine":{"Mighty Jute Insignia":1,"Rawhide Legging Strap":1,"Rawhide Legging Panel":1},
		"Minor Rune of the Engineer":{"Iron Ore":1,"Destroyer Sliver":2,"Stretched Rawhide Leather Square":1},
		"Minor Rune of the Thief":{"Crystal Sliver":2,"Stretched Rawhide Leather Square":1},
		"Rawhide Boot Sole":{"Stretched Rawhide Leather Square":1},
		"Rawhide Boot Upper":{"Spool of Jute Thread":1,"Stretched Rawhide Leather Square":2},
		"Rawhide Chestguard Padding":{"Bolt of Jute":1,"Spool of Jute Thread":2},
		"Rawhide Chestguard Panel":{"Spool of Jute Thread":1,"Stretched Rawhide Leather Square":5},
		"Rawhide Glove Lining":{"Bolt of Jute":1,"Spool of Jute Thread":1},
		"Rawhide Glove Strap":{"Stretched Rawhide Leather Square":2},
		"Rawhide Legging Panel":{"Bolt of Jute":1,"Spool of Jute Thread":1,"Stretched Rawhide Leather Square":3},
		"Rawhide Legging Strap":{"Spool of Jute Thread":2,"Stretched Rawhide Leather Square":1},
		"Stretched Rawhide Leather Square":{"Rawhide Leather Section":2},
		"Vital Seeker Boots-Fine":{"Rawhide Boot Upper":1,"Vital Jute Insignia":1,"Rawhide Boot Sole":2},
		"Vital Seeker Coat-Fine":{"Rawhide Chestguard Panel":1,"Vital Jute Insignia":1,"Rawhide Chestguard Padding":1},
		"Vital Seeker Gloves-Fine":{"Rawhide Glove Lining":1,"Vital Jute Insignia":1,"Rawhide Glove Strap":1},
		"Vital Seeker Pants-Fine":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Vital Jute Insignia":1}
	},
	"10":{
		"Rune of Life":{"Bolt of Jute":1,"Stretched Rawhide Leather Square":2}
	},
	"25":{
		"Giver's Seeker Boots-Fine":{"Rawhide Boot Upper":1,"Rawhide Boot Sole":2,"Giver's Embroidered Jute Insignia":1},
		"Giver's Seeker Coat-Fine":{"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Seeker Gloves-Fine":{"Rawhide Glove Lining":1,"Rawhide Glove Strap":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Seeker Mask-Fine":{"Rawhide Mask Padding":1,"Rawhide Mask Strap":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Seeker Pants-Fine":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Giver's Embroidered Jute Insignia":1},
		"Healing Seeker Boots-Fine":{"Rawhide Boot Upper":1,"Healing Jute Insignia":1,"Rawhide Boot Sole":2},
		"Healing Seeker Coat-Fine":{"Healing Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Healing Seeker Gloves-Fine":{"Rawhide Glove Lining":1,"Healing Jute Insignia":1,"Rawhide Glove Strap":1},
		"Healing Seeker Mask-Fine":{"Healing Jute Insignia":1,"Rawhide Mask Strap":1,"Rawhide Mask Padding":1},
		"Healing Seeker Pants-Fine":{"Rawhide Legging Strap":1,"Healing Jute Insignia":1,"Rawhide Legging Panel":1},
		"Minor Rune of the Adventurer":{"Copper Doubloon":2,"Stretched Rawhide Leather Square":1},
		"Minor Rune of the Ranger":{"Onyx Sliver":2,"Tiny Fang":1,"Stretched Rawhide Leather Square":1},
		"Precise Seeker Boots-Fine":{"Rawhide Boot Upper":1,"Rawhide Boot Sole":2,"Precise Jute Insignia":1},
		"Precise Seeker Coat-Fine":{"Rawhide Chestguard Panel":1,"Precise Jute Insignia":1,"Rawhide Chestguard Padding":1},
		"Precise Seeker Gloves-Fine":{"Rawhide Glove Lining":1,"Rawhide Glove Strap":1,"Precise Jute Insignia":1},
		"Precise Seeker Mask-Fine":{"Rawhide Mask Padding":1,"Rawhide Mask Strap":1,"Precise Jute Insignia":1},
		"Precise Seeker Pants-Fine":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Precise Jute Insignia":1},
		"Rawhide Mask Padding":{"Bolt of Jute":1,"Spool of Jute Thread":1},
		"Rawhide Mask Strap":{"Bolt of Jute":1,"Stretched Rawhide Leather Square":1},
		"Resilient Seeker Boots-Fine":{"Resilient Jute Insignia":1,"Rawhide Boot Upper":1,"Rawhide Boot Sole":2},
		"Resilient Seeker Coat-Fine":{"Resilient Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Resilient Seeker Gloves-Fine":{"Resilient Jute Insignia":1,"Rawhide Glove Lining":1,"Rawhide Glove Strap":1},
		"Resilient Seeker Mask-Fine":{"Resilient Jute Insignia":1,"Rawhide Mask Padding":1,"Rawhide Mask Strap":1},
		"Resilient Seeker Pants-Fine":{"Resilient Jute Insignia":1,"Rawhide Legging Strap":1,"Rawhide Legging Panel":1}
	},
	"50":{
		"Healing Seeker Boots-Master":{"Rawhide Boot Upper":1,"Healing Embroidered Jute Insignia":1,"Rawhide Boot Sole":2},
		"Healing Seeker Coat-Master":{"Healing Embroidered Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Healing Seeker Gloves-Master":{"Rawhide Glove Lining":1,"Healing Embroidered Jute Insignia":1,"Rawhide Glove Strap":1},
		"Healing Seeker Mask-Master":{"Healing Embroidered Jute Insignia":1,"Rawhide Mask Strap":1,"Rawhide Mask Padding":1},
		"Healing Seeker Pants-Master":{"Rawhide Legging Strap":1,"Healing Embroidered Jute Insignia":1,"Rawhide Legging Panel":1},
		"Healing Seeker Shoulders-Master":{"Healing Embroidered Jute Insignia":1,"Rawhide Shoulderguard Padding":1,"Rawhide Shoulderguard Panel":1},
		"Malign Seeker Boots-Master":{"Rawhide Boot Upper":1,"Rawhide Boot Sole":2,"Malign Embroidered Jute Insignia":1},
		"Malign Seeker Coat-Master":{"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1,"Malign Embroidered Jute Insignia":1},
		"Malign Seeker Gloves-Master":{"Rawhide Glove Lining":1,"Rawhide Glove Strap":1,"Malign Embroidered Jute Insignia":1},
		"Malign Seeker Mask-Master":{"Rawhide Mask Padding":1,"Rawhide Mask Strap":1,"Malign Embroidered Jute Insignia":1},
		"Malign Seeker Pants-Master":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Malign Embroidered Jute Insignia":1},
		"Malign Seeker Shoulders-Master":{"Rawhide Shoulderguard Padding":1,"Rawhide Shoulderguard Panel":1,"Malign Embroidered Jute Insignia":1},
		"Mighty Seeker Boots-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Boot Upper":1,"Rawhide Boot Sole":2},
		"Mighty Seeker Coat-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Mighty Seeker Gloves-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Glove Lining":1,"Rawhide Glove Strap":1},
		"Mighty Seeker Mask-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Mask Padding":1,"Rawhide Mask Strap":1},
		"Mighty Seeker Pants-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Legging Strap":1,"Rawhide Legging Panel":1},
		"Mighty Seeker Shoulders-Master":{"Mighty Embroidered Jute Insignia":1,"Rawhide Shoulderguard Padding":1,"Rawhide Shoulderguard Panel":1},
		"Minor Rune of the Ogre":{"Onyx Sliver":2,"Stretched Rawhide Leather Square":1},
		"Minor Rune of the Wurm":{"Corrupted Sliver":2,"Stretched Rawhide Leather Square":1},
		"Precise Seeker Boots-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Boot Upper":1,"Rawhide Boot Sole":2},
		"Precise Seeker Coat-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Chestguard Panel":1,"Rawhide Chestguard Padding":1},
		"Precise Seeker Gloves-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Glove Lining":1,"Rawhide Glove Strap":1},
		"Precise Seeker Mask-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Mask Padding":1,"Rawhide Mask Strap":1},
		"Precise Seeker Pants-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Legging Strap":1,"Rawhide Legging Panel":1},
		"Precise Seeker Shoulders-Master":{"Precise Embroidered Jute Insignia":1,"Rawhide Shoulderguard Padding":1,"Rawhide Shoulderguard Panel":1},
		"Rawhide Shoulderguard Padding":{"Bolt of Jute":1,"Spool of Jute Thread":1},
		"Rawhide Shoulderguard Panel":{"Stretched Rawhide Leather Square":2},
		"Resilient Seeker Boots-Master":{"Rawhide Boot Upper":1,"Rawhide Boot Sole":2,"Resilient Embroidered Jute Insignia":1},
		"Resilient Seeker Coat-Master":{"Rawhide Chestguard Panel":1,"Resilient Embroidered Jute Insignia":1,"Rawhide Chestguard Padding":1},
		"Resilient Seeker Gloves-Master":{"Rawhide Glove Lining":1,"Rawhide Glove Strap":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Seeker Mask-Master":{"Rawhide Mask Padding":1,"Rawhide Mask Strap":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Seeker Pants-Master":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Seeker Shoulders-Master":{"Rawhide Shoulderguard Panel":1,"Rawhide Shoulderguard Padding":1,"Resilient Embroidered Jute Insignia":1},
		"Vital Seeker Boots-Master":{"Rawhide Boot Upper":1,"Vital Embroidered Jute Insignia":1,"Rawhide Boot Sole":2},
		"Vital Seeker Coat-Master":{"Rawhide Chestguard Panel":1,"Vital Embroidered Jute Insignia":1,"Rawhide Chestguard Padding":1},
		"Vital Seeker Gloves-Master":{"Rawhide Glove Lining":1,"Vital Embroidered Jute Insignia":1,"Rawhide Glove Strap":1},
		"Vital Seeker Mask-Master":{"Rawhide Mask Padding":1,"Rawhide Mask Strap":1,"Vital Embroidered Jute Insignia":1},
		"Vital Seeker Pants-Master":{"Rawhide Legging Strap":1,"Rawhide Legging Panel":1,"Vital Embroidered Jute Insignia":1},
		"Vital Seeker Shoulders-Master":{"Rawhide Shoulderguard Padding":1,"Vital Embroidered Jute Insignia":1,"Rawhide Shoulderguard Panel":1}
	},
	"75":{
		"Bolt of Wool":{"Wool Scrap":2},
		"Cured Thin Leather Square":{"Thin Leather Section":2},
		"Giver's Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Outlaw Coat-Fine":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Outlaw Mask-Fine":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Outlaw Pants-Fine":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Outlaw Shoulders-Fine":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Giver's Embroidered Wool Insignia":1},
		"Minor Rune of Speed":{"Charged Sliver":2,"Cured Thin Leather Square":1},
		"Minor Rune of the Ice":{"Cured Thin Leather Square":1,"Glacial Sliver":2},
		"Minor Rune of the Mad King":{"Piece of Candy Corn":75,"Onyx Fragment":2,"Iron Ingot":1,"Chattering Skull":1},
		"Pillaging Outlaw Boots-Fine":{"Thin Boot Sole":2,"Pillaging Wool Insignia":1,"Thin Boot Upper":1},
		"Pillaging Outlaw Coat-Fine":{"Pillaging Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Pillaging Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Pillaging Wool Insignia":1,"Thin Glove Lining":1},
		"Pillaging Outlaw Mask-Fine":{"Pillaging Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Pillaging Outlaw Pants-Fine":{"Pillaging Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Pillaging Outlaw Shoulders-Fine":{"Pillaging Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Ravaging Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Ravaging Wool Insignia":1},
		"Ravaging Outlaw Coat-Fine":{"Ravaging Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Ravaging Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Ravaging Wool Insignia":1,"Thin Glove Lining":1},
		"Ravaging Outlaw Mask-Fine":{"Ravaging Wool Insignia":1,"Thin Mask Strap":1,"Thin Mask Panel":1},
		"Ravaging Outlaw Pants-Fine":{"Ravaging Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Ravaging Outlaw Shoulders-Fine":{"Ravaging Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Thin Boot Sole":{"Cured Thin Leather Square":1},
		"Thin Boot Upper":{"Spool of Wool Thread":1,"Cured Thin Leather Square":2},
		"Thin Glove Lining":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Thin Glove Strap":{"Cured Thin Leather Square":2},
		"Thin Jerkin Padding":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Thin Jerkin Panel":{"Spool of Wool Thread":2,"Cured Thin Leather Square":5},
		"Thin Legging Padding":{"Spool of Wool Thread":2,"Bolt of Wool":1},
		"Thin Legging Panel":{"Spool of Wool Thread":1,"Cured Thin Leather Square":4},
		"Thin Mask Panel":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Thin Mask Strap":{"Cured Thin Leather Square":1,"Bolt of Wool":1},
		"Thin Shoulderguard Padding":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Thin Shoulderguard Panel":{"Cured Thin Leather Square":2},
		"Vigorous Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Vigorous Wool Insignia":1},
		"Vigorous Outlaw Coat-Fine":{"Thin Jerkin Panel":1,"Vigorous Wool Insignia":1,"Thin Jerkin Padding":1},
		"Vigorous Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Vigorous Wool Insignia":1,"Thin Glove Lining":1},
		"Vigorous Outlaw Mask-Fine":{"Thin Mask Panel":1,"Vigorous Wool Insignia":1,"Thin Mask Strap":1},
		"Vigorous Outlaw Pants-Fine":{"Thin Legging Panel":1,"Vigorous Wool Insignia":1,"Thin Legging Padding":1},
		"Vigorous Outlaw Shoulders-Fine":{"Thin Shoulderguard Padding":1,"Vigorous Wool Insignia":1,"Thin Shoulderguard Panel":1}
	},
	"100":{
		"Hearty Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Hearty Wool Insignia":1},
		"Hearty Outlaw Coat-Fine":{"Thin Jerkin Padding":1,"Thin Jerkin Panel":1,"Hearty Wool Insignia":1},
		"Hearty Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Hearty Wool Insignia":1},
		"Hearty Outlaw Mask-Fine":{"Thin Mask Panel":1,"Hearty Wool Insignia":1,"Thin Mask Strap":1},
		"Hearty Outlaw Pants-Fine":{"Thin Legging Panel":1,"Thin Legging Padding":1,"Hearty Wool Insignia":1},
		"Hearty Outlaw Shoulders-Fine":{"Thin Shoulderguard Panel":1,"Thin Shoulderguard Padding":1,"Hearty Wool Insignia":1},
		"Honed Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Honed Wool Insignia":1},
		"Honed Outlaw Coat-Fine":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Honed Wool Insignia":1},
		"Honed Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Honed Wool Insignia":1},
		"Honed Outlaw Mask-Fine":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Honed Wool Insignia":1},
		"Honed Outlaw Pants-Fine":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Honed Wool Insignia":1},
		"Honed Outlaw Shoulders-Fine":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Honed Wool Insignia":1},
		"Minor Rune of Altruism":{"Glacial Fragment":1,"Cured Thin Leather Square":1,"Delicate Snowflake":1},
		"Minor Rune of the Engineer-2":{"Destroyer Fragment":1,"Cured Thin Leather Square":1,"Iron Ore":1},
		"Minor Rune of the Thief-2":{"Crystal Fragment":1,"Cured Thin Leather Square":1},
		"Rejuvenating Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Outlaw Coat-Fine":{"Thin Jerkin Panel":1,"Rejuvenating Wool Insignia":1,"Thin Jerkin Padding":1},
		"Rejuvenating Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Rejuvenating Wool Insignia":1,"Thin Glove Lining":1},
		"Rejuvenating Outlaw Mask-Fine":{"Thin Mask Panel":1,"Rejuvenating Wool Insignia":1,"Thin Mask Strap":1},
		"Rejuvenating Outlaw Pants-Fine":{"Thin Legging Panel":1,"Rejuvenating Wool Insignia":1,"Thin Legging Padding":1},
		"Rejuvenating Outlaw Shoulders-Fine":{"Thin Shoulderguard Padding":1,"Rejuvenating Wool Insignia":1,"Thin Shoulderguard Panel":1},
		"Strong Outlaw Boots-Fine":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Strong Wool Insignia":1},
		"Strong Outlaw Coat-Fine":{"Thin Jerkin Padding":1,"Thin Jerkin Panel":1,"Strong Wool Insignia":1},
		"Strong Outlaw Gloves-Fine":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Strong Wool Insignia":1},
		"Strong Outlaw Mask-Fine":{"Thin Mask Panel":1,"Strong Wool Insignia":1,"Thin Mask Strap":1},
		"Strong Outlaw Pants-Fine":{"Thin Legging Panel":1,"Thin Legging Padding":1,"Strong Wool Insignia":1},
		"Strong Outlaw Shoulders-Fine":{"Thin Shoulderguard Panel":1,"Thin Shoulderguard Padding":1,"Strong Wool Insignia":1}
	},
	"125":{
		"Hearty Noble Boots-t2":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Noble Coat-t2":{"Thin Jerkin Panel":1,"Hearty Intricate Wool Insignia":1,"Thin Jerkin Padding":1},
		"Hearty Noble Gloves-t2":{"Thin Glove Strap":1,"Hearty Intricate Wool Insignia":1,"Thin Glove Lining":1},
		"Hearty Noble Mask-t2":{"Thin Mask Panel":1,"Hearty Intricate Wool Insignia":1,"Thin Mask Strap":1},
		"Hearty Noble Pants-t2":{"Thin Legging Panel":1,"Hearty Intricate Wool Insignia":1,"Thin Legging Padding":1},
		"Hearty Noble Shoulders-t2":{"Thin Shoulderguard Padding":1,"Hearty Intricate Wool Insignia":1,"Thin Shoulderguard Panel":1},
		"Hearty Outlaw Boots-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Boot Sole":2,"Thin Boot Upper":1},
		"Hearty Outlaw Coat-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Hearty Outlaw Gloves-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Glove Strap":1,"Thin Glove Lining":1},
		"Hearty Outlaw Mask-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Hearty Outlaw Pants-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Hearty Outlaw Shoulders-Master":{"Hearty Embroidered Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Honed Noble Boots-t2":{"Thin Boot Sole":2,"Honed Intricate Wool Insignia":1,"Thin Boot Upper":1},
		"Honed Noble Coat-t2":{"Honed Intricate Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Honed Noble Gloves-t2":{"Thin Glove Strap":1,"Honed Intricate Wool Insignia":1,"Thin Glove Lining":1},
		"Honed Noble Mask-t2":{"Honed Intricate Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Honed Noble Pants-t2":{"Honed Intricate Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Honed Noble Shoulders-t2":{"Honed Intricate Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Honed Outlaw Boots-Master":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Honed Embroidered Wool Insignia":1},
		"Honed Outlaw Coat-Master":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Honed Embroidered Wool Insignia":1},
		"Honed Outlaw Gloves-Master":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Honed Embroidered Wool Insignia":1},
		"Honed Outlaw Mask-Master":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Honed Embroidered Wool Insignia":1},
		"Honed Outlaw Pants-Master":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Honed Embroidered Wool Insignia":1},
		"Honed Outlaw Shoulders-Master":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Honed Embroidered Wool Insignia":1},
		"Minor Rune of the Adventurer-2":{"Cured Thin Leather Square":1,"Silver Doubloon":1},
		"Minor Rune of the Ranger-2":{"Small Fang":1,"Cured Thin Leather Square":1,"Onyx Fragment":1},
		"Pillaging Noble Boots-t2":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Pillaging Intricate Wool Insignia":1},
		"Pillaging Noble Coat-t2":{"Pillaging Intricate Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Pillaging Noble Gloves-t2":{"Thin Glove Strap":1,"Pillaging Intricate Wool Insignia":1,"Thin Glove Lining":1},
		"Pillaging Noble Mask-t2":{"Pillaging Intricate Wool Insignia":1,"Thin Mask Strap":1,"Thin Mask Panel":1},
		"Pillaging Noble Pants-t2":{"Pillaging Intricate Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Pillaging Noble Shoulders-t2":{"Pillaging Intricate Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Pillaging Outlaw Boots-Master":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Outlaw Coat-Master":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Outlaw Gloves-Master":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Outlaw Mask-Master":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Outlaw Pants-Master":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Outlaw Shoulders-Master":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Pillaging Embroidered Wool Insignia":1},
		"Ravaging Noble Boots-t2":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Noble Coat-t2":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Noble Gloves-t2":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Noble Mask-t2":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Noble Pants-t2":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Noble Shoulders-t2":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Outlaw Boots-Master":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Outlaw Coat-Master":{"Thin Jerkin Panel":1,"Thin Jerkin Padding":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Outlaw Gloves-Master":{"Thin Glove Strap":1,"Thin Glove Lining":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Outlaw Mask-Master":{"Thin Mask Panel":1,"Thin Mask Strap":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Outlaw Pants-Master":{"Thin Legging Padding":1,"Thin Legging Panel":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Outlaw Shoulders-Master":{"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1,"Ravaging Embroidered Wool Insignia":1},
		"Rejuvenating Noble Boots-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Boot Sole":2,"Thin Boot Upper":1},
		"Rejuvenating Noble Coat-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Rejuvenating Noble Gloves-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Glove Strap":1,"Thin Glove Lining":1},
		"Rejuvenating Noble Mask-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Rejuvenating Noble Pants-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Rejuvenating Noble Shoulders-t2":{"Rejuvenating Intricate Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Rejuvenating Outlaw Boots-Master":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Outlaw Coat-Master":{"Thin Jerkin Panel":1,"Rejuvenating Embroidered Wool Insignia":1,"Thin Jerkin Padding":1},
		"Rejuvenating Outlaw Gloves-Master":{"Thin Glove Strap":1,"Rejuvenating Embroidered Wool Insignia":1,"Thin Glove Lining":1},
		"Rejuvenating Outlaw Mask-Master":{"Thin Mask Panel":1,"Rejuvenating Embroidered Wool Insignia":1,"Thin Mask Strap":1},
		"Rejuvenating Outlaw Pants-Master":{"Thin Legging Panel":1,"Rejuvenating Embroidered Wool Insignia":1,"Thin Legging Padding":1},
		"Rejuvenating Outlaw Shoulders-Master":{"Thin Shoulderguard Padding":1,"Rejuvenating Embroidered Wool Insignia":1,"Thin Shoulderguard Panel":1},
		"Strong Noble Boots-t2":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Strong Intricate Wool Insignia":1},
		"Strong Noble Coat-t2":{"Thin Jerkin Panel":1,"Strong Intricate Wool Insignia":1,"Thin Jerkin Padding":1},
		"Strong Noble Gloves-t2":{"Thin Glove Strap":1,"Strong Intricate Wool Insignia":1,"Thin Glove Lining":1},
		"Strong Noble Mask-t2":{"Thin Mask Panel":1,"Strong Intricate Wool Insignia":1,"Thin Mask Strap":1},
		"Strong Noble Pants-t2":{"Thin Legging Panel":1,"Strong Intricate Wool Insignia":1,"Thin Legging Padding":1},
		"Strong Noble Shoulders-t2":{"Thin Shoulderguard Padding":1,"Strong Intricate Wool Insignia":1,"Thin Shoulderguard Panel":1},
		"Strong Outlaw Boots-Master":{"Strong Embroidered Wool Insignia":1,"Thin Boot Sole":2,"Thin Boot Upper":1},
		"Strong Outlaw Coat-Master":{"Strong Embroidered Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Strong Outlaw Gloves-Master":{"Strong Embroidered Wool Insignia":1,"Thin Glove Strap":1,"Thin Glove Lining":1},
		"Strong Outlaw Mask-Master":{"Strong Embroidered Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Strong Outlaw Pants-Master":{"Strong Embroidered Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Strong Outlaw Shoulders-Master":{"Strong Embroidered Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Vigorous Noble Boots-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Boot Sole":2,"Thin Boot Upper":1},
		"Vigorous Noble Coat-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Jerkin Panel":1,"Thin Jerkin Padding":1},
		"Vigorous Noble Gloves-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Glove Strap":1,"Thin Glove Lining":1},
		"Vigorous Noble Mask-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Mask Panel":1,"Thin Mask Strap":1},
		"Vigorous Noble Pants-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Legging Padding":1,"Thin Legging Panel":1},
		"Vigorous Noble Shoulders-t2":{"Vigorous Intricate Wool Insignia":1,"Thin Shoulderguard Padding":1,"Thin Shoulderguard Panel":1},
		"Vigorous Outlaw Boots-Master":{"Thin Boot Sole":2,"Thin Boot Upper":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Outlaw Coat-Master":{"Thin Jerkin Panel":1,"Vigorous Embroidered Wool Insignia":1,"Thin Jerkin Padding":1},
		"Vigorous Outlaw Gloves-Master":{"Thin Glove Strap":1,"Vigorous Embroidered Wool Insignia":1,"Thin Glove Lining":1},
		"Vigorous Outlaw Mask-Master":{"Thin Mask Panel":1,"Vigorous Embroidered Wool Insignia":1,"Thin Mask Strap":1},
		"Vigorous Outlaw Pants-Master":{"Thin Legging Panel":1,"Vigorous Embroidered Wool Insignia":1,"Thin Legging Padding":1},
		"Vigorous Outlaw Shoulders-Master":{"Thin Shoulderguard Padding":1,"Vigorous Embroidered Wool Insignia":1,"Thin Shoulderguard Panel":1}
	},
	"150":{
		"Bolt of Cotton":{"Cotton Scrap":2},
		"Coarse Boot Sole":{"Cured Coarse Leather Square":1},
		"Coarse Boot Upper":{"Spool of Cotton Thread":1,"Cured Coarse Leather Square":2},
		"Coarse Glove Lining":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Coarse Glove Panel":{"Cured Coarse Leather Square":2},
		"Coarse Goggle Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":2},
		"Coarse Goggle Strap":{"Cured Coarse Leather Square":1},
		"Coarse Longcoat Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Coarse Longcoat Panel":{"Spool of Cotton Thread":2,"Cured Coarse Leather Square":5},
		"Coarse Shoulderguard Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Coarse Shoulderguard Panel":{"Cured Coarse Leather Square":2},
		"Coarse Trouser Padding":{"Spool of Cotton Thread":2,"Bolt of Cotton":1},
		"Coarse Trouser Panel":{"Spool of Cotton Thread":1,"Cured Coarse Leather Square":4},
		"Cured Coarse Leather Square":{"Coarse Leather Section":2},
		"Minor Rune of the Ogre-2":{"Cured Coarse Leather Square":1,"Onyx Fragment":1},
		"Minor Rune of the Wurm-2":{"Cured Coarse Leather Square":1,"Corrupted Fragment":1},
		"Pillaging Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Pillaging Cotton Insignia":1},
		"Pillaging Leather Gloves-Fine":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Pillaging Cotton Insignia":1},
		"Pillaging Leather Mask-Fine":{"Coarse Goggle Strap":1,"Pillaging Cotton Insignia":1,"Coarse Goggle Padding":1},
		"Pillaging Leather Pants-Fine":{"Coarse Trouser Panel":1,"Pillaging Cotton Insignia":1,"Coarse Trouser Padding":1},
		"Pillaging Leather Shoes-Fine":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Pillaging Cotton Insignia":1},
		"Pillaging Outlaw Shoulders-Fine2":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Pillaging Cotton Insignia":1},
		"Ravaging Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Ravaging Cotton Insignia":1},
		"Ravaging Leather Gloves-Fine":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Ravaging Cotton Insignia":1},
		"Ravaging Leather Mask-Fine":{"Coarse Goggle Strap":1,"Coarse Goggle Padding":1,"Ravaging Cotton Insignia":1},
		"Ravaging Leather Pants-Fine":{"Coarse Trouser Panel":1,"Coarse Trouser Padding":1,"Ravaging Cotton Insignia":1},
		"Ravaging Leather Shoes-Fine":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Ravaging Cotton Insignia":1},
		"Ravaging Outlaw Shoulders-Fine2":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Ravaging Cotton Insignia":1},
		"Vigorous Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Vigorous Cotton Insignia":1},
		"Vigorous Leather Gloves-Fine":{"Coarse Glove Lining":1,"Vigorous Cotton Insignia":1,"Coarse Glove Panel":1},
		"Vigorous Leather Mask-Fine":{"Vigorous Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Vigorous Leather Pants-Fine":{"Vigorous Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Vigorous Leather Shoes-Fine":{"Coarse Boot Upper":1,"Vigorous Cotton Insignia":1,"Coarse Boot Sole":2},
		"Vigorous Outlaw Shoulders-Fine2":{"Vigorous Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1}
	},
	"175":{
		"Hearty Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Hearty Cotton Insignia":1},
		"Hearty Leather Gloves-Fine":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Hearty Cotton Insignia":1},
		"Hearty Leather Mask-Fine":{"Hearty Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Hearty Leather Pants-Fine":{"Hearty Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Hearty Leather Shoes-Fine":{"Coarse Boot Sole":2,"Coarse Boot Upper":1,"Hearty Cotton Insignia":1},
		"Hearty Outlaw Shoulders-Fine2":{"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1,"Hearty Cotton Insignia":1},
		"Honed Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Honed Cotton Insignia":1},
		"Honed Leather Gloves-Fine":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Honed Cotton Insignia":1},
		"Honed Leather Mask-Fine":{"Coarse Goggle Strap":1,"Coarse Goggle Padding":1,"Honed Cotton Insignia":1},
		"Honed Leather Pants-Fine":{"Coarse Trouser Panel":1,"Coarse Trouser Padding":1,"Honed Cotton Insignia":1},
		"Honed Leather Shoes-Fine":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Honed Cotton Insignia":1},
		"Honed Outlaw Shoulders-Fine2":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Honed Cotton Insignia":1},
		"Minor Rune of Speed-2":{"Charged Fragment":1,"Cured Coarse Leather Square":1},
		"Minor Rune of the Ice-2":{"Glacial Fragment":1,"Cured Coarse Leather Square":1},
		"Rejuvenating Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Rejuvenating Cotton Insignia":1},
		"Rejuvenating Leather Gloves-Fine":{"Coarse Glove Lining":1,"Rejuvenating Cotton Insignia":1,"Coarse Glove Panel":1},
		"Rejuvenating Leather Mask-Fine":{"Rejuvenating Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Rejuvenating Leather Pants-Fine":{"Rejuvenating Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Rejuvenating Leather Shoes-Fine":{"Coarse Boot Upper":1,"Rejuvenating Cotton Insignia":1,"Coarse Boot Sole":2},
		"Rejuvenating Outlaw Shoulders-Fine2":{"Rejuvenating Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1},
		"Strong Leather Coat-Fine":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Strong Cotton Insignia":1},
		"Strong Leather Gloves-Fine":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Strong Cotton Insignia":1},
		"Strong Leather Mask-Fine":{"Strong Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Strong Leather Pants-Fine":{"Strong Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Strong Leather Shoes-Fine":{"Coarse Boot Sole":2,"Coarse Boot Upper":1,"Strong Cotton Insignia":1},
		"Strong Outlaw Shoulders-Fine2":{"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1,"Strong Cotton Insignia":1}
	},
	"200":{
		"Giver's Leather Coat-Master":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Leather Gloves-Master":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Leather Mask-Master":{"Coarse Goggle Strap":1,"Giver's Embroidered Cotton Insignia":1,"Coarse Goggle Padding":1},
		"Giver's Leather Pants-Master":{"Coarse Trouser Panel":1,"Giver's Embroidered Cotton Insignia":1,"Coarse Trouser Padding":1},
		"Giver's Leather Shoes-Master":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Leather Shoulders-Master":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Giver's Embroidered Cotton Insignia":1},
		"Hearty Leather Coat-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1},
		"Hearty Leather Gloves-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Glove Lining":1,"Coarse Glove Panel":1},
		"Hearty Leather Mask-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Hearty Leather Pants-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Hearty Leather Shoes-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Hearty Noble Boots-t3":{"Coarse Boot Upper":1,"Hearty Intricate Cotton Insignia":1,"Coarse Boot Sole":2},
		"Hearty Noble Coat-t3":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Hearty Intricate Cotton Insignia":1},
		"Hearty Noble Gloves-t3":{"Coarse Glove Lining":1,"Hearty Intricate Cotton Insignia":1,"Coarse Glove Panel":1},
		"Hearty Noble Mask-t3":{"Hearty Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Hearty Noble Pants-t3":{"Hearty Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Hearty Noble Shoulders-t3":{"Hearty Intricate Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1},
		"Hearty Outlaw Shoulders-Master":{"Hearty Embroidered Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Honed Leather Coat-Master":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Leather Gloves-Master":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Leather Mask-Master":{"Coarse Goggle Strap":1,"Coarse Goggle Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Leather Pants-Master":{"Coarse Trouser Panel":1,"Coarse Trouser Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Leather Shoes-Master":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Honed Embroidered Cotton Insignia":1},
		"Honed Noble Boots-t3":{"Honed Intricate Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Honed Noble Coat-t3":{"Honed Intricate Cotton Insignia":1,"Coarse Longcoat Padding":1,"Coarse Longcoat Panel":1},
		"Honed Noble Gloves-t3":{"Coarse Glove Lining":1,"Honed Intricate Cotton Insignia":1,"Coarse Glove Panel":1},
		"Honed Noble Mask-t3":{"Honed Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Honed Noble Pants-t3":{"Honed Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Honed Noble Shoulders-t3":{"Honed Intricate Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Honed Outlaw Shoulders-Master":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Honed Embroidered Cotton Insignia":1},
		"Pillaging Leather Coat-Master":{"Pillaging Embroidered Cotton Insignia":1,"Coarse Longcoat Padding":1,"Coarse Longcoat Panel":1},
		"Pillaging Leather Gloves-Master":{"Coarse Glove Lining":1,"Pillaging Embroidered Cotton Insignia":1,"Coarse Glove Panel":1},
		"Pillaging Leather Mask-Master":{"Pillaging Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Pillaging Leather Pants-Master":{"Pillaging Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Pillaging Leather Shoes-Master":{"Pillaging Embroidered Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Pillaging Noble Boots-t3":{"Coarse Boot Upper":1,"Coarse Boot Sole":2,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Noble Coat-t3":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Noble Gloves-t3":{"Coarse Glove Lining":1,"Coarse Glove Panel":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Noble Mask-t3":{"Coarse Goggle Strap":1,"Coarse Goggle Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Noble Pants-t3":{"Coarse Trouser Panel":1,"Coarse Trouser Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Noble Shoulders-t3":{"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Outlaw Shoulders-Master":{"Pillaging Embroidered Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Ravaging Leather Coat-Master":{"Coarse Longcoat Panel":1,"Ravaging Embroidered Cotton Insignia":1,"Coarse Longcoat Padding":1},
		"Ravaging Leather Gloves-Master":{"Coarse Glove Lining":1,"Ravaging Embroidered Cotton Insignia":1,"Coarse Glove Panel":1},
		"Ravaging Leather Mask-Master":{"Ravaging Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Ravaging Leather Pants-Master":{"Ravaging Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Ravaging Leather Shoes-Master":{"Coarse Boot Upper":1,"Ravaging Embroidered Cotton Insignia":1,"Coarse Boot Sole":2},
		"Ravaging Noble Boots-t3":{"Ravaging Intricate Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Ravaging Noble Coat-t3":{"Ravaging Intricate Cotton Insignia":1,"Coarse Longcoat Padding":1,"Coarse Longcoat Panel":1},
		"Ravaging Noble Gloves-t3":{"Coarse Glove Lining":1,"Ravaging Intricate Cotton Insignia":1,"Coarse Glove Panel":1},
		"Ravaging Noble Mask-t3":{"Ravaging Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Ravaging Noble Pants-t3":{"Ravaging Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Ravaging Noble Shoulders-t3":{"Ravaging Intricate Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Ravaging Outlaw Shoulders-Master":{"Ravaging Embroidered Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Rejuvenating Leather Coat-Master":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Rejuvenating Embroidered Cotton Insignia":1},
		"Rejuvenating Leather Gloves-Master":{"Coarse Glove Lining":1,"Rejuvenating Embroidered Cotton Insignia":1,"Coarse Glove Panel":1},
		"Rejuvenating Leather Mask-Master":{"Rejuvenating Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Rejuvenating Leather Pants-Master":{"Rejuvenating Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Rejuvenating Leather Shoes-Master":{"Coarse Boot Upper":1,"Rejuvenating Embroidered Cotton Insignia":1,"Coarse Boot Sole":2},
		"Rejuvenating Noble Boots-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Rejuvenating Noble Coat-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1},
		"Rejuvenating Noble Gloves-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Glove Lining":1,"Coarse Glove Panel":1},
		"Rejuvenating Noble Mask-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Rejuvenating Noble Pants-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Rejuvenating Noble Shoulders-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Rejuvenating Outlaw Shoulders-Master":{"Rejuvenating Embroidered Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1},
		"Strong Leather Coat-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1},
		"Strong Leather Gloves-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Glove Lining":1,"Coarse Glove Panel":1},
		"Strong Leather Mask-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Strong Leather Pants-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Strong Leather Shoes-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Strong Noble Boots-t3":{"Coarse Boot Upper":1,"Strong Intricate Cotton Insignia":1,"Coarse Boot Sole":2},
		"Strong Noble Coat-t3":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Strong Intricate Cotton Insignia":1},
		"Strong Noble Gloves-t3":{"Coarse Glove Lining":1,"Strong Intricate Cotton Insignia":1,"Coarse Glove Panel":1},
		"Strong Noble Mask-t3":{"Strong Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Strong Noble Pants-t3":{"Strong Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Strong Noble Shoulders-t3":{"Strong Intricate Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1},
		"Strong Outlaw Shoulders-Master":{"Strong Embroidered Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Vigorous Leather Coat-Master":{"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1,"Vigorous Embroidered Cotton Insignia":1},
		"Vigorous Leather Gloves-Master":{"Coarse Glove Lining":1,"Vigorous Embroidered Cotton Insignia":1,"Coarse Glove Panel":1},
		"Vigorous Leather Mask-Master":{"Vigorous Embroidered Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Vigorous Leather Pants-Master":{"Vigorous Embroidered Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Vigorous Leather Shoes-Master":{"Coarse Boot Upper":1,"Vigorous Embroidered Cotton Insignia":1,"Coarse Boot Sole":2},
		"Vigorous Noble Boots-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Boot Upper":1,"Coarse Boot Sole":2},
		"Vigorous Noble Coat-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Longcoat Panel":1,"Coarse Longcoat Padding":1},
		"Vigorous Noble Gloves-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Glove Lining":1,"Coarse Glove Panel":1},
		"Vigorous Noble Mask-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Goggle Strap":1,"Coarse Goggle Padding":1},
		"Vigorous Noble Pants-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Trouser Panel":1,"Coarse Trouser Padding":1},
		"Vigorous Noble Shoulders-t3":{"Vigorous Intricate Cotton Insignia":1,"Coarse Shoulderguard Padding":1,"Coarse Shoulderguard Panel":1},
		"Vigorous Outlaw Shoulders-Master":{"Vigorous Embroidered Cotton Insignia":1,"Coarse Shoulderguard Panel":1,"Coarse Shoulderguard Padding":1},
		"Major Rune of the Engineer":{"Iron Ore":1,"Cured Coarse Leather Square":1,"Destroyer Shard":2},
		"Major Rune of the Thief":{"Crystal Shard":2,"Cured Coarse Leather Square":1}
	},
	"225":{
		"Bolt of Linen":{"Linen Scrap":2},
		"Carrion Rascal Boots-Fine":{"Carrion Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Carrion Rascal Coat-Fine":{"Carrion Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Carrion Rascal Gloves-Fine":{"Carrion Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Carrion Rascal Mask-Fine":{"Carrion Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Carrion Rascal Pants-Fine":{"Carrion Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Carrion Rascal Shoulders-Fine":{"Carrion Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Cured Rugged Leather Square":{"Rugged Leather Section":2},
		"Knight's Rascal Boots-Fine":{"Rugged Boot Upper":1,"Knight's Linen Insignia":1,"Rugged Boot Sole":2},
		"Knight's Rascal Coat-Fine":{"Rugged Longcoat Padding":1,"Knight's Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Knight's Rascal Gloves-Fine":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Knight's Linen Insignia":1},
		"Knight's Rascal Mask-Fine":{"Rugged Goggle Strap":1,"Knight's Linen Insignia":1,"Rugged Goggle Padding":1},
		"Knight's Rascal Pants-Fine":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Knight's Linen Insignia":1},
		"Knight's Rascal Shoulders-Fine":{"Knight's Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Major Rune of the Ranger":{"Sharp Fang":1,"Onyx Shard":2,"Cured Rugged Leather Square":1},
		"Rugged Boot Sole":{"Cured Rugged Leather Square":1},
		"Rugged Boot Upper":{"Spool of Linen Thread":1,"Cured Rugged Leather Square":2},
		"Rugged Glove Lining":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Rugged Glove Panel":{"Cured Rugged Leather Square":2},
		"Rugged Goggle Padding":{"Spool of Linen Thread":1,"Bolt of Linen":2},
		"Rugged Goggle Strap":{"Cured Rugged Leather Square":1},
		"Rugged Longcoat Padding":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Rugged Longcoat Panel":{"Spool of Linen Thread":2,"Cured Rugged Leather Square":5},
		"Rugged Shoulderguard Padding":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Rugged Shoulderguard Panel":{"Cured Rugged Leather Square":2},
		"Rugged Trouser Padding":{"Spool of Linen Thread":2,"Bolt of Linen":1},
		"Rugged Trouser Panel":{"Spool of Linen Thread":1,"Cured Rugged Leather Square":4},
		"Valkyrie Rascal Boots-Fine":{"Rugged Boot Upper":1,"Rugged Boot Sole":2,"Valkyrie Linen Insignia":1},
		"Valkyrie Rascal Coat-Fine":{"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Rascal Gloves-Fine":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Rascal Mask-Fine":{"Rugged Goggle Strap":1,"Rugged Goggle Padding":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Rascal Pants-Fine":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Rascal Shoulders-Fine":{"Rugged Shoulderguard Padding":1,"Rugged Shoulderguard Panel":1,"Valkyrie Linen Insignia":1}
	},
	"250":{
		"Berserker's Rascal Boots-Fine":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Berserker's Linen Insignia":1},
		"Berserker's Rascal Coat-Fine":{"Rugged Longcoat Padding":1,"Berserker's Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Berserker's Rascal Gloves-Fine":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Berserker's Linen Insignia":1},
		"Berserker's Rascal Mask-Fine":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Berserker's Linen Insignia":1},
		"Berserker's Rascal Pants-Fine":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Berserker's Linen Insignia":1},
		"Berserker's Rascal Shoulders-Fine":{"Rugged Shoulderguard Panel":1,"Berserker's Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Cleric's Rascal Boots-Fine":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Cleric's Linen Insignia":1},
		"Cleric's Rascal Coat-Fine":{"Rugged Longcoat Padding":1,"Cleric's Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Cleric's Rascal Gloves-Fine":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Cleric's Linen Insignia":1},
		"Cleric's Rascal Mask-Fine":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Cleric's Linen Insignia":1},
		"Cleric's Rascal Pants-Fine":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Cleric's Linen Insignia":1},
		"Cleric's Rascal Shoulders-Fine":{"Rugged Shoulderguard Panel":1,"Cleric's Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Explorer's Rascal Boots-Fine":{"Rugged Boot Upper":1,"Explorer's Linen Insignia":1,"Rugged Boot Sole":2},
		"Explorer's Rascal Coat-Fine":{"Rugged Longcoat Padding":1,"Explorer's Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Explorer's Rascal Gloves-Fine":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Explorer's Linen Insignia":1},
		"Explorer's Rascal Mask-Fine":{"Rugged Goggle Strap":1,"Explorer's Linen Insignia":1,"Rugged Goggle Padding":1},
		"Explorer's Rascal Pants-Fine":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Explorer's Linen Insignia":1},
		"Explorer's Rascal Shoulders-Fine":{"Explorer's Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Major Rune of the Ogre":{"Onyx Shard":2,"Cured Rugged Leather Square":1},
		"Major Rune of the Wurm":{"Corrupted Shard":2,"Cured Rugged Leather Square":1},
		"Rampager's Rascal Boots-Fine":{"Rampager's Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Rampager's Rascal Coat-Fine":{"Rampager's Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Rampager's Rascal Gloves-Fine":{"Rampager's Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Rampager's Rascal Mask-Fine":{"Rampager's Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Rampager's Rascal Pants-Fine":{"Rampager's Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Rampager's Rascal Shoulders-Fine":{"Rampager's Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1}
	},
	"275":{
		"Major Rune of Speed":{"Cured Rugged Leather Square":1,"Charged Shard":2},
		"Major Rune of the Ice":{"Glacial Shard":2,"Cured Rugged Leather Square":1},
		"Berserker's Noble Boots-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Berserker's Noble Coat-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Berserker's Noble Gloves-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Berserker's Noble Mask-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Berserker's Noble Pants-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Berserker's Noble Shoulders-t4":{"Berserker's Intricate Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Berserker's Rascal Boots-Master":{"Berserker's Embroidered Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Berserker's Rascal Coat-Master":{"Berserker's Embroidered Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Berserker's Rascal Gloves-Master":{"Berserker's Embroidered Linen Insignia":1,"Rugged Glove Lining":1,"Rugged Glove Panel":1},
		"Berserker's Rascal Mask-Master":{"Berserker's Embroidered Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Berserker's Rascal Pants-Master":{"Rugged Trouser Panel":1,"Berserker's Embroidered Linen Insignia":1,"Rugged Trouser Padding":1},
		"Berserker's Rascal Shoulders-Master":{"Berserker's Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Carrion Noble Boots-t4":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Noble Coat-t4":{"Rugged Longcoat Padding":1,"Carrion Intricate Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Carrion Noble Gloves-t4":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Noble Mask-t4":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Noble Pants-t4":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Noble Shoulders-t4":{"Rugged Shoulderguard Panel":1,"Carrion Intricate Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Carrion Rascal Boots-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Carrion Rascal Coat-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Carrion Rascal Gloves-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Carrion Rascal Mask-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Carrion Rascal Pants-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Carrion Rascal Shoulders-Master":{"Carrion Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Cleric's Noble Boots-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Cleric's Noble Coat-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Cleric's Noble Gloves-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Cleric's Noble Mask-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Cleric's Noble Pants-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Cleric's Noble Shoulders-t4":{"Cleric's Intricate Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Cleric's Rascal Boots-Master":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Rascal Coat-Master":{"Rugged Longcoat Padding":1,"Cleric's Embroidered Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Cleric's Rascal Gloves-Master":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Rascal Mask-Master":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Rascal Pants-Master":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Rascal Shoulders-Master":{"Rugged Shoulderguard Panel":1,"Cleric's Embroidered Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Explorer's Noble Boots-t4":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Noble Coat-t4":{"Rugged Longcoat Padding":1,"Explorer's Intricate Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Explorer's Noble Gloves-t4":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Noble Mask-t4":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Noble Pants-t4":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Noble Shoulders-t4":{"Rugged Shoulderguard Panel":1,"Explorer's Intricate Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Explorer's Rascal Boots-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Explorer's Rascal Coat-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Explorer's Rascal Gloves-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Explorer's Rascal Mask-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Explorer's Rascal Pants-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Explorer's Rascal Shoulders-Master":{"Explorer's Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Giver's Noble Boots-t4":{"Rugged Boot Sole":2,"Rugged Boot Upper":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Noble Coat-t4":{"Rugged Longcoat Padding":1,"Giver's Embroidered Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Giver's Noble Gloves-t4":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Noble Mask-t4":{"Rugged Goggle Padding":1,"Rugged Goggle Strap":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Noble Pants-t4":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Noble Shoulders-t4":{"Rugged Shoulderguard Panel":1,"Giver's Embroidered Linen Insignia":1,"Rugged Shoulderguard Padding":1},
		"Knight's Noble Boots-t4":{"Knight's Intricate Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Knight's Noble Coat-t4":{"Knight's Intricate Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Knight's Noble Gloves-t4":{"Knight's Intricate Linen Insignia":1,"Rugged Glove Lining":1,"Rugged Glove Panel":1},
		"Knight's Noble Mask-t4":{"Knight's Intricate Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Knight's Noble Pants-t4":{"Rugged Trouser Panel":1,"Knight's Intricate Linen Insignia":1,"Rugged Trouser Padding":1},
		"Knight's Noble Shoulders-t4":{"Knight's Intricate Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Knight's Rascal Boots-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Knight's Rascal Coat-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Knight's Rascal Gloves-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Glove Panel":1,"Rugged Glove Lining":1},
		"Knight's Rascal Mask-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Knight's Rascal Pants-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Trouser Panel":1,"Rugged Trouser Padding":1},
		"Knight's Rascal Shoulders-Master":{"Knight's Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Rampager's Noble Boots-t4":{"Rampager's Intricate Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Rampager's Noble Coat-t4":{"Rampager's Intricate Linen Insignia":1,"Rugged Longcoat Padding":1,"Rugged Longcoat Panel":1},
		"Rampager's Noble Gloves-t4":{"Rampager's Intricate Linen Insignia":1,"Rugged Glove Lining":1,"Rugged Glove Panel":1},
		"Rampager's Noble Mask-t4":{"Rampager's Intricate Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Rampager's Noble Pants-t4":{"Rugged Trouser Panel":1,"Rampager's Intricate Linen Insignia":1,"Rugged Trouser Padding":1},
		"Rampager's Noble Shoulders-t4":{"Rampager's Intricate Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Rampager's Rascal Boots-Master":{"Rugged Boot Upper":1,"Rampager's Embroidered Linen Insignia":1,"Rugged Boot Sole":2},
		"Rampager's Rascal Coat-Master":{"Rugged Longcoat Padding":1,"Rampager's Embroidered Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Rampager's Rascal Gloves-Master":{"Rugged Glove Panel":1,"Rugged Glove Lining":1,"Rampager's Embroidered Linen Insignia":1},
		"Rampager's Rascal Mask-Master":{"Rugged Goggle Strap":1,"Rampager's Embroidered Linen Insignia":1,"Rugged Goggle Padding":1},
		"Rampager's Rascal Pants-Master":{"Rugged Trouser Panel":1,"Rugged Trouser Padding":1,"Rampager's Embroidered Linen Insignia":1},
		"Rampager's Rascal Shoulders-Master":{"Rampager's Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Valkyrie Noble Boots-t4":{"Valkyrie Intricate Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Valkyrie Noble Coat-t4":{"Rugged Longcoat Padding":1,"Valkyrie Intricate Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Valkyrie Noble Gloves-t4":{"Rugged Glove Lining":1,"Valkyrie Intricate Linen Insignia":1,"Rugged Glove Panel":1},
		"Valkyrie Noble Mask-t4":{"Rugged Goggle Strap":1,"Valkyrie Intricate Linen Insignia":1,"Rugged Goggle Padding":1},
		"Valkyrie Noble Pants-t4":{"Rugged Trouser Panel":1,"Valkyrie Intricate Linen Insignia":1,"Rugged Trouser Padding":1},
		"Valkyrie Noble Shoulders-t4":{"Valkyrie Intricate Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1},
		"Valkyrie Rascal Boots-Master":{"Valkyrie Embroidered Linen Insignia":1,"Rugged Boot Upper":1,"Rugged Boot Sole":2},
		"Valkyrie Rascal Coat-Master":{"Rugged Longcoat Padding":1,"Valkyrie Embroidered Linen Insignia":1,"Rugged Longcoat Panel":1},
		"Valkyrie Rascal Gloves-Master":{"Rugged Glove Panel":1,"Valkyrie Embroidered Linen Insignia":1,"Rugged Glove Lining":1},
		"Valkyrie Rascal Mask-Master":{"Valkyrie Embroidered Linen Insignia":1,"Rugged Goggle Strap":1,"Rugged Goggle Padding":1},
		"Valkyrie Rascal Pants-Master":{"Rugged Trouser Panel":1,"Valkyrie Embroidered Linen Insignia":1,"Rugged Trouser Padding":1},
		"Valkyrie Rascal Shoulders-Master":{"Valkyrie Embroidered Linen Insignia":1,"Rugged Shoulderguard Panel":1,"Rugged Shoulderguard Padding":1}
	},
	"300":{
		"Bolt of Silk":{"Silk Scrap":2},
		"Carrion Prowler Boots-Fine":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Carrion Silk Insignia":1},
		"Carrion Prowler Coat-Fine":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Carrion Silk Insignia":1},
		"Carrion Prowler Gloves-Fine":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Carrion Silk Insignia":1},
		"Carrion Prowler Mask-Fine":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Carrion Silk Insignia":1},
		"Carrion Prowler Pants-Fine":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Carrion Silk Insignia":1},
		"Carrion Prowler Shoulders-Fine":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Carrion Silk Insignia":1},
		"Cured Thick Leather Square":{"Thick Leather Section":2},
		"Knight's Prowler Boots-Fine":{"Thick Boot Upper":1,"Knight's Silk Insignia":1,"Thick Boot Sole":2},
		"Knight's Prowler Coat-Fine":{"Knight's Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Knight's Prowler Gloves-Fine":{"Knight's Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Knight's Prowler Mask-Fine":{"Knight's Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Knight's Prowler Pants-Fine":{"Thick Trouser Padding":1,"Knight's Silk Insignia":1,"Thick Trouser Panel":1},
		"Knight's Prowler Shoulders-Fine":{"Knight's Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Major Rune of Altruism":{"Cured Thick Leather Square":1,"Pristine Snowflake":1,"Glacial Core":1},
		"Major Rune of the Engineer-2":{"Destroyer Core":1,"Cured Thick Leather Square":1,"Iron Ore":1},
		"Major Rune of the Thief-2":{"Crystal Core":1,"Cured Thick Leather Square":1},
		"Thick Boot Sole":{"Cured Thick Leather Square":1},
		"Thick Boot Upper":{"Spool of Silk Thread":1,"Cured Thick Leather Square":2},
		"Thick Glove Lining":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Thick Glove Panel":{"Cured Thick Leather Square":2},
		"Thick Longcoat Padding":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Thick Longcoat Panel":{"Spool of Silk Thread":2,"Cured Thick Leather Square":5},
		"Thick Mask Padding":{"Spool of Silk Thread":1,"Bolt of Silk":2},
		"Thick Mask Strap":{"Cured Thick Leather Square":1},
		"Thick Shoulderguard Padding":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Thick Shoulderguard Panel":{"Cured Thick Leather Square":2},
		"Thick Trouser Padding":{"Spool of Silk Thread":2,"Bolt of Silk":1},
		"Thick Trouser Panel":{"Spool of Silk Thread":1,"Cured Thick Leather Square":4},
		"Valkyrie Prowler Boots-Fine":{"Valkyrie Silk Insignia":1,"Thick Boot Upper":1,"Thick Boot Sole":2},
		"Valkyrie Prowler Coat-Fine":{"Valkyrie Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Valkyrie Prowler Gloves-Fine":{"Valkyrie Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Valkyrie Prowler Mask-Fine":{"Valkyrie Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Valkyrie Prowler Pants-Fine":{"Valkyrie Silk Insignia":1,"Thick Trouser Padding":1,"Thick Trouser Panel":1},
		"Valkyrie Prowler Shoulders-Fine":{"Valkyrie Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1}
	},
	"325":{
		"Berserker's Prowler Boots-Fine":{"Berserker's Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Berserker's Prowler Coat-Fine":{"Berserker's Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Berserker's Prowler Gloves-Fine":{"Berserker's Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Berserker's Prowler Mask-Fine":{"Berserker's Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Berserker's Prowler Pants-Fine":{"Thick Trouser Padding":1,"Berserker's Silk Insignia":1,"Thick Trouser Panel":1},
		"Berserker's Prowler Shoulders-Fine":{"Berserker's Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Cleric's Prowler Boots-Fine":{"Cleric's Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Cleric's Prowler Coat-Fine":{"Cleric's Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Cleric's Prowler Gloves-Fine":{"Cleric's Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Cleric's Prowler Mask-Fine":{"Cleric's Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Cleric's Prowler Pants-Fine":{"Thick Trouser Padding":1,"Cleric's Silk Insignia":1,"Thick Trouser Panel":1},
		"Cleric's Prowler Shoulders-Fine":{"Cleric's Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Explorer's Prowler Boots-Fine":{"Thick Boot Upper":1,"Explorer's Silk Insignia":1,"Thick Boot Sole":2},
		"Explorer's Prowler Coat-Fine":{"Explorer's Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Explorer's Prowler Gloves-Fine":{"Explorer's Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Explorer's Prowler Mask-Fine":{"Explorer's Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Explorer's Prowler Pants-Fine":{"Thick Trouser Padding":1,"Explorer's Silk Insignia":1,"Thick Trouser Panel":1},
		"Explorer's Prowler Shoulders-Fine":{"Explorer's Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Major Rune of the Adventurer":{"Cured Thick Leather Square":1,"Gold Doubloon":1},
		"Major Rune of the Ranger-2":{"Onyx Core":1,"Large Fang":1,"Cured Thick Leather Square":1},
		"Rampager's Prowler Boots-Fine":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Rampager's Silk Insignia":1},
		"Rampager's Prowler Coat-Fine":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Rampager's Silk Insignia":1},
		"Rampager's Prowler Gloves-Fine":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Rampager's Silk Insignia":1},
		"Rampager's Prowler Mask-Fine":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Rampager's Silk Insignia":1},
		"Rampager's Prowler Pants-Fine":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Rampager's Silk Insignia":1},
		"Rampager's Prowler Shoulders-Fine":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Rampager's Silk Insignia":1}
	},
	"350":{
		"Berserker's Prowler Boots-Master":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Prowler Coat-Master":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Prowler Gloves-Master":{"Thick Glove Lining":1,"Thick Glove Panel":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Prowler Mask-Master":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Prowler Pants-Master":{"Thick Trouser Padding":1,"Berserker's Embroidered Silk Insignia":1,"Thick Trouser Panel":1},
		"Berserker's Prowler Shoulders-Master":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Berserker's Embroidered Silk Insignia":1},
		"Carrion Prowler Boots-Master":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Carrion Embroidered Silk Insignia":1},
		"Carrion Prowler Coat-Master":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Prowler Gloves-Master":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Prowler Mask-Master":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Prowler Pants-Master":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Prowler Shoulders-Master":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Carrion Embroidered Silk Insignia":1},
		"Cleric's Prowler Boots-Master":{"Cleric's Embroidered Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Cleric's Prowler Coat-Master":{"Cleric's Embroidered Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Cleric's Prowler Gloves-Master":{"Cleric's Embroidered Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Cleric's Prowler Mask-Master":{"Cleric's Embroidered Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Cleric's Prowler Pants-Master":{"Thick Trouser Padding":1,"Cleric's Embroidered Silk Insignia":1,"Thick Trouser Panel":1},
		"Cleric's Prowler Shoulders-Master":{"Cleric's Embroidered Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Explorer's Prowler Boots-Master":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Prowler Coat-Master":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Prowler Gloves-Master":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Prowler Mask-Master":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Prowler Pants-Master":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Prowler Shoulders-Master":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Explorer's Embroidered Silk Insignia":1},
		"Knight's Prowler Boots-Master":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Knight's Embroidered Silk Insignia":1},
		"Knight's Prowler Coat-Master":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Prowler Gloves-Master":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Prowler Mask-Master":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Prowler Pants-Master":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Prowler Shoulders-Master":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Knight's Embroidered Silk Insignia":1},
		"Major Rune of the Ogre-2":{"Onyx Core":1,"Cured Thick Leather Square":1},
		"Major Rune of the Wurm-2":{"Corrupted Core":1,"Cured Thick Leather Square":1},
		"Rampager's Prowler Boots-Master":{"Thick Boot Upper":1,"Rampager's Embroidered Silk Insignia":1,"Thick Boot Sole":2},
		"Rampager's Prowler Coat-Master":{"Rampager's Embroidered Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Rampager's Prowler Gloves-Master":{"Rampager's Embroidered Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Rampager's Prowler Mask-Master":{"Rampager's Embroidered Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Rampager's Prowler Pants-Master":{"Thick Trouser Padding":1,"Rampager's Embroidered Silk Insignia":1,"Thick Trouser Panel":1},
		"Rampager's Prowler Shoulders-Master":{"Rampager's Embroidered Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Valkyrie Prowler Boots-Master":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Prowler Coat-Master":{"Thick Longcoat Panel":1,"Thick Longcoat Padding":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Prowler Gloves-Master":{"Thick Glove Panel":1,"Valkyrie Embroidered Silk Insignia":1,"Thick Glove Lining":1},
		"Valkyrie Prowler Mask-Master":{"Thick Mask Padding":1,"Thick Mask Strap":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Prowler Pants-Master":{"Thick Trouser Padding":1,"Valkyrie Embroidered Silk Insignia":1,"Thick Trouser Panel":1},
		"Valkyrie Prowler Shoulders-Master":{"Thick Shoulderguard Padding":1,"Thick Shoulderguard Panel":1,"Valkyrie Embroidered Silk Insignia":1}
	},
	"375":{
		"Apothecary's Noble Boots-t5":{"Thick Boot Upper":1,"Apothecary's Intricate Silk Insignia":1,"Thick Boot Sole":2},
		"Apothecary's Noble Coat-t5":{"Apothecary's Intricate Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Apothecary's Noble Gloves-t5":{"Apothecary's Intricate Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Apothecary's Noble Mask-t5":{"Apothecary's Intricate Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Apothecary's Noble Pants-t5":{"Thick Trouser Padding":1,"Apothecary's Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Apothecary's Noble Shoulders-t5":{"Apothecary's Intricate Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Berserker's Noble Boots-t5":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Noble Coat-t5":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Noble Gloves-t5":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Noble Mask-t5":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Noble Pants-t5":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Noble Shoulders-t5":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Berserker's Intricate Silk Insignia":1},
		"Carrion Noble Boots-t5":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Carrion Intricate Silk Insignia":1},
		"Carrion Noble Coat-t5":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Noble Gloves-t5":{"Thick Glove Lining":1,"Thick Glove Panel":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Noble Mask-t5":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Noble Pants-t5":{"Thick Trouser Padding":1,"Carrion Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Carrion Noble Shoulders-t5":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Carrion Intricate Silk Insignia":1},
		"Cleric's Noble Boots-t5":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Noble Coat-t5":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Noble Gloves-t5":{"Thick Glove Panel":1,"Thick Glove Lining":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Noble Mask-t5":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Noble Pants-t5":{"Thick Trouser Padding":1,"Thick Trouser Panel":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Noble Shoulders-t5":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Cleric's Intricate Silk Insignia":1},
		"Explorer's Noble Boots-t5":{"Explorer's Intricate Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Explorer's Noble Coat-t5":{"Explorer's Intricate Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Explorer's Noble Gloves-t5":{"Explorer's Intricate Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Explorer's Noble Mask-t5":{"Explorer's Intricate Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Explorer's Noble Pants-t5":{"Thick Trouser Padding":1,"Explorer's Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Explorer's Noble Shoulders-t5":{"Explorer's Intricate Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Giver's Noble Boots-t5":{"Giver's Embroidered Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Giver's Noble Coat-t5":{"Giver's Embroidered Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Giver's Noble Gloves-t5":{"Giver's Embroidered Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Giver's Noble Mask-t5":{"Giver's Embroidered Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Giver's Noble Pants-t5":{"Thick Trouser Padding":1,"Giver's Embroidered Silk Insignia":1,"Thick Trouser Panel":1},
		"Giver's Noble Shoulders-t5":{"Giver's Embroidered Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Knight's Noble Boots-t5":{"Knight's Intricate Silk Insignia":1,"Thick Boot Sole":2,"Thick Boot Upper":1},
		"Knight's Noble Coat-t5":{"Knight's Intricate Silk Insignia":1,"Thick Longcoat Padding":1,"Thick Longcoat Panel":1},
		"Knight's Noble Gloves-t5":{"Knight's Intricate Silk Insignia":1,"Thick Glove Panel":1,"Thick Glove Lining":1},
		"Knight's Noble Mask-t5":{"Knight's Intricate Silk Insignia":1,"Thick Mask Strap":1,"Thick Mask Padding":1},
		"Knight's Noble Pants-t5":{"Thick Trouser Padding":1,"Knight's Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Knight's Noble Shoulders-t5":{"Knight's Intricate Silk Insignia":1,"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1},
		"Major Rune of Speed-2":{"Charged Core":1,"Cured Thick Leather Square":1},
		"Major Rune of the Ice-2":{"Cured Thick Leather Square":1,"Glacial Core":1},
		"Rampager's Noble Boots-t5":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Noble Coat-t5":{"Thick Longcoat Padding":1,"Thick Longcoat Panel":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Noble Gloves-t5":{"Thick Glove Lining":1,"Thick Glove Panel":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Noble Mask-t5":{"Thick Mask Strap":1,"Thick Mask Padding":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Noble Pants-t5":{"Thick Trouser Padding":1,"Rampager's Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Rampager's Noble Shoulders-t5":{"Thick Shoulderguard Panel":1,"Thick Shoulderguard Padding":1,"Rampager's Intricate Silk Insignia":1},
		"Valkyrie Noble Boots-t5":{"Thick Boot Upper":1,"Thick Boot Sole":2,"Valkyrie Intricate Silk Insignia":1},
		"Valkyrie Noble Coat-t5":{"Valkyrie Intricate Silk Insignia":1,"Thick Longcoat Panel":1,"Thick Longcoat Padding":1},
		"Valkyrie Noble Gloves-t5":{"Thick Glove Panel":1,"Valkyrie Intricate Silk Insignia":1,"Thick Glove Lining":1},
		"Valkyrie Noble Mask-t5":{"Thick Mask Strap":1,"Valkyrie Intricate Silk Insignia":1,"Thick Mask Padding":1},
		"Valkyrie Noble Pants-t5":{"Thick Trouser Padding":1,"Valkyrie Intricate Silk Insignia":1,"Thick Trouser Panel":1},
		"Valkyrie Noble Shoulders-t5":{"Thick Shoulderguard Padding":1,"Valkyrie Intricate Silk Insignia":1,"Thick Shoulderguard Panel":1}
	},
}
