# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/11/2013
Last Updated: 1/21/2013
Purpose: Recipe list for Tailoring used by Crafting.py
'''
tailor = {
	"0":{
		"Bolt of Jute":{"Jute Scrap":2},
		"Jute Breeches Lining":{"Bolt of Jute":1},
		"Jute Breeches Panel":{"Bolt of Jute":4,"Spool of Jute Thread":3},
		"Jute Sandal Sole":{"Stretched Rawhide Leather Square":1},
		"Jute Sandal Upper":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Jute Tunic Lining":{"Bolt of Jute":1},
		"Jute Tunic Panel":{"Bolt of Jute":4,"Stretched Rawhide Leather Square":1,"Spool of Jute Thread":3},
		"Jute Wristguard Padding":{"Bolt of Jute":1,"Spool of Jute Thread":1},
		"Jute Wristguard Strap":{"Bolt of Jute":1,"Stretched Rawhide Leather Square":1},
		"Malign Embroidered Coat-Fine":{"Jute Tunic Panel":1,"Jute Tunic Lining":1,"Malign Jute Insignia":1},
		"Malign Embroidered Pants-Fine":{"Jute Breeches Lining":1,"Jute Breeches Panel":1,"Malign Jute Insignia":1},
		"Malign Embroidered Sandals-Fine":{"Jute Sandal Sole":2,"Jute Sandal Upper":1,"Malign Jute Insignia":1},
		"Malign Embroidered Wristguards-Fine":{"Jute Wristguard Strap":1,"Jute Wristguard Padding":1,"Malign Jute Insignia":1},
		"Mighty Embroidered Coat-Fine":{"Mighty Jute Insignia":1,"Jute Tunic Panel":1,"Jute Tunic Lining":1},
		"Mighty Embroidered Pants-Fine":{"Mighty Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Mighty Embroidered Sandals-Fine":{"Mighty Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Mighty Embroidered Wristguards-Fine":{"Mighty Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1},
		"Minor Rune of the Elementalist":{"Bolt of Jute":1,"Destroyer Sliver":2},
		"Minor Rune of the Mesmer":{"Crystal Sliver":2,"Bolt of Jute":1},
		"Stretched Rawhide Leather Square":{"Rawhide Leather Section":2},
		"Vital Embroidered Coat-Fine":{"Jute Tunic Panel":1,"Vital Jute Insignia":1,"Jute Tunic Lining":1},
		"Vital Embroidered Pants-Fine":{"Jute Breeches Lining":1,"Vital Jute Insignia":1,"Jute Breeches Panel":1},
		"Vital Embroidered Sandals-Fine":{"Vital Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Vital Embroidered Wristguards-Fine":{"Jute Wristguard Strap":1,"Vital Jute Insignia":1,"Jute Wristguard Padding":1}
	},
	"10":{
		"Rune of Life":{"Bolt of Jute":2,"Stretched Rawhide Leather Square":1}
	},
	"25":{
		"Giver's Embroidered Coat-Fine":{"Jute Tunic Panel":1,"Jute Tunic Lining":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Embroidered Mask-Fine":{"Jute Headpiece Strap":1,"Jute Headpiece Padding":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Embroidered Pants-Fine":{"Jute Breeches Lining":1,"Jute Breeches Panel":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Embroidered Sandals-Fine":{"Jute Sandal Sole":2,"Jute Sandal Upper":1,"Giver's Embroidered Jute Insignia":1},
		"Giver's Embroidered Wristguards-Fine":{"Jute Wristguard Strap":1,"Jute Wristguard Padding":1,"Giver's Embroidered Jute Insignia":1},
		"Healing Embroidered Coat-Fine":{"Healing Jute Insignia":1,"Jute Tunic Lining":1,"Jute Tunic Panel":1},
		"Healing Embroidered Mask-Fine":{"Jute Headpiece Strap":1,"Healing Jute Insignia":1,"Jute Headpiece Padding":1},
		"Healing Embroidered Pants-Fine":{"Healing Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Healing Embroidered Sandals-Fine":{"Healing Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Healing Embroidered Wristguards-Fine":{"Healing Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1},
		"Jute Headpiece Padding":{"Bolt of Jute":1,"Spool of Jute Thread":1},
		"Jute Headpiece Strap":{"Bolt of Jute":1,"Stretched Rawhide Leather Square":1},
		"Minor Rune of the Necromancer":{"Bolt of Jute":1,"Pile of Soiled Essence":2,"Tiny Venom Sac":1},
		"Minor Rune of the Scholar":{"Bolt of Jute":1,"Charged Sliver":2,"Tiny Totem":1},
		"Precise Embroidered Coat-Fine":{"Jute Tunic Panel":1,"Jute Tunic Lining":1,"Precise Jute Insignia":1},
		"Precise Embroidered Mask-Fine":{"Jute Headpiece Strap":1,"Jute Headpiece Padding":1,"Precise Jute Insignia":1},
		"Precise Embroidered Pants-Fine":{"Jute Breeches Panel":1,"Jute Breeches Lining":1,"Precise Jute Insignia":1},
		"Precise Embroidered Sandals-Fine":{"Precise Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Precise Embroidered Wristguards-Fine":{"Jute Wristguard Strap":1,"Precise Jute Insignia":1,"Jute Wristguard Padding":1},
		"Resilient Embroidered Coat-Fine":{"Resilient Jute Insignia":1,"Jute Tunic Panel":1,"Jute Tunic Lining":1},
		"Resilient Embroidered Mask-Fine":{"Resilient Jute Insignia":1,"Jute Headpiece Strap":1,"Jute Headpiece Padding":1},
		"Resilient Embroidered Pants-Fine":{"Resilient Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Resilient Embroidered Sandals-Fine":{"Resilient Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Resilient Embroidered Wristguards-Fine":{"Resilient Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1}
	},
	"50":{
		"Healing Embroidered Coat-Master":{"Healing Embroidered Jute Insignia":1,"Jute Tunic Lining":1,"Jute Tunic Panel":1},
		"Healing Embroidered Mantle-Master":{"Healing Embroidered Jute Insignia":1,"Jute Epaulet Padding":1,"Jute Epaulet Panel":1},
		"Healing Embroidered Mask-Master":{"Jute Headpiece Strap":1,"Healing Embroidered Jute Insignia":1,"Jute Headpiece Padding":1},
		"Healing Embroidered Pants-Master":{"Healing Embroidered Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Healing Embroidered Sandals-Master":{"Healing Embroidered Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Healing Embroidered Wristguards-Master":{"Healing Embroidered Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1},
		"Jute Epaulet Padding":{"Bolt of Jute":2,"Spool of Jute Thread":1},
		"Jute Epaulet Panel":{"Spool of Jute Thread":1,"Stretched Rawhide Leather Square":1},
		"Malign Embroidered Coat-Master":{"Jute Tunic Panel":1,"Jute Tunic Lining":1,"Malign Embroidered Jute Insignia":1},
		"Malign Embroidered Mantle-Master":{"Jute Epaulet Padding":1,"Jute Epaulet Panel":1,"Malign Embroidered Jute Insignia":1},
		"Malign Embroidered Mask-Master":{"Jute Headpiece Strap":1,"Jute Headpiece Padding":1,"Malign Embroidered Jute Insignia":1},
		"Malign Embroidered Pants-Master":{"Jute Breeches Lining":1,"Jute Breeches Panel":1,"Malign Embroidered Jute Insignia":1},
		"Malign Embroidered Sandals-Master":{"Jute Sandal Sole":2,"Jute Sandal Upper":1,"Malign Embroidered Jute Insignia":1},
		"Malign Embroidered Wristguards-Master":{"Jute Wristguard Strap":1,"Jute Wristguard Padding":1,"Malign Embroidered Jute Insignia":1},
		"Mighty Embroidered Coat-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Tunic Panel":1,"Jute Tunic Lining":1},
		"Mighty Embroidered Mantle-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Epaulet Padding":1,"Jute Epaulet Panel":1},
		"Mighty Embroidered Mask-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Headpiece Strap":1,"Jute Headpiece Padding":1},
		"Mighty Embroidered Pants-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Mighty Embroidered Sandals-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Mighty Embroidered Wristguards-Master":{"Mighty Embroidered Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1},
		"Minor Rune of the Pirate":{"Bolt of Jute":1,"Silver Doubloon":2},
		"Minor Rune of the Undead":{"Bolt of Jute":1,"Pile of Soiled Essence":2},
		"Precise Embroidered Coat-Master":{"Precise Embroidered Jute Insignia":1,"Jute Tunic Panel":1,"Jute Tunic Lining":1},
		"Precise Embroidered Mantle-Master":{"Precise Embroidered Jute Insignia":1,"Jute Epaulet Padding":1,"Jute Epaulet Panel":1},
		"Precise Embroidered Mask-Master":{"Precise Embroidered Jute Insignia":1,"Jute Headpiece Strap":1,"Jute Headpiece Padding":1},
		"Precise Embroidered Pants-Master":{"Precise Embroidered Jute Insignia":1,"Jute Breeches Lining":1,"Jute Breeches Panel":1},
		"Precise Embroidered Sandals-Master":{"Precise Embroidered Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Precise Embroidered Wristguards-Master":{"Precise Embroidered Jute Insignia":1,"Jute Wristguard Strap":1,"Jute Wristguard Padding":1},
		"Resilient Embroidered Coat-Master":{"Jute Tunic Panel":1,"Jute Tunic Lining":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Embroidered Mantle-Master":{"Jute Epaulet Padding":1,"Resilient Embroidered Jute Insignia":1,"Jute Epaulet Panel":1},
		"Resilient Embroidered Mask-Master":{"Jute Headpiece Strap":1,"Jute Headpiece Padding":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Embroidered Pants-Master":{"Jute Breeches Panel":1,"Jute Breeches Lining":1,"Resilient Embroidered Jute Insignia":1},
		"Resilient Embroidered Sandals-Master":{"Resilient Embroidered Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Resilient Embroidered Wristguards-Master":{"Jute Wristguard Strap":1,"Resilient Embroidered Jute Insignia":1,"Jute Wristguard Padding":1},
		"Vital Embroidered Coat-Master":{"Jute Tunic Panel":1,"Vital Embroidered Jute Insignia":1,"Jute Tunic Lining":1},
		"Vital Embroidered Mantle-Master":{"Jute Epaulet Padding":1,"Vital Embroidered Jute Insignia":1,"Jute Epaulet Panel":1},
		"Vital Embroidered Mask-Master":{"Jute Headpiece Strap":1,"Vital Embroidered Jute Insignia":1,"Jute Headpiece Padding":1},
		"Vital Embroidered Pants-Master":{"Jute Breeches Lining":1,"Vital Embroidered Jute Insignia":1,"Jute Breeches Panel":1},
		"Vital Embroidered Sandals-Master":{"Vital Embroidered Jute Insignia":1,"Jute Sandal Sole":2,"Jute Sandal Upper":1},
		"Vital Embroidered Wristguards-Master":{"Jute Wristguard Strap":1,"Vital Embroidered Jute Insignia":1,"Jute Wristguard Padding":1}
	},
	"75":{
		"Bolt of Wool":{"Wool Scrap":2},
		"Cured Thin Leather Square":{"Thin Leather Section":2},
		"Giver's Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Student Mantle-Fine":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Student Pants-Fine":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Giver's Embroidered Wool Insignia":1},
		"Giver's Student Shoes-Fine":{"Wool Footwear Sole":2,"Wool Footwear Upper":1,"Giver's Embroidered Wool Insignia":1},
		"Minor Rune of the Air":{"Charged Sliver":2,"Bolt of Wool":1},
		"Minor Rune of the Mad King":{"Nougat Center":1,"Onyx Fragment":2,"Iron Ingot":1,"Piece of Candy Corn":75},
		"Minor Rune of the Water":{"Bolt of Wool":1,"Glacial Sliver":2},
		"Pillaging Student Circlet-Fine":{"Pillaging Wool Insignia":1,"Wool Headpiece Padding":1,"Wool Headpiece Strap":1},
		"Pillaging Student Coat-Fine":{"Wool Vestments Panel":1,"Pillaging Wool Insignia":1,"Wool Vestments Lining":1},
		"Pillaging Student Gloves-Fine":{"Wool Gloves Panel":1,"Pillaging Wool Insignia":1,"Wool Gloves Padding":1},
		"Pillaging Student Mantle-Fine":{"Pillaging Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Pillaging Student Pants-Fine":{"Pillaging Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Pillaging Student Shoes-Fine":{"Pillaging Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Ravaging Student Circlet-Fine":{"Wool Headpiece Strap":1,"Ravaging Wool Insignia":1,"Wool Headpiece Padding":1},
		"Ravaging Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Ravaging Wool Insignia":1},
		"Ravaging Student Gloves-Fine":{"Wool Gloves Panel":1,"Ravaging Wool Insignia":1,"Wool Gloves Padding":1},
		"Ravaging Student Mantle-Fine":{"Ravaging Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Ravaging Student Pants-Fine":{"Wool Trouser Lining":1,"Ravaging Wool Insignia":1,"Wool Trouser Panel":1},
		"Ravaging Student Shoes-Fine":{"Ravaging Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Vigorous Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Vigorous Wool Insignia":1},
		"Vigorous Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Vigorous Wool Insignia":1},
		"Vigorous Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Vigorous Wool Insignia":1},
		"Vigorous Student Mantle-Fine":{"Wool Epaulet Padding":1,"Vigorous Wool Insignia":1,"Wool Epaulet Panel":1},
		"Vigorous Student Pants-Fine":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Vigorous Wool Insignia":1},
		"Vigorous Student Shoes-Fine":{"Vigorous Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Wool Epaulet Padding":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Wool Epaulet Panel":{"Cured Thin Leather Square":1},
		"Wool Footwear Sole":{"Cured Thin Leather Square":1},
		"Wool Footwear Upper":{"Spool of Wool Thread":1,"Bolt of Wool":2},
		"Wool Gloves Padding":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Wool Gloves Panel":{"Cured Thin Leather Square":1,"Bolt of Wool":1},
		"Wool Headpiece Padding":{"Spool of Wool Thread":1,"Bolt of Wool":1},
		"Wool Headpiece Strap":{"Cured Thin Leather Square":1,"Bolt of Wool":1},
		"Wool Trouser Lining":{"Bolt of Wool":1},
		"Wool Trouser Panel":{"Spool of Wool Thread":3,"Bolt of Wool":4},
		"Wool Vestments Lining":{"Bolt of Wool":1},
		"Wool Vestments Panel":{"Cured Thin Leather Square":1,"Spool of Wool Thread":3,"Bolt of Wool":4}
	},
	"100":{
		"Hearty Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Hearty Wool Insignia":1},
		"Hearty Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Hearty Wool Insignia":1},
		"Hearty Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Hearty Wool Insignia":1},
		"Hearty Student Mantle-Fine":{"Wool Epaulet Padding":1,"Wool Epaulet Panel":1,"Hearty Wool Insignia":1},
		"Hearty Student Pants-Fine":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Hearty Wool Insignia":1},
		"Hearty Student Shoes-Fine":{"Wool Footwear Upper":1,"Hearty Wool Insignia":1,"Wool Footwear Sole":2},
		"Honed Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Honed Wool Insignia":1},
		"Honed Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Honed Wool Insignia":1},
		"Honed Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Honed Wool Insignia":1},
		"Honed Student Mantle-Fine":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Honed Wool Insignia":1},
		"Honed Student Pants-Fine":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Honed Wool Insignia":1},
		"Honed Student Shoes-Fine":{"Wool Footwear Upper":1,"Wool Footwear Sole":2,"Honed Wool Insignia":1},
		"Minor Rune of Altruism":{"Glacial Fragment":1,"Bolt of Wool":1,"Delicate Snowflake":1},
		"Minor Rune of the Elementalist-2":{"Destroyer Fragment":1,"Bolt of Wool":1},
		"Minor Rune of the Mesmer-2":{"Crystal Fragment":1,"Bolt of Wool":1},
		"Rejuvenating Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Student Mantle-Fine":{"Wool Epaulet Padding":1,"Rejuvenating Wool Insignia":1,"Wool Epaulet Panel":1},
		"Rejuvenating Student Pants-Fine":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Rejuvenating Wool Insignia":1},
		"Rejuvenating Student Shoes-Fine":{"Rejuvenating Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Strong Student Circlet-Fine":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Strong Wool Insignia":1},
		"Strong Student Coat-Fine":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Strong Wool Insignia":1},
		"Strong Student Gloves-Fine":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Strong Wool Insignia":1},
		"Strong Student Mantle-Fine":{"Wool Epaulet Padding":1,"Wool Epaulet Panel":1,"Strong Wool Insignia":1},
		"Strong Student Pants-Fine":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Strong Wool Insignia":1},
		"Strong Student Shoes-Fine":{"Wool Footwear Upper":1,"Strong Wool Insignia":1,"Wool Footwear Sole":2}
	},
	"125":{
		"Hearty Masquerade Boots-t2":{"Hearty Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Hearty Masquerade Gloves-t2":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Masquerade Leggings-t2":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Masquerade Mantle-t2":{"Wool Epaulet Padding":1,"Hearty Intricate Wool Insignia":1,"Wool Epaulet Panel":1},
		"Hearty Masquerade Mask-t2":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Masquerade Raiments-t2":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Hearty Intricate Wool Insignia":1},
		"Hearty Student Circlet-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Headpiece Strap":1,"Wool Headpiece Padding":1},
		"Hearty Student Coat-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Vestments Panel":1,"Wool Vestments Lining":1},
		"Hearty Student Gloves-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Gloves Panel":1,"Wool Gloves Padding":1},
		"Hearty Student Mantle-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Hearty Student Pants-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Hearty Student Shoes-Master":{"Hearty Embroidered Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Honed Masquerade Boots-t2":{"Honed Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Honed Masquerade Gloves-t2":{"Wool Gloves Panel":1,"Honed Intricate Wool Insignia":1,"Wool Gloves Padding":1},
		"Honed Masquerade Leggings-t2":{"Honed Intricate Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Honed Masquerade Mantle-t2":{"Honed Intricate Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Honed Masquerade Mask-t2":{"Honed Intricate Wool Insignia":1,"Wool Headpiece Padding":1,"Wool Headpiece Strap":1},
		"Honed Masquerade Raiments-t2":{"Wool Vestments Panel":1,"Honed Intricate Wool Insignia":1,"Wool Vestments Lining":1},
		"Honed Student Circlet-Master":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Honed Embroidered Wool Insignia":1},
		"Honed Student Coat-Master":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Honed Embroidered Wool Insignia":1},
		"Honed Student Gloves-Master":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Honed Embroidered Wool Insignia":1},
		"Honed Student Mantle-Master":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Honed Embroidered Wool Insignia":1},
		"Honed Student Pants-Master":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Honed Embroidered Wool Insignia":1},
		"Honed Student Shoes-Master":{"Wool Footwear Upper":1,"Wool Footwear Sole":2,"Honed Embroidered Wool Insignia":1},
		"Minor Rune of the Necromancer-2":{"Pile of Foul Essence":1,"Bolt of Wool":1,"Small Venom Sac":1},
		"Minor Rune of the Scholar-2":{"Charged Fragment":1,"Small Totem":1,"Bolt of Wool":1},
		"Pillaging Masquerade Boots-t2":{"Pillaging Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Pillaging Masquerade Gloves-t2":{"Wool Gloves Panel":1,"Pillaging Intricate Wool Insignia":1,"Wool Gloves Padding":1},
		"Pillaging Masquerade Leggings-t2":{"Wool Trouser Lining":1,"Pillaging Intricate Wool Insignia":1,"Wool Trouser Panel":1},
		"Pillaging Masquerade Mantle-t2":{"Pillaging Intricate Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Pillaging Masquerade Mask-t2":{"Wool Headpiece Strap":1,"Pillaging Intricate Wool Insignia":1,"Wool Headpiece Padding":1},
		"Pillaging Masquerade Raiments-t2":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Pillaging Intricate Wool Insignia":1},
		"Pillaging Student Circlet-Master":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Student Coat-Master":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Student Gloves-Master":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Student Mantle-Master":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Student Pants-Master":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Pillaging Embroidered Wool Insignia":1},
		"Pillaging Student Shoes-Master":{"Wool Footwear Sole":2,"Wool Footwear Upper":1,"Pillaging Embroidered Wool Insignia":1},
		"Ravaging Masquerade Boots-t2":{"Wool Footwear Sole":2,"Wool Footwear Upper":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Masquerade Gloves-t2":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Masquerade Leggings-t2":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Masquerade Mantle-t2":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Masquerade Mask-t2":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Masquerade Raiments-t2":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Ravaging Intricate Wool Insignia":1},
		"Ravaging Student Circlet-Master":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Student Coat-Master":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Student Gloves-Master":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Student Mantle-Master":{"Wool Epaulet Panel":1,"Wool Epaulet Padding":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Student Pants-Master":{"Wool Trouser Lining":1,"Wool Trouser Panel":1,"Ravaging Embroidered Wool Insignia":1},
		"Ravaging Student Shoes-Master":{"Wool Footwear Upper":1,"Wool Footwear Sole":2,"Ravaging Embroidered Wool Insignia":1},
		"Rejuvenating Masquerade Boots-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Rejuvenating Masquerade Gloves-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Gloves Panel":1,"Wool Gloves Padding":1},
		"Rejuvenating Masquerade Leggings-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Rejuvenating Masquerade Mantle-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Rejuvenating Masquerade Mask-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Headpiece Strap":1,"Wool Headpiece Padding":1},
		"Rejuvenating Masquerade Raiments-t2":{"Rejuvenating Intricate Wool Insignia":1,"Wool Vestments Panel":1,"Wool Vestments Lining":1},
		"Rejuvenating Student Circlet-Master":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Student Coat-Master":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Student Gloves-Master":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Student Mantle-Master":{"Wool Epaulet Padding":1,"Rejuvenating Embroidered Wool Insignia":1,"Wool Epaulet Panel":1},
		"Rejuvenating Student Pants-Master":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Rejuvenating Embroidered Wool Insignia":1},
		"Rejuvenating Student Shoes-Master":{"Rejuvenating Embroidered Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Strong Masquerade Boots-t2":{"Strong Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Strong Masquerade Gloves-t2":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Strong Intricate Wool Insignia":1},
		"Strong Masquerade Leggings-t2":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Strong Intricate Wool Insignia":1},
		"Strong Masquerade Mantle-t2":{"Wool Epaulet Padding":1,"Strong Intricate Wool Insignia":1,"Wool Epaulet Panel":1},
		"Strong Masquerade Mask-t2":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Strong Intricate Wool Insignia":1},
		"Strong Masquerade Raiments-t2":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Strong Intricate Wool Insignia":1},
		"Strong Student Circlet-Master":{"Strong Embroidered Wool Insignia":1,"Wool Headpiece Strap":1,"Wool Headpiece Padding":1},
		"Strong Student Coat-Master":{"Strong Embroidered Wool Insignia":1,"Wool Vestments Panel":1,"Wool Vestments Lining":1},
		"Strong Student Gloves-Master":{"Strong Embroidered Wool Insignia":1,"Wool Gloves Panel":1,"Wool Gloves Padding":1},
		"Strong Student Mantle-Master":{"Strong Embroidered Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Strong Student Pants-Master":{"Strong Embroidered Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Strong Student Shoes-Master":{"Strong Embroidered Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Vigorous Masquerade Boots-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2},
		"Vigorous Masquerade Gloves-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Gloves Panel":1,"Wool Gloves Padding":1},
		"Vigorous Masquerade Leggings-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Trouser Lining":1,"Wool Trouser Panel":1},
		"Vigorous Masquerade Mantle-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Epaulet Panel":1,"Wool Epaulet Padding":1},
		"Vigorous Masquerade Mask-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Headpiece Strap":1,"Wool Headpiece Padding":1},
		"Vigorous Masquerade Raiments-t2":{"Vigorous Intricate Wool Insignia":1,"Wool Vestments Panel":1,"Wool Vestments Lining":1},
		"Vigorous Student Circlet-Master":{"Wool Headpiece Strap":1,"Wool Headpiece Padding":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Student Coat-Master":{"Wool Vestments Panel":1,"Wool Vestments Lining":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Student Gloves-Master":{"Wool Gloves Panel":1,"Wool Gloves Padding":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Student Mantle-Master":{"Wool Epaulet Padding":1,"Vigorous Embroidered Wool Insignia":1,"Wool Epaulet Panel":1},
		"Vigorous Student Pants-Master":{"Wool Trouser Panel":1,"Wool Trouser Lining":1,"Vigorous Embroidered Wool Insignia":1},
		"Vigorous Student Shoes-Master":{"Vigorous Embroidered Wool Insignia":1,"Wool Footwear Upper":1,"Wool Footwear Sole":2}
	},
	"150":{
		"Bolt of Cotton":{"Cotton Scrap":2},
		"Cotton Coat Lining":{"Bolt of Cotton":1},
		"Cotton Coat Panel":{"Spool of Cotton Thread":3,"Bolt of Cotton":4,"Cured Coarse Leather Square":1},
		"Cotton Epaulet Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":2},
		"Cotton Epaulet Panel":{"Cured Coarse Leather Square":1},
		"Cotton Gloves Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Cotton Gloves Panel":{"Bolt of Cotton":1,"Cured Coarse Leather Square":1},
		"Cotton Helm Padding":{"Spool of Cotton Thread":1,"Bolt of Cotton":1},
		"Cotton Helm Strap":{"Bolt of Cotton":1,"Cured Coarse Leather Square":1},
		"Cotton Pants Lining":{"Bolt of Cotton":1},
		"Cotton Pants Panel":{"Spool of Cotton Thread":3,"Bolt of Cotton":4},
		"Cotton Shoe Sole":{"Cured Coarse Leather Square":1},
		"Cotton Shoe Upper":{"Spool of Cotton Thread":1,"Bolt of Cotton":2},
		"Cured Coarse Leather Square":{"Coarse Leather Section":2},
		"Minor Rune of the Pirate-2":{"Bolt of Wool":1,"Silver Doubloon":1},
		"Minor Rune of the Undead-2":{"Pile of Foul Essence":1,"Bolt of Cotton":1},
		"Pillaging Acolyte Boots-Fine":{"Cotton Shoe Sole":2,"Cotton Shoe Upper":1,"Pillaging Cotton Insignia":1},
		"Pillaging Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Pillaging Cotton Insignia":1},
		"Pillaging Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Pillaging Cotton Insignia":1},
		"Pillaging Acolyte Mantle-Fine":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Pillaging Cotton Insignia":1},
		"Pillaging Acolyte Mask-Fine":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Pillaging Cotton Insignia":1},
		"Pillaging Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Pillaging Cotton Insignia":1},
		"Ravaging Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Cotton Shoe Sole":2,"Ravaging Cotton Insignia":1},
		"Ravaging Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Ravaging Cotton Insignia":1},
		"Ravaging Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Ravaging Cotton Insignia":1},
		"Ravaging Acolyte Mantle-Fine":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Ravaging Cotton Insignia":1},
		"Ravaging Acolyte Mask-Fine":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Ravaging Cotton Insignia":1},
		"Ravaging Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Ravaging Cotton Insignia":1},
		"Vigorous Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Vigorous Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Vigorous Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Vigorous Cotton Insignia":1,"Cotton Coat Lining":1},
		"Vigorous Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Vigorous Cotton Insignia":1},
		"Vigorous Acolyte Mantle-Fine":{"Cotton Epaulet Padding":1,"Vigorous Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Vigorous Acolyte Mask-Fine":{"Vigorous Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Vigorous Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Vigorous Cotton Insignia":1,"Cotton Pants Panel":1}
	},
	"175":{
		"Hearty Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Hearty Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Hearty Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Hearty Cotton Insignia":1},
		"Hearty Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Hearty Cotton Insignia":1},
		"Hearty Acolyte Mantle-Fine":{"Cotton Epaulet Padding":1,"Cotton Epaulet Panel":1,"Hearty Cotton Insignia":1},
		"Hearty Acolyte Mask-Fine":{"Cotton Helm Strap":1,"Cotton Helm Padding":1,"Hearty Cotton Insignia":1},
		"Hearty Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Hearty Cotton Insignia":1},
		"Honed Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Cotton Shoe Sole":2,"Honed Cotton Insignia":1},
		"Honed Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Honed Cotton Insignia":1},
		"Honed Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Honed Cotton Insignia":1},
		"Honed Acolyte Mantle-Fine":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Honed Cotton Insignia":1},
		"Honed Acolyte Mask-Fine":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Honed Cotton Insignia":1},
		"Honed Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Honed Cotton Insignia":1},
		"Minor Rune of the Air-2":{"Charged Fragment":1,"Bolt of Cotton":1},
		"Minor Rune of the Water-2":{"Glacial Fragment":1,"Bolt of Cotton":1},
		"Rejuvenating Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Rejuvenating Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Rejuvenating Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Rejuvenating Cotton Insignia":1,"Cotton Coat Lining":1},
		"Rejuvenating Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Rejuvenating Cotton Insignia":1},
		"Rejuvenating Acolyte Mantle-Fine":{"Cotton Epaulet Padding":1,"Rejuvenating Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Rejuvenating Acolyte Mask-Fine":{"Rejuvenating Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Rejuvenating Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Rejuvenating Cotton Insignia":1,"Cotton Pants Panel":1},
		"Strong Acolyte Boots-Fine":{"Cotton Shoe Upper":1,"Strong Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Strong Acolyte Coat-Fine":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Strong Cotton Insignia":1},
		"Strong Acolyte Gloves-Fine":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Strong Cotton Insignia":1},
		"Strong Acolyte Mantle-Fine":{"Cotton Epaulet Padding":1,"Cotton Epaulet Panel":1,"Strong Cotton Insignia":1},
		"Strong Acolyte Mask-Fine":{"Cotton Helm Strap":1,"Cotton Helm Padding":1,"Strong Cotton Insignia":1},
		"Strong Acolyte Pants-Fine":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Strong Cotton Insignia":1}
	},
	"200":{
		"Major Rune of the Elementalist":{"Bolt of Cotton":1,"Destroyer Shard":2},
		"Major Rune of the Mesmer":{"Crystal Shard":2,"Bolt of Cotton":1},
		"Giver's Acolyte Boots-Master":{"Cotton Shoe Sole":2,"Cotton Shoe Upper":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Acolyte Coat-Master":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Acolyte Mantle-Master":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Acolyte Mask-Master":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Giver's Embroidered Cotton Insignia":1},
		"Giver's Acolyte Pants-Master":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Giver's Embroidered Cotton Insignia":1},
		"Hearty Acolyte Boots-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Hearty Acolyte Coat-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Hearty Acolyte Gloves-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Gloves Panel":1,"Cotton Gloves Padding":1},
		"Hearty Acolyte Mantle-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Hearty Acolyte Mask-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Hearty Acolyte Pants-Master":{"Hearty Embroidered Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Hearty Masquerade Boots-t3":{"Cotton Shoe Upper":1,"Hearty Intricate Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Hearty Masquerade Gloves-t3":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Hearty Intricate Cotton Insignia":1},
		"Hearty Masquerade Leggings-t3":{"Cotton Pants Lining":1,"Hearty Intricate Cotton Insignia":1,"Cotton Pants Panel":1},
		"Hearty Masquerade Mantle-t3":{"Cotton Epaulet Padding":1,"Hearty Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Hearty Masquerade Mask-t3":{"Hearty Intricate Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Hearty Masquerade Raiments-t3":{"Cotton Coat Panel":1,"Hearty Intricate Cotton Insignia":1,"Cotton Coat Lining":1},
		"Honed Acolyte Boots-Master":{"Cotton Shoe Upper":1,"Cotton Shoe Sole":2,"Honed Embroidered Cotton Insignia":1},
		"Honed Acolyte Coat-Master":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Acolyte Mantle-Master":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Acolyte Mask-Master":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Acolyte Pants-Master":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Honed Embroidered Cotton Insignia":1},
		"Honed Masquerade Boots-t3":{"Honed Intricate Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Honed Masquerade Gloves-t3":{"Cotton Gloves Panel":1,"Honed Intricate Cotton Insignia":1,"Cotton Gloves Padding":1},
		"Honed Masquerade Leggings-t3":{"Honed Intricate Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Honed Masquerade Mantle-t3":{"Honed Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Honed Masquerade Mask-t3":{"Honed Intricate Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Honed Masquerade Raiments-t3":{"Honed Intricate Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Pillaging Acolyte Boots-Master":{"Pillaging Embroidered Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Pillaging Acolyte Coat-Master":{"Pillaging Embroidered Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Pillaging Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Pillaging Embroidered Cotton Insignia":1,"Cotton Gloves Padding":1},
		"Pillaging Acolyte Mantle-Master":{"Pillaging Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Pillaging Acolyte Mask-Master":{"Pillaging Embroidered Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Pillaging Acolyte Pants-Master":{"Pillaging Embroidered Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Pillaging Masquerade Boots-t3":{"Cotton Shoe Upper":1,"Cotton Shoe Sole":2,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Masquerade Gloves-t3":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Masquerade Leggings-t3":{"Cotton Pants Lining":1,"Cotton Pants Panel":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Masquerade Mantle-t3":{"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Masquerade Mask-t3":{"Cotton Helm Padding":1,"Cotton Helm Strap":1,"Pillaging Intricate Cotton Insignia":1},
		"Pillaging Masquerade Raiments-t3":{"Cotton Coat Panel":1,"Cotton Coat Lining":1,"Pillaging Intricate Cotton Insignia":1},
		"Ravaging Acolyte Boots-Master":{"Ravaging Embroidered Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Ravaging Acolyte Coat-Master":{"Cotton Coat Panel":1,"Ravaging Embroidered Cotton Insignia":1,"Cotton Coat Lining":1},
		"Ravaging Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Ravaging Embroidered Cotton Insignia":1,"Cotton Gloves Padding":1},
		"Ravaging Acolyte Mantle-Master":{"Ravaging Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Ravaging Acolyte Mask-Master":{"Ravaging Embroidered Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Ravaging Acolyte Pants-Master":{"Cotton Pants Lining":1,"Ravaging Embroidered Cotton Insignia":1,"Cotton Pants Panel":1},
		"Ravaging Masquerade Boots-t3":{"Ravaging Intricate Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Ravaging Masquerade Gloves-t3":{"Cotton Gloves Panel":1,"Ravaging Intricate Cotton Insignia":1,"Cotton Gloves Padding":1},
		"Ravaging Masquerade Leggings-t3":{"Ravaging Intricate Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Ravaging Masquerade Mantle-t3":{"Ravaging Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Ravaging Masquerade Mask-t3":{"Ravaging Intricate Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Ravaging Masquerade Raiments-t3":{"Ravaging Intricate Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Rejuvenating Acolyte Boots-Master":{"Cotton Shoe Upper":1,"Rejuvenating Embroidered Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Rejuvenating Acolyte Coat-Master":{"Cotton Coat Panel":1,"Rejuvenating Embroidered Cotton Insignia":1,"Cotton Coat Lining":1},
		"Rejuvenating Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Rejuvenating Embroidered Cotton Insignia":1},
		"Rejuvenating Acolyte Mantle-Master":{"Cotton Epaulet Padding":1,"Rejuvenating Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Rejuvenating Acolyte Mask-Master":{"Rejuvenating Embroidered Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Rejuvenating Acolyte Pants-Master":{"Cotton Pants Lining":1,"Rejuvenating Embroidered Cotton Insignia":1,"Cotton Pants Panel":1},
		"Rejuvenating Masquerade Boots-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Rejuvenating Masquerade Gloves-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Gloves Panel":1,"Cotton Gloves Padding":1},
		"Rejuvenating Masquerade Leggings-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Rejuvenating Masquerade Mantle-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Rejuvenating Masquerade Mask-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Rejuvenating Masquerade Raiments-t3":{"Rejuvenating Intricate Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Strong Acolyte Boots-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Strong Acolyte Coat-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
		"Strong Acolyte Gloves-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Gloves Panel":1,"Cotton Gloves Padding":1},
		"Strong Acolyte Mantle-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Strong Acolyte Mask-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Strong Acolyte Pants-Master":{"Strong Embroidered Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Strong Masquerade Boots-t3":{"Cotton Shoe Upper":1,"Strong Intricate Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Strong Masquerade Gloves-t3":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Strong Intricate Cotton Insignia":1},
		"Strong Masquerade Leggings-t3":{"Cotton Pants Lining":1,"Strong Intricate Cotton Insignia":1,"Cotton Pants Panel":1},
		"Strong Masquerade Mantle-t3":{"Cotton Epaulet Padding":1,"Strong Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Strong Masquerade Mask-t3":{"Strong Intricate Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Strong Masquerade Raiments-t3":{"Cotton Coat Panel":1,"Strong Intricate Cotton Insignia":1,"Cotton Coat Lining":1},
		"Vigorous Acolyte Boots-Master":{"Cotton Shoe Upper":1,"Vigorous Embroidered Cotton Insignia":1,"Cotton Shoe Sole":2},
		"Vigorous Acolyte Coat-Master":{"Cotton Coat Panel":1,"Vigorous Embroidered Cotton Insignia":1,"Cotton Coat Lining":1},
		"Vigorous Acolyte Gloves-Master":{"Cotton Gloves Panel":1,"Cotton Gloves Padding":1,"Vigorous Embroidered Cotton Insignia":1},
		"Vigorous Acolyte Mantle-Master":{"Cotton Epaulet Padding":1,"Vigorous Embroidered Cotton Insignia":1,"Cotton Epaulet Panel":1},
		"Vigorous Acolyte Mask-Master":{"Vigorous Embroidered Cotton Insignia":1,"Cotton Helm Strap":1,"Cotton Helm Padding":1},
		"Vigorous Acolyte Pants-Master":{"Cotton Pants Lining":1,"Vigorous Embroidered Cotton Insignia":1,"Cotton Pants Panel":1},
		"Vigorous Masquerade Boots-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Shoe Upper":1,"Cotton Shoe Sole":2},
		"Vigorous Masquerade Gloves-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Gloves Panel":1,"Cotton Gloves Padding":1},
		"Vigorous Masquerade Leggings-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Pants Lining":1,"Cotton Pants Panel":1},
		"Vigorous Masquerade Mantle-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Epaulet Panel":1,"Cotton Epaulet Padding":1},
		"Vigorous Masquerade Mask-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Helm Padding":1,"Cotton Helm Strap":1},
		"Vigorous Masquerade Raiments-t3":{"Vigorous Intricate Cotton Insignia":1,"Cotton Coat Panel":1,"Cotton Coat Lining":1},
	},
	"225":{
		"Bolt of Linen":{"Linen Scrap":2},
		"Carrion Winged Boots-Fine":{"Carrion Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Carrion Winged Gloves-Fine":{"Carrion Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Carrion Winged Headpiece-Fine":{"Carrion Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Carrion Winged Mantle-Fine":{"Carrion Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Carrion Winged Pants-Fine":{"Carrion Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Carrion Winged Tunic-Fine":{"Carrion Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Cured Rugged Leather Square":{"Rugged Leather Section":2},
		"Knight's Winged Boots-Fine":{"Linen Shoe Sole":2,"Knight's Linen Insignia":1,"Linen Shoe Upper":1},
		"Knight's Winged Gloves-Fine":{"Linen Gloves Padding":1,"Knight's Linen Insignia":1,"Linen Gloves Panel":1},
		"Knight's Winged Headpiece-Fine":{"Linen Helm Strap":1,"Knight's Linen Insignia":1,"Linen Helm Padding":1},
		"Knight's Winged Mantle-Fine":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Knight's Linen Insignia":1},
		"Knight's Winged Pants-Fine":{"Linen Pants Lining":1,"Knight's Linen Insignia":1,"Linen Pants Panel":1},
		"Knight's Winged Tunic-Fine":{"Linen Coat Panel":1,"Knight's Linen Insignia":1,"Linen Coat Lining":1},
		"Linen Coat Lining":{"Bolt of Linen":1},
		"Linen Coat Panel":{"Spool of Linen Thread":3,"Cured Rugged Leather Square":1,"Bolt of Linen":4},
		"Linen Epaulet Padding":{"Spool of Linen Thread":1,"Bolt of Linen":2},
		"Linen Epaulet Panel":{"Cured Rugged Leather Square":1},
		"Linen Gloves Padding":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Linen Gloves Panel":{"Cured Rugged Leather Square":1,"Bolt of Linen":1},
		"Linen Helm Padding":{"Spool of Linen Thread":1,"Bolt of Linen":1},
		"Linen Helm Strap":{"Cured Rugged Leather Square":1,"Bolt of Linen":1},
		"Linen Pants Lining":{"Bolt of Linen":1},
		"Linen Pants Panel":{"Spool of Linen Thread":3,"Bolt of Linen":4},
		"Linen Shoe Sole":{"Cured Rugged Leather Square":1},
		"Linen Shoe Upper":{"Spool of Linen Thread":1,"Bolt of Linen":2},
		"Major Rune of the Necromancer":{"Full Venom Sac":1,"Pile of Filthy Essence":2,"Bolt of Linen":1},
		"Major Rune of the Scholar":{"Charged Shard":2,"Engraved Totem":1,"Bolt of Linen":1},
		"Valkyrie Winged Boots-Fine":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Winged Gloves-Fine":{"Linen Gloves Padding":1,"Linen Gloves Panel":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Winged Headpiece-Fine":{"Linen Helm Strap":1,"Linen Helm Padding":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Winged Mantle-Fine":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Winged Pants-Fine":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Valkyrie Linen Insignia":1},
		"Valkyrie Winged Tunic-Fine":{"Linen Coat Panel":1,"Linen Coat Lining":1,"Valkyrie Linen Insignia":1}
	},
	"250":{
		"Berserker's Winged Boots-Fine":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Berserker's Linen Insignia":1},
		"Berserker's Winged Gloves-Fine":{"Linen Gloves Padding":1,"Berserker's Linen Insignia":1,"Linen Gloves Panel":1},
		"Berserker's Winged Headpiece-Fine":{"Linen Helm Strap":1,"Berserker's Linen Insignia":1,"Linen Helm Padding":1},
		"Berserker's Winged Mantle-Fine":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Berserker's Linen Insignia":1},
		"Berserker's Winged Pants-Fine":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Berserker's Linen Insignia":1},
		"Berserker's Winged Tunic-Fine":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Berserker's Linen Insignia":1},
		"Cleric's Winged Boots-Fine":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Cleric's Linen Insignia":1},
		"Cleric's Winged Gloves-Fine":{"Linen Gloves Padding":1,"Cleric's Linen Insignia":1,"Linen Gloves Panel":1},
		"Cleric's Winged Headpiece-Fine":{"Linen Helm Strap":1,"Cleric's Linen Insignia":1,"Linen Helm Padding":1},
		"Cleric's Winged Mantle-Fine":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Cleric's Linen Insignia":1},
		"Cleric's Winged Pants-Fine":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Cleric's Linen Insignia":1},
		"Cleric's Winged Tunic-Fine":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Cleric's Linen Insignia":1},
		"Explorer's Winged Boots-Fine":{"Linen Shoe Sole":2,"Explorer's Linen Insignia":1,"Linen Shoe Upper":1},
		"Explorer's Winged Gloves-Fine":{"Linen Gloves Padding":1,"Explorer's Linen Insignia":1,"Linen Gloves Panel":1},
		"Explorer's Winged Headpiece-Fine":{"Linen Helm Strap":1,"Explorer's Linen Insignia":1,"Linen Helm Padding":1},
		"Explorer's Winged Mantle-Fine":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Explorer's Linen Insignia":1},
		"Explorer's Winged Pants-Fine":{"Linen Pants Lining":1,"Explorer's Linen Insignia":1,"Linen Pants Panel":1},
		"Explorer's Winged Tunic-Fine":{"Linen Coat Panel":1,"Explorer's Linen Insignia":1,"Linen Coat Lining":1},
		"Major Rune of the Pirate":{"Gold Doubloon":2,"Bolt of Linen":1},
		"Major Rune of the Undead":{"Pile of Filthy Essence":2,"Bolt of Linen":1},
		"Rampager's Winged Boots-Fine":{"Rampager's Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Rampager's Winged Gloves-Fine":{"Rampager's Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Rampager's Winged Headpiece-Fine":{"Rampager's Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Rampager's Winged Mantle-Fine":{"Rampager's Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Rampager's Winged Pants-Fine":{"Rampager's Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Rampager's Winged Tunic-Fine":{"Rampager's Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1}
	},
	"275":{
		"Major Rune of the Air":{"Charged Shard":2,"Bolt of Linen":1},
		"Major Rune of the Water":{"Glacial Shard":2,"Bolt of Linen":1},
		"Berserker's Masquerade Boots-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Berserker's Masquerade Gloves-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Berserker's Masquerade Leggings-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Berserker's Masquerade Mantle-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Berserker's Masquerade Mask-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Berserker's Masquerade Raiments-t4":{"Berserker's Intricate Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Berserker's Winged Boots-Master":{"Berserker's Embroidered Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Berserker's Winged Gloves-Master":{"Berserker's Embroidered Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Berserker's Winged Headpiece-Master":{"Berserker's Embroidered Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Berserker's Winged Mantle-Master":{"Linen Epaulet Panel":1,"Berserker's Embroidered Linen Insignia":1,"Linen Epaulet Padding":1},
		"Berserker's Winged Pants-Master":{"Berserker's Embroidered Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Berserker's Winged Tunic-Master":{"Berserker's Embroidered Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Carrion Masquerade Boots-t4":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Masquerade Gloves-t4":{"Linen Gloves Padding":1,"Carrion Intricate Linen Insignia":1,"Linen Gloves Panel":1},
		"Carrion Masquerade Leggings-t4":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Masquerade Mask-t4":{"Linen Helm Strap":1,"Carrion Intricate Linen Insignia":1,"Linen Helm Padding":1},
		"Carrion Masquerade Raiments-t4":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Carrion Intricate Linen Insignia":1},
		"Carrion Winged Boots-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Carrion Winged Gloves-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Carrion Winged Headpiece-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Carrion Winged Mantle-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Carrion Winged Pants-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Carrion Winged Tunic-Master":{"Carrion Embroidered Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Cleric's Masquerade Boots-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Cleric's Masquerade Gloves-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Cleric's Masquerade Leggings-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Cleric's Masquerade Mantle-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Cleric's Masquerade Mask-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Cleric's Masquerade Raiments-t4":{"Cleric's Intricate Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Cleric's Winged Boots-Master":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Winged Gloves-Master":{"Linen Gloves Padding":1,"Cleric's Embroidered Linen Insignia":1,"Linen Gloves Panel":1},
		"Cleric's Winged Headpiece-Master":{"Linen Helm Strap":1,"Cleric's Embroidered Linen Insignia":1,"Linen Helm Padding":1},
		"Cleric's Winged Mantle-Master":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Winged Pants-Master":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Cleric's Embroidered Linen Insignia":1},
		"Cleric's Winged Tunic-Master":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Cleric's Embroidered Linen Insignia":1},
		"Explorer's Masquerade Boots-t4":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Masquerade Gloves-t4":{"Linen Gloves Padding":1,"Explorer's Intricate Linen Insignia":1,"Linen Gloves Panel":1},
		"Explorer's Masquerade Leggings-t4":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Masquerade Mask-t4":{"Linen Helm Strap":1,"Explorer's Intricate Linen Insignia":1,"Linen Helm Padding":1},
		"Explorer's Masquerade Raiments-t4":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Explorer's Intricate Linen Insignia":1},
		"Explorer's Winged Boots-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Explorer's Winged Gloves-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Explorer's Winged Headpiece-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Explorer's Winged Mantle-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Explorer's Winged Pants-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Explorer's Winged Tunic-Master":{"Explorer's Embroidered Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Giver's Masquerade Boots-t4":{"Linen Shoe Sole":2,"Linen Shoe Upper":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Masquerade Gloves-t4":{"Linen Gloves Padding":1,"Giver's Embroidered Linen Insignia":1,"Linen Gloves Panel":1},
		"Giver's Masquerade Leggings-t4":{"Linen Pants Lining":1,"Linen Pants Panel":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Giver's Embroidered Linen Insignia":1},
		"Giver's Masquerade Mask-t4":{"Linen Helm Strap":1,"Giver's Embroidered Linen Insignia":1,"Linen Helm Padding":1},
		"Giver's Masquerade Raiments-t4":{"Linen Coat Lining":1,"Linen Coat Panel":1,"Giver's Embroidered Linen Insignia":1},
		"Knight's Masquerade Boots-t4":{"Knight's Intricate Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Knight's Masquerade Gloves-t4":{"Knight's Intricate Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Knight's Masquerade Leggings-t4":{"Knight's Intricate Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Knight's Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Knight's Intricate Linen Insignia":1,"Linen Epaulet Padding":1},
		"Knight's Masquerade Mask-t4":{"Knight's Intricate Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Knight's Masquerade Raiments-t4":{"Knight's Intricate Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Knight's Winged Boots-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Knight's Winged Gloves-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Knight's Winged Headpiece-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Knight's Winged Mantle-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Epaulet Panel":1,"Linen Epaulet Padding":1},
		"Knight's Winged Pants-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Knight's Winged Tunic-Master":{"Knight's Embroidered Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Rampager's Masquerade Boots-t4":{"Rampager's Intricate Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Rampager's Masquerade Gloves-t4":{"Rampager's Intricate Linen Insignia":1,"Linen Gloves Padding":1,"Linen Gloves Panel":1},
		"Rampager's Masquerade Leggings-t4":{"Rampager's Intricate Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Rampager's Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Rampager's Intricate Linen Insignia":1,"Linen Epaulet Padding":1},
		"Rampager's Masquerade Mask-t4":{"Rampager's Intricate Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Rampager's Masquerade Raiments-t4":{"Rampager's Intricate Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
		"Rampager's Winged Boots-Master":{"Linen Shoe Sole":2,"Rampager's Embroidered Linen Insignia":1,"Linen Shoe Upper":1},
		"Rampager's Winged Gloves-Master":{"Linen Gloves Padding":1,"Rampager's Embroidered Linen Insignia":1,"Linen Gloves Panel":1},
		"Rampager's Winged Headpiece-Master":{"Linen Helm Strap":1,"Rampager's Embroidered Linen Insignia":1,"Linen Helm Padding":1},
		"Rampager's Winged Mantle-Master":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Rampager's Embroidered Linen Insignia":1},
		"Rampager's Winged Pants-Master":{"Linen Pants Lining":1,"Rampager's Embroidered Linen Insignia":1,"Linen Pants Panel":1},
		"Rampager's Winged Tunic-Master":{"Linen Coat Panel":1,"Rampager's Embroidered Linen Insignia":1,"Linen Coat Lining":1},
		"Valkyrie Masquerade Boots-t4":{"Linen Shoe Sole":2,"Valkyrie Intricate Linen Insignia":1,"Linen Shoe Upper":1},
		"Valkyrie Masquerade Gloves-t4":{"Linen Gloves Padding":1,"Valkyrie Intricate Linen Insignia":1,"Linen Gloves Panel":1},
		"Valkyrie Masquerade Leggings-t4":{"Linen Pants Lining":1,"Valkyrie Intricate Linen Insignia":1,"Linen Pants Panel":1},
		"Valkyrie Masquerade Mantle-t4":{"Linen Epaulet Panel":1,"Linen Epaulet Padding":1,"Valkyrie Intricate Linen Insignia":1},
		"Valkyrie Masquerade Mask-t4":{"Linen Helm Strap":1,"Valkyrie Intricate Linen Insignia":1,"Linen Helm Padding":1},
		"Valkyrie Masquerade Raiments-t4":{"Valkyrie Intricate Linen Insignia":1,"Linen Coat Lining":1,"Linen Coat Panel":1},
		"Valkyrie Winged Boots-Master":{"Valkyrie Embroidered Linen Insignia":1,"Linen Shoe Sole":2,"Linen Shoe Upper":1},
		"Valkyrie Winged Gloves-Master":{"Linen Gloves Padding":1,"Valkyrie Embroidered Linen Insignia":1,"Linen Gloves Panel":1},
		"Valkyrie Winged Headpiece-Master":{"Valkyrie Embroidered Linen Insignia":1,"Linen Helm Strap":1,"Linen Helm Padding":1},
		"Valkyrie Winged Mantle-Master":{"Linen Epaulet Panel":1,"Valkyrie Embroidered Linen Insignia":1,"Linen Epaulet Padding":1},
		"Valkyrie Winged Pants-Master":{"Valkyrie Embroidered Linen Insignia":1,"Linen Pants Lining":1,"Linen Pants Panel":1},
		"Valkyrie Winged Tunic-Master":{"Valkyrie Embroidered Linen Insignia":1,"Linen Coat Panel":1,"Linen Coat Lining":1},
	},
	"300":{
		"Bolt of Silk":{"Silk Scrap":2},
		"Carrion Feathered Boots-Fine":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Carrion Silk Insignia":1},
		"Carrion Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Carrion Silk Insignia":1},
		"Carrion Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Carrion Silk Insignia":1},
		"Carrion Feathered Mantle-Fine":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Carrion Silk Insignia":1},
		"Carrion Feathered Pants-Fine":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Carrion Silk Insignia":1},
		"Carrion Feathered Vestments-Fine":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Carrion Silk Insignia":1},
		"Cured Thick Leather Square":{"Thick Leather Section":2},
		"Knight's Feathered Boots-Fine":{"Knight's Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Knight's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Knight's Silk Insignia":1,"Silk Gloves Padding":1},
		"Knight's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Knight's Silk Insignia":1,"Silk Helm Padding":1},
		"Knight's Feathered Mantle-Fine":{"Knight's Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Knight's Feathered Pants-Fine":{"Silk Pants Lining":1,"Knight's Silk Insignia":1,"Silk Pants Panel":1},
		"Knight's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Knight's Silk Insignia":1,"Silk Coat Lining":1},
		"Major Rune of Altruism":{"Bolt of Silk":1,"Pristine Snowflake":1,"Glacial Core":1},
		"Major Rune of the Elementalist-2":{"Destroyer Core":1,"Bolt of Silk":1},
		"Major Rune of the Mesmer-2":{"Crystal Core":1,"Bolt of Silk":1},
		"Silk Coat Lining":{"Bolt of Silk":1},
		"Silk Coat Panel":{"Spool of Silk Thread":3,"Bolt of Silk":4,"Cured Thick Leather Square":1},
		"Silk Epaulet Padding":{"Spool of Silk Thread":1,"Bolt of Silk":2},
		"Silk Epaulet Panel":{"Cured Thick Leather Square":1},
		"Silk Gloves Padding":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Silk Gloves Panel":{"Bolt of Silk":1,"Cured Thick Leather Square":1},
		"Silk Helm Padding":{"Spool of Silk Thread":1,"Bolt of Silk":1},
		"Silk Helm Strap":{"Bolt of Silk":1,"Cured Thick Leather Square":1},
		"Silk Pants Lining":{"Bolt of Silk":1},
		"Silk Pants Panel":{"Spool of Silk Thread":3,"Bolt of Silk":4},
		"Silk Shoe Sole":{"Cured Thick Leather Square":1},
		"Silk Shoe Upper":{"Spool of Silk Thread":1,"Bolt of Silk":2},
		"Valkyrie Feathered Boots-Fine":{"Valkyrie Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Valkyrie Feathered Gloves-Fine":{"Valkyrie Silk Insignia":1,"Silk Gloves Panel":1,"Silk Gloves Padding":1},
		"Valkyrie Feathered Headpiece-Fine":{"Valkyrie Silk Insignia":1,"Silk Helm Strap":1,"Silk Helm Padding":1},
		"Valkyrie Feathered Mantle-Fine":{"Valkyrie Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Valkyrie Feathered Pants-Fine":{"Valkyrie Silk Insignia":1,"Silk Pants Lining":1,"Silk Pants Panel":1},
		"Valkyrie Feathered Vestments-Fine":{"Valkyrie Silk Insignia":1,"Silk Coat Panel":1,"Silk Coat Lining":1}
	},
	"325":{
		"Berserker's Feathered Boots-Fine":{"Berserker's Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Berserker's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Berserker's Silk Insignia":1,"Silk Gloves Padding":1},
		"Berserker's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Berserker's Silk Insignia":1,"Silk Helm Padding":1},
		"Berserker's Feathered Mantle-Fine":{"Berserker's Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Berserker's Feathered Pants-Fine":{"Berserker's Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Berserker's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Berserker's Silk Insignia":1,"Silk Coat Lining":1},
		"Cleric's Feathered Boots-Fine":{"Cleric's Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Cleric's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Cleric's Silk Insignia":1,"Silk Gloves Padding":1},
		"Cleric's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Cleric's Silk Insignia":1,"Silk Helm Padding":1},
		"Cleric's Feathered Mantle-Fine":{"Cleric's Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Cleric's Feathered Pants-Fine":{"Cleric's Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Cleric's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Cleric's Silk Insignia":1,"Silk Coat Lining":1},
		"Explorer's Feathered Boots-Fine":{"Explorer's Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Explorer's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Explorer's Silk Insignia":1,"Silk Gloves Padding":1},
		"Explorer's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Explorer's Silk Insignia":1,"Silk Helm Padding":1},
		"Explorer's Feathered Mantle-Fine":{"Explorer's Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Explorer's Feathered Pants-Fine":{"Silk Pants Lining":1,"Explorer's Silk Insignia":1,"Silk Pants Panel":1},
		"Explorer's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Explorer's Silk Insignia":1,"Silk Coat Lining":1},
		"Major Rune of the Necromancer-2":{"Bolt of Silk":1,"Potent Venom Sac":1,"Pile of Vile Essence":1},
		"Major Rune of the Scholar-2":{"Charged Core":1,"Intricate Totem":1,"Bolt of Silk":1},
		"Rampager's Feathered Boots-Fine":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Rampager's Silk Insignia":1},
		"Rampager's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Rampager's Silk Insignia":1},
		"Rampager's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Rampager's Silk Insignia":1},
		"Rampager's Feathered Mantle-Fine":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Rampager's Silk Insignia":1},
		"Rampager's Feathered Pants-Fine":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Rampager's Silk Insignia":1},
		"Rampager's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Rampager's Silk Insignia":1},
		"Sentinel's Feathered Boots-Fine":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Sentinel's Silk Insignia":1},
		"Sentinel's Feathered Gloves-Fine":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Sentinel's Silk Insignia":1},
		"Sentinel's Feathered Headpiece-Fine":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Sentinel's Silk Insignia":1},
		"Sentinel's Feathered Mantle-Fine":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Sentinel's Silk Insignia":1},
		"Sentinel's Feathered Pants-Fine":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Sentinel's Silk Insignia":1},
		"Sentinel's Feathered Vestments-Fine":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Sentinel's Silk Insignia":1}
	},
	"350":{
		"Berserker's Feathered Boots-Master":{"Silk Shoe Sole":2,"Silk Shoe Upper":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Feathered Mantle-Master":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Feathered Pants-Master":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Berserker's Embroidered Silk Insignia":1},
		"Berserker's Feathered Vestments-Master":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Berserker's Embroidered Silk Insignia":1},
		"Carrion Feathered Boots-Master":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Carrion Embroidered Silk Insignia":1},
		"Carrion Feathered Gloves-Master":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Feathered Headpiece-Master":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Feathered Mantle-Master":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Feathered Pants-Master":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Carrion Embroidered Silk Insignia":1},
		"Carrion Feathered Vestments-Master":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Carrion Embroidered Silk Insignia":1},
		"Cleric's Feathered Boots-Master":{"Cleric's Embroidered Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Cleric's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Cleric's Embroidered Silk Insignia":1,"Silk Gloves Padding":1},
		"Cleric's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Cleric's Embroidered Silk Insignia":1,"Silk Helm Padding":1},
		"Cleric's Feathered Mantle-Master":{"Cleric's Embroidered Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Cleric's Feathered Pants-Master":{"Cleric's Embroidered Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Cleric's Feathered Vestments-Master":{"Silk Coat Panel":1,"Cleric's Embroidered Silk Insignia":1,"Silk Coat Lining":1},
		"Explorer's Feathered Boots-Master":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Feathered Mantle-Master":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Feathered Pants-Master":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Explorer's Embroidered Silk Insignia":1},
		"Explorer's Feathered Vestments-Master":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Explorer's Embroidered Silk Insignia":1},
		"Knight's Feathered Boots-Master":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Knight's Embroidered Silk Insignia":1},
		"Knight's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Feathered Mantle-Master":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Feathered Pants-Master":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Knight's Embroidered Silk Insignia":1},
		"Knight's Feathered Vestments-Master":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Knight's Embroidered Silk Insignia":1},
		"Major Rune of the Pirate-2":{"Bolt of Silk":1,"Gold Doubloon":1},
		"Major Rune of the Undead-2":{"Bolt of Silk":1,"Pile of Vile Essence":1},
		"Rampager's Feathered Boots-Master":{"Rampager's Embroidered Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Rampager's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Rampager's Embroidered Silk Insignia":1,"Silk Gloves Padding":1},
		"Rampager's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Rampager's Embroidered Silk Insignia":1,"Silk Helm Padding":1},
		"Rampager's Feathered Mantle-Master":{"Rampager's Embroidered Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Rampager's Feathered Pants-Master":{"Silk Pants Lining":1,"Rampager's Embroidered Silk Insignia":1,"Silk Pants Panel":1},
		"Rampager's Feathered Vestments-Master":{"Silk Coat Panel":1,"Rampager's Embroidered Silk Insignia":1,"Silk Coat Lining":1},
		"Sentinel's Feathered Boots-Master":{"Sentinel's Embroidered Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Sentinel's Feathered Gloves-Master":{"Silk Gloves Panel":1,"Sentinel's Embroidered Silk Insignia":1,"Silk Gloves Padding":1},
		"Sentinel's Feathered Headpiece-Master":{"Silk Helm Strap":1,"Sentinel's Embroidered Silk Insignia":1,"Silk Helm Padding":1},
		"Sentinel's Feathered Mantle-Master":{"Sentinel's Embroidered Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Sentinel's Feathered Pants-Master":{"Silk Pants Lining":1,"Sentinel's Embroidered Silk Insignia":1,"Silk Pants Panel":1},
		"Sentinel's Feathered Vestments-Master":{"Silk Coat Panel":1,"Sentinel's Embroidered Silk Insignia":1,"Silk Coat Lining":1},
		"Valkyrie Feathered Boots-Master":{"Silk Shoe Upper":1,"Valkyrie Embroidered Silk Insignia":1,"Silk Shoe Sole":2},
		"Valkyrie Feathered Gloves-Master":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Feathered Headpiece-Master":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Feathered Mantle-Master":{"Silk Epaulet Padding":1,"Silk Epaulet Panel":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Feathered Pants-Master":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Valkyrie Embroidered Silk Insignia":1},
		"Valkyrie Feathered Vestments-Master":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Valkyrie Embroidered Silk Insignia":1}
	},
	"375":{
		"Apothecary's Masquerade Boots-t5":{"Apothecary's Intricate Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Apothecary's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Apothecary's Intricate Silk Insignia":1,"Silk Gloves Padding":1},
		"Apothecary's Masquerade Leggings-t5":{"Silk Pants Lining":1,"Apothecary's Intricate Silk Insignia":1,"Silk Pants Panel":1},
		"Apothecary's Masquerade Mantle-t5":{"Apothecary's Intricate Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Apothecary's Masquerade Mask-t5":{"Silk Helm Strap":1,"Apothecary's Intricate Silk Insignia":1,"Silk Helm Padding":1},
		"Apothecary's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Apothecary's Intricate Silk Insignia":1,"Silk Coat Lining":1},
		"Berserker's Masquerade Boots-t5":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Masquerade Leggings-t5":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Masquerade Mantle-t5":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Masquerade Mask-t5":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Berserker's Intricate Silk Insignia":1},
		"Berserker's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Berserker's Intricate Silk Insignia":1},
		"Carrion Masquerade Boots-t5":{"Silk Shoe Sole":2,"Silk Shoe Upper":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Masquerade Leggings-t5":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Masquerade Mantle-t5":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Masquerade Mask-t5":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Carrion Intricate Silk Insignia":1},
		"Carrion Masquerade Raiments-t5":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Carrion Intricate Silk Insignia":1},
		"Cleric's Masquerade Boots-t5":{"Silk Shoe Upper":1,"Silk Shoe Sole":2,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Masquerade Leggings-t5":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Masquerade Mantle-t5":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Masquerade Mask-t5":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Cleric's Intricate Silk Insignia":1},
		"Cleric's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Cleric's Intricate Silk Insignia":1},
		"Explorer's Masquerade Boots-t5":{"Explorer's Intricate Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Explorer's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Explorer's Intricate Silk Insignia":1,"Silk Gloves Padding":1},
		"Explorer's Masquerade Leggings-t5":{"Explorer's Intricate Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Explorer's Masquerade Mantle-t5":{"Explorer's Intricate Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Explorer's Masquerade Mask-t5":{"Silk Helm Strap":1,"Explorer's Intricate Silk Insignia":1,"Silk Helm Padding":1},
		"Explorer's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Explorer's Intricate Silk Insignia":1,"Silk Coat Lining":1},
		"Giver's Masquerade Boots-t5":{"Giver's Embroidered Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Giver's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Giver's Embroidered Silk Insignia":1,"Silk Gloves Padding":1},
		"Giver's Masquerade Leggings-t5":{"Giver's Embroidered Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Giver's Masquerade Mantle-t5":{"Giver's Embroidered Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Giver's Masquerade Mask-t5":{"Silk Helm Strap":1,"Giver's Embroidered Silk Insignia":1,"Silk Helm Padding":1},
		"Giver's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Giver's Embroidered Silk Insignia":1,"Silk Coat Lining":1},
		"Knight's Masquerade Boots-t5":{"Knight's Intricate Silk Insignia":1,"Silk Shoe Upper":1,"Silk Shoe Sole":2},
		"Knight's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Knight's Intricate Silk Insignia":1,"Silk Gloves Padding":1},
		"Knight's Masquerade Leggings-t5":{"Knight's Intricate Silk Insignia":1,"Silk Pants Panel":1,"Silk Pants Lining":1},
		"Knight's Masquerade Mantle-t5":{"Knight's Intricate Silk Insignia":1,"Silk Epaulet Panel":1,"Silk Epaulet Padding":1},
		"Knight's Masquerade Mask-t5":{"Silk Helm Strap":1,"Knight's Intricate Silk Insignia":1,"Silk Helm Padding":1},
		"Knight's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Knight's Intricate Silk Insignia":1,"Silk Coat Lining":1},
		"Major Rune of the Air-2":{"Charged Core":1,"Bolt of Silk":1},
		"Major Rune of the Water-2":{"Bolt of Silk":1,"Glacial Core":1},
		"Rampager's Masquerade Boots-t5":{"Silk Shoe Sole":2,"Silk Shoe Upper":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Masquerade Leggings-t5":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Masquerade Mantle-t5":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Masquerade Mask-t5":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Rampager's Intricate Silk Insignia":1},
		"Rampager's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Rampager's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Boots-t5":{"Silk Shoe Sole":2,"Silk Shoe Upper":1,"Sentinel's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Silk Gloves Padding":1,"Sentinel's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Leggings-t5":{"Silk Pants Lining":1,"Silk Pants Panel":1,"Sentinel's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Mantle-t5":{"Silk Epaulet Panel":1,"Silk Epaulet Padding":1,"Sentinel's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Mask-t5":{"Silk Helm Strap":1,"Silk Helm Padding":1,"Sentinel's Intricate Silk Insignia":1},
		"Sentinel's Masquerade Raiments-t5":{"Silk Coat Panel":1,"Silk Coat Lining":1,"Sentinel's Intricate Silk Insignia":1},
		"Valkyrie Masquerade Boots-t5":{"Silk Shoe Sole":2,"Valkyrie Intricate Silk Insignia":1,"Silk Shoe Upper":1},
		"Valkyrie Masquerade Gloves-t5":{"Silk Gloves Panel":1,"Valkyrie Intricate Silk Insignia":1,"Silk Gloves Padding":1},
		"Valkyrie Masquerade Leggings-t5":{"Silk Pants Lining":1,"Valkyrie Intricate Silk Insignia":1,"Silk Pants Panel":1},
		"Valkyrie Masquerade Mantle-t5":{"Valkyrie Intricate Silk Insignia":1,"Silk Epaulet Padding":1,"Silk Epaulet Panel":1},
		"Valkyrie Masquerade Mask-t5":{"Silk Helm Strap":1,"Valkyrie Intricate Silk Insignia":1,"Silk Helm Padding":1},
		"Valkyrie Masquerade Raiments-t5":{"Silk Coat Panel":1,"Valkyrie Intricate Silk Insignia":1,"Silk Coat Lining":1}
	}
}
