# coding=unicode-escape
'''
* Copyright (c) 2013 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Creation Date: 1/7/2013
Last Updated: 1/7/2013
Purpose: Recipe list for Weaponcrafting used by Crafting.py
'''
weaponcraft = {
	"0":{
		"Bronze Axe Blade":{"Bronze Ingot":3},
		"Bronze Dagger Blade":{"Bronze Ingot":3},
		"Bronze Dagger Hilt":{"Bronze Ingot":2},
		"Bronze Greatsword Blade":{"Bronze Ingot":3},
		"Bronze Greatsword Hilt":{"Bronze Ingot":3},
		"Bronze Hammer Head":{"Bronze Ingot":3},
		"Bronze Ingot":{"Copper Ore":2,"Lump of Tin":1},
		"Bronze Mace Head":{"Bronze Ingot":3},
		"Bronze Shield Backing":{"Bronze Ingot":2},
		"Bronze Shield Boss":{"Bronze Ingot":2},
		"Bronze Spear Head":{"Bronze Ingot":3},
		"Bronze Sword Blade":{"Bronze Ingot":3},
		"Bronze Sword Hilt":{"Bronze Ingot":3},
		"Green Wood Dowel":{"Green Wood Plank":1},
		"Green Wood Plank":{"Green Wood Log":3},
		"Large Green Haft":{"Green Wood Plank":2},
		"Malign Bronze Axe-Fine":{"Small Green Haft":1,"Bronze Axe Blade":1,"Malign Green Inscription":1},
		"Malign Bronze Dagger-Fine":{"Bronze Dagger Blade":1,"Malign Green Inscription":1,"Bronze Dagger Hilt":1},
		"Malign Bronze Greatsword-Fine":{"Bronze Greatsword Blade":1,"Malign Green Inscription":1,"Bronze Greatsword Hilt":1},
		"Malign Bronze Hammer-Fine":{"Malign Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Malign Bronze Mace-Fine":{"Bronze Mace Head":1,"Small Green Haft":1,"Malign Green Inscription":1},
		"Malign Bronze Shield-Fine":{"Bronze Shield Backing":1,"Malign Green Inscription":1,"Bronze Shield Boss":1},
		"Malign Bronze Spear-Fine":{"Bronze Spear Head":1,"Malign Green Inscription":1,"Large Green Haft":1},
		"Malign Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Malign Green Inscription":1,"Bronze Sword Blade":1},
		"Mighty Bronze Axe-Fine":{"Mighty Green Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Mighty Bronze Dagger-Fine":{"Mighty Green Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Mighty Bronze Greatsword-Fine":{"Mighty Green Inscription":1,"Bronze Greatsword Blade":1,"Bronze Greatsword Hilt":1},
		"Mighty Bronze Hammer-Fine":{"Mighty Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Mighty Bronze Mace-Fine":{"Bronze Mace Head":1,"Mighty Green Inscription":1,"Small Green Haft":1},
		"Mighty Bronze Shield-Fine":{"Mighty Green Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Mighty Bronze Spear-Fine":{"Mighty Green Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Mighty Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Mighty Green Inscription":1,"Bronze Sword Blade":1},
		"Minor Sigil of Strength":{"Onyx Sliver":2,"Bronze Ingot":1},
		"Rough Sharpening Stone":{"Pile of Glittering Dust":3,"Bronze Ingot":3},
		"Small Green Haft":{"Green Wood Plank":2},
		"Vital Bronze Axe-Fine":{"Vital Green Inscription":1,"Small Green Haft":1,"Bronze Axe Blade":1},
		"Vital Bronze Dagger-Fine":{"Vital Green Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Vital Bronze Greatsword-Fine":{"Bronze Greatsword Hilt":1,"Vital Green Inscription":1,"Bronze Greatsword Blade":1},
		"Vital Bronze Hammer-Fine":{"Vital Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Vital Bronze Mace-Fine":{"Bronze Mace Head":1,"Vital Green Inscription":1,"Small Green Haft":1},
		"Vital Bronze Shield-Fine":{"Bronze Shield Backing":1,"Vital Green Inscription":1,"Bronze Shield Boss":1},
		"Vital Bronze Spear-Fine":{"Vital Green Inscription":1,"Large Green Haft":1,"Bronze Spear Head":1},
		"Vital Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Vital Green Inscription":1,"Bronze Sword Blade":1}
	},
	"25":{
		"Giver's Bronze Axe-Fine":{"Small Green Haft":1,"Bronze Axe Blade":1,"Giver's Green Inscription":1},
		"Giver's Bronze Dagger-Fine":{"Bronze Dagger Blade":1,"Giver's Green Inscription":1,"Bronze Dagger Hilt":1},
		"Giver's Bronze Greatsword-Fine":{"Bronze Greatsword Blade":1,"Giver's Green Inscription":1,"Bronze Greatsword Hilt":1},
		"Giver's Bronze Hammer-Fine":{"Giver's Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Giver's Bronze Mace-Fine":{"Bronze Mace Head":1,"Small Green Haft":1,"Giver's Green Inscription":1},
		"Giver's Bronze Shield-Fine":{"Bronze Shield Backing":1,"Giver's Green Inscription":1,"Bronze Shield Boss":1},
		"Giver's Bronze Spear-Fine":{"Bronze Spear Head":1,"Giver's Green Inscription":1,"Large Green Haft":1},
		"Giver's Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Giver's Green Inscription":1,"Bronze Sword Blade":1},
		"Healing Bronze Axe-Fine":{"Healing Green Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Healing Bronze Dagger-Fine":{"Healing Green Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Healing Bronze Greatsword-Fine":{"Healing Green Inscription":1,"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1},
		"Healing Bronze Hammer-Fine":{"Healing Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Healing Bronze Mace-Fine":{"Healing Green Inscription":1,"Bronze Mace Head":1,"Small Green Haft":1},
		"Healing Bronze Shield-Fine":{"Healing Green Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Healing Bronze Spear-Fine":{"Healing Green Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Healing Bronze Sword-Fine":{"Healing Green Inscription":1,"Bronze Sword Hilt":1,"Bronze Sword Blade":1},
		"Minor Sigil of Sanctuary":{"Crystal Sliver":2,"Bronze Ingot":1},
		"Precise Bronze Axe-Fine":{"Bronze Axe Blade":1,"Small Green Haft":1,"Precise Green Inscription":1},
		"Precise Bronze Dagger-Fine":{"Bronze Dagger Hilt":1,"Bronze Dagger Blade":1,"Precise Green Inscription":1},
		"Precise Bronze Greatsword-Fine":{"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1,"Precise Green Inscription":1},
		"Precise Bronze Hammer-Fine":{"Large Green Haft":1,"Precise Green Inscription":1,"Bronze Hammer Head":1},
		"Precise Bronze Mace-Fine":{"Bronze Mace Head":1,"Small Green Haft":1,"Precise Green Inscription":1},
		"Precise Bronze Shield-Fine":{"Bronze Shield Backing":1,"Bronze Shield Boss":1,"Precise Green Inscription":1},
		"Precise Bronze Spear-Fine":{"Bronze Spear Head":1,"Large Green Haft":1,"Precise Green Inscription":1},
		"Precise Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Bronze Sword Blade":1,"Precise Green Inscription":1},
		"Resilient Bronze Axe-Fine":{"Resilient Green Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Resilient Bronze Dagger-Fine":{"Resilient Green Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Resilient Bronze Greatsword-Fine":{"Resilient Green Inscription":1,"Bronze Greatsword Blade":1,"Bronze Greatsword Hilt":1},
		"Resilient Bronze Hammer-Fine":{"Resilient Green Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Resilient Bronze Mace-Fine":{"Bronze Mace Head":1,"Resilient Green Inscription":1,"Small Green Haft":1},
		"Resilient Bronze Shield-Fine":{"Resilient Green Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Resilient Bronze Spear-Fine":{"Resilient Green Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Resilient Bronze Sword-Fine":{"Bronze Sword Hilt":1,"Resilient Green Inscription":1,"Bronze Sword Blade":1}
	},
	"50":{
		"Bronze Plated Dowel":{"Green Wood Plank":2,"Bronze Ingot":3},
		"Healing Bronze Axe-Master":{"Healing Bronze Plated Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Healing Bronze Dagger-Master":{"Healing Bronze Plated Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Healing Bronze Greatsword-Master":{"Healing Bronze Plated Inscription":1,"Bronze Greatsword Blade":1,"Bronze Greatsword Hilt":1},
		"Healing Bronze Hammer-Master":{"Healing Bronze Plated Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Healing Bronze Mace-Master":{"Bronze Mace Head":1,"Healing Bronze Plated Inscription":1,"Small Green Haft":1},
		"Healing Bronze Shield-Master":{"Healing Bronze Plated Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Healing Bronze Spear-Master":{"Healing Bronze Plated Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Healing Bronze Sword-Master":{"Bronze Sword Hilt":1,"Healing Bronze Plated Inscription":1,"Bronze Sword Blade":1},
		"Malign Bronze Axe-Master":{"Bronze Axe Blade":1,"Small Green Haft":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Dagger-Master":{"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Greatsword-Master":{"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Hammer-Master":{"Large Green Haft":1,"Bronze Hammer Head":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Mace-Master":{"Bronze Mace Head":1,"Small Green Haft":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Shield-Master":{"Bronze Shield Backing":1,"Bronze Shield Boss":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Spear-Master":{"Bronze Spear Head":1,"Large Green Haft":1,"Malign Bronze Plated Inscription":1},
		"Malign Bronze Sword-Master":{"Bronze Sword Hilt":1,"Bronze Sword Blade":1,"Malign Bronze Plated Inscription":1},
		"Mighty Bronze Axe-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Mighty Bronze Dagger-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Mighty Bronze Greatsword-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1},
		"Mighty Bronze Hammer-Master":{"Mighty Bronze Plated Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Mighty Bronze Mace-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Mace Head":1,"Small Green Haft":1},
		"Mighty Bronze Shield-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Mighty Bronze Spear-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Mighty Bronze Sword-Master":{"Mighty Bronze Plated Inscription":1,"Bronze Sword Hilt":1,"Bronze Sword Blade":1},
		"Minor Sigil of Destroyer Slayer":{"Destroyer Sliver":2,"Bronze Ingot":1},
		"Precise Bronze Axe-Master":{"Precise Bronze Plated Inscription":1,"Bronze Axe Blade":1,"Small Green Haft":1},
		"Precise Bronze Dagger-Master":{"Precise Bronze Plated Inscription":1,"Bronze Dagger Blade":1,"Bronze Dagger Hilt":1},
		"Precise Bronze Greatsword-Master":{"Precise Bronze Plated Inscription":1,"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1},
		"Precise Bronze Hammer-Master":{"Precise Bronze Plated Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Precise Bronze Mace-Master":{"Precise Bronze Plated Inscription":1,"Bronze Mace Head":1,"Small Green Haft":1},
		"Precise Bronze Shield-Master":{"Precise Bronze Plated Inscription":1,"Bronze Shield Backing":1,"Bronze Shield Boss":1},
		"Precise Bronze Spear-Master":{"Precise Bronze Plated Inscription":1,"Bronze Spear Head":1,"Large Green Haft":1},
		"Precise Bronze Sword-Master":{"Precise Bronze Plated Inscription":1,"Bronze Sword Hilt":1,"Bronze Sword Blade":1},
		"Resilient Bronze Axe-Master":{"Bronze Axe Blade":1,"Small Green Haft":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Bronze Dagger-Master":{"Bronze Dagger Blade":1,"Resilient Bronze Plated Inscription":1,"Bronze Dagger Hilt":1},
		"Resilient Bronze Greatsword-Master":{"Bronze Greatsword Hilt":1,"Bronze Greatsword Blade":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Bronze Hammer-Master":{"Large Green Haft":1,"Resilient Bronze Plated Inscription":1,"Bronze Hammer Head":1},
		"Resilient Bronze Mace-Master":{"Bronze Mace Head":1,"Small Green Haft":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Bronze Shield-Master":{"Bronze Shield Backing":1,"Resilient Bronze Plated Inscription":1,"Bronze Shield Boss":1},
		"Resilient Bronze Spear-Master":{"Bronze Spear Head":1,"Large Green Haft":1,"Resilient Bronze Plated Inscription":1},
		"Resilient Bronze Sword-Master":{"Bronze Sword Hilt":1,"Bronze Sword Blade":1,"Resilient Bronze Plated Inscription":1},
		"Vital Bronze Axe-Master":{"Small Green Haft":1,"Bronze Axe Blade":1,"Vital Bronze Plated Inscription":1},
		"Vital Bronze Dagger-Master":{"Bronze Dagger Blade":1,"Vital Bronze Plated Inscription":1,"Bronze Dagger Hilt":1},
		"Vital Bronze Greatsword-Master":{"Bronze Greatsword Blade":1,"Vital Bronze Plated Inscription":1,"Bronze Greatsword Hilt":1},
		"Vital Bronze Hammer-Master":{"Vital Bronze Plated Inscription":1,"Large Green Haft":1,"Bronze Hammer Head":1},
		"Vital Bronze Mace-Master":{"Bronze Mace Head":1,"Small Green Haft":1,"Vital Bronze Plated Inscription":1},
		"Vital Bronze Shield-Master":{"Bronze Shield Backing":1,"Vital Bronze Plated Inscription":1,"Bronze Shield Boss":1},
		"Vital Bronze Spear-Master":{"Bronze Spear Head":1,"Vital Bronze Plated Inscription":1,"Large Green Haft":1},
		"Vital Bronze Sword-Master":{"Bronze Sword Hilt":1,"Vital Bronze Plated Inscription":1,"Bronze Sword Blade":1}
	},
	"75":{
		"Iron Axe Blade":{"Iron Ingot":3},
		"Iron Dagger Blade":{"Iron Ingot":3},
		"Iron Dagger Hilt":{"Iron Ingot":2},
		"Iron Greatsword Blade":{"Iron Ingot":3},
		"Iron Greatsword Hilt":{"Iron Ingot":3},
		"Iron Hammer Head":{"Iron Ingot":3},
		"Iron Ingot":{"Iron Ore":3},
		"Iron Mace Head":{"Iron Ingot":3},
		"Iron Shield Backing":{"Iron Ingot":2},
		"Iron Shield Boss":{"Iron Ingot":2},
		"Iron Spear Head":{"Iron Ingot":3},
		"Iron Sword Blade":{"Iron Ingot":3},
		"Iron Sword Hilt":{"Iron Ingot":3},
		"Large Soft Haft":{"Soft Wood Plank":2},
		"Minor Sigil of Doom":{"Molten Sliver":2,"Iron Ingot":1},
		"Pillaging Iron Axe-Fine":{"Pillaging Soft Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Pillaging Iron Dagger-Fine":{"Pillaging Soft Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Pillaging Iron Greatsword-Fine":{"Pillaging Soft Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Pillaging Iron Hammer-Fine":{"Pillaging Soft Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Pillaging Iron Mace-Fine":{"Iron Mace Head":1,"Pillaging Soft Inscription":1,"Small Soft Haft":1},
		"Pillaging Iron Shield-Fine":{"Pillaging Soft Inscription":1,"Iron Shield Backing":1,"Iron Shield Boss":1},
		"Pillaging Iron Spear-Fine":{"Pillaging Soft Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Pillaging Iron Sword-Fine":{"Pillaging Soft Inscription":1,"Iron Sword Blade":1,"Iron Sword Hilt":1},
		"Ravaging Iron Axe-Fine":{"Ravaging Soft Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Ravaging Iron Dagger-Fine":{"Iron Dagger Blade":1,"Ravaging Soft Inscription":1,"Iron Dagger Hilt":1},
		"Ravaging Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Ravaging Soft Inscription":1,"Iron Greatsword Hilt":1},
		"Ravaging Iron Hammer-Fine":{"Iron Hammer Head":1,"Ravaging Soft Inscription":1,"Large Soft Haft":1},
		"Ravaging Iron Mace-Fine":{"Iron Mace Head":1,"Ravaging Soft Inscription":1,"Small Soft Haft":1},
		"Ravaging Iron Shield-Fine":{"Iron Shield Backing":1,"Ravaging Soft Inscription":1,"Iron Shield Boss":1},
		"Ravaging Iron Spear-Fine":{"Ravaging Soft Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Ravaging Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Ravaging Soft Inscription":1},
		"Simple Sharpening Stone":{"Iron Ingot":3,"Pile of Shimmering Dust":3},
		"Small Soft Haft":{"Soft Wood Plank":2},
		"Soft Wood Dowel":{"Soft Wood Plank":1},
		"Soft Wood Plank":{"Soft Wood Log":4},
		"Vigorous Iron Axe-Fine":{"Vigorous Soft Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Vigorous Iron Dagger-Fine":{"Iron Dagger Blade":1,"Vigorous Soft Inscription":1,"Iron Dagger Hilt":1},
		"Vigorous Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Vigorous Soft Inscription":1,"Iron Greatsword Hilt":1},
		"Vigorous Iron Hammer-Fine":{"Iron Hammer Head":1,"Vigorous Soft Inscription":1,"Large Soft Haft":1},
		"Vigorous Iron Mace-Fine":{"Iron Mace Head":1,"Vigorous Soft Inscription":1,"Small Soft Haft":1},
		"Vigorous Iron Shield-Fine":{"Iron Shield Backing":1,"Vigorous Soft Inscription":1,"Iron Shield Boss":1},
		"Vigorous Iron Spear-Fine":{"Vigorous Soft Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Vigorous Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Vigorous Soft Inscription":1}
	},
	"100":{
		"Minor Sigil of Strength-2":{"Iron Ingot":1,"Onyx Fragment":1},
		"Hearty Iron Axe-Fine":{"Small Soft Haft":1,"Iron Axe Blade":1,"Hearty Soft Inscription":1},
		"Hearty Iron Dagger-Fine":{"Iron Dagger Blade":1,"Iron Dagger Hilt":1,"Hearty Soft Inscription":1},
		"Hearty Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1,"Hearty Soft Inscription":1},
		"Hearty Iron Hammer-Fine":{"Iron Hammer Head":1,"Large Soft Haft":1,"Hearty Soft Inscription":1},
		"Hearty Iron Mace-Fine":{"Iron Mace Head":1,"Small Soft Haft":1,"Hearty Soft Inscription":1},
		"Hearty Iron Shield-Fine":{"Iron Shield Backing":1,"Iron Shield Boss":1,"Hearty Soft Inscription":1},
		"Hearty Iron Spear-Fine":{"Large Soft Haft":1,"Iron Spear Head":1,"Hearty Soft Inscription":1},
		"Hearty Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Hearty Soft Inscription":1},
		"Honed Iron Axe-Fine":{"Honed Soft Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Honed Iron Dagger-Fine":{"Iron Dagger Blade":1,"Honed Soft Inscription":1,"Iron Dagger Hilt":1},
		"Honed Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Honed Soft Inscription":1,"Iron Greatsword Hilt":1},
		"Honed Iron Hammer-Fine":{"Iron Hammer Head":1,"Honed Soft Inscription":1,"Large Soft Haft":1},
		"Honed Iron Mace-Fine":{"Iron Mace Head":1,"Honed Soft Inscription":1,"Small Soft Haft":1},
		"Honed Iron Shield-Fine":{"Iron Shield Backing":1,"Honed Soft Inscription":1,"Iron Shield Boss":1},
		"Honed Iron Spear-Fine":{"Honed Soft Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Honed Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Honed Soft Inscription":1},
		"Rejuvenating Iron Axe-Fine":{"Rejuvenating Soft Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Rejuvenating Iron Dagger-Fine":{"Iron Dagger Blade":1,"Rejuvenating Soft Inscription":1,"Iron Dagger Hilt":1},
		"Rejuvenating Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Rejuvenating Soft Inscription":1,"Iron Greatsword Hilt":1},
		"Rejuvenating Iron Hammer-Fine":{"Iron Hammer Head":1,"Rejuvenating Soft Inscription":1,"Large Soft Haft":1},
		"Rejuvenating Iron Mace-Fine":{"Iron Mace Head":1,"Rejuvenating Soft Inscription":1,"Small Soft Haft":1},
		"Rejuvenating Iron Shield-Fine":{"Iron Shield Backing":1,"Rejuvenating Soft Inscription":1,"Iron Shield Boss":1},
		"Rejuvenating Iron Spear-Fine":{"Rejuvenating Soft Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Rejuvenating Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Rejuvenating Soft Inscription":1},
		"Strong Iron Axe-Fine":{"Small Soft Haft":1,"Iron Axe Blade":1,"Strong Soft Inscription":1},
		"Strong Iron Dagger-Fine":{"Iron Dagger Blade":1,"Iron Dagger Hilt":1,"Strong Soft Inscription":1},
		"Strong Iron Greatsword-Fine":{"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1,"Strong Soft Inscription":1},
		"Strong Iron Hammer-Fine":{"Iron Hammer Head":1,"Large Soft Haft":1,"Strong Soft Inscription":1},
		"Strong Iron Mace-Fine":{"Iron Mace Head":1,"Small Soft Haft":1,"Strong Soft Inscription":1},
		"Strong Iron Shield-Fine":{"Iron Shield Backing":1,"Iron Shield Boss":1,"Strong Soft Inscription":1},
		"Strong Iron Spear-Fine":{"Large Soft Haft":1,"Iron Spear Head":1,"Strong Soft Inscription":1},
		"Strong Iron Sword-Fine":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Strong Soft Inscription":1}
	},
	"125":{
		"Minor Sigil of Sanctuary-2":{"Iron Ingot":1,"Crystal Fragment":1},
		"Giver's Iron Axe-Master":{"Giver's Iron-Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Giver's Iron Dagger-Master":{"Iron Dagger Blade":1,"Giver's Iron-Plated Inscription":1,"Iron Dagger Hilt":1},
		"Giver's Iron Greatsword-Master":{"Iron Greatsword Blade":1,"Giver's Iron-Plated Inscription":1,"Iron Greatsword Hilt":1},
		"Giver's Iron Hammer-Master":{"Iron Hammer Head":1,"Giver's Iron-Plated Inscription":1,"Large Soft Haft":1},
		"Giver's Iron Shield-Master":{"Iron Shield Backing":1,"Giver's Iron-Plated Inscription":1,"Iron Shield Boss":1},
		"Giver's Iron Spear-Master":{"Giver's Iron-Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Giver's Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Giver's Iron-Plated Inscription":1},
		"Hearty Bandit Cleaver":{"Hearty Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Hearty Bandit Demolisher":{"Hearty Iron Imbued Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Hearty Bandit Mallet":{"Iron Mace Head":1,"Hearty Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Hearty Bandit Shiv":{"Hearty Iron Imbued Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Hearty Bandit Slicer":{"Hearty Iron Imbued Inscription":1,"Iron Sword Blade":1,"Iron Sword Hilt":1},
		"Hearty Bandit Spear":{"Hearty Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Hearty Bandit Sunderer":{"Hearty Iron Imbued Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Hearty Bandit Ward":{"Hearty Iron Imbued Inscription":1,"Iron Shield Backing":1,"Iron Shield Boss":1},
		"Hearty Iron Axe-Master":{"Hearty Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Hearty Iron Dagger-Master":{"Iron Dagger Blade":1,"Hearty Iron Plated Inscription":1,"Iron Dagger Hilt":1},
		"Hearty Iron Greatsword-Master":{"Iron Greatsword Blade":1,"Hearty Iron Plated Inscription":1,"Iron Greatsword Hilt":1},
		"Hearty Iron Hammer-Master":{"Iron Hammer Head":1,"Hearty Iron Plated Inscription":1,"Large Soft Haft":1},
		"Hearty Iron Mace-Master":{"Iron Mace Head":1,"Hearty Iron Plated Inscription":1,"Small Soft Haft":1},
		"Hearty Iron Shield-Master":{"Iron Shield Backing":1,"Hearty Iron Plated Inscription":1,"Iron Shield Boss":1},
		"Hearty Iron Spear-Master":{"Hearty Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Hearty Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Hearty Iron Plated Inscription":1},
		"Honed Bandit Cleaver":{"Honed Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Honed Bandit Demolisher":{"Iron Hammer Head":1,"Honed Iron Imbued Inscription":1,"Large Soft Haft":1},
		"Honed Bandit Mallet":{"Iron Mace Head":1,"Honed Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Honed Bandit Shiv":{"Iron Dagger Blade":1,"Honed Iron Imbued Inscription":1,"Iron Dagger Hilt":1},
		"Honed Bandit Slicer":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Honed Iron Imbued Inscription":1},
		"Honed Bandit Spear":{"Honed Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Honed Bandit Sunderer":{"Iron Greatsword Blade":1,"Honed Iron Imbued Inscription":1,"Iron Greatsword Hilt":1},
		"Honed Bandit Ward":{"Iron Shield Backing":1,"Honed Iron Imbued Inscription":1,"Iron Shield Boss":1},
		"Honed Iron Axe-Master":{"Small Soft Haft":1,"Honed Iron Plated Inscription":1,"Iron Axe Blade":1},
		"Honed Iron Dagger-Master":{"Iron Dagger Hilt":1,"Iron Dagger Blade":1,"Honed Iron Plated Inscription":1},
		"Honed Iron Greatsword-Master":{"Iron Greatsword Hilt":1,"Iron Greatsword Blade":1,"Honed Iron Plated Inscription":1},
		"Honed Iron Hammer-Master":{"Iron Hammer Head":1,"Honed Iron Plated Inscription":1,"Large Soft Haft":1},
		"Honed Iron Mace-Master":{"Iron Mace Head":1,"Honed Iron Plated Inscription":1,"Small Soft Haft":1},
		"Honed Iron Shield-Master":{"Iron Shield Backing":1,"Iron Shield Boss":1,"Honed Iron Plated Inscription":1},
		"Honed Iron Spear-Master":{"Large Soft Haft":1,"Honed Iron Plated Inscription":1,"Iron Spear Head":1},
		"Honed Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Honed Iron Plated Inscription":1},
		"Iron Plated Dowel":{"Soft Wood Plank":2,"Iron Ingot":3},
		"Pillaging Bandit Cleaver":{"Pillaging Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Pillaging Bandit Demolisher":{"Pillaging Iron Imbued Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Pillaging Bandit Mallet":{"Pillaging Iron Imbued Inscription":1,"Iron Mace Head":1,"Small Soft Haft":1},
		"Pillaging Bandit Shiv":{"Pillaging Iron Imbued Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Pillaging Bandit Slicer":{"Pillaging Iron Imbued Inscription":1,"Iron Sword Hilt":1,"Iron Sword Blade":1},
		"Pillaging Bandit Spear":{"Pillaging Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Pillaging Bandit Sunderer":{"Pillaging Iron Imbued Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Pillaging Bandit Ward":{"Pillaging Iron Imbued Inscription":1,"Iron Shield Backing":1,"Iron Shield Boss":1},
		"Pillaging Iron Axe-Master":{"Pillaging Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Pillaging Iron Dagger-Master":{"Pillaging Iron Plated Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Pillaging Iron Greatsword-Master":{"Pillaging Iron Plated Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Pillaging Iron Hammer-Master":{"Pillaging Iron Plated Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Pillaging Iron Mace-Master":{"Iron Mace Head":1,"Pillaging Iron Plated Inscription":1,"Small Soft Haft":1},
		"Pillaging Iron Shield-Master":{"Iron Shield Backing":1,"Pillaging Iron Plated Inscription":1,"Iron Shield Boss":1},
		"Pillaging Iron Spear-Master":{"Pillaging Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Pillaging Iron Sword-Master":{"Iron Sword Hilt":1,"Pillaging Iron Plated Inscription":1,"Iron Sword Blade":1},
		"Ravaging Bandit Cleaver":{"Ravaging Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Ravaging Bandit Demolisher":{"Iron Hammer Head":1,"Ravaging Iron Imbued Inscription":1,"Large Soft Haft":1},
		"Ravaging Bandit Mallet":{"Iron Mace Head":1,"Ravaging Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Ravaging Bandit Shiv":{"Iron Dagger Blade":1,"Ravaging Iron Imbued Inscription":1,"Iron Dagger Hilt":1},
		"Ravaging Bandit Slicer":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Ravaging Iron Imbued Inscription":1},
		"Ravaging Bandit Spear":{"Ravaging Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Ravaging Bandit Sunderer":{"Iron Greatsword Blade":1,"Ravaging Iron Imbued Inscription":1,"Iron Greatsword Hilt":1},
		"Ravaging Bandit Ward":{"Iron Shield Backing":1,"Ravaging Iron Imbued Inscription":1,"Iron Shield Boss":1},
		"Ravaging Iron Axe-Master":{"Ravaging Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Ravaging Iron Dagger-Master":{"Ravaging Iron Plated Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Ravaging Iron Greatsword-Master":{"Ravaging Iron Plated Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Ravaging Iron Hammer-Master":{"Ravaging Iron Plated Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Ravaging Iron Mace-Master":{"Iron Mace Head":1,"Ravaging Iron Plated Inscription":1,"Small Soft Haft":1},
		"Ravaging Iron Shield-Master":{"Ravaging Iron Plated Inscription":1,"Iron Shield Backing":1,"Iron Shield Boss":1},
		"Ravaging Iron Spear-Master":{"Ravaging Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Ravaging Iron Sword-Master":{"Ravaging Iron Plated Inscription":1,"Iron Sword Blade":1,"Iron Sword Hilt":1},
		"Rejuvenating Bandit Cleaver":{"Rejuvenating Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Rejuvenating Bandit Demolisher":{"Rejuvenating Iron Imbued Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Rejuvenating Bandit Mallet":{"Iron Mace Head":1,"Rejuvenating Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Rejuvenating Bandit Shiv":{"Rejuvenating Iron Imbued Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Rejuvenating Bandit Slicer":{"Iron Sword Hilt":1,"Rejuvenating Iron Imbued Inscription":1,"Iron Sword Blade":1},
		"Rejuvenating Bandit Spear":{"Rejuvenating Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Rejuvenating Bandit Sunderer":{"Rejuvenating Iron Imbued Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Rejuvenating Bandit Ward":{"Iron Shield Backing":1,"Rejuvenating Iron Imbued Inscription":1,"Iron Shield Boss":1},
		"Rejuvenating Iron Axe-Master":{"Rejuvenating Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Rejuvenating Iron Dagger-Master":{"Iron Dagger Blade":1,"Rejuvenating Iron Plated Inscription":1,"Iron Dagger Hilt":1},
		"Rejuvenating Iron Greatsword-Master":{"Iron Greatsword Blade":1,"Rejuvenating Iron Plated Inscription":1,"Iron Greatsword Hilt":1},
		"Rejuvenating Iron Hammer-Master":{"Iron Hammer Head":1,"Rejuvenating Iron Plated Inscription":1,"Large Soft Haft":1},
		"Rejuvenating Iron Mace-Master":{"Iron Mace Head":1,"Rejuvenating Iron Plated Inscription":1,"Small Soft Haft":1},
		"Rejuvenating Iron Shield-Master":{"Iron Shield Backing":1,"Rejuvenating Iron Plated Inscription":1,"Iron Shield Boss":1},
		"Rejuvenating Iron Spear-Master":{"Rejuvenating Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Rejuvenating Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Rejuvenating Iron Plated Inscription":1},
		"Strong Bandit Cleaver":{"Strong Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Strong Bandit Demolisher":{"Strong Iron Imbued Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Strong Bandit Mallet":{"Iron Mace Head":1,"Strong Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Strong Bandit Shiv":{"Strong Iron Imbued Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Strong Bandit Slicer":{"Strong Iron Imbued Inscription":1,"Iron Sword Blade":1,"Iron Sword Hilt":1},
		"Strong Bandit Spear":{"Strong Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Strong Bandit Sunderer":{"Strong Iron Imbued Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Strong Bandit Ward":{"Strong Iron Imbued Inscription":1,"Iron Shield Backing":1,"Iron Shield Boss":1},
		"Strong Iron Axe-Master":{"Strong Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Strong Iron Dagger-Master":{"Iron Dagger Blade":1,"Strong Iron Plated Inscription":1,"Iron Dagger Hilt":1},
		"Strong Iron Greatsword-Master":{"Iron Greatsword Blade":1,"Strong Iron Plated Inscription":1,"Iron Greatsword Hilt":1},
		"Strong Iron Hammer-Master":{"Iron Hammer Head":1,"Strong Iron Plated Inscription":1,"Large Soft Haft":1},
		"Strong Iron Mace-Master":{"Iron Mace Head":1,"Strong Iron Plated Inscription":1,"Small Soft Haft":1},
		"Strong Iron Shield-Master":{"Iron Shield Backing":1,"Strong Iron Plated Inscription":1,"Iron Shield Boss":1},
		"Strong Iron Spear-Master":{"Strong Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Strong Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Strong Iron Plated Inscription":1},
		"Vigorous Bandit Cleaver":{"Vigorous Iron Imbued Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Vigorous Bandit Demolisher":{"Vigorous Iron Imbued Inscription":1,"Iron Hammer Head":1,"Large Soft Haft":1},
		"Vigorous Bandit Mallet":{"Iron Mace Head":1,"Vigorous Iron Imbued Inscription":1,"Small Soft Haft":1},
		"Vigorous Bandit Shiv":{"Vigorous Iron Imbued Inscription":1,"Iron Dagger Blade":1,"Iron Dagger Hilt":1},
		"Vigorous Bandit Slicer":{"Iron Sword Hilt":1,"Vigorous Iron Imbued Inscription":1,"Iron Sword Blade":1},
		"Vigorous Bandit Spear":{"Vigorous Iron Imbued Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Vigorous Bandit Sunderer":{"Vigorous Iron Imbued Inscription":1,"Iron Greatsword Blade":1,"Iron Greatsword Hilt":1},
		"Vigorous Bandit Ward":{"Iron Shield Backing":1,"Vigorous Iron Imbued Inscription":1,"Iron Shield Boss":1},
		"Vigorous Iron Axe-Master":{"Vigorous Iron Plated Inscription":1,"Small Soft Haft":1,"Iron Axe Blade":1},
		"Vigorous Iron Dagger-Master":{"Iron Dagger Blade":1,"Vigorous Iron Plated Inscription":1,"Iron Dagger Hilt":1},
		"Vigorous Iron Greatsword-Master":{"Iron Greatsword Blade":1,"Vigorous Iron Plated Inscription":1,"Iron Greatsword Hilt":1},
		"Vigorous Iron Hammer-Master":{"Iron Hammer Head":1,"Vigorous Iron Plated Inscription":1,"Large Soft Haft":1},
		"Vigorous Iron Mace-Master":{"Iron Mace Head":1,"Vigorous Iron Plated Inscription":1,"Small Soft Haft":1},
		"Vigorous Iron Shield-Master":{"Iron Shield Backing":1,"Vigorous Iron Plated Inscription":1,"Iron Shield Boss":1},
		"Vigorous Iron Spear-Master":{"Vigorous Iron Plated Inscription":1,"Large Soft Haft":1,"Iron Spear Head":1},
		"Vigorous Iron Sword-Master":{"Iron Sword Hilt":1,"Iron Sword Blade":1,"Vigorous Iron Plated Inscription":1}
	},
	"150":{
		"Minor Sigil of Destroyer Slayer-2":{"Steel Ingot":1,"Destroyer Fragment":1},
		"Large Seasoned Haft":{"Seasoned Wood Plank":2},
		"Pillaging Steel Axe-Fine":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Dagger-Fine":{"Steel Dagger Blade":1,"Steel Dagger Hilt":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Greatsword-Fine":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Hammer-Fine":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Mace-Fine":{"Small Seasoned Haft":1,"Pillaging Seasoned Inscription":1,"Steel Mace Head":1},
		"Pillaging Steel Shield-Fine":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Spear-Fine":{"Large Seasoned Haft":1,"Steel Spear Head":1,"Pillaging Seasoned Inscription":1},
		"Pillaging Steel Sword-Fine":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Pillaging Seasoned Inscription":1},
		"Ravaging Steel Axe-Fine":{"Steel Axe Blade":1,"Ravaging Seasoned Inscription":1,"Small Seasoned Haft":1},
		"Ravaging Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Ravaging Seasoned Inscription":1,"Steel Dagger Blade":1},
		"Ravaging Steel Greatsword-Fine":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Steel Hammer-Fine":{"Steel Hammer Head":1,"Ravaging Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Ravaging Steel Mace-Fine":{"Ravaging Seasoned Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Ravaging Steel Shield-Fine":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Ravaging Seasoned Inscription":1},
		"Ravaging Steel Spear-Fine":{"Steel Spear Head":1,"Ravaging Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Ravaging Steel Sword-Fine":{"Steel Sword Hilt":1,"Ravaging Seasoned Inscription":1,"Steel Sword Blade":1},
		"Seasoned Wood Dowel":{"Seasoned Wood Plank":1},
		"Seasoned Wood Plank":{"Seasoned Wood Log":3},
		"Small Seasoned Haft":{"Seasoned Wood Plank":2},
		"Standard Sharpening Stone":{"Pile of Radiant Dust":3,"Steel Ingot":3},
		"Steel Axe Blade":{"Steel Ingot":3},
		"Steel Dagger Blade":{"Steel Ingot":3},
		"Steel Dagger Hilt":{"Steel Ingot":2},
		"Steel Greatsword Blade":{"Steel Ingot":3},
		"Steel Greatsword Hilt":{"Steel Ingot":3},
		"Steel Hammer Head":{"Steel Ingot":3},
		"Steel Ingot":{"Iron Ore":3,"Lump of Coal":1},
		"Steel Mace Head":{"Steel Ingot":3},
		"Steel Shield Backing":{"Steel Ingot":2},
		"Steel Shield Boss":{"Steel Ingot":2},
		"Steel Spear Head":{"Steel Ingot":3},
		"Steel Sword Blade":{"Steel Ingot":3},
		"Steel Sword Hilt":{"Steel Ingot":3},
		"Vigorous Steel Axe-Fine":{"Steel Axe Blade":1,"Vigorous Seasoned Inscription":1,"Small Seasoned Haft":1},
		"Vigorous Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Vigorous Seasoned Inscription":1,"Steel Dagger Blade":1},
		"Vigorous Steel Greatsword-Fine":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Vigorous Seasoned Inscription":1},
		"Vigorous Steel Hammer-Fine":{"Steel Hammer Head":1,"Vigorous Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Vigorous Steel Mace-Fine":{"Vigorous Seasoned Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Vigorous Steel Shield-Fine":{"Steel Shield Boss":1,"Vigorous Seasoned Inscription":1,"Steel Shield Backing":1},
		"Vigorous Steel Spear-Fine":{"Vigorous Seasoned Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Vigorous Steel Sword-Fine":{"Steel Sword Hilt":1,"Vigorous Seasoned Inscription":1,"Steel Sword Blade":1}
	},
	"175":{
		"Minor Sigil of Doom-2":{"Steel Ingot":1,"Molten Fragment":1},
		"Hearty Steel Axe-Fine":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Steel Dagger Blade":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Greatsword-Fine":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Hammer-Fine":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Mace-Fine":{"Small Seasoned Haft":1,"Steel Mace Head":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Shield-Fine":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Spear-Fine":{"Steel Spear Head":1,"Large Seasoned Haft":1,"Hearty Seasoned Inscription":1},
		"Hearty Steel Sword-Fine":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Hearty Seasoned Inscription":1},
		"Honed Steel Axe-Fine":{"Steel Axe Blade":1,"Honed Seasoned Inscription":1,"Small Seasoned Haft":1},
		"Honed Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Honed Seasoned Inscription":1,"Steel Dagger Blade":1},
		"Honed Steel Greatsword-Fine":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Honed Seasoned Inscription":1},
		"Honed Steel Hammer-Fine":{"Steel Hammer Head":1,"Honed Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Honed Steel Mace-Fine":{"Honed Seasoned Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Honed Steel Shield-Fine":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Honed Seasoned Inscription":1},
		"Honed Steel Spear-Fine":{"Steel Spear Head":1,"Honed Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Honed Steel Sword-Fine":{"Steel Sword Hilt":1,"Honed Seasoned Inscription":1,"Steel Sword Blade":1},
		"Rejuvenating Steel Axe-Fine":{"Steel Axe Blade":1,"Rejuvenating Seasoned Inscription":1,"Small Seasoned Haft":1},
		"Rejuvenating Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Rejuvenating Seasoned Inscription":1,"Steel Dagger Blade":1},
		"Rejuvenating Steel Greatsword-Fine":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Rejuvenating Seasoned Inscription":1},
		"Rejuvenating Steel Hammer-Fine":{"Steel Hammer Head":1,"Rejuvenating Seasoned Inscription":1,"Large Seasoned Haft":1},
		"Rejuvenating Steel Mace-Fine":{"Rejuvenating Seasoned Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Rejuvenating Steel Shield-Fine":{"Steel Shield Boss":1,"Rejuvenating Seasoned Inscription":1,"Steel Shield Backing":1},
		"Rejuvenating Steel Spear-Fine":{"Rejuvenating Seasoned Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Rejuvenating Steel Sword-Fine":{"Steel Sword Hilt":1,"Rejuvenating Seasoned Inscription":1,"Steel Sword Blade":1},
		"Strong Steel Axe-Fine":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Strong Seasoned Inscription":1},
		"Strong Steel Dagger-Fine":{"Steel Dagger Hilt":1,"Steel Dagger Blade":1,"Strong Seasoned Inscription":1},
		"Strong Steel Greatsword-Fine":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Strong Seasoned Inscription":1},
		"Strong Steel Hammer-Fine":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Strong Seasoned Inscription":1},
		"Strong Steel Mace-Fine":{"Small Seasoned Haft":1,"Steel Mace Head":1,"Strong Seasoned Inscription":1},
		"Strong Steel Shield-Fine":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Strong Seasoned Inscription":1},
		"Strong Steel Spear-Fine":{"Steel Spear Head":1,"Large Seasoned Haft":1,"Strong Seasoned Inscription":1},
		"Strong Steel Sword-Fine":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Strong Seasoned Inscription":1}
	},
	"200":{
		"Giver's Steel Axe-Master":{"Steel Axe Blade":1,"Giver's Steel-Plated Inscription":1,"Small Seasoned Haft":1},
		"Giver's Steel Dagger-Master":{"Steel Dagger Hilt":1,"Giver's Steel-Plated Inscription":1,"Steel Dagger Blade":1},
		"Giver's Steel Greatsword-Master":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Giver's Steel-Plated Inscription":1},
		"Giver's Steel Hammer-Master":{"Steel Hammer Head":1,"Giver's Steel-Plated Inscription":1,"Large Seasoned Haft":1},
		"Giver's Steel Mace-Master":{"Giver's Steel-Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Giver's Steel Shield-Master":{"Steel Shield Boss":1,"Giver's Steel-Plated Inscription":1,"Steel Shield Backing":1},
		"Giver's Steel Spear-Master":{"Giver's Steel-Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Giver's Steel Sword-Master":{"Steel Sword Hilt":1,"Giver's Steel-Plated Inscription":1,"Steel Sword Blade":1},
		"Hearty Dredge Barricade":{"Steel Shield Boss":1,"Hearty Steel Imbued Inscription":1,"Steel Shield Backing":1},
		"Hearty Dredge Bloodletter":{"Steel Dagger Hilt":1,"Hearty Steel Imbued Inscription":1,"Steel Dagger Blade":1},
		"Hearty Dredge Bonehewer":{"Steel Axe Blade":1,"Hearty Steel Imbued Inscription":1,"Small Seasoned Haft":1},
		"Hearty Dredge Edge":{"Steel Sword Hilt":1,"Hearty Steel Imbued Inscription":1,"Steel Sword Blade":1},
		"Hearty Dredge Flanged Mace":{"Hearty Steel Imbued Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Hearty Dredge Pulverizer":{"Steel Hammer Head":1,"Hearty Steel Imbued Inscription":1,"Large Seasoned Haft":1},
		"Hearty Dredge Spear":{"Hearty Steel Imbued Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Hearty Dredge Sunderer":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Hearty Steel Imbued Inscription":1},
		"Hearty Steel Axe-Master":{"Steel Axe Blade":1,"Hearty Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Hearty Steel Dagger-Master":{"Hearty Steel Plated Inscription":1,"Steel Dagger Hilt":1,"Steel Dagger Blade":1},
		"Hearty Steel Greatsword-Master":{"Hearty Steel Plated Inscription":1,"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1},
		"Hearty Steel Hammer-Master":{"Steel Hammer Head":1,"Hearty Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Hearty Steel Mace-Master":{"Hearty Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Hearty Steel Shield-Master":{"Hearty Steel Plated Inscription":1,"Steel Shield Boss":1,"Steel Shield Backing":1},
		"Hearty Steel Spear-Master":{"Hearty Steel Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Hearty Steel Sword-Master":{"Hearty Steel Plated Inscription":1,"Steel Sword Hilt":1,"Steel Sword Blade":1},
		"Honed Dredge Barricade":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Bloodletter":{"Steel Dagger Blade":1,"Steel Dagger Hilt":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Bonehewer":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Edge":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Flanged Mace":{"Small Seasoned Haft":1,"Honed Steel Imbued Inscription":1,"Steel Mace Head":1},
		"Honed Dredge Pulverizer":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Spear":{"Large Seasoned Haft":1,"Steel Spear Head":1,"Honed Steel Imbued Inscription":1},
		"Honed Dredge Sunderer":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Honed Steel Imbued Inscription":1},
		"Honed Steel Axe-Master":{"Steel Axe Blade":1,"Honed Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Honed Steel Dagger-Master":{"Steel Dagger Hilt":1,"Honed Steel Plated Inscription":1,"Steel Dagger Blade":1},
		"Honed Steel Greatsword-Master":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Honed Steel Plated Inscription":1},
		"Honed Steel Hammer-Master":{"Steel Hammer Head":1,"Honed Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Honed Steel Mace-Master":{"Honed Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Honed Steel Shield-Master":{"Steel Shield Boss":1,"Honed Steel Plated Inscription":1,"Steel Shield Backing":1},
		"Honed Steel Spear-Master":{"Honed Steel Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Honed Steel Sword-Master":{"Steel Sword Hilt":1,"Honed Steel Plated Inscription":1,"Steel Sword Blade":1},
		"Major Sigil of Strength":{"Onyx Shard":2,"Steel Ingot":1},
		"Pillaging Dredge Barricade":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Dredge Bloodletter":{"Steel Dagger Hilt":1,"Pillaging Steel Imbued Inscription":1,"Steel Dagger Blade":1},
		"Pillaging Dredge Bonehewer":{"Steel Axe Blade":1,"Pillaging Steel Imbued Inscription":1,"Small Seasoned Haft":1},
		"Pillaging Dredge Edge":{"Steel Sword Hilt":1,"Pillaging Steel Imbued Inscription":1,"Steel Sword Blade":1},
		"Pillaging Dredge Flanged Mace":{"Pillaging Steel Imbued Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Pillaging Dredge Pulverizer":{"Steel Hammer Head":1,"Pillaging Steel Imbued Inscription":1,"Large Seasoned Haft":1},
		"Pillaging Dredge Spear":{"Steel Spear Head":1,"Pillaging Steel Imbued Inscription":1,"Large Seasoned Haft":1},
		"Pillaging Dredge Sunderer":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Pillaging Steel Imbued Inscription":1},
		"Pillaging Steel Axe-Master":{"Steel Axe Blade":1,"Pillaging Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Pillaging Steel Dagger-Master":{"Pillaging Steel Plated Inscription":1,"Steel Dagger Hilt":1,"Steel Dagger Blade":1},
		"Pillaging Steel Greatsword-Master":{"Steel Greatsword Blade":1,"Pillaging Steel Plated Inscription":1,"Steel Greatsword Hilt":1},
		"Pillaging Steel Hammer-Master":{"Steel Hammer Head":1,"Pillaging Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Pillaging Steel Mace-Master":{"Pillaging Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Pillaging Steel Shield-Master":{"Pillaging Steel Plated Inscription":1,"Steel Shield Backing":1,"Steel Shield Boss":1},
		"Pillaging Steel Spear-Master":{"Pillaging Steel Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Pillaging Steel Sword-Master":{"Pillaging Steel Plated Inscription":1,"Steel Sword Hilt":1,"Steel Sword Blade":1},
		"Ravaging Dredge Barricade":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Bloodletter":{"Steel Dagger Blade":1,"Steel Dagger Hilt":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Bonehewer":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Edge":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Flanged Mace":{"Small Seasoned Haft":1,"Ravaging Steel Imbued Inscription":1,"Steel Mace Head":1},
		"Ravaging Dredge Pulverizer":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Spear":{"Large Seasoned Haft":1,"Steel Spear Head":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Dredge Sunderer":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Ravaging Steel Imbued Inscription":1},
		"Ravaging Steel Axe-Master":{"Steel Axe Blade":1,"Ravaging Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Ravaging Steel Dagger-Master":{"Steel Dagger Hilt":1,"Ravaging Steel Plated Inscription":1,"Steel Dagger Blade":1},
		"Ravaging Steel Greatsword-Master":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Ravaging Steel Plated Inscription":1},
		"Ravaging Steel Hammer-Master":{"Steel Hammer Head":1,"Ravaging Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Ravaging Steel Mace-Master":{"Ravaging Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Ravaging Steel Shield-Master":{"Steel Shield Boss":1,"Ravaging Steel Plated Inscription":1,"Steel Shield Backing":1},
		"Ravaging Steel Spear-Master":{"Ravaging Steel Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Ravaging Steel Sword-Master":{"Steel Sword Hilt":1,"Ravaging Steel Plated Inscription":1,"Steel Sword Blade":1},
		"Rejuvenating Dredge Barricade":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Bloodletter":{"Steel Dagger Hilt":1,"Steel Dagger Blade":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Bonehewer":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Edge":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Flanged Mace":{"Small Seasoned Haft":1,"Steel Mace Head":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Pulverizer":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Spear":{"Steel Spear Head":1,"Large Seasoned Haft":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Dredge Sunderer":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Rejuvenating Steel Imbued Inscription":1},
		"Rejuvenating Steel Axe-Master":{"Steel Axe Blade":1,"Rejuvenating Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Rejuvenating Steel Dagger-Master":{"Steel Dagger Hilt":1,"Rejuvenating Steel Plated Inscription":1,"Steel Dagger Blade":1},
		"Rejuvenating Steel Greatsword-Master":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Steel Hammer-Master":{"Steel Hammer Head":1,"Rejuvenating Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Rejuvenating Steel Mace-Master":{"Rejuvenating Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Rejuvenating Steel Shield-Master":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Rejuvenating Steel Plated Inscription":1},
		"Rejuvenating Steel Spear-Master":{"Steel Spear Head":1,"Rejuvenating Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Rejuvenating Steel Sword-Master":{"Steel Sword Hilt":1,"Rejuvenating Steel Plated Inscription":1,"Steel Sword Blade":1},
		"Steel Plated Dowel":{"Steel Ingot":3,"Seasoned Wood Plank":2},
		"Strong Dredge Barricade":{"Steel Shield Boss":1,"Strong Steel Imbued Inscription":1,"Steel Shield Backing":1},
		"Strong Dredge Bloodletter":{"Steel Dagger Hilt":1,"Strong Steel Imbued Inscription":1,"Steel Dagger Blade":1},
		"Strong Dredge Bonehewer":{"Steel Axe Blade":1,"Strong Steel Imbued Inscription":1,"Small Seasoned Haft":1},
		"Strong Dredge Edge":{"Steel Sword Hilt":1,"Strong Steel Imbued Inscription":1,"Steel Sword Blade":1},
		"Strong Dredge Flanged Mace":{"Strong Steel Imbued Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Strong Dredge Pulverizer":{"Steel Hammer Head":1,"Strong Steel Imbued Inscription":1,"Large Seasoned Haft":1},
		"Strong Dredge Spear":{"Strong Steel Imbued Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Strong Dredge Sunderer":{"Steel Greatsword Hilt":1,"Steel Greatsword Blade":1,"Strong Steel Imbued Inscription":1},
		"Strong Steel Axe-Master":{"Steel Axe Blade":1,"Strong Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Strong Steel Dagger-Master":{"Strong Steel Plated Inscription":1,"Steel Dagger Hilt":1,"Steel Dagger Blade":1},
		"Strong Steel Greatsword-Master":{"Strong Steel Plated Inscription":1,"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1},
		"Strong Steel Hammer-Master":{"Steel Hammer Head":1,"Strong Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Strong Steel Mace-Master":{"Strong Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Strong Steel Shield-Master":{"Strong Steel Plated Inscription":1,"Steel Shield Boss":1,"Steel Shield Backing":1},
		"Strong Steel Spear-Master":{"Strong Steel Plated Inscription":1,"Steel Spear Head":1,"Large Seasoned Haft":1},
		"Strong Steel Sword-Master":{"Strong Steel Plated Inscription":1,"Steel Sword Hilt":1,"Steel Sword Blade":1},
		"Vigorous Dredge Barricade":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Bloodletter":{"Steel Dagger Hilt":1,"Steel Dagger Blade":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Bonehewer":{"Steel Axe Blade":1,"Small Seasoned Haft":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Edge":{"Steel Sword Hilt":1,"Steel Sword Blade":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Flanged Mace":{"Small Seasoned Haft":1,"Steel Mace Head":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Pulverizer":{"Steel Hammer Head":1,"Large Seasoned Haft":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Spear":{"Steel Spear Head":1,"Large Seasoned Haft":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Dredge Sunderer":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Vigorous Steel Imbued Inscription":1},
		"Vigorous Steel Axe-Master":{"Steel Axe Blade":1,"Vigorous Steel Plated Inscription":1,"Small Seasoned Haft":1},
		"Vigorous Steel Dagger-Master":{"Steel Dagger Hilt":1,"Vigorous Steel Plated Inscription":1,"Steel Dagger Blade":1},
		"Vigorous Steel Greatsword-Master":{"Steel Greatsword Blade":1,"Steel Greatsword Hilt":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Steel Hammer-Master":{"Steel Hammer Head":1,"Vigorous Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Vigorous Steel Mace-Master":{"Vigorous Steel Plated Inscription":1,"Small Seasoned Haft":1,"Steel Mace Head":1},
		"Vigorous Steel Shield-Master":{"Steel Shield Boss":1,"Steel Shield Backing":1,"Vigorous Steel Plated Inscription":1},
		"Vigorous Steel Spear-Master":{"Steel Spear Head":1,"Vigorous Steel Plated Inscription":1,"Large Seasoned Haft":1},
		"Vigorous Steel Sword-Master":{"Steel Sword Hilt":1,"Vigorous Steel Plated Inscription":1,"Steel Sword Blade":1}
	},
	"225":{
		"Carrion Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Carrion Hard Inscription":1},
		"Carrion Darksteel Dagger-Fine":{"Darksteel Dagger Hilt":1,"Carrion Hard Inscription":1,"Darksteel Dagger Blade":1},
		"Carrion Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Carrion Hard Inscription":1},
		"Carrion Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Carrion Hard Inscription":1},
		"Carrion Darksteel Mace-Fine":{"Small Hard Haft":1,"Carrion Hard Inscription":1,"Darksteel Mace Head":1},
		"Carrion Darksteel Shield-Fine":{"Darksteel Shield Boss":1,"Carrion Hard Inscription":1,"Darksteel Shield Backing":1},
		"Carrion Darksteel Spear-Fine":{"Large Hard Haft":1,"Carrion Hard Inscription":1,"Darksteel Spear Head":1},
		"Carrion Darksteel Sword-Fine":{"Darksteel Sword Hilt":1,"Carrion Hard Inscription":1,"Darksteel Sword Blade":1},
		"Darksteel Axe Blade":{"Darksteel Ingot":3},
		"Darksteel Dagger Blade":{"Darksteel Ingot":3},
		"Darksteel Dagger Hilt":{"Darksteel Ingot":2},
		"Darksteel Greatsword Blade":{"Darksteel Ingot":3},
		"Darksteel Greatsword Hilt":{"Darksteel Ingot":3},
		"Darksteel Hammer Head":{"Darksteel Ingot":3},
		"Darksteel Ingot":{"Lump of Primordium":1,"Platinum Ore":2},
		"Darksteel Mace Head":{"Darksteel Ingot":3},
		"Darksteel Shield Backing":{"Darksteel Ingot":2},
		"Darksteel Shield Boss":{"Darksteel Ingot":2},
		"Darksteel Spear Head":{"Darksteel Ingot":3},
		"Darksteel Sword Blade":{"Darksteel Ingot":3},
		"Darksteel Sword Hilt":{"Darksteel Ingot":3},
		"Hard Wood Dowel":{"Hard Wood Plank":1},
		"Hard Wood Plank":{"Hard Wood Log":3},
		"Knight's Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Knight's Hard Inscription":1},
		"Knight's Darksteel Dagger-Fine":{"Darksteel Dagger Hilt":1,"Knight's Hard Inscription":1,"Darksteel Dagger Blade":1},
		"Knight's Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Knight's Hard Inscription":1},
		"Knight's Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Knight's Hard Inscription":1},
		"Knight's Darksteel Mace-Fine":{"Small Hard Haft":1,"Knight's Hard Inscription":1,"Darksteel Mace Head":1},
		"Knight's Darksteel Shield-Fine":{"Darksteel Shield Boss":1,"Knight's Hard Inscription":1,"Darksteel Shield Backing":1},
		"Knight's Darksteel Spear-Fine":{"Large Hard Haft":1,"Knight's Hard Inscription":1,"Darksteel Spear Head":1},
		"Knight's Darksteel Sword-Fine":{"Darksteel Sword Hilt":1,"Knight's Hard Inscription":1,"Darksteel Sword Blade":1},
		"Large Hard Haft":{"Hard Wood Plank":2},
		"Major Sigil of Sanctuary":{"Crystal Shard":2,"Darksteel Ingot":1},
		"Quality Sharpening Stone":{"Darksteel Ingot":3,"Pile of Luminous Dust":3},
		"Small Hard Haft":{"Hard Wood Plank":2},
		"Valkyrie Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Valkyrie Hard Inscription":1,"Small Hard Haft":1},
		"Valkyrie Darksteel Dagger-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Valkyrie Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Valkyrie Hard Inscription":1,"Darksteel Greatsword Hilt":1},
		"Valkyrie Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Valkyrie Hard Inscription":1,"Large Hard Haft":1},
		"Valkyrie Darksteel Mace-Fine":{"Small Hard Haft":1,"Valkyrie Hard Inscription":1,"Darksteel Mace Head":1},
		"Valkyrie Darksteel Shield-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Shield Boss":1,"Darksteel Shield Backing":1},
		"Valkyrie Darksteel Spear-Fine":{"Large Hard Haft":1,"Valkyrie Hard Inscription":1,"Darksteel Spear Head":1},
		"Valkyrie Darksteel Sword-Fine":{"Valkyrie Hard Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1}
	},
	"250":{
		"Berserker's Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Dagger-Fine":{"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Mace-Fine":{"Small Hard Haft":1,"Darksteel Mace Head":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Shield-Fine":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Spear-Fine":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Berserker's Hard Inscription":1},
		"Berserker's Darksteel Sword-Fine":{"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1,"Berserker's Hard Inscription":1},
		"Cleric's Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Cleric's Hard Inscription":1},
		"Cleric's Darksteel Dagger-Fine":{"Cleric's Hard Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Cleric's Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Cleric's Hard Inscription":1,"Darksteel Greatsword Hilt":1},
		"Cleric's Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Cleric's Hard Inscription":1},
		"Cleric's Darksteel Mace-Fine":{"Small Hard Haft":1,"Cleric's Hard Inscription":1,"Darksteel Mace Head":1},
		"Cleric's Darksteel Shield-Fine":{"Cleric's Hard Inscription":1,"Darksteel Shield Backing":1,"Darksteel Shield Boss":1},
		"Cleric's Darksteel Spear-Fine":{"Large Hard Haft":1,"Cleric's Hard Inscription":1,"Darksteel Spear Head":1},
		"Cleric's Darksteel Sword-Fine":{"Cleric's Hard Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1},
		"Explorer's Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Explorer's Hard Inscription":1},
		"Explorer's Darksteel Dagger-Fine":{"Darksteel Dagger Hilt":1,"Explorer's Hard Inscription":1,"Darksteel Dagger Blade":1},
		"Explorer's Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Explorer's Hard Inscription":1},
		"Explorer's Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Explorer's Hard Inscription":1},
		"Explorer's Darksteel Mace-Fine":{"Small Hard Haft":1,"Explorer's Hard Inscription":1,"Darksteel Mace Head":1},
		"Explorer's Darksteel Shield-Fine":{"Darksteel Shield Boss":1,"Explorer's Hard Inscription":1,"Darksteel Shield Backing":1},
		"Explorer's Darksteel Spear-Fine":{"Large Hard Haft":1,"Explorer's Hard Inscription":1,"Darksteel Spear Head":1},
		"Explorer's Darksteel Sword-Fine":{"Darksteel Sword Hilt":1,"Explorer's Hard Inscription":1,"Darksteel Sword Blade":1},
		"Major Sigil of Destroyer Slayer":{"Darksteel Ingot":1,"Destroyer Shard":2},
		"Rampager's Darksteel Axe-Fine":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Rampager's Hard Inscription":1},
		"Rampager's Darksteel Dagger-Fine":{"Darksteel Dagger Hilt":1,"Rampager's Hard Inscription":1,"Darksteel Dagger Blade":1},
		"Rampager's Darksteel Greatsword-Fine":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Rampager's Hard Inscription":1},
		"Rampager's Darksteel Hammer-Fine":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Rampager's Hard Inscription":1},
		"Rampager's Darksteel Mace-Fine":{"Small Hard Haft":1,"Rampager's Hard Inscription":1,"Darksteel Mace Head":1},
		"Rampager's Darksteel Shield-Fine":{"Darksteel Shield Boss":1,"Rampager's Hard Inscription":1,"Darksteel Shield Backing":1},
		"Rampager's Darksteel Spear-Fine":{"Large Hard Haft":1,"Rampager's Hard Inscription":1,"Darksteel Spear Head":1},
		"Rampager's Darksteel Sword-Fine":{"Darksteel Sword Hilt":1,"Rampager's Hard Inscription":1,"Darksteel Sword Blade":1}
	},
	"275":{
		"Berserker's Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Berserker's Darksteel Plated Inscription":1},
		"Berserker's Darksteel Dagger-Master":{"Berserker's Darksteel Plated Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Berserker's Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Berserker's Darksteel Plated Inscription":1,"Darksteel Greatsword Hilt":1},
		"Berserker's Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Berserker's Darksteel Plated Inscription":1},
		"Berserker's Darksteel Mace-Master":{"Small Hard Haft":1,"Berserker's Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Berserker's Darksteel Shield-Master":{"Berserker's Darksteel Plated Inscription":1,"Darksteel Shield Backing":1,"Darksteel Shield Boss":1},
		"Berserker's Darksteel Spear-Master":{"Large Hard Haft":1,"Berserker's Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Berserker's Darksteel Sword-Master":{"Berserker's Darksteel Plated Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1},
		"Berserker's Ogre Bludgeoner":{"Small Hard Haft":1,"Berserker's Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Berserker's Ogre Breaker":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Bulwark":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Cleaver":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Dirk":{"Darksteel Dagger Hilt":1,"Berserker's Darksteel Imbued Inscription":1,"Darksteel Dagger Blade":1},
		"Berserker's Ogre Javelin":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Longsword":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Berserker's Darksteel Imbued Inscription":1},
		"Berserker's Ogre Scimitar":{"Darksteel Sword Hilt":1,"Berserker's Darksteel Imbued Inscription":1,"Darksteel Sword Blade":1},
		"Carrion Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Darksteel Dagger-Master":{"Darksteel Dagger Hilt":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Dagger Blade":1},
		"Carrion Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Carrion Darksteel Plated Inscription":1},
		"Carrion Darksteel Mace-Master":{"Small Hard Haft":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Carrion Darksteel Shield-Master":{"Darksteel Shield Boss":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Shield Backing":1},
		"Carrion Darksteel Spear-Master":{"Large Hard Haft":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Carrion Darksteel Sword-Master":{"Darksteel Sword Hilt":1,"Carrion Darksteel Plated Inscription":1,"Darksteel Sword Blade":1},
		"Carrion Ogre Bludgeoner":{"Small Hard Haft":1,"Carrion Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Carrion Ogre Breaker":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Bulwark":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Cleaver":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Dirk":{"Darksteel Dagger Hilt":1,"Carrion Darksteel Imbued Inscription":1,"Darksteel Dagger Blade":1},
		"Carrion Ogre Javelin":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Longsword":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Carrion Darksteel Imbued Inscription":1},
		"Carrion Ogre Scimitar":{"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1,"Carrion Darksteel Imbued Inscription":1},
		"Cleric's Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Cleric's Darksteel Plated Inscription":1},
		"Cleric's Darksteel Dagger-Master":{"Cleric's Darksteel Plated Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Cleric's Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Cleric's Darksteel Plated Inscription":1,"Darksteel Greatsword Hilt":1},
		"Cleric's Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Cleric's Darksteel Plated Inscription":1},
		"Cleric's Darksteel Mace-Master":{"Small Hard Haft":1,"Cleric's Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Cleric's Darksteel Shield-Master":{"Cleric's Darksteel Plated Inscription":1,"Darksteel Shield Backing":1,"Darksteel Shield Boss":1},
		"Cleric's Darksteel Spear-Master":{"Large Hard Haft":1,"Cleric's Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Cleric's Darksteel Sword-Master":{"Cleric's Darksteel Plated Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1},
		"Cleric's Ogre Bludgeoner":{"Cleric's Darksteel Imbued Inscription":1,"Small Hard Haft":1,"Darksteel Mace Head":1},
		"Cleric's Ogre Breaker":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Hammer Head":1,"Large Hard Haft":1},
		"Cleric's Ogre Bulwark":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Shield Boss":1,"Darksteel Shield Backing":1},
		"Cleric's Ogre Cleaver":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Axe Blade":1,"Small Hard Haft":1},
		"Cleric's Ogre Dirk":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Cleric's Ogre Javelin":{"Cleric's Darksteel Imbued Inscription":1,"Large Hard Haft":1,"Darksteel Spear Head":1},
		"Cleric's Ogre Longsword":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1},
		"Cleric's Ogre Scimitar":{"Cleric's Darksteel Imbued Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1},
		"Darksteel Plated Dowel":{"Darksteel Ingot":3,"Hard Wood Plank":2},
		"Explorer's Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Darksteel Dagger-Master":{"Darksteel Dagger Hilt":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Dagger Blade":1},
		"Explorer's Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Explorer's Darksteel Plated Inscription":1},
		"Explorer's Darksteel Mace-Master":{"Small Hard Haft":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Explorer's Darksteel Shield-Master":{"Darksteel Shield Boss":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Shield Backing":1},
		"Explorer's Darksteel Spear-Master":{"Large Hard Haft":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Explorer's Darksteel Sword-Master":{"Darksteel Sword Hilt":1,"Explorer's Darksteel Plated Inscription":1,"Darksteel Sword Blade":1},
		"Explorer's Ogre Bludgeoner":{"Small Hard Haft":1,"Explorer's Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Explorer's Ogre Breaker":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Bulwark":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Cleaver":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Dirk":{"Darksteel Dagger Hilt":1,"Explorer's Darksteel Imbued Inscription":1,"Darksteel Dagger Blade":1},
		"Explorer's Ogre Javelin":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Longsword":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Explorer's Darksteel Imbued Inscription":1},
		"Explorer's Ogre Scimitar":{"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1,"Explorer's Darksteel Imbued Inscription":1},
		"Knight's Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Darksteel Dagger-Master":{"Darksteel Dagger Hilt":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Dagger Blade":1},
		"Knight's Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Knight's Darksteel Plated Inscription":1},
		"Knight's Darksteel Mace-Master":{"Small Hard Haft":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Knight's Darksteel Shield-Master":{"Darksteel Shield Boss":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Shield Backing":1},
		"Knight's Darksteel Spear-Master":{"Large Hard Haft":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Knight's Darksteel Sword-Master":{"Darksteel Sword Hilt":1,"Knight's Darksteel Plated Inscription":1,"Darksteel Sword Blade":1},
		"Knight's Ogre Bludgeoner":{"Small Hard Haft":1,"Knight's Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Knight's Ogre Breaker":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Bulwark":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Cleaver":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Dirk":{"Darksteel Dagger Hilt":1,"Knight's Darksteel Imbued Inscription":1,"Darksteel Dagger Blade":1},
		"Knight's Ogre Javelin":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Longsword":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Knight's Darksteel Imbued Inscription":1},
		"Knight's Ogre Scimitar":{"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1,"Knight's Darksteel Imbued Inscription":1},
		"Major Sigil of Doom":{"Molten Shard":2,"Darksteel Ingot":1},
		"Rampager's Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Darksteel Dagger-Master":{"Darksteel Dagger Hilt":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Dagger Blade":1},
		"Rampager's Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Rampager's Darksteel Plated Inscription":1},
		"Rampager's Darksteel Mace-Master":{"Small Hard Haft":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Rampager's Darksteel Shield-Master":{"Darksteel Shield Boss":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Shield Backing":1},
		"Rampager's Darksteel Spear-Master":{"Large Hard Haft":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Spear Head":1},
		"Rampager's Darksteel Sword-Master":{"Darksteel Sword Hilt":1,"Rampager's Darksteel Plated Inscription":1,"Darksteel Sword Blade":1},
		"Rampager's Ogre Bludgeoner":{"Small Hard Haft":1,"Rampager's Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Rampager's Ogre Breaker":{"Darksteel Hammer Head":1,"Rampager's Darksteel Imbued Inscription":1,"Large Hard Haft":1},
		"Rampager's Ogre Bulwark":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Shield Boss":1,"Darksteel Shield Backing":1},
		"Rampager's Ogre Cleaver":{"Darksteel Axe Blade":1,"Rampager's Darksteel Imbued Inscription":1,"Small Hard Haft":1},
		"Rampager's Ogre Dirk":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Dagger Hilt":1,"Darksteel Dagger Blade":1},
		"Rampager's Ogre Javelin":{"Large Hard Haft":1,"Rampager's Darksteel Imbued Inscription":1,"Darksteel Spear Head":1},
		"Rampager's Ogre Longsword":{"Darksteel Greatsword Blade":1,"Rampager's Darksteel Imbued Inscription":1,"Darksteel Greatsword Hilt":1},
		"Rampager's Ogre Scimitar":{"Rampager's Darksteel Imbued Inscription":1,"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1},
		"Valkyrie Darksteel Axe-Master":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Darksteel Dagger-Master":{"Darksteel Dagger Hilt":1,"Valkyrie Darksteel Plated Inscription":1,"Darksteel Dagger Blade":1},
		"Valkyrie Darksteel Greatsword-Master":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Darksteel Hammer-Master":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Darksteel Mace-Master":{"Small Hard Haft":1,"Valkyrie Darksteel Plated Inscription":1,"Darksteel Mace Head":1},
		"Valkyrie Darksteel Shield-Master":{"Darksteel Shield Boss":1,"Darksteel Shield Backing":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Darksteel Spear-Master":{"Large Hard Haft":1,"Darksteel Spear Head":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Darksteel Sword-Master":{"Darksteel Sword Hilt":1,"Darksteel Sword Blade":1,"Valkyrie Darksteel Plated Inscription":1},
		"Valkyrie Ogre Bludgeoner":{"Small Hard Haft":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Mace Head":1},
		"Valkyrie Ogre Breaker":{"Darksteel Hammer Head":1,"Large Hard Haft":1,"Valkyrie Darksteel Imbued Inscription":1},
		"Valkyrie Ogre Bulwark":{"Darksteel Shield Boss":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Shield Backing":1},
		"Valkyrie Ogre Cleaver":{"Darksteel Axe Blade":1,"Small Hard Haft":1,"Valkyrie Darksteel Imbued Inscription":1},
		"Valkyrie Ogre Dirk":{"Darksteel Dagger Hilt":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Dagger Blade":1},
		"Valkyrie Ogre Javelin":{"Large Hard Haft":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Spear Head":1},
		"Valkyrie Ogre Longsword":{"Darksteel Greatsword Blade":1,"Darksteel Greatsword Hilt":1,"Valkyrie Darksteel Imbued Inscription":1},
		"Valkyrie Ogre Scimitar":{"Darksteel Sword Hilt":1,"Valkyrie Darksteel Imbued Inscription":1,"Darksteel Sword Blade":1}
	},
	"300":{
		"Major Sigil of Strength-2":{"Mithril Ingot":1,"Onyx Core":1},
		"Carrion Mithril Axe-Fine":{"Mithril Axe Blade":1,"Carrion Elder Inscription":1,"Small Elder Haft":1},
		"Carrion Mithril Dagger-Fine":{"Carrion Elder Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Carrion Mithril Greatsword-Fine":{"Carrion Elder Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Carrion Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Carrion Elder Inscription":1,"Large Elder Haft":1},
		"Carrion Mithril Mace-Fine":{"Small Elder Haft":1,"Carrion Elder Inscription":1,"Mithril Mace Head":1},
		"Carrion Mithril Shield-Fine":{"Carrion Elder Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Carrion Mithril Spear-Fine":{"Large Elder Haft":1,"Carrion Elder Inscription":1,"Mithril Spear Head":1},
		"Carrion Mithril Sword-Fine":{"Carrion Elder Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Elder Wood Dowel":{"Elder Wood Plank":1},
		"Elder Wood Plank":{"Elder Wood Log":3},
		"Hardened Sharpening Stone":{"Mithril Ingot":3,"Pile of Incandescent Dust":3},
		"Knight's Mithril Axe-Fine":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Dagger-Fine":{"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Greatsword-Fine":{"Mithril Greatsword Blade":1,"Mithril Greatsword Hilt":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Mace-Fine":{"Small Elder Haft":1,"Mithril Mace Head":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Shield-Fine":{"Mithril Shield Backing":1,"Knight's Elder Inscription":1,"Mithril Shield Boss":1},
		"Knight's Mithril Spear-Fine":{"Large Elder Haft":1,"Mithril Spear Head":1,"Knight's Elder Inscription":1},
		"Knight's Mithril Sword-Fine":{"Mithril Sword Blade":1,"Mithril Sword Hilt":1,"Knight's Elder Inscription":1},
		"Large Elder Haft":{"Elder Wood Plank":2},
		"Mithril Axe Blade":{"Mithril Ingot":3},
		"Mithril Dagger Blade":{"Mithril Ingot":3},
		"Mithril Dagger Hilt":{"Mithril Ingot":2},
		"Mithril Greatsword Blade":{"Mithril Ingot":3},
		"Mithril Greatsword Hilt":{"Mithril Ingot":3},
		"Mithril Hammer Head":{"Mithril Ingot":3},
		"Mithril Ingot":{"Mithril Ore":2},
		"Mithril Mace Head":{"Mithril Ingot":3},
		"Mithril Shield Backing":{"Mithril Ingot":2},
		"Mithril Shield Boss":{"Mithril Ingot":2},
		"Mithril Spear Head":{"Mithril Ingot":3},
		"Mithril Sword Blade":{"Mithril Ingot":3},
		"Mithril Sword Hilt":{"Mithril Ingot":3},
		"Small Elder Haft":{"Elder Wood Plank":2},
		"Valkyrie Mithril Axe-Fine":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Mithril Dagger-Fine":{"Valkyrie Elder Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Valkyrie Mithril Greatsword-Fine":{"Valkyrie Elder Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Valkyrie Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Mithril Mace-Fine":{"Small Elder Haft":1,"Mithril Mace Head":1,"Valkyrie Elder Inscription":1},
		"Valkyrie Mithril Shield-Fine":{"Valkyrie Elder Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Valkyrie Mithril Spear-Fine":{"Large Elder Haft":1,"Valkyrie Elder Inscription":1,"Mithril Spear Head":1},
		"Valkyrie Mithril Sword-Fine":{"Valkyrie Elder Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1}
	},
	"325":{
		"Major Sigil of Sanctuary-2":{"Mithril Ingot":1,"Crystal Core":1},
		"Berserker's Mithril Axe-Fine":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Dagger-Fine":{"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Greatsword-Fine":{"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Mace-Fine":{"Small Elder Haft":1,"Mithril Mace Head":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Shield-Fine":{"Mithril Shield Backing":1,"Mithril Shield Boss":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Spear-Fine":{"Large Elder Haft":1,"Mithril Spear Head":1,"Berserker's Elder Inscription":1},
		"Berserker's Mithril Sword-Fine":{"Mithril Sword Hilt":1,"Mithril Sword Blade":1,"Berserker's Elder Inscription":1},
		"Cleric's Mithril Axe-Fine":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Dagger-Fine":{"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Greatsword-Fine":{"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Mace-Fine":{"Small Elder Haft":1,"Mithril Mace Head":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Shield-Fine":{"Mithril Shield Backing":1,"Mithril Shield Boss":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Spear-Fine":{"Large Elder Haft":1,"Mithril Spear Head":1,"Cleric's Elder Inscription":1},
		"Cleric's Mithril Sword-Fine":{"Mithril Sword Hilt":1,"Mithril Sword Blade":1,"Cleric's Elder Inscription":1},
		"Explorer's Mithril Axe-Fine":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Dagger-Fine":{"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Greatsword-Fine":{"Mithril Greatsword Blade":1,"Mithril Greatsword Hilt":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Mace-Fine":{"Small Elder Haft":1,"Mithril Mace Head":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Shield-Fine":{"Mithril Shield Backing":1,"Explorer's Elder Inscription":1,"Mithril Shield Boss":1},
		"Explorer's Mithril Spear-Fine":{"Large Elder Haft":1,"Mithril Spear Head":1,"Explorer's Elder Inscription":1},
		"Explorer's Mithril Sword-Fine":{"Mithril Sword Blade":1,"Mithril Sword Hilt":1,"Explorer's Elder Inscription":1},
		"Rampager's Mithril Axe-Fine":{"Mithril Axe Blade":1,"Rampager's Elder Inscription":1,"Small Elder Haft":1},
		"Rampager's Mithril Dagger-Fine":{"Rampager's Elder Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Rampager's Mithril Greatsword-Fine":{"Rampager's Elder Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Rampager's Mithril Hammer-Fine":{"Mithril Hammer Head":1,"Rampager's Elder Inscription":1,"Large Elder Haft":1},
		"Rampager's Mithril Mace-Fine":{"Small Elder Haft":1,"Rampager's Elder Inscription":1,"Mithril Mace Head":1},
		"Rampager's Mithril Shield-Fine":{"Rampager's Elder Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Rampager's Mithril Spear-Fine":{"Large Elder Haft":1,"Rampager's Elder Inscription":1,"Mithril Spear Head":1},
		"Rampager's Mithril Sword-Fine":{"Rampager's Elder Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1}
	},
	"350":{
		"Major Sigil of Destroyer Slayer-2":{"Mithril Ingot":1,"Destroyer Core":1},
		"Berserker's Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Dagger-Master":{"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Greatsword-Master":{"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Shield-Master":{"Mithril Shield Backing":1,"Mithril Shield Boss":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Spear-Master":{"Large Elder Haft":1,"Mithril Spear Head":1,"Berserker's Mithril Plated Inscription":1},
		"Berserker's Mithril Sword-Master":{"Mithril Sword Hilt":1,"Mithril Sword Blade":1,"Berserker's Mithril Plated Inscription":1},
		"Carrion Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Mithril Dagger-Master":{"Carrion Mithril Plated Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Carrion Mithril Greatsword-Master":{"Carrion Mithril Plated Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Carrion Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Carrion Mithril Plated Inscription":1},
		"Carrion Mithril Shield-Master":{"Carrion Mithril Plated Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Carrion Mithril Spear-Master":{"Large Elder Haft":1,"Carrion Mithril Plated Inscription":1,"Mithril Spear Head":1},
		"Carrion Mithril Sword-Master":{"Carrion Mithril Plated Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Cleric's Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Dagger-Master":{"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Greatsword-Master":{"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Shield-Master":{"Mithril Shield Backing":1,"Mithril Shield Boss":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Spear-Master":{"Large Elder Haft":1,"Mithril Spear Head":1,"Cleric's Mithril Plated Inscription":1},
		"Cleric's Mithril Sword-Master":{"Mithril Sword Hilt":1,"Mithril Sword Blade":1,"Cleric's Mithril Plated Inscription":1},
		"Explorer's Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Mithril Dagger-Master":{"Explorer's Mithril Plated Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Explorer's Mithril Greatsword-Master":{"Explorer's Mithril Plated Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Explorer's Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Explorer's Mithril Plated Inscription":1},
		"Explorer's Mithril Shield-Master":{"Explorer's Mithril Plated Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Explorer's Mithril Spear-Master":{"Large Elder Haft":1,"Explorer's Mithril Plated Inscription":1,"Mithril Spear Head":1},
		"Explorer's Mithril Sword-Master":{"Explorer's Mithril Plated Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Knight's Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Mithril Dagger-Master":{"Knight's Mithril Plated Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Knight's Mithril Greatsword-Master":{"Knight's Mithril Plated Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Knight's Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Knight's Mithril Plated Inscription":1},
		"Knight's Mithril Shield-Master":{"Knight's Mithril Plated Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Knight's Mithril Spear-Master":{"Large Elder Haft":1,"Knight's Mithril Plated Inscription":1,"Mithril Spear Head":1},
		"Knight's Mithril Sword-Master":{"Knight's Mithril Plated Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Mithril Plated Dowel":{"Mithril Ingot":3,"Elder Wood Plank":2},
		"Rampager's Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Mithril Dagger-Master":{"Rampager's Mithril Plated Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Rampager's Mithril Greatsword-Master":{"Rampager's Mithril Plated Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Rampager's Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Rampager's Mithril Plated Inscription":1},
		"Rampager's Mithril Shield-Master":{"Rampager's Mithril Plated Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Rampager's Mithril Spear-Master":{"Large Elder Haft":1,"Rampager's Mithril Plated Inscription":1,"Mithril Spear Head":1},
		"Rampager's Mithril Sword-Master":{"Rampager's Mithril Plated Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Valkyrie Mithril Axe-Master":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Dagger-Master":{"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Greatsword-Master":{"Mithril Greatsword Blade":1,"Mithril Greatsword Hilt":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Hammer-Master":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Mace-Master":{"Small Elder Haft":1,"Mithril Mace Head":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Shield-Master":{"Mithril Shield Backing":1,"Valkyrie Mithril Plated Inscription":1,"Mithril Shield Boss":1},
		"Valkyrie Mithril Spear-Master":{"Large Elder Haft":1,"Mithril Spear Head":1,"Valkyrie Mithril Plated Inscription":1},
		"Valkyrie Mithril Sword-Master":{"Mithril Sword Blade":1,"Mithril Sword Hilt":1,"Valkyrie Mithril Plated Inscription":1}
	},
	"375":{
		"Major Sigil of Doom-2":{"Mithril Ingot":1,"Molten Core":1},
		"Berserker's Krait Battleaxe":{"Berserker's Mithril Imbued Inscription":1,"Mithril Axe Blade":1,"Small Elder Haft":1},
		"Berserker's Krait Machete":{"Berserker's Mithril Imbued Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Berserker's Krait Morning Star":{"Berserker's Mithril Imbued Inscription":1,"Small Elder Haft":1,"Mithril Mace Head":1},
		"Berserker's Krait Pilum":{"Berserker's Mithril Imbued Inscription":1,"Large Elder Haft":1,"Mithril Spear Head":1},
		"Berserker's Krait Ripper":{"Berserker's Mithril Imbued Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Berserker's Krait Shell":{"Berserker's Mithril Imbued Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Berserker's Krait Slayer":{"Berserker's Mithril Imbued Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Berserker's Krait Warhammer":{"Berserker's Mithril Imbued Inscription":1,"Mithril Hammer Head":1,"Large Elder Haft":1},
		"Carrion Krait Battleaxe":{"Mithril Axe Blade":1,"Carrion Mithril Imbued Inscription":1,"Small Elder Haft":1},
		"Carrion Krait Machete":{"Carrion Mithril Imbued Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Carrion Krait Morning Star":{"Small Elder Haft":1,"Carrion Mithril Imbued Inscription":1,"Mithril Mace Head":1},
		"Carrion Krait Pilum":{"Large Elder Haft":1,"Carrion Mithril Imbued Inscription":1,"Mithril Spear Head":1},
		"Carrion Krait Ripper":{"Carrion Mithril Imbued Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Carrion Krait Shell":{"Carrion Mithril Imbued Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Carrion Krait Slayer":{"Carrion Mithril Imbued Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Carrion Krait Warhammer":{"Mithril Hammer Head":1,"Carrion Mithril Imbued Inscription":1,"Large Elder Haft":1},
		"Cleric's Krait Battleaxe":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Machete":{"Mithril Sword Hilt":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Sword Blade":1},
		"Cleric's Krait Morning Star":{"Small Elder Haft":1,"Mithril Mace Head":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Pilum":{"Large Elder Haft":1,"Mithril Spear Head":1,"Cleric's Mithril Imbued Inscription":1},
		"Cleric's Krait Ripper":{"Mithril Dagger Hilt":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Dagger Blade":1},
		"Cleric's Krait Shell":{"Mithril Shield Backing":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Shield Boss":1},
		"Cleric's Krait Slayer":{"Mithril Greatsword Hilt":1,"Cleric's Mithril Imbued Inscription":1,"Mithril Greatsword Blade":1},
		"Cleric's Krait Warhammer":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Cleric's Mithril Imbued Inscription":1},
		"Explorer's Krait Battleaxe":{"Mithril Axe Blade":1,"Explorer's Mithril Imbued Inscription":1,"Small Elder Haft":1},
		"Explorer's Krait Machete":{"Explorer's Mithril Imbued Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Explorer's Krait Morning Star":{"Small Elder Haft":1,"Explorer's Mithril Imbued Inscription":1,"Mithril Mace Head":1},
		"Explorer's Krait Pilum":{"Large Elder Haft":1,"Explorer's Mithril Imbued Inscription":1,"Mithril Spear Head":1},
		"Explorer's Krait Ripper":{"Explorer's Mithril Imbued Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Explorer's Krait Shell":{"Explorer's Mithril Imbued Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Explorer's Krait Slayer":{"Explorer's Mithril Imbued Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Explorer's Krait Warhammer":{"Mithril Hammer Head":1,"Explorer's Mithril Imbued Inscription":1,"Large Elder Haft":1},
		"Knight's Krait Battleaxe":{"Mithril Axe Blade":1,"Knight's Mithril Imbued Inscription":1,"Small Elder Haft":1},
		"Knight's Krait Machete":{"Knight's Mithril Imbued Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Knight's Krait Morning Star":{"Small Elder Haft":1,"Knight's Mithril Imbued Inscription":1,"Mithril Mace Head":1},
		"Knight's Krait Pilum":{"Large Elder Haft":1,"Knight's Mithril Imbued Inscription":1,"Mithril Spear Head":1},
		"Knight's Krait Ripper":{"Knight's Mithril Imbued Inscription":1,"Mithril Dagger Hilt":1,"Mithril Dagger Blade":1},
		"Knight's Krait Shell":{"Knight's Mithril Imbued Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Knight's Krait Slayer":{"Knight's Mithril Imbued Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Knight's Krait Warhammer":{"Mithril Hammer Head":1,"Knight's Mithril Imbued Inscription":1,"Large Elder Haft":1},
		"Rampager's Krait Battleaxe":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Machete":{"Mithril Sword Blade":1,"Mithril Sword Hilt":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Morning Star":{"Small Elder Haft":1,"Mithril Mace Head":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Pilum":{"Large Elder Haft":1,"Mithril Spear Head":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Ripper":{"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Shell":{"Mithril Shield Backing":1,"Rampager's Mithril Imbued Inscription":1,"Mithril Shield Boss":1},
		"Rampager's Krait Slayer":{"Mithril Greatsword Blade":1,"Mithril Greatsword Hilt":1,"Rampager's Mithril Imbued Inscription":1},
		"Rampager's Krait Warhammer":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Rampager's Mithril Imbued Inscription":1},
		"Valkyrie Krait Battleaxe":{"Mithril Axe Blade":1,"Small Elder Haft":1,"Valkyrie Mithril Imbued Inscription":1},
		"Valkyrie Krait Machete":{"Valkyrie Mithril Imbued Inscription":1,"Mithril Sword Hilt":1,"Mithril Sword Blade":1},
		"Valkyrie Krait Morning Star":{"Small Elder Haft":1,"Mithril Mace Head":1,"Valkyrie Mithril Imbued Inscription":1},
		"Valkyrie Krait Pilum":{"Large Elder Haft":1,"Valkyrie Mithril Imbued Inscription":1,"Mithril Spear Head":1},
		"Valkyrie Krait Ripper":{"Valkyrie Mithril Imbued Inscription":1,"Mithril Dagger Blade":1,"Mithril Dagger Hilt":1},
		"Valkyrie Krait Shell":{"Valkyrie Mithril Imbued Inscription":1,"Mithril Shield Backing":1,"Mithril Shield Boss":1},
		"Valkyrie Krait Slayer":{"Valkyrie Mithril Imbued Inscription":1,"Mithril Greatsword Hilt":1,"Mithril Greatsword Blade":1},
		"Valkyrie Krait Warhammer":{"Mithril Hammer Head":1,"Large Elder Haft":1,"Valkyrie Mithril Imbued Inscription":1}
	}
}
